import {endstopFormats} from '../../src/inputs/endstop.ts';
import {trsyncFormats} from '../../src/inputs/trsync.ts';
import {PrinterPins} from '../../src/protocol/pins.ts';
import {MessageDictionary} from '../../src/protocol/dictionary.ts';
import {ConfigurationReader} from '../../src/moonraker/config-reader.ts';
import {ConfigurationSource} from '../../src/moonraker/config-source.ts';
export function stepperBatchFixture(reserved=false){
 const dictionary=new MessageDictionary();dictionary.identify(Buffer.from(JSON.stringify({commands:{'config_analog_in oid=%c pin=%u':32,'query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u bytes_per_report=%c min_value=%hu max_value=%hu range_check_count=%c':33,'config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u':25,'queue_pwm_out oid=%c clock=%u value=%hu':26,'set_digital_out_pwm_cycle oid=%c cycle_ticks=%u':27,'reset_pwm_out_generation oid=%c generation=%u':28,'queue_pwm_out_generation oid=%c clock=%u value=%hu generation=%u':29,'reset_digital_out_generation oid=%c generation=%u':30,'queue_digital_out_generation oid=%c clock=%u on_ticks=%u generation=%u':31,[endstopFormats.config]:15,[endstopFormats.home]:16,[endstopFormats.query]:17,[trsyncFormats.config]:19,[trsyncFormats.start]:20,[trsyncFormats.timeout]:21,[trsyncFormats.trigger]:22,[trsyncFormats.stepper]:23,'config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u':12,'update_digital_out oid=%c value=%c':13,'queue_digital_out oid=%c clock=%u on_ticks=%u':14,get_config:8,'allocate_oids count=%c':9,'finalize_config crc=%u':10,'config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u':7,'queue_step oid=%c interval=%u count=%hu add=%hi':2,'set_next_step_dir oid=%c dir=%c':3,'reset_step_clock oid=%c clock=%u':4,'stepper_get_position oid=%c':5},responses:{'analog_in_state oid=%c next_clock=%u values=%*s':34,[endstopFormats.state]:18,[trsyncFormats.state]:24,'config is_config=%c crc=%u is_shutdown=%c move_count=%hu':11,'stepper_position oid=%c pos=%i':6},enumerations:{pin:{PA0:0,PA0_ALIAS:0,PA1:1,PA2:2,PA3:3,PA3_ALIAS:3,PA4:4,PA5:5,PA6:6,PA7:7}},config:{ADC_MAX:4095,PWM_MAX:255,CLOCK_FREQ:1e6,...reserved?{RESERVE_PINS_debug:'PA3'}:{}}})),false);
 const pins=new PrinterPins<object>(),chip={},aux={};pins.register('mcu',chip);pins.register('aux',aux);pins.resolver('mcu').alias('STEP','PA0');return {pins,mcus:new Map([['mcu',{chip,dictionary}],['aux',{chip:aux,dictionary}]]),dictionary};
}
export const batchReader=(second:Record<string,string>={})=>new ConfigurationReader(new ConfigurationSource('/steppers.cfg',{stepper_x:{step_pin:'!STEP',dir_pin:'!PA1',rotation_distance:'40',microsteps:'16'},stepper_y:{step_pin:'PA2',dir_pin:'PA3',rotation_distance:'40',microsteps:'16',...second}},[]),null);
