import assert from 'node:assert/strict';
import {mkdtemp,writeFile,open,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {setImmediate} from 'node:timers/promises';
import {PublishedPrintFiles} from '../../src/storage/published-files.ts';
import {NativePersistentMetadata} from '../../src/moonraker/native-persistent-metadata.ts';
import type {Json} from '../../src/moonraker/rpc.ts';
if(!global.gc)throw new Error('Retention control requires explicit GC');
const dir=await mkdtemp(join(tmpdir(),'metadata-response-retention-')),signal=new AbortController().signal;let files:PublishedPrintFiles|undefined,owner:NativePersistentMetadata|undefined;
try{
 await writeFile(join(dir,'source'),'; generated by Cura_SteamEngine 5.10.0\nG1 X1\n');const source=await open(join(dir,'source'),'r');
 files=await PublishedPrintFiles.open(join(dir,'files'));try{await files.publish('part','part.gcode',source,signal);}finally{await source.close();}
 owner=await NativePersistentMetadata.open(join(dir,'metadata'),files);await owner.metadata('part.gcode',signal);
 const refs=await (async()=>{const values:WeakRef<Record<string,Json>>[]=[];for(let i=0;i<64;i++)values.push(new WeakRef(await owner!.metadata('part.gcode',signal)));return values;})();
 // Leave each WeakRef creation job and never dereference between collections.
 for(let i=0;i<8;i++){await setImmediate();global.gc();}
 await setImmediate();const live=refs.filter(ref=>ref.deref()!==undefined).length;
 assert.equal(live,0);assert.equal(owner.status.pending,0);assert.equal(owner.status.scans,1);
 console.log(JSON.stringify({copies:64,gcRequests:8,liveResponseCopies:live,scope:'Response retention control; no process-wide leak claim'}));
}finally{await owner?.close();await files?.close();await rm(dir,{recursive:true,force:true});}
