import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
export function stallguardOracle(blocks:{data:number[][]}[],times:number[],selection:string,bench=false):{values:(number|null)[];ms:number[]}{
 const source=execFileSync('git',['show','2c7ba578:scripts/motan/readlog.py']);if(createHash('sha256').update(source).digest('hex')!=='f89b7eff1f4592399d9eb9ad0f679d894cb9a0d2a40a79f81f48d139c16e9ca2')throw new Error('Motan source changed');const script=`import json,sys,time\nscope={}\nexec(${JSON.stringify(source.toString())},scope)\nx=json.load(sys.stdin)\nclass Manager:\n def __init__(self): self.blocks=iter(x['blocks'])\n def get_jdispatch(self): return self\n def get_initial_status(self): return {'configfile':{'settings':{'tmc2209 stepper_x':{}}}}\n def get_status_tracker(self): return None\n def pull_msg(self,*args):\n  v=next(self.blocks,None)\n  return None if v is None else {'data':v['data'][:]}\ndef run():\n h=scope['HandleStallguard'](Manager(),'s',['stallguard','stepper_x',x['selection']])\n return [h.pull_data(t) for t in x['times']]\nvalues=run();ms=[]\nif ${bench?'True':'False'}:\n for i in range(9):\n  start=time.perf_counter();run();elapsed=(time.perf_counter()-start)*1000\n  if i>=2: ms.append(elapsed)\nprint(json.dumps(dict(values=values,ms=ms)))`;
 return JSON.parse(execFileSync('python3',['-c',script],{input:JSON.stringify({blocks,times,selection}),encoding:'utf8',maxBuffer:16*1024**2}));
}
export function statusFieldOracle(times:number[],bench=false):{values:number[];ms:number[]}{
 const source=execFileSync('git',['show','2c7ba578:scripts/motan/readlog.py']);if(createHash('sha256').update(source).digest('hex')!=='f89b7eff1f4592399d9eb9ad0f679d894cb9a0d2a40a79f81f48d139c16e9ca2')throw new Error('Motan source changed');const script=`import json,sys,time,math\nscope={}\nexec(${JSON.stringify(source.toString())},scope)\ntimes=json.load(sys.stdin)\nclass Manager:\n def get_status_tracker(self): return self\n def pull_status(self,t): return {'sensor':{'value':math.floor(t)}}, math.floor(t)+1\ndef run():\n h=scope['HandleStatusField'](Manager(),'s',['status','sensor.value'])\n return [h.pull_data(t) for t in times]\nvalues=run();ms=[]\nif ${bench?'True':'False'}:\n for i in range(9):\n  start=time.perf_counter();run();elapsed=(time.perf_counter()-start)*1000\n  if i>=2: ms.append(elapsed)\nprint(json.dumps(dict(values=values,ms=ms)))`;
 return JSON.parse(execFileSync('python3',['-c',script],{input:JSON.stringify(times),encoding:'utf8',maxBuffer:16*1024**2}));
}
