import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
/** Write a plain-JS probe inside the artifact so dependencies resolve exactly
 * as deployment would. The child is run with TS stripping and PATH disabled. */
export async function productBuildSmoke(output:string,work:string){
 const path=join(output,'smoke.mjs');
 await writeFile(path,`import assert from 'node:assert/strict';
import {writeFile,open} from 'node:fs/promises';
import sharp from 'sharp';
import {PrintJournal} from './host/src/operations/print-journal.js';
import {DatabaseStore} from './host/src/moonraker/database.js';
import {FileListing} from './host/src/moonraker/file-list.js';
import {MetadataExtractor} from './host/src/moonraker/metadata-extractor.js';
import {ThumbnailProcessor} from './host/src/moonraker/thumbnail-process.js';
import {SpectrumExecutor} from './host/src/calibration/background.js';
import {ShaperFitExecutor} from './host/src/calibration/shaper-fit-executor.js';
import {TrapQueue} from './host/src/motion/trap-queue.js';
import {diagnosticPdf} from './host/src/diagnostics/diagnostic-pdf.js';
const dir=${JSON.stringify(work)},signal=new AbortController().signal;
const journal=await PrintJournal.open({path:dir+'/journal.db',deviceId:'printer'});
try{await journal.reserve({version:1,requestId:'job',fileId:'file',nozzle:0,bed:0});assert.equal((await journal.get('job')).state,'reserved');}finally{await journal.close();}
const database=await DatabaseStore.open({path:dir+'/moonraker.db'});
try{await database.insert('ui','exact',1.005);assert.equal(await database.get('ui','exact'),1.005);}finally{await database.close();}
await writeFile(dir+'/sample.gcode','; generated by PrusaSlicer 2.7.0 on 2026-01-01 at 12:34:56\\nG1 Z0.3 X1\\n');
const files=await FileListing.open({roots:[{name:'gcodes',path:dir,writable:true}]}),extractor=await MetadataExtractor.open();
try{assert((await files.list('gcodes',signal)).some(file=>file.path==='sample.gcode'));assert.equal((await extractor.extract(await open(dir+'/sample.gcode','r'),signal)).fields.slicer,'PrusaSlicer');}finally{await files.close();await extractor.close();}
const processor=await ThumbnailProcessor.open();
try{const bytes=await sharp({create:{width:32,height:32,channels:4,background:'#2468ac'}}).png().toBuffer(),base64=bytes.toString('base64');const images=await processor.prepare('; thumbnail begin 32x32 '+base64.length+'\\n; '+base64+'\\n; thumbnail end\\n',signal);assert.equal(images.length,1);assert.deepEqual(images[0].bytes,bytes);}finally{await processor.close();}
const samples=()=>Float64Array.from({length:4096*4},(_,i)=>i%4===0?Math.floor(i/4)/1024:Math.sin(2*Math.PI*64*Math.floor(i/4)/1024));
const executor=new SpectrumExecutor(),cancel=new AbortController(),pending=executor.calculate('cancel',samples(),{signal:cancel.signal});cancel.abort(new Error('compiled cancellation'));await assert.rejects(pending,/compiled cancellation/);
const spectrum=await executor.calculate('compiled',samples());
const dataset=()=>({frequencies:Float64Array.from({length:128},(_,i)=>i*2),psd:Float64Array.from({length:128},(_,i)=>Math.exp(-(((i*2-45)/8)**2))+.01)});
const fit=await new ShaperFitExecutor().fit([dataset()],{shapers:['mzv','ei'],frequencies:[35,40,45,50]});
using queue=new TrapQueue();queue.appendRaw(new Float64Array([1,0,1,0,0,0,0,1,0,0,10,10,0]));
using stepper=queue.createStepper({frequency:1e6,timeOffset:0,oid:1,maxError:0,queueStepTag:5,directionTag:6},'x',.01);stepper.generate(2);assert.equal(stepper.flush().position,1000n);
const pdf=await diagnosticPdf('<svg width="100" height="40" xmlns="http://www.w3.org/2000/svg"><text x="2" y="20">Build</text></svg>',signal);assert.equal(pdf.subarray(0,4).toString(),'%PDF');
console.log(JSON.stringify({spectrum,fit,steps:'1000'}));
`);return path;
}
