import {endstopFormats} from '../../src/inputs/endstop.ts';
import {trsyncFormats} from '../../src/inputs/trsync.ts';
import {deflateSync} from 'node:zlib';
import {MessageDictionary} from '../../src/protocol/dictionary.ts';
import {FrameDecoder,encodeFrame} from '../../src/protocol/codec.ts';
import {serialClock} from '../../src/protocol/serial-queue.ts';
import {serialPair} from './serial-pair.ts';
export async function serialFirmware<T extends {fd:number;peer:{on(event:'data',callback:(chunk:Buffer|string)=>void):unknown;write(data:Uint8Array):unknown};close():Promise<void>}=Awaited<ReturnType<typeof serialPair>>>(provided?:T,options:{extendedPins?:boolean;stepperBytePins?:boolean;triggerSync?:boolean;debugRead?:(order:number,address:number)=>number;canIdentity?:{uuid:string;nodeId:number}}={}){
 const pair=provided??await serialPair() as unknown as T,dictionary=new MessageDictionary();const compressed=deflateSync(Buffer.from(JSON.stringify({commands:{...options.triggerSync?{[endstopFormats.config]:44,[endstopFormats.home]:45,[endstopFormats.query]:46,[trsyncFormats.config]:38,[trsyncFormats.start]:39,[trsyncFormats.timeout]:40,[trsyncFormats.trigger]:41,[trsyncFormats.stepper]:42}:{},...options.canIdentity?{get_canbus_id:36}:{},...options.debugRead?{'debug_read order=%c addr=%u':34}:{},'queue_pwm_out_generation oid=%c clock=%u value=%hu generation=%u':30,'reset_pwm_out_generation oid=%c generation=%u':31,'queue_digital_out_generation oid=%c clock=%u on_ticks=%u generation=%u':32,'reset_digital_out_generation oid=%c generation=%u':33,'config_analog_in oid=%c pin=%u':27,'query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u bytes_per_report=%c min_value=%hu max_value=%hu range_check_count=%c':28,'config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u':24,'queue_pwm_out oid=%c clock=%u value=%hu':25,'set_digital_out_pwm_cycle oid=%c cycle_ticks=%u':26,'config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u':21,'update_digital_out oid=%c value=%c':22,'queue_digital_out oid=%c clock=%u on_ticks=%u':23,get_uptime:2,get_clock:3,get_config:10,[options.stepperBytePins?'config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u':'config_stepper oid=%c step_pin=%u dir_pin=%u invert_step=%c step_pulse_ticks=%u']:14,'reset_step_clock oid=%c clock=%u':15,'stepper_get_position oid=%c':16,'allocate_oids count=%c':11,'finalize_config crc=%u':12,'echo value=%u':6,'queue_step oid=%c interval=%u count=%hu add=%hi':8,'set_next_step_dir oid=%c dir=%c':9},responses:{...options.triggerSync?{[endstopFormats.state]:47,[trsyncFormats.state]:43}:{},...options.canIdentity?{'canbus_id canbus_uuid=%*s canbus_nodeid=%u':37}:{},...options.debugRead?{'debug_result val=%u':35}:{},'analog_in_state oid=%c next_clock=%u values=%*s':29,'shutdown clock=%u static_string_id=%hu':18,'is_shutdown static_string_id=%hu':19,'starting':20,'stepper_position oid=%c pos=%i':17,'config is_config=%c crc=%u is_shutdown=%c move_count=%hu':13,'uptime high=%u clock=%u':4,'clock clock=%u':5,'echo_response value=%u':7},enumerations:{static_string_id:{'Timer too close':1,'Command request':2},pin:{...options.extendedPins?{PA4:4,PA5:5,PA6:6,PA7:7,PA8:8,PA9:9,PA10:10,PA11:11,PA12:12,PA13:13}:{},PA0:0,PA1:1,PA2:2,PA3:3,PA3_ALIAS:3}},config:{...options.canIdentity?{CANBUS_FREQUENCY:1000000}:{},ADC_MAX:4095,PWM_MAX:255,STEPPER_STEP_BOTH_EDGE:1,CLOCK_FREQ:1e6,RECEIVE_WINDOW:256}})));dictionary.identify(compressed);
 const delayed=new Set<ReturnType<typeof setTimeout>>();let echoDelay=0,holdEcho=false,triggerReason:number|undefined,endstopState={homing:0,next_clock:0,pin_value:0};const positions=new Map<number,number>(),triggerReasons=new Map<number,number>(),endstopStates=new Map<number,typeof endstopState>();const heldEchoes:Uint8Array[]=[];const decoder=new FrameDecoder(),start=serialClock.now();let ignored:string|undefined,frames=0,sequence=1,configured=0,configCRC=0;const outputs:{name:string;parameters:Record<string,unknown>}[]=[];const stepperConfigs:Record<string,unknown>[]=[];const motion:{name:string;parameters:Record<string,unknown>;time:number}[]=[];
 pair.peer.on('data',(chunk:Buffer|string)=>{for(const frame of decoder.push(typeof chunk==='string'?Buffer.from(chunk):chunk)){frames++;if((frame[1]&15)!==sequence){pair.peer.write(encodeFrame(sequence,new Uint8Array()));continue;}const seq=(frame[1]+1)&15;sequence=seq;
  for(const cmd of dictionary.parseFrame(frame)){
   if(cmd.name===ignored)continue;
   if(['config_endstop','endstop_home','config_trsync','trsync_start','trsync_set_timeout','stepper_stop_on_trigger','queue_pwm_out_generation','reset_pwm_out_generation','queue_digital_out_generation','reset_digital_out_generation','config_analog_in','query_analog_in','config_digital_out','update_digital_out','queue_digital_out','config_pwm_out','queue_pwm_out','set_digital_out_pwm_cycle'].includes(cmd.name)){outputs.push({name:cmd.name,parameters:cmd.parameters});continue;}
   if(cmd.name==='queue_step'||cmd.name==='set_next_step_dir'){motion.push({name:cmd.name,parameters:cmd.parameters,time:serialClock.now()});continue;}
   if(cmd.name==='allocate_oids')continue;
   if(cmd.name==='reset_step_clock'){if(options.triggerSync)outputs.push({name:cmd.name,parameters:cmd.parameters});continue;}
   if(cmd.name==='config_stepper'){stepperConfigs.push({...cmd.parameters});continue;}
   if(cmd.name==='finalize_config'){configured=1;configCRC=cmd.parameters.crc as number;continue;}
   const ticks=Math.round(1e6+(serialClock.now()-start)*1e6);let payload:Uint8Array;
   if(cmd.name==='identify'){const offset=cmd.parameters.offset as number;payload=dictionary.encode('identify_response',{offset,data:compressed.subarray(offset,offset+40)});}
   else if(cmd.name==='get_canbus_id'&&options.canIdentity)payload=dictionary.encode('canbus_id',{canbus_uuid:Buffer.from(options.canIdentity.uuid,'hex'),canbus_nodeid:options.canIdentity.nodeId});
   else if(cmd.name==='debug_read'&&options.debugRead)payload=dictionary.encode('debug_result',{val:options.debugRead(cmd.parameters.order as number,cmd.parameters.addr as number)});
   else if(cmd.name==='trsync_trigger'){outputs.push({name:cmd.name,parameters:cmd.parameters});payload=dictionary.encode('trsync_state',{oid:cmd.parameters.oid,can_trigger:0,trigger_reason:triggerReasons.get(cmd.parameters.oid as number)??triggerReason??cmd.parameters.reason,clock:0});}
   else if(cmd.name==='endstop_query_state'){outputs.push({name:cmd.name,parameters:cmd.parameters});payload=dictionary.encode('endstop_state',{oid:cmd.parameters.oid,...(endstopStates.get(cmd.parameters.oid as number)??endstopState)});}
   else if(cmd.name==='stepper_get_position'){if(options.triggerSync)outputs.push({name:cmd.name,parameters:cmd.parameters});payload=dictionary.encode('stepper_position',{oid:cmd.parameters.oid,pos:positions.get(cmd.parameters.oid as number)??0});}
   else if(cmd.name==='get_config')payload=dictionary.encode('config',{is_config:configured,crc:configCRC,is_shutdown:0,move_count:512});
   else if(cmd.name==='get_uptime')payload=dictionary.encode('uptime',{high:0,clock:ticks});
   else if(cmd.name==='get_clock')payload=dictionary.encode('clock',{clock:ticks});
   else payload=dictionary.encode('echo_response',{value:cmd.parameters.value});
   // Firmware command_add_frame reads next_sequence when sending, not
   // when the request arrived; other commands may have advanced it meanwhile.
   if(cmd.name==='echo'&&holdEcho)heldEchoes.push(payload);
   else if(cmd.name==='echo'&&echoDelay){const timer=setTimeout(()=>{delayed.delete(timer);pair.peer.write(encodeFrame(sequence,payload));},echoDelay);delayed.add(timer);}else pair.peer.write(encodeFrame(seq,payload));
  }
  pair.peer.write(encodeFrame(seq,new Uint8Array()));
 }});
 return {...pair,currentClock(){return Math.round(1e6+(serialClock.now()-start)*1e6);},setTriggerReason(reason:number,oid?:number){if(oid===undefined)triggerReason=reason;else triggerReasons.set(oid,reason);},setEndstopState(state:typeof endstopState,oid?:number){if(oid===undefined)endstopState={...state};else endstopStates.set(oid,{...state});},setStepperPosition(oid:number,pos:number){positions.set(oid,pos);},async close(){for(const timer of delayed)clearTimeout(timer);delayed.clear();heldEchoes.length=0;await pair.close();},holdEcho(){holdEcho=true;},releaseEcho(){holdEcho=false;for(const payload of heldEchoes.splice(0))pair.peer.write(encodeFrame(sequence,payload));},delayEcho(milliseconds:number){echoDelay=milliseconds;},dictionary,motion,stepperConfigs,outputs,get frames(){return frames;},emit(name:string,parameters:Parameters<MessageDictionary['encode']>[1]={}){pair.peer.write(encodeFrame(sequence,dictionary.encode(name,parameters)));},emitEcho(value:number){pair.peer.write(encodeFrame(sequence,dictionary.encode('echo_response',{value})));},ignore(name:string){ignored=name;}};
}
