import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {extruderPlot,extruderPositions,rawPressureAdvance,weightedExtruder} from '../src/diagnostics/graph-extruder.ts';
import {writeStatsPlot} from '../src/diagnostics/graphstats-file.ts';
import {extruderReference,extruderManifest} from './extruder-reference.ts';
const reference=extruderReference(),times:number[]=[],exports:number[]=[],signal=new AbortController().signal;
const error=(a:readonly number[],b:readonly number[])=>{assert.equal(a.length,b.length);let max=0;for(let i=0;i<a.length;i++){assert.ok(Number.isFinite(a[i]));max=Math.max(max,Math.abs(a[i]-b[i]));}return max;};
let velocityError=0;for(let i=0;i<16;i++){const start=performance.now(),plot=extruderPlot();if(i>=5)times.push(performance.now()-start);plot.curves.forEach((c,j)=>{assert.deepEqual(c.times,reference.plot.curves[j].times);velocityError=Math.max(velocityError,error(c.values,reference.plot.curves[j].values));});assert.ok(velocityError<=2e-8);const exportStart=performance.now();await writeStatsPlot(plot,'/tmp/graph-extruder-review.png',signal,{label:'Time (s)',format:'number'});if(i>=5)exports.push(performance.now()-exportStart);}
const positions=extruderPositions(),raw=rawPressureAdvance(positions),smooth=weightedExtruder(raw);const errors={positionMm:error(positions,reference.positions),rawPositionMm:error(raw,reference.raw),smoothPositionMm:error(smooth,reference.smooth),velocityMmPerSecond:velocityError};assert.ok(errors.positionMm<=1e-14&&errors.rawPositionMm<=1e-12&&errors.smoothPositionMm<=1e-12);
const stats=(a:number[])=>{a.sort((a,b)=>a-b);return {medianMs:a[Math.floor(a.length/2)],p95Ms:a[Math.ceil(a.length*.95)-1]};};const compute=stats(times),png=stats(exports),before=extruderManifest.before;assert.ok(compute.medianMs<=before.nodeCompute.medianMs*1.25+2);assert.ok(compute.p95Ms<=before.nodeCompute.p95Ms*1.5+2);assert.ok(png.medianMs<=before.nodePngExport.medianMs*1.25+10);assert.ok(png.p95Ms<=before.nodePngExport.p95Ms*1.5+20);console.log(JSON.stringify({node:process.version,samples:positions.length,curvePoints:extruderPlot().curves[0].times.length,warmups:5,runs:11,nodeCompute:compute,historicalPythonCompute:stats(reference.samples.slice(5)),nodePngExport:png,errors,scope:'Fixed original Python plot_motion data and historical timing captured with recording Matplotlib adapter versus current Node curve calculation. No Python process. Startup/IPC and rendering excluded from compute. Node PNG export separately includes SVG, sharp and atomic file replacement. Offline diagnostic only; not real-time motion or hardware acceptance.'},null,2));
