import {createServer,type Socket} from 'node:net';
import {once} from 'node:events';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {performance} from 'node:perf_hooks';
import {WebSocket} from 'ws';
import assert from 'node:assert/strict';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
const root=await mkdtemp(join(tmpdir(),'http-subscribe-')),path=join(root,'klippy.sock'),sockets:Socket[]=[],wire=(v:unknown)=>JSON.stringify(v)+'\x03';let clock=0,associations=0;
const peer=createServer(socket=>{sockets.push(socket);let buffer='';socket.on('data',data=>{buffer+=data.toString();let at:number;while((at=buffer.indexOf('\x03'))>=0){const m=JSON.parse(buffer.slice(0,at));buffer=buffer.slice(at+1);let result:any={};switch(m.method){case 'info':result={state:'ready',state_message:'Ready'};break;case 'list_endpoints':result={endpoints:['objects/subscribe','objects/list']};break;case 'objects/list':result={objects:['virtual_sdcard','display_status','pause_resume']};break;case 'objects/subscribe':result={eventtime:++clock,status:{webhooks:{state:'ready'},...(m.params.objects.toolhead?{toolhead:{position:[1.25,2,3],velocity:100}}:{})}};break;}socket.write(wire({id:m.id,result}));}});});await new Promise<void>(r=>peer.listen(path,r));const config=join(root,'moonraker.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'bench',missingRequirements:[]},authorize(){},authorizeNotification(){},authorizeSubscriptionConnection(source,target){assert.equal(source.request.headers['x-owner'],target.request.headers['x-owner']);associations++;}}),address=await server.start(),base=`http://127.0.0.1:${address.port}`,ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`,{headers:{'x-owner':'bench'}}),samples={http:[] as number[],websocket:[] as number[]},opened=once(ws,'open');
try{await server.attachKlippy(path);await opened;const id=server.clients[0].id;for(let run=0;run<54;run++)for(const mode of (run%2?['http','websocket']:['websocket','http']) as ('http'|'websocket')[]){const start=performance.now();for(let i=0;i<100;i++){let result:any;if(mode==='http')result=await(await fetch(base+`/printer/objects/subscribe?connection_id=${id}&toolhead=position`,{headers:{'x-owner':'bench'}})).json();else{const pending=new Promise<any>(resolve=>{const receive=(message:unknown)=>{const value=JSON.parse(String(message));if(value.id===i+1){ws.off('message',receive);resolve(value);}};ws.on('message',receive);});ws.send(JSON.stringify({jsonrpc:'2.0',method:'printer.objects.subscribe',params:{objects:{toolhead:['position']}},id:i+1}));result=await pending;}assert.deepEqual(result.result.status,{toolhead:{position:[1.25,2,3]}});}if(run>=3)samples[mode].push(performance.now()-start);}assert.equal(associations,5400);}finally{ws.terminate();await server.close();for(const socket of sockets)socket.destroy();await new Promise<void>(r=>peer.close(()=>r()));await rm(root,{recursive:true,force:true});}
console.log(JSON.stringify({node:process.version,samples:51,subscriptions:100,associations,results:Object.fromEntries(Object.entries(samples).map(([mode,times])=>{times.sort((a,b)=>a-b);return [mode,{medianMs:times[25],p95Ms:times[48]}];})),scope:'Alternating 100 real HTTP versus WebSocket subscriptions, same target and actual Unix peer. HTTP includes explicit ownership callback; results checked. Different transport overhead, not Python equivalence or printing deadline acceptance.'},null,2));
