import {createServer,type Socket} from 'node:net';
import {once} from 'node:events';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {performance} from 'node:perf_hooks';
import {WebSocket} from 'ws';
import assert from 'node:assert/strict';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import {KlippyLifecycle} from '../src/moonraker/klippy-lifecycle.ts';
import {MoonrakerNetwork} from '../src/moonraker/server.ts';
import {JsonRpcDispatcher} from '../src/moonraker/rpc.ts';
const wire=(v:unknown)=>JSON.stringify(v)+'\x03',root=await mkdtemp(join(tmpdir(),'klippy-events-'));
async function setup(mode:'broadcast'|'manual'){
 const path=join(root,mode+'.sock');let klippy!:Socket,counts=Array(10).fill(0),completed:()=>void=()=>{};const peer=createServer(socket=>{klippy=socket;let buffer='';socket.on('data',data=>{buffer+=data.toString();let at:number;while((at=buffer.indexOf('\x03'))>=0){const m=JSON.parse(buffer.slice(0,at));buffer=buffer.slice(at+1);let result:any={};switch(m.method){case 'info':result={state:'ready',state_message:'Ready'};break;case 'list_endpoints':result={endpoints:['objects/subscribe','objects/list']};break;case 'objects/list':result={objects:['virtual_sdcard','display_status','pause_resume']};break;case 'objects/subscribe':result={eventtime:0,status:{webhooks:{state:'ready'}}};break;}socket.write(wire({id:m.id,result}));}});});await new Promise<void>(r=>peer.listen(path,r));
 let service:ConfiguredMoonraker|MoonrakerNetwork,runtime:KlippyLifecycle|undefined,address:{port:number};if(mode==='broadcast'){const config=join(root,mode+'.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');service=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'bench',missingRequirements:[]},authorize(){},authorizeNotification(){}});address=await service.start();await service.attachKlippy(path);}else{service=new MoonrakerNetwork(new JsonRpcDispatcher(),{authorize(){},authorizeNotification(){}});address=await service.listen();let previous='disconnected';runtime=new KlippyLifecycle({version:'bench',onSnapshot:snapshot=>{if(snapshot.initialized&&snapshot.connected&&snapshot.state==='shutdown'&&previous!=='shutdown')for(const client of service.clients)void service.notifyAuthorized(client.id,'notify_klippy_shutdown',[]);previous=snapshot.state;}});await runtime.initialize(path);}
 const clients:WebSocket[]=[];for(let i=0;i<10;i++){const ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);clients.push(ws);await once(ws,'open');ws.on('message',message=>{const value=JSON.parse(String(message));assert.deepEqual(value,{jsonrpc:'2.0',method:'notify_klippy_shutdown'});counts[i]++;if(counts.every(n=>n===100))completed();});}
 return {async sample(){counts=Array(10).fill(0);let timer:ReturnType<typeof setTimeout>;const done=new Promise<void>((resolve,reject)=>{completed=resolve;timer=setTimeout(()=>reject(new Error('Lifecycle notification timeout')),5000);}),start=performance.now();try{for(let i=0;i<200;i++)klippy.write(wire({method:'process_status_update',params:{eventtime:i,status:{webhooks:{state:i%2?'shutdown':'ready'}}}}));await done;return performance.now()-start;}finally{clearTimeout(timer!);}},async close(){for(const ws of clients)ws.terminate();await service.close();await runtime?.close();klippy.destroy();await new Promise<void>(r=>peer.close(()=>r()));}};
}
const broadcast=await setup('broadcast'),manual=await setup('manual'),samples={broadcast:[] as number[],manual:[] as number[]};try{for(let run=0;run<54;run++)for(const mode of (run%2?['broadcast','manual']:['manual','broadcast']) as ('broadcast'|'manual')[]){const time=await(mode==='broadcast'?broadcast:manual).sample();if(run>=3)samples[mode].push(time);}}finally{await broadcast.close();await manual.close();await rm(root,{recursive:true,force:true});}
console.log(JSON.stringify({node:process.version,samples:51,clients:10,stateUpdates:200,deliveries:1000,results:Object.fromEntries(Object.entries(samples).map(([mode,times])=>{times.sort((a,b)=>a-b);return [mode,{medianMs:times[25],p95Ms:times[48]}];})),scope:'Real Unix ready/shutdown transitions to 10 WebSockets. Configured metadata/routes and authorized lifecycle broadcast versus low-level lifecycle with manual authorized sends. Alternating order and all 1000 notifications consumed. Stress workload, not normal printer transitions or Python performance equivalence.'},null,2));
