import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {performance,monitorEventLoopDelay} from 'node:perf_hooks';
import {MetadataFiles} from '../src/moonraker/metadata-files.ts';
import {MetadataLifecycle} from '../src/moonraker/metadata-lifecycle.ts';
import {MetadataScanIntents} from '../src/moonraker/metadata-intents.ts';
import {MetadataSnapshots} from '../src/moonraker/metadata-snapshots.ts';
import {MetadataVersions} from '../src/moonraker/metadata-versions.ts';
import {ThumbnailStorage} from '../src/moonraker/thumbnail-storage.ts';
import {MetadataExtractor} from '../src/moonraker/metadata-extractor.ts';
import {ThumbnailProcessor} from '../src/moonraker/thumbnail-process.ts';
import {FileMetadataStore} from '../src/moonraker/file-metadata.ts';
const dir=await mkdtemp(join(tmpdir(),'metadata-startup-')),signal=new AbortController().signal,count=128,stats=(v:number[])=>{v.sort((a,b)=>a-b);return {medianMs:v[Math.floor(v.length/2)],p95Ms:v[Math.ceil(v.length*.95)-1]};};
const extractor=await MetadataExtractor.open(),processor=await ThumbnailProcessor.open();let images=await ThumbnailStorage.open(join(dir,'images')),intents=await MetadataScanIntents.open(join(dir,'intents')),snapshots=await MetadataSnapshots.open(join(dir,'snapshots')),versions=await MetadataVersions.open(join(dir,'versions')),cache=new FileMetadataStore(),owner=new MetadataLifecycle({extractor,processor,images,intents,snapshots,versions,cache}),files=await MetadataFiles.open({root:dir,lifecycle:owner});
try{
 const data='; generated by PrusaSlicer 2.9.0 on 2026-09-21 at 12:00:00\n; layer_height = 0.2\nG1 X1\n',readPath=join(dir,'read.bin');await writeFile(readPath,Buffer.alloc(65536));
 for(let i=0;i<count;i++){const name=`part-${i}.gcode`;await writeFile(join(dir,name),data);assert.equal((await files.rescan(name,signal)).layer_height,.2);}
 await files.close();await owner.close();await images.close();await intents.close();await snapshots.close();await versions.close();
 const opened=performance.now();images=await ThumbnailStorage.open(join(dir,'images'));intents=await MetadataScanIntents.open(join(dir,'intents'));snapshots=await MetadataSnapshots.open(join(dir,'snapshots'));versions=await MetadataVersions.open(join(dir,'versions'));cache=new FileMetadataStore();owner=new MetadataLifecycle({extractor,processor,images,intents,snapshots,versions,cache});files=await MetadataFiles.open({root:dir,lifecycle:owner});const reopenMs=performance.now()-opened,first=performance.now();assert.deepEqual(await files.restoreSelected(signal),{restored:count,unavailable:0});const firstRestoreMs=performance.now()-first;
 const samples:number[]=[],reads:number[]=[],loop=monitorEventLoopDelay({resolution:1});let stop=false,reader:Promise<void>|undefined;
 try{for(let i=0;i<16;i++){if(i===5){loop.enable();reader=(async()=>{while(!stop){const at=performance.now();await readFile(readPath);reads.push(performance.now()-at);}})();}const at=performance.now();assert.deepEqual(await files.restoreSelected(signal),{restored:count,unavailable:0});if(i>=5)samples.push(performance.now()-at);for(let n=0;n<count;n++)assert.equal(cache.metadata(`part-${n}.gcode`).layer_height,.2);}}
 finally{stop=true;await reader;loop.disable();}
 const config=join(dir,'moonraker.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0\n');const startup=performance.now(),server=await ConfiguredMoonraker.load(config,{metadataFiles:files,authorize(){},information:{connected:false,state:'disconnected',components:['application'],failedComponents:[],directories:[],warnings:[],version:'benchmark',missingRequirements:[]}});let configuredStartupMs:number;try{const address=await server.start();configuredStartupMs=performance.now()-startup;assert.deepEqual(server.metadataRecovery,{restored:count,unavailable:0});const response=await fetch(`http://127.0.0.1:${address.port}/server/files/metadata?filename=part-0.gcode`);assert.equal(response.status,200);assert.equal((await response.json() as any).result.layer_height,.2);}finally{await server.close();}
 console.log(JSON.stringify({node:process.version,files:count,warmups:5,runs:11,reopenMs,firstRestoreMs,configuredStartupMs,restoreSelected:stats(samples),parentRead64KiB:stats(reads),parentEventLoop:{p95Ms:loop.percentile(95)/1e6,maxMs:loop.max/1e6},scope:'128 persisted selected files without images. Stores, root and public cache recreated before first restore. Worker processes retained; no parsing during recovery. Warm repetitions still reread snapshots and reopen sources for fingerprint validation. Configured startup includes config read, endpoint registration, 128-file recovery and listening, measured once after warm batches; HTTP query correctness checked outside its timer. No startup directory discovery, Python comparison, target-board or physical printing claim.'},null,2));
}finally{await files.close();await owner.close();await extractor.close();await processor.close();await images.close();await intents.close();await snapshots.close();await versions.close();await rm(dir,{recursive:true,force:true});}
