import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,open,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {monitorEventLoopDelay} from 'node:perf_hooks';
import {MetadataExtractor,type MetadataFieldExtraction} from '../src/moonraker/metadata-extractor.ts';

// Same four byte inputs and 5 warm/11 retained rounds as metadata-extractor.ts.
// Compare the Node implementation before this cleanup change; no Python oracle
// or source installation is introduced into the product.
const baseline=process.env.ANYRAID_METADATA_BASELINE;
if(!baseline)throw new Error('Set ANYRAID_METADATA_BASELINE to an unchanged baseline repository');
const hashes={
 'metadata-extractor.ts':'373963efd5b64fd93e663b83be90efa04d80956478571761ab07a023a16a15a1',
 'metadata-extractor-worker.ts':'7ec5e608732d484b5a1c6d1447b146aedfb9179696d679cdc0572005a9afa6b2'
};
for(const [name,hash] of Object.entries(hashes))assert.equal(createHash('sha256').update(await readFile(join(baseline,'host/src/moonraker',name))).digest('hex'),hash,'Baseline source changed');
const Original=(await import(pathToFileURL(join(baseline,'host/src/moonraker/metadata-extractor.ts')).href)).MetadataExtractor as typeof MetadataExtractor;
const texts=['; generated by PrusaSlicer 2.8 on 2026-01-01 at 12:34:56\n'+'G1 Z.2 X1 F1200\n'.repeat(160000)+'; layer_height = .2\n; first_layer_height = 150%\n; filament used [mm] = 1234.5\n','Cura_SteamEngine 5.0\n;MINZ:.2\n;MAXZ:20\n;TIME:3600\n'+'G1 X1 Y2 E3\n'.repeat(300000),'; BambuStudio 2.0\n; initial_layer_print_height = .2\n; max_z_height: 20\n'+'G1 X1 Y2 E3\n'.repeat(300000),'G1 Z.2 X1\n'.repeat(200000)];
const directory=await mkdtemp(join(tmpdir(),'metadata-close-bench-')),expected:MetadataFieldExtraction[]=[];
const stats=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return {medianMs:sorted[5],p95Ms:sorted[10],samplesMs:values};};
try{
 const paths:string[]=[];for(const [i,text] of texts.entries()){const path=join(directory,i+'.gcode');await writeFile(path,text);paths.push(path);}
 const reports=[];
 for(const [label,Factory] of [['original',Original],['acknowledged-close',MetadataExtractor]] as const){
  const owner=await Factory.open(),samples:number[][]=paths.map(()=>[]),eventLoop=monitorEventLoopDelay({resolution:1});eventLoop.enable();
  try{
   for(let i=0;i<16;i++)for(const [j,path] of paths.entries()){
    const started=performance.now(),source=await open(path,'r');
    try{const result=await owner.extract(source,new AbortController().signal);if(i>=5)samples[j].push(performance.now()-started);
     const value={fields:result.fields,objects:result.objects};if(label==='original')expected[j]=value;else assert.deepEqual(value,expected[j]);
    }finally{await source.close();}
   }
   eventLoop.disable();const closing=performance.now();await owner.close();
   reports.push({label,scans:samples.map(stats),parentEventLoop:{p95Ms:eventLoop.percentile(95)/1e6,maxMs:eventLoop.max/1e6},completedWorkCloseMs:performance.now()-closing});
  }finally{eventLoop.disable();await owner.close();}
 }
 console.log(JSON.stringify({node:process.version,baselineHashes:hashes,warmups:5,runs:11,variants:['PrusaSlicer','Cura','BambuStudio','UnknownSlicer'],bytes:texts.map(v=>Buffer.byteLength(v)),reports,scope:'Sequential desktop Node baseline then candidate. Original byte inputs, source transfer/stat/parse/close and field equality retained. No target board, mixed printing, Python comparison or statistical non-regression claim.'},null,2));
}finally{await rm(directory,{recursive:true,force:true});}
