import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {mkdtemp,writeFile,open,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {performance,monitorEventLoopDelay} from 'node:perf_hooks';
import {MetadataExtractor} from '../src/moonraker/metadata-extractor.ts';
const source=process.env.MOONRAKER_METADATA_SOURCE;if(!source)throw new Error('Set MOONRAKER_METADATA_SOURCE');assert.equal(createHash('sha256').update(readFileSync(source)).digest('hex'),'ae2488ff23e6ddcaf961b063506dad1a7141b38b92102bc174422ed244641d2e');
const directory=await mkdtemp(join(tmpdir(),'metadata-extraction-bench-'));let extractor:MetadataExtractor|undefined;
const texts=['; generated by PrusaSlicer 2.8 on 2026-01-01 at 12:34:56\n'+'G1 Z.2 X1 F1200\n'.repeat(160000)+'; layer_height = .2\n; first_layer_height = 150%\n; filament used [mm] = 1234.5\n','Cura_SteamEngine 5.0\n;MINZ:.2\n;MAXZ:20\n;TIME:3600\n'+'G1 X1 Y2 E3\n'.repeat(300000),'; BambuStudio 2.0\n; initial_layer_print_height = .2\n; max_z_height: 20\n'+'G1 X1 Y2 E3\n'.repeat(300000),'G1 Z.2 X1\n'.repeat(200000)];
const python=String.raw`
import ast,re,json,sys,time,logging,os
from typing import *
r=json.load(sys.stdin);m=ast.parse(open(r['source']).read());READ_SIZE=1024**2;logger=logging.getLogger('metadata')
exec('from __future__ import annotations\n'+ast.unparse(ast.Module(body=[n for n in m.body if isinstance(n,(ast.ClassDef,ast.FunctionDef))],type_ignores=[])),globals())
def parse(path):
 obj=BaseSlicer.from_file(path);result=dict(size=obj.size,modified=os.path.getmtime(path),slicer=obj.slicer_name,slicer_version=obj.slicer_version)
 for name in vars(BaseSlicer):
  if name.startswith('parse_') and name!='parse_thumbnails':
   value=getattr(obj,name)()
   if value is not None:result[name[6:]]=value
 return result
results=[parse(path) for path in r['paths']];samples=[[] for _ in r['paths']]
for i in range(16):
 for j,path in enumerate(r['paths']):
  t=time.perf_counter();parse(path);elapsed=(time.perf_counter()-t)*1000
  if i>=5:samples[j].append(elapsed)
print(json.dumps(dict(results=results,samples=samples,python=sys.version.split()[0])))
`;
try{
 const paths:string[]=[];for(const [i,text] of texts.entries()){const path=join(directory,String(i)+'.gcode');await writeFile(path,text);paths.push(path);}
 const child=spawnSync('/usr/bin/python3',['-c',python],{input:JSON.stringify({source,paths}),encoding:'utf8',maxBuffer:8*1024**2,timeout:60000});if(child.status!==0)throw new Error(child.stderr);const oracle=JSON.parse(child.stdout);
 extractor=await MetadataExtractor.open();const delay=monitorEventLoopDelay({resolution:1});delay.enable();const samples:number[][]=paths.map(()=>[]);
 for(let i=0;i<16;i++)for(const [j,path] of paths.entries()){const begin=performance.now(),file=await open(path,'r');try{const result=await extractor.extract(file,new AbortController().signal);if(i>=5)samples[j].push(performance.now()-begin);assert.deepEqual(result.fields,oracle.results[j]);}finally{await file.close();}}
 delay.disable();const stats=(values:number[])=>{values.sort((a,b)=>a-b);return {medianMs:values[5],p95Ms:values[10]};};
 console.log(JSON.stringify({node:process.version,python:oracle.python,warmups:5,runs:11,variants:['PrusaSlicer','Cura','BambuStudio','UnknownSlicer'],bytes:texts.map(v=>Buffer.byteLength(v)),nodeWorker:samples.map(stats),pythonOriginal:oracle.samples.map(stats),parentEventLoop:{p95Ms:delay.percentile(95)/1e6,maxMs:delay.max/1e6},scope:'Actual warm-file open/read/identify/non-image fields; Node Worker transfer, source stat validation and close included. Python first. No images/processors/UUID/cache publication/network or physical print acceptance.'},null,2));
}finally{await extractor?.close();await rm(directory,{recursive:true,force:true});}
