import assert from 'node:assert/strict';
import {mkdtemp,writeFile,open,rm,statfs} from 'node:fs/promises';
import {join} from 'node:path';
import {cpus} from 'node:os';
import {monitorEventLoopDelay} from 'node:perf_hooks';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
import {NativePrintUploads} from '../src/moonraker/native-print-uploads.ts';
import {MaintenanceGate} from '../src/operations/maintenance-gate.ts';
const nested=process.env.ANYRAID_BENCH_NAMESPACE==='nested',count=1024,warmups=3,runs=11,requests=100;
// Workspace filesystem, never silently substitute tmpfs for publication fsync.
const directory=await mkdtemp(new URL('../build/namespace-bench-',import.meta.url).pathname),signal=new AbortController().signal,files=await PublishedPrintFiles.open(join(directory,'files')),uploads=new NativePrintUploads(files,new MaintenanceGate());
const samples={catalog:[] as number[],directory:[] as number[],metadata:[] as number[],download:[] as number[]},loop=monitorEventLoopDelay({resolution:1});
try{
 const sourcePath=join(directory,'source'),body='; generated by PrusaSlicer 2.8 on 2026-01-01 at 12:34:56\n; layer_height = .2\n; first_layer_height = 150%\nG1 X1\n';await writeFile(sourcePath,body);const source=await open(sourcePath,'r');
 try{
  if(nested)await files.mutateDirectory('parts',false,signal);
  for(let i=0;i<count;i++){const id='f'+String(i).padStart(4,'0');await files.publish(id,'part.gcode',source,signal,nested?'parts/'+id+'.gcode':undefined);}
 }finally{await source.close();}
 const filename=(nested?'parts/':'')+'f0000.gcode';await uploads.metadata({filename},signal);loop.enable();
 for(let run=0;run<warmups+runs;run++){
  for(let i=0;i<requests;i++){
   let begin=performance.now();const list=await uploads.list({},signal);assert(Array.isArray(list));assert.equal(list.length,count);JSON.stringify(list);if(run>=warmups)samples.catalog.push(performance.now()-begin);
   begin=performance.now();const dir=await uploads.directory({path:nested?'gcodes/parts':'gcodes',extended:true},signal) as {files:unknown[]};assert.equal(dir.files.length,count);JSON.stringify(dir);if(run>=warmups)samples.directory.push(performance.now()-begin);
   begin=performance.now();const metadata=await uploads.metadata({filename},signal);assert.equal(metadata.file_id,'f0000');assert.equal(metadata.layer_height,.2);JSON.stringify(metadata);if(run>=warmups)samples.metadata.push(performance.now()-begin);
   if(i%20===0){begin=performance.now();await uploads.download('/server/files/gcodes/'+filename,{signal,transport:'http',authorize(){}},async(file,s)=>{let bytes=0;for await(const chunk of file.reader.chunks(s))bytes+=chunk.length;assert.equal(bytes,Buffer.byteLength(body));});if(run>=warmups)samples.download.push(performance.now()-begin);}
  }
 }
 loop.disable();const stats=Object.fromEntries(Object.entries(samples).map(([name,values])=>{values.sort((a,b)=>a-b);return [name,{requests:values.length,medianMs:values[Math.floor(values.length*.5)],p95Ms:values[Math.floor(values.length*.95)],p99Ms:values[Math.floor(values.length*.99)]}];}));
 for(const name of ['catalog','directory','metadata'])assert(stats[name].p99Ms<50,name+' exceeds existing local API budget');assert.equal(uploads.status.downloadSnapshots.reservations,0);assert.equal(files.status.reservedBytes,0);
 console.log(JSON.stringify({node:process.version,cpu:cpus()[0].model,filesystemType:(await statfs(directory)).type,namespace:nested?'nested':'legacy-flat',files:count,warmups,runs,requestsPerRun:requests,stats,eventLoop:{p99Ms:loop.percentile(99)/1e6,maxMs:loop.max/1e6},scope:'Same explicit-ID workload supports isolated previous/current source comparison; includes JSON serialization and hot receipt checks on the workspace filesystem. Nested mode additionally exercises visible paths. Not target-board timing, cold storage, power-loss or actual printing proof.'},null,2));
}finally{loop.disable();await uploads.close();await files.close();await rm(directory,{recursive:true,force:true});}
