import assert from 'node:assert/strict';
import {mkdtemp,writeFile,open,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir,cpus} from 'node:os';
import {monitorEventLoopDelay} from 'node:perf_hooks';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
import {NativeFileMetadata} from '../src/moonraker/native-file-metadata.ts';
const dir=await mkdtemp(join(tmpdir(),'native-metadata-bench-')),files=await PublishedPrintFiles.open(join(dir,'files')),metadata=new NativeFileMetadata(files),signal=new AbortController().signal,results:unknown[]=[];
try{
 for(const size of [64*1024,4*1024**2,64*1024**2]){
  const header='; generated by PrusaSlicer 2.8 on 2026-01-01 at 12:34:56\n; layer_height = .2\n; first_layer_height = 150%\n',body=Buffer.alloc(size,59);body.write(header);const footer='\n; layer_height = .2\n; first_layer_height = 150%\n';body.write(footer,size-Buffer.byteLength(footer));const path=join(dir,'source');await writeFile(path,body);const source=await open(path,'r');
  try{for(let run=0;run<14;run++)await files.publish('f-'+size+'-'+run,'part.gcode',source,signal);}finally{await source.close();}
  const loop=monitorEventLoopDelay({resolution:1});loop.enable();const cold:number[]=[],hot:number[]=[];
  for(let run=0;run<14;run++){const name='f-'+size+'-'+run+'.gcode';let start=performance.now();const first=await metadata.metadata(name,signal);const uncached=performance.now()-start;assert.equal(first.first_layer_height,.3);start=performance.now();const repeated=await metadata.metadata(name,signal);const cached=performance.now()-start;assert.deepEqual(repeated,first);if(run>=3){cold.push(uncached);hot.push(cached);}}
  loop.disable();assert.equal(metadata.status.snapshots.reservations,0);const stats=(values:number[])=>{values.sort((a,b)=>a-b);return {medianMs:values[5],p95Ms:values[10]};};const cached=stats(hot);assert(cached.p95Ms<50,'Cached metadata exceeds API latency budget');results.push({bytes:size,cold:stats(cold),cached,eventLoop:{p99Ms:loop.percentile(99)/1e6,maxMs:loop.max/1e6}});
 }
 console.log(JSON.stringify({node:process.version,cpu:cpus()[0].model,warmups:3,runs:11,results,scope:'Local immutable files: cold path includes full SHA-256 sealed copy, bounded byte windows and Worker scalar extraction; cached path revalidates receipt identity. Excludes publication, HTTP and hardware. Worker startup is warmed; full-file metadata and images are not claimed.'},null,2));
}finally{await metadata.close();await files.close();await rm(dir,{recursive:true,force:true});}
