import assert from 'node:assert/strict';
import {mkdtemp,open,writeFile,readFile,rm,statfs,readdir,stat} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {monitorEventLoopDelay} from 'node:perf_hooks';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
const baselinePath=process.env.PUBLISHED_COPY_BASELINE;if(!baselinePath)throw new Error('Expected fixed pre-copy store in PUBLISHED_COPY_BASELINE');
const Baseline=(await import(pathToFileURL(baselinePath).href)).PublishedPrintFiles as typeof PublishedPrintFiles;
const directory=await mkdtemp(join(process.cwd(),'.published-copy-bench-')),signal=new AbortController().signal,stores:PublishedPrintFiles[]=[];
const summarize=(values:number[])=>{const s=[...values].sort((a,b)=>a-b);return {medianMs:s[Math.floor(s.length/2)],p95Ms:s[Math.floor(s.length*.95)],maxMs:s.at(-1)};};
try{
 const sourcePath=join(directory,'source');await writeFile(sourcePath,'G1 X1.000001\n');const source=await open(sourcePath,'r');
 try{for(const [index,Store] of [Baseline,PublishedPrintFiles].entries()){const store=await Store.open(join(directory,'files-'+index),{maxPublishedFiles:2048});stores.push(store);await store.mutateDirectory('parts',false,signal);await store.mutateDirectory('parts/empty',false,signal);for(let i=0;i<1024;i++)await store.publish(String(i).padStart(4,'0'),'part.gcode',source,signal,i<128?'parts/'+i+'.gcode':i+'.gcode');}}finally{await source.close();}
 const samples:number[][]=[[],[]];for(let run=0;run<14;run++)for(const index of run%2?[1,0]:[0,1]){const begin=performance.now();for(let n=0;n<50;n++)assert.equal((await stores[index].catalog(signal)).length,1024);if(run>=3)samples[index].push((performance.now()-begin)/50);}
 const catalogs=samples.map(summarize);assert(catalogs[1].p95Ms<50,'Preserve catalog P95 budget');
 const store=stores[1],loop=monitorEventLoopDelay({resolution:1}),fileTimes:number[]=[],overwriteTimes:number[]=[],treeTimes:number[]=[],reads:number[]=[];loop.enable();await new Promise(resolve=>setTimeout(resolve,10));
 const measured=async(source:string,destination:string,expected:number)=>{const begin=performance.now();let finished=false;const mutation=(async()=>store.copy(await store.prepareCopy(source,destination,signal),signal))().finally(()=>{finished=true;});while(!finished){const start=performance.now(),count=(await store.catalog(signal)).length;assert(count===1024||count===expected,'Catalog must be a complete pre- or post-commit namespace');reads.push(performance.now()-start);await new Promise(resolve=>setTimeout(resolve,5));}await mutation;return performance.now()-begin;};
 for(let i=0;i<100;i++){const path='copy.gcode';fileTimes.push(await measured('parts/0.gcode',path,1025));const old=await store.resolvePath(path,signal);overwriteTimes.push(await measured('parts/1.gcode',path,1025));assert.notEqual(await store.resolvePath(path,signal),old);await store.remove(await store.resolvePath(path,signal),signal);}
 for(let i=0;i<8;i++){treeTimes.push(await measured('parts','copy',1152));assert(await store.hasDirectory('copy/empty',signal));for(const row of (await store.catalog(signal)).filter(r=>r.file.path?.startsWith('copy/')))await store.remove(row.file.id,signal);await store.mutateDirectory('copy/empty',true,signal);await store.mutateDirectory('copy',true,signal);}
 await new Promise(resolve=>setTimeout(resolve,10));loop.disable();assert.equal(store.filename('0000'),'parts/0.gcode');assert.equal((await store.catalog(signal)).length,1024);assert.equal(store.status.reservedBytes,0);assert.equal(await readFile(join(directory,'files-1',(await store.inspect('0000')).sha256+'.gcode'),'utf8'),'G1 X1.000001\n');
 const charged=(await Promise.all((await readdir(join(directory,'files-1'))).map(async name=>(await stat(join(directory,'files-1',name))).size))).reduce((a,b)=>a+b,0);assert.equal(store.status.storedBytes,charged);
 const eventLoop={p99Ms:loop.percentile(99)/1e6,maxMs:loop.max/1e6};assert(summarize(reads).p95Ms<50);assert(eventLoop.p99Ms<50);assert(eventLoop.maxMs<100);
 await store.close();const reopened=await PublishedPrintFiles.open(join(directory,'files-1'),{maxPublishedFiles:2048});stores[1]=reopened;assert.equal((await reopened.catalog(signal)).length,1024);assert.equal(reopened.status.storedBytes,charged);
 console.log(JSON.stringify({node:process.version,baseline:baselinePath,filesystemType:'0x'+(await statfs(directory,{bigint:true})).type.toString(16),files:1024,catalog:{baseline:catalogs[0],candidate:catalogs[1],medianRatio:catalogs[1].medianMs/catalogs[0].medianMs},fileCopies:{operations:100,...summarize(fileTimes)},overwrites:{operations:100,...summarize(overwriteTimes)},directoryCopies:{operations:8,filesPerOperation:128,...summarize(treeTimes)},concurrentCatalog:{reads:reads.length,...summarize(reads)},eventLoop,chargedBytes:charged,reopened:true,scope:'Durable copy/overwrite on the workspace filesystem; alternating pre-change cached catalog baseline and original 50 ms catalog/50-100 ms loop gates. Shared immutable content is hashed and receipts are new. No upstream Python copy-speed comparison, target-board budget, physical power-loss or actual print-duration acceptance.'}));
}finally{await Promise.all(stores.map(store=>store.close()));await rm(directory,{recursive:true,force:true});}
