import {once} from 'node:events';
import {performance} from 'node:perf_hooks';
import assert from 'node:assert/strict';
import {WebSocket} from 'ws';
import {JsonRpcDispatcher} from '../src/moonraker/rpc.ts';
import {MoonrakerNetwork} from '../src/moonraker/server.ts';
const rpc=new JsonRpcDispatcher();let completions=0;rpc.register('echo',['http','websocket'],(p,c)=>{if(p.barrier)c.afterResponse!(sent=>{assert.equal(sent,true);completions++;});return {position:[1.25,2,3],exact:'9007199254740993'};});const network=new MoonrakerNetwork(rpc,{authorize(){}}),address=await network.listen(),base=`http://127.0.0.1:${address.port}`,ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`),samples={websocket:{plain:[] as number[],barrier:[] as number[]},http:{plain:[] as number[],barrier:[] as number[]}};let id=0;
try{await once(ws,'open');for(const transport of ['websocket','http'] as const)for(let run=0;run<54;run++)for(const mode of (run%2?['plain','barrier']:['barrier','plain']) as ('plain'|'barrier')[]){const start=performance.now(),before=completions,count=transport==='websocket'?500:100;for(let i=0;i<count;i++){const request=JSON.stringify({jsonrpc:'2.0',method:'echo',params:{barrier:mode==='barrier'},id:++id});let result:any;if(transport==='websocket'){const pending=once(ws,'message');ws.send(request);result=JSON.parse(String((await pending)[0]));}else result=await(await fetch(base+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request})).json();assert.equal(result.id,id);assert.deepEqual(result.result,{position:[1.25,2,3],exact:'9007199254740993'});}assert.equal(completions-before,mode==='barrier'?count:0);if(run>=3)samples[transport][mode].push(performance.now()-start);}}finally{ws.terminate();await network.close();}
const summary=Object.fromEntries(Object.entries(samples).map(([transport,modes])=>[transport,Object.fromEntries(Object.entries(modes).map(([mode,times])=>{times.sort((a,b)=>a-b);return [mode,{medianMs:times[25],p95Ms:times[48]}];}))]));console.log(JSON.stringify({node:process.version,samples:51,websocketRequests:500,httpRequests:100,completions,results:summary,scope:'Alternating real network serial echo with versus without one synchronous completion callback. Includes complete reply consumption and exact result checks. Measures barrier overhead only; no subscription fanout or printer acceptance.'},null,2));
