import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {performance} from 'node:perf_hooks';
import {identifySlicer} from '../src/moonraker/slicer-identification.ts';
import {parseUnknownMetadata} from '../src/moonraker/metadata-common.ts';
const source=process.env.MOONRAKER_METADATA_SOURCE;if(!source)throw new Error('Set MOONRAKER_METADATA_SOURCE');
assert.equal(createHash('sha256').update(readFileSync(source)).digest('hex'),'ae2488ff23e6ddcaf961b063506dad1a7141b38b92102bc174422ed244641d2e');
const banners=['','Slic3r Prusa Edition 1.4 on date','Slic3r 1.3 on date','; BambuStudio-xx 2.0\r','; generated by New Fork 1.2 on 2026-01-01 at 12:34:56','; generated by Nameless on 2026-01-01 at 12:34:56','; generated by Slic3r on 2026-01-01 at 12:34:56','OrcaSlicer 2.3 on date','Cura_SteamEngine 5.0\r\u2028tail','Simplify3D(R) Version 5.1','; KISSlicer\n; version 1 2 3','; KISSlicer','; ideaMaker 5.2, date','<IceSL 2.4>','<IceSL dev>','<IceSL ²beta>','; Generated by Kiri:Moto 3.1','; Generated by Kiri:Moto (SimplyPrint) beta'];
const headers=[...banners,...banners.flatMap(a=>banners.map(b=>a+'\n'+b)),...['\u001c','\ufeff','\u0085','\u00a0'].flatMap(s=>['Cura_SteamEngine'+s+'5','Slic3r'+s+'١.٢ on date']),'; generated by Fork 1 on ٢٠٢٦-٠١-٠١ at ١٢:٣٤:٥٦','; generated by BambuStudio 1 on 2026-01-01 at 12:34:56'];
const texts=['','G1 X1\n',';😀\nG1 Z.2 X1\nM109 S210\nM190 S60\nM191 S40\nG1 Z12.5 X2\n;尾\n','\nG١ X1\r\nM2 X3\n','\nG1 Z-1 X\nG1 Z1e2 X\n','\nG1\u001cZ.1\u0085\nG1 Z2.0 X\n',';x\nG1 Z0.2 X1\n'.repeat(50000)];
let seed=42;const parts=['\n','G1','M٢',' X1','\r','😀',';',' Z.2','\u0085','\u001c','G2\n','\nM1 X\n'];for(let i=0;i<1000;i++){let text='';for(let j=0;j<20;j++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;text+=parts[seed%parts.length];}texts.splice(texts.length-1,0,text);}
const python=String.raw`
import ast,re,sys,json,time,logging
from typing import *
logging.disable(logging.CRITICAL)
r=json.load(sys.stdin);m=ast.parse(open(r['source']).read());nodes=[n for n in m.body if isinstance(n,(ast.ClassDef,ast.FunctionDef))]
READ_SIZE=1024**2
exec('from __future__ import annotations\n'+ast.unparse(ast.Module(body=nodes,type_ignores=[])),globals())
def identify(h):
 for cls in BaseSlicer.registered_slicers:
  ident=cls.identify(h)
  if ident is not None:return dict(family=cls.__name__,name=ident[0],version=ident[1])
 return dict(family='UnknownSlicer',name='Unknown',version='?')
def parse(s):
 obj=UnknownSlicer('',len(s.encode()),s);return {n[6:]:v for n in ['parse_gcode_start_byte','parse_gcode_end_byte','parse_first_layer_height','parse_object_height','parse_first_layer_extr_temp','parse_first_layer_bed_temp','parse_chamber_temp'] if (v:=getattr(obj,n)()) is not None}
ids=[identify(h) for h in r['headers']];parsed=[parse(s) for s in r['texts']];samples=[]
for i in range(16):
 t=time.perf_counter()
 for h in r['headers']:identify(h)
 parse(r['texts'][-1]);elapsed=(time.perf_counter()-t)*1000
 if i>=5:samples.append(elapsed)
print(json.dumps(dict(ids=ids,parsed=parsed,samples=samples,python=sys.version.split()[0])))
`;
const child=spawnSync('/usr/bin/python3',['-c',python],{input:JSON.stringify({source,headers,texts}),encoding:'utf8',timeout:60000,maxBuffer:8*1024**2});if(child.status!==0)throw new Error(child.stderr);const oracle=JSON.parse(child.stdout);
const parse=(text:string)=>parseUnknownMetadata({size:Buffer.byteLength(text),header:Array.from(text).slice(0,1024**2).join(''),footer:Array.from(text).slice(-(1024**2)).join('')});
assert.deepEqual(headers.map(identifySlicer),oracle.ids);assert.deepEqual(texts.map(parse),oracle.parsed);
const prepared={size:Buffer.byteLength(texts.at(-1)!),header:texts.at(-1)!,footer:texts.at(-1)!},samples:number[]=[];
for(let i=0;i<16;i++){const begin=performance.now();headers.forEach(identifySlicer);parseUnknownMetadata(prepared);if(i>=5)samples.push(performance.now()-begin);}
const stats=(values:number[])=>{values.sort((a,b)=>a-b);return {medianMs:values[5],p95Ms:values[10]};};
console.log(JSON.stringify({node:process.version,python:oracle.python,identificationFixtures:headers.length,fieldFixtures:texts.length,warmups:5,runs:11,parseBytes:prepared.size,nodeResult:stats(samples),pythonResult:stats(oracle.samples),scope:'All fixed upstream slicer identifiers plus shared and UnknownSlicer fields; batch identification and large text parsing, no IO/images/known-family fields or print timing.'},null,2));
