import {createServer,type Socket} from 'node:net';
import {once} from 'node:events';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {performance} from 'node:perf_hooks';
import {WebSocket} from 'ws';
import assert from 'node:assert/strict';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import type {Json} from '../src/moonraker/rpc.ts';
const wire=(v:unknown)=>JSON.stringify(v)+'\x03',root=await mkdtemp(join(tmpdir(),'subscription-wire-'));
async function setup(mode:'subscription'|'direct'){
 const socketPath=join(root,mode+'.sock');let klippy!:Socket,clock=0,counts=Array(10).fill(0),completed:()=>void=()=>{};const peer=createServer(socket=>{klippy=socket;let buffer='';socket.on('data',data=>{buffer+=data.toString();let at:number;while((at=buffer.indexOf('\x03'))>=0){const m=JSON.parse(buffer.slice(0,at));buffer=buffer.slice(at+1);let result:any={};switch(m.method){case 'info':result={state:'ready',state_message:'Ready'};break;case 'list_endpoints':result={endpoints:['objects/subscribe','objects/list']};break;case 'objects/list':result={objects:['virtual_sdcard','display_status','pause_resume']};break;case 'objects/subscribe':result={eventtime:clock,status:{webhooks:{state:'ready',state_message:'Ready'},...(m.params.objects.toolhead?{toolhead:{position:[0,2,3]}}:{})}};break;}socket.write(wire({id:m.id,result}));}});});await new Promise<void>(r=>peer.listen(socketPath,r));const config=join(root,mode+'.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'bench',missingRequirements:[]},authorize(){},authorizeNotification(){}}),address=await server.start(),clients:WebSocket[]=[];
 await server.attachKlippy(socketPath,{onStatus:(status,time)=>{if(mode==='direct'){const fields=status.toolhead as Record<string,Json>;for(const client of server.clients)void server.notifyAuthorized(client.id,'notify_status_update',[{toolhead:{position:fields.position}},time]);}}});
 for(let i=0;i<10;i++){const ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);clients.push(ws);await once(ws,'open');if(mode==='subscription'){const response=once(ws,'message');ws.send(JSON.stringify({jsonrpc:'2.0',method:'printer.objects.subscribe',params:{objects:{toolhead:['position']}},id:i+1}));const value=JSON.parse(String((await response)[0]));assert.equal(value.id,i+1);assert.ok(value.result);}ws.on('message',message=>{const value=JSON.parse(String(message));assert.equal(value.method,'notify_status_update');assert.deepEqual(Object.keys(value.params[0].toolhead),['position']);counts[i]++;if(counts.every(n=>n===200))completed();});}
 return {async sample(){counts=Array(10).fill(0);let timer:ReturnType<typeof setTimeout>;const done=new Promise<void>((resolve,reject)=>{completed=resolve;timer=setTimeout(()=>reject(new Error('Delivery timeout')),5000);});const start=performance.now();try{for(let i=0;i<200;i++)klippy.write(wire({method:'process_status_update',params:{eventtime:++clock,status:{toolhead:{position:[i,2,3],velocity:100}}}}));await done;return performance.now()-start;}finally{clearTimeout(timer!);}},async close(){for(const ws of clients)ws.terminate();await server.close();klippy.destroy();await new Promise<void>(r=>peer.close(()=>r()));}};
}
const subscription=await setup('subscription'),direct=await setup('direct'),samples={subscription:[] as number[],direct:[] as number[]};try{for(let run=0;run<54;run++)for(const mode of (run%2?['subscription','direct']:['direct','subscription']) as ('subscription'|'direct')[]){const time=await(mode==='subscription'?subscription:direct).sample();if(run>=3)samples[mode].push(time);}}finally{await subscription.close();await direct.close();await rm(root,{recursive:true,force:true});}
console.log(JSON.stringify({node:process.version,samples:51,clients:10,updates:200,deliveries:2000,results:Object.fromEntries(Object.entries(samples).map(([mode,times])=>{times.sort((a,b)=>a-b);return [mode,{medianMs:times[25],p95Ms:times[48]}];})),scope:'Real Unix Klippy notifications through cache and 10 real WebSocket receivers. Full public subscription route versus manually projected per-client authorized notifications. Alternating order and complete receive counts; no hardware printing or Python end-to-end equivalence claim.'},null,2));
