// GPL-3.0-or-later. Surface selection from graph_mesh.py (Eric Callahan, 2024).
import {meshGrid,type MeshParams} from './mesh-analysis.ts';
export type MeshSurfaceType='probedz'|'meshz'|'overlay'|'delta';
export interface MeshSurface {name:string;x:number[];y:number[];z:number[];}
export interface MeshSurfacePlot {type:MeshSurfaceType;title:string;surfaces:MeshSurface[];bounds:{x:[number,number];y:[number,number];z:[number,number]};}
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new TypeError('Expected mesh object');return v as Record<string,unknown>;};
export function meshSurfacePlot(value:unknown,type:MeshSurfaceType,profile?:string,scalePlot=false):MeshSurfacePlot{
 if(!['probedz','meshz','overlay','delta'].includes(type))throw new RangeError('Unknown surface type');const data=object(value),surfaces:MeshSurface[]=[];
 const current=()=>{const m=object(data.current_mesh);if(!Object.keys(m).length)throw new Error('No current mesh data in dump');if(typeof m.name!=='string')throw new TypeError('Invalid current mesh name');return m;};
 const saved=()=>{if(profile===undefined)throw new Error('A profile is required');const profiles=object(data.profiles);if(!Object.hasOwn(profiles,profile))throw new Error('Profile not found');return object(profiles[profile]);};
 const add=(m:Record<string,unknown>,field:string,name:string)=>{if(!name||name.length>1024)throw new RangeError('Invalid mesh name');const g=meshGrid(m[field] as number[][],object(m.mesh_params) as unknown as MeshParams);const surface={name,x:Array.from(g.x),y:Array.from(g.y),z:Array.from(g.z)};surfaces.push(surface);return surface;};
 let title:string;if(type==='probedz'){const m=profile===undefined?current():saved(),name=profile??String(m.name);add(m,profile===undefined?'probed_matrix':'points',name);title=`Probed Mesh (${name})`;}else if(type==='meshz'){const m=current();add(m,'mesh_matrix',String(m.name));title=`Interpolated Mesh (${m.name})`;}else{const p=saved(),c=current();if(type==='overlay'){add(p,'points',profile!);add(c,'probed_matrix',String(c.name));title='Probed Mesh Overlay';}else{const a=object(p.mesh_params),b=object(c.mesh_params);for(const field of ['x_count','y_count','min_x','max_x','min_y','max_y'])if(typeof a[field]!=='number'||typeof b[field]!=='number'||!Number.isFinite(a[field])||!Number.isFinite(b[field])||Math.abs((a[field] as number)-(b[field] as number))>=1e-6)throw new RangeError(`Mesh parameter mismatch: ${field}`);const pgrid=meshGrid(p.points as number[][],a as unknown as MeshParams),surface=add(c,'probed_matrix',`${c.name} - ${profile}`);if(surface.x.length!==pgrid.x.length||surface.y.length!==pgrid.y.length)throw new RangeError('Mesh matrix dimensions differ');for(let i=0;i<surface.z.length;i++){surface.z[i]-=pgrid.z[i];if(!Number.isFinite(surface.z[i]))throw new RangeError('Mesh delta overflow');}title=`Probed Mesh Delta (${c.name} - ${profile})`;}}
 let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity,peak=0;for(const s of surfaces){xmin=Math.min(xmin,s.x[0]);xmax=Math.max(xmax,s.x.at(-1)!);ymin=Math.min(ymin,s.y[0]);ymax=Math.max(ymax,s.y.at(-1)!);for(const z of s.z)peak=Math.max(peak,Math.abs(z));}
 if(scalePlot){const a=data.axis_minimum,b=data.axis_maximum;if(!Array.isArray(a)||!Array.isArray(b)||a.length<2||b.length<2)throw new RangeError('Missing machine axis bounds');[xmin,ymin]=a;[xmax,ymax]=b;}
 const zmax=peak*3||.001;if(![xmin,xmax,ymin,ymax,zmax,xmax-xmin,ymax-ymin].every(Number.isFinite)||xmax<=xmin||ymax<=ymin)throw new RangeError('Invalid surface range');return {type,title,surfaces,bounds:{x:[xmin,xmax],y:[ymin,ymax],z:[-zmax,zmax]}};
}
const escape=(s:string)=>s.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'�').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
type Vertex=[number,number,number];
function clip(vertices:Vertex[],axis:0|1,limit:number,lower:boolean):Vertex[]{const result:Vertex[]=[];for(let i=0;i<vertices.length;i++){const a=vertices[i],b=vertices[(i+1)%vertices.length],inside=(p:Vertex)=>lower?p[axis]>=limit:p[axis]<=limit,ai=inside(a),bi=inside(b);if(ai)result.push(a);if(ai!==bi){const t=(limit-a[axis])/(b[axis]-a[axis]);const p=a.map((v,k)=>v*(1-t)+b[k]*t) as Vertex;p[axis]=limit;if(!p.every(Number.isFinite))throw new RangeError('Surface clipping overflow');result.push(p);}}return result;}
export function renderMeshSurfaceSvg(plot:MeshSurfacePlot):string{
 if(!plot.surfaces.length||plot.surfaces.length>2||plot.title.length>4096)throw new RangeError('Invalid surface plot');const {x:[xmin,xmax],y:[ymin,ymax],z:[zmin,zmax]}=plot.bounds,span=Math.max(xmax-xmin,ymax-ymin);
 if(![xmin,xmax,ymin,ymax,zmin,zmax,span].every(Number.isFinite)||xmax<=xmin||ymax<=ymin||zmax<=0||zmin!==-zmax)throw new RangeError('Invalid surface bounds');
 let faces=0;for(const s of plot.surfaces){if(s.x.length<2||s.y.length<2||s.z.length!==s.x.length*s.y.length||s.z.length>1000000||s.name.length>1024)throw new RangeError('Invalid surface grid');for(const a of [s.x,s.y])for(let i=0;i<a.length;i++)if(!Number.isFinite(a[i])||i>0&&a[i]<=a[i-1])throw new RangeError('Invalid surface coordinates');if(!s.z.every(Number.isFinite))throw new RangeError('Invalid surface height');faces+=(s.x.length-1)*(s.y.length-1);}if(faces>50000)throw new RangeError('Surface image exceeds 50000 cells; use JSON for full grid');
 const project=([x,y,z]:Vertex)=>{const nx=(x-xmin)/span-(xmax-xmin)/span/2,ny=(y-ymin)/span-(ymax-ymin)/span/2,nz=z/zmax;const p=[470+350*(nx-ny),355+120*(nx+ny)-160*nz,nx+ny+1.5*nz];if(!p.every(Number.isFinite))throw new RangeError('Surface projection overflow');return p;},fmt=(v:number)=>v.toFixed(3),label=(v:number)=>Number(v.toPrecision(4)).toString();
 const out=[`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="760" viewBox="0 0 1000 760" role="img"><title>${escape(plot.title)}</title><desc>Fixed orthographic projection. X/Y share physical scale; Z is exaggerated and labeled separately. Overlay surfaces are translucent; JSON retains all original vertices.</desc><style>text{font-family:DejaVu Sans,sans-serif;font-size:12px;fill:#172033}</style><rect width="1000" height="760" fill="white"/><text x="500" y="30" text-anchor="middle" style="font-size:18px">${escape(Array.from(plot.title).slice(0,100).join(''))}</text>`],polygons:{depth:number;svg:string}[]=[];
 for(let index=0;index<plot.surfaces.length;index++){const s=plot.surfaces[index];let low=Infinity,high=-Infinity;for(const z of s.z){low=Math.min(low,z);high=Math.max(high,z);}const vertex=(r:number,c:number):Vertex=>[s.x[c],s.y[r],s.z[r*s.x.length+c]];
  for(let r=0;r<s.y.length-1;r++)for(let c=0;c<s.x.length-1;c++){let vertices=[vertex(r,c),vertex(r,c+1),vertex(r+1,c+1),vertex(r+1,c)];vertices=clip(clip(clip(clip(vertices,0,xmin,true),0,xmax,false),1,ymin,true),1,ymax,false);if(vertices.length<3)continue;const projected=vertices.map(project),mean=vertices.reduce((sum,p)=>sum+p[2]/vertices.length,0),ratio=high===low?.5:(mean-low)/(high-low),color=index?`rgb(${Math.round(180+75*ratio)},${Math.round(70+100*ratio)},40)`:`rgb(${Math.round(30+180*ratio)},${Math.round(90+110*ratio)},${Math.round(180-120*ratio)})`;polygons.push({depth:projected.reduce((sum,p)=>sum+p[2]/projected.length,0),svg:`<polygon points="${projected.map(p=>`${fmt(p[0])},${fmt(p[1])}`).join(' ')}" fill="${color}" fill-opacity="${plot.surfaces.length===2?.6:1}" stroke="${index?'#9a3412':'#334155'}" stroke-opacity=".3" stroke-width=".4"/>`});}
  out.push(`<defs><linearGradient id="surface-scale-${index}"><stop offset="0" stop-color="${index?'rgb(180,70,40)':'rgb(30,90,180)'}"/><stop offset="1" stop-color="${index?'rgb(255,170,40)':'rgb(210,200,60)'}"/></linearGradient></defs><text x="80" y="${660+index*34}"><title>${escape(s.name)}</title>${escape(Array.from(s.name).slice(0,40).join(''))}: Z ${label(low)} .. ${label(high)} mm</text><rect x="710" y="${647+index*34}" width="200" height="12" fill="${low===high?(index?'rgb(218,120,40)':'rgb(120,145,120)'):'url(#surface-scale-'+index+')'}"/><text x="710" y="${672+index*34}">${label(low)}</text><text x="910" y="${672+index*34}" text-anchor="end">${label(high)}</text>`);
 }
 polygons.sort((a,b)=>a.depth-b.depth);out.push(...polygons.map(p=>p.svg));const line=(a:Vertex,b:Vertex,text:string,leftLabel=false)=>{const p=project(a),q=project(b);out.push(`<path d="M${fmt(p[0])} ${fmt(p[1])}L${fmt(q[0])} ${fmt(q[1])}" stroke="#172033"/><text x="${fmt(q[0]+(leftLabel?-12:8))}" y="${fmt(q[1]+15)}" text-anchor="${leftLabel?'end':'start'}">${text}</text>`);};line([xmin,ymin,0],[xmax,ymin,0],`X ${label(xmin)}..${label(xmax)} mm`);line([xmin,ymin,0],[xmin,ymax,0],`Y ${label(ymin)}..${label(ymax)} mm`,true);line([xmin,ymin,zmin],[xmin,ymin,zmax],`Z ±${label(zmax)} mm`);out.push('<text x="500" y="735" text-anchor="middle">Fixed 3D view · Z scale exaggerated · Full coordinates available in JSON</text></svg>');const svg=out.join('');if(Buffer.byteLength(svg)>64*1024**2)throw new RangeError('Surface SVG size limit exceeded');return svg;
}
