// GPL-3.0-or-later. Bed-mesh diagnostics derived from graph_mesh.py.
// Original Copyright (C) 2024 Eric Callahan.
export interface MeshGrid {x:Float64Array;y:Float64Array;z:Float64Array;}
export interface MeshParams {min_x:number;max_x:number;min_y:number;max_y:number;}
export interface MeshStatistics {minimum:{value:number;x:number;y:number};maximum:{value:number;x:number;y:number};mean:number;standardDeviation:number;absoluteMaximum:number;absoluteMean:number;rows:number;columns:number;}
function mean(values:Float64Array,absolute=false):number{let largest=0;for(let i=0;i<values.length;i++)largest=Math.max(largest,Math.abs(values[i]));const divisor=largest>Number.MAX_VALUE/values.length?values.length:1;let sum=0,correction=0;for(let i=0;i<values.length;i++){const term=(absolute?Math.abs(values[i]):values[i])/divisor,next=sum+term;correction+=Math.abs(sum)>=Math.abs(term)?sum-next+term:term-next+sum;sum=next;}const result=(sum+correction)/(values.length/divisor);if(!Number.isFinite(result))throw new RangeError('Mesh mean overflow');return result;}
function coordinates(low:number,high:number,count:number):Float64Array{if(!Number.isFinite(low)||!Number.isFinite(high)||high<=low)throw new RangeError('Invalid mesh extent');const step=(high-low)/(count-1);if(!Number.isFinite(step)||step<=0)throw new RangeError('Mesh coordinate overflow');const result=Float64Array.from({length:count},(_,i)=>low+i*step);for(let i=1;i<count;i++)if(!Number.isFinite(result[i])||result[i]<=result[i-1])throw new RangeError('Mesh coordinate resolution exceeded');return result;}
export function meshGrid(matrix:readonly (readonly number[])[],params:MeshParams):MeshGrid{
 if(!Array.isArray(matrix)||matrix.length<2||matrix.length>1024||!Array.isArray(matrix[0])||matrix[0].length<2||matrix[0].length>1024||matrix.length*matrix[0].length>1000000)throw new RangeError('Invalid mesh dimensions');const rows=matrix.length,cols=matrix[0].length,z=new Float64Array(rows*cols);
 for(let row=0;row<rows;row++){if(!Array.isArray(matrix[row])||matrix[row].length!==cols)throw new RangeError('Ragged mesh');for(let col=0;col<cols;col++){const v=matrix[row][col];if(!Number.isFinite(v))throw new RangeError('Nonfinite mesh height');z[row*cols+col]=v;}}
 // Fix the legacy _format_mesh_data max_x typo on the Y axis.
 return {x:coordinates(params.min_x,params.max_x,cols),y:coordinates(params.min_y,params.max_y,rows),z};
}
function validate(grid:MeshGrid){const {x,y,z}=grid;if(![x,y,z].every(a=>a instanceof Float64Array&&!(a.buffer instanceof SharedArrayBuffer))||x.length<2||x.length>1024||y.length<2||y.length>1024||z.length!==x.length*y.length||z.length>1000000)throw new RangeError('Invalid mesh grid');for(const axis of [x,y])for(let i=0;i<axis.length;i++)if(!Number.isFinite(axis[i])||i>0&&axis[i]<=axis[i-1])throw new RangeError('Invalid mesh coordinates');for(let i=0;i<z.length;i++)if(!Number.isFinite(z[i]))throw new RangeError('Invalid mesh heights');}
export function meshStatistics(grid:MeshGrid):MeshStatistics{
 validate(grid);const {x,y,z}=grid,average=mean(z);let min=0,max=0,deviation=0;
 for(let i=0;i<z.length;i++){if(z[i]<z[min])min=i;if(z[i]>z[max])max=i;deviation=Math.max(deviation,Math.abs(z[i]-average));}if(!Number.isFinite(deviation))throw new RangeError('Mesh deviation overflow');
 let variance=0,correction=0;if(deviation)for(let i=0;i<z.length;i++){const term=((z[i]-average)/deviation)**2/z.length,next=variance+term;correction+=Math.abs(variance)>=Math.abs(term)?variance-next+term:term-next+variance;variance=next;}
 const at=(i:number)=>({value:z[i],x:x[i%x.length],y:y[Math.floor(i/x.length)]});return {minimum:at(min),maximum:at(max),mean:average,standardDeviation:deviation*Math.sqrt(Math.min(1,variance+correction)),absoluteMaximum:Math.max(Math.abs(z[min]),Math.abs(z[max])),absoluteMean:mean(z,true),rows:y.length,columns:x.length};
}
/** Delta is a - b; grids must match exactly, without silent broadcasting/interpolation. */
export function meshDifference(a:MeshGrid,b:MeshGrid):MeshGrid|null{
 validate(a);validate(b);if(a.x.length!==b.x.length||a.y.length!==b.y.length||!a.x.every((v,i)=>v===b.x[i])||!a.y.every((v,i)=>v===b.y[i]))return null;const z=new Float64Array(a.z.length);for(let i=0;i<z.length;i++){z[i]=a.z[i]-b.z[i];if(!Number.isFinite(z[i]))throw new RangeError('Mesh delta overflow');}return {x:a.x.slice(),y:a.y.slice(),z};
}
export type MeshPoint=readonly [number,number];
function points(values:readonly MeshPoint[]){if(!Array.isArray(values)||values.length>100000)throw new RangeError('Path point limit exceeded');for(const p of values)if(!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite))throw new RangeError('Invalid path point');}
const key=(point:MeshPoint)=>`${point[0]},${point[1]}`;
export function duplicateMeshPoints(path:readonly MeshPoint[]):{point:MeshPoint;count:number}[]{points(path);const counts=new Map<string,{point:MeshPoint;count:number}>();for(const p of path){const k=key(p),found=counts.get(k);if(found)found.count++;else counts.set(k,{point:[p[0],p[1]],count:1});}return [...counts.values()].filter(p=>p.count>1).sort((a,b)=>a.point[0]-b.point[0]||a.point[1]-b.point[1]);}
export function analyzeMeshPaths(original:readonly MeshPoint[],probe:readonly MeshPoint[],rapid:readonly (readonly [MeshPoint,boolean])[]){points(original);points(probe);if(!Array.isArray(rapid)||rapid.length>100000)throw new RangeError('Rapid path limit exceeded');const travel:MeshPoint[]=[],sampled:MeshPoint[]=[];for(const entry of rapid){if(!Array.isArray(entry)||entry.length!==2||typeof entry[1]!=='boolean')throw new RangeError('Invalid rapid entry');points([entry[0]]);travel.push(entry[0]);if(entry[1])sampled.push(entry[0]);}const probeKeys=new Set(probe.map(key)),sampledKeys=new Set(sampled.map(key));return {originalCount:original.length,probeCount:probe.length,rapidSampleCount:sampled.length,rapidMoveCount:travel.length,matches:sampled.length===probe.length&&sampled.every((p,i)=>key(p)===key(probe[i])),rapidOnly:sampled.filter(p=>!probeKeys.has(key(p))).map(p=>[...p]),probeOnly:probe.filter(p=>!sampledKeys.has(key(p))).map(p=>[...p]),probeDuplicates:duplicateMeshPoints(probe),rapidDuplicates:duplicateMeshPoints(travel)};}
