import type {StatsPlot} from './graphstats.ts';
const colors=['#15803d','#dc2626','#0891b2','#a16207','#7c3aed','#2563eb','#be185d','#475569'];
const escape=(value:string)=>value.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'�').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
function domain(low:number,high:number):[number,number]{if(low===Infinity)return [0,1];if(low===high){const pad=Math.abs(low)*.05||1;return [Math.max(-Number.MAX_VALUE,low-pad),Math.min(Number.MAX_VALUE,high+pad)];}return [low,high];}
function scale(value:number,range:readonly number[]):number{const span=range[1]-range[0];if(Number.isFinite(span)&&span>0)return (value-range[0])/span;const norm=Math.max(Math.abs(range[0]),Math.abs(range[1]))||1;return (value/norm-range[0]/norm)/(range[1]/norm-range[0]/norm);}
function tick(value:number):string{return value===0?'0':Number(value.toPrecision(4)).toString();}
/** Standalone diagnostic SVG, preserving every admitted point (no decimation). */
export interface PlotXAxis {label:string;format:'utc'|'number';}
export function renderStatsSvg(plot:StatsPlot,xAxis:PlotXAxis={label:'Time (UTC)',format:'utc'},yRanges?:readonly (readonly [number,number])[],fullLegend=false,reserveRightAxis=false):string{
 if(typeof fullLegend!=='boolean'||typeof reserveRightAxis!=='boolean')throw new TypeError('Invalid plot legend mode');
 if(plot.curves.length>128||plot.axes.length<1||plot.axes.length>2)throw new RangeError('Plot series capacity exceeded');
 if(yRanges&&(yRanges.length!==plot.axes.length||yRanges.some(r=>r.length!==2||!r.every(Number.isFinite)||r[0]>=r[1])))throw new RangeError('Invalid plot axis range');
 const labels=fullLegend?plot.curves.map(c=>{const chars=Array.from(c.label),lines:string[]=[];for(let i=0;i<chars.length;i+=60)lines.push(chars.slice(i,i+60).join(''));return lines.length?lines:[''];}):[];
 const legendHeight=fullLegend?labels.reduce((n,lines)=>n+lines.length*16+4,0):Math.ceil(plot.curves.length/3)*20;
 const width=800,height=Math.max(600,(fullLegend?520:220)+legendHeight),left=84,right=plot.axes.length===2||reserveRightAxis?100:36,top=66,bottom=70+legendHeight,w=width-left-right,h=height-top-bottom;
 let xmin=Infinity,xmax=-Infinity,points=0;const ymin=[Infinity,Infinity],ymax=[-Infinity,-Infinity];
 for(const c of plot.curves){if(c.times.length!==c.values.length||c.axis<0||c.axis>=plot.axes.length)throw new TypeError('Invalid plot curve');points+=c.times.length;if(points>500000)throw new RangeError('Plot point capacity exceeded');for(let i=0;i<c.times.length;i++){const x=c.times[i],y=c.values[i];if(!Number.isFinite(x)||!Number.isFinite(y)||x< -62135596800||x>=253402300800)throw new TypeError('Invalid plot coordinates');xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin[c.axis]=Math.min(ymin[c.axis],y);ymax[c.axis]=Math.max(ymax[c.axis],y);}}
 const xr=xmin===xmax&&Number.isFinite(xmin)?[xmin-.5,xmax+.5]:domain(xmin,xmax),yr=plot.axes.map((_,i)=>yRanges?.[i]??domain(ymin[i],ymax[i])),x=(value:number)=>left+scale(value,xr)*w,y=(value:number,axis:number)=>top+(1-scale(value,yr[axis]))*h;
 const parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img"><title>${escape(plot.title)}</title><desc>All ${points} data points; ${xAxis.format==='utc'?'time labels are UTC':'numeric horizontal axis'}. Plot values are diagnostic measurements.</desc><style>text{font-family:DejaVu Sans,sans-serif;font-size:11px;fill:#172033}.title{font-size:18px;font-weight:bold}.grid{stroke:#dce2e8;stroke-width:1}</style><rect width="100%" height="100%" fill="white"/><defs><clipPath id="plot"><rect x="${left}" y="${top}" width="${w}" height="${h}"/></clipPath></defs><text class="title" x="${width/2}" y="28" text-anchor="middle">${escape(plot.title.slice(0,90))}</text>`];
 for(let i=0;i<=5;i++){const t=i/5,px=left+t*w,py=top+(1-t)*h;parts.push(`<path class="grid" d="M${px} ${top}V${top+h}M${left} ${py}H${left+w}"/>`);const timestamp=xr[0]*(1-t)+xr[1]*t,date=new Date(timestamp*1000);const label=xAxis.format==='utc'&&Number.isFinite(date.getTime())?date.toISOString().slice(11,19):tick(timestamp);parts.push(`<text x="${px}" y="${top+h+20}" text-anchor="middle">${label}</text>`);for(let axis=0;axis<plot.axes.length;axis++){const range=yr[axis],label=tick(range[0]*(1-t)+range[1]*t);parts.push(`<text x="${axis?left+w+8:left-8}" y="${py+4}" text-anchor="${axis?'start':'end'}">${escape(label)}</text>`);}}
 parts.push(`<rect x="${left}" y="${top}" width="${w}" height="${h}" fill="none" stroke="#64748b"/><text x="${left+w/2}" y="${top+h+42}" text-anchor="middle">${escape(xAxis.label)}</text>`);
 plot.axes.forEach((label,i)=>parts.push(`<text transform="translate(${i?width-15:17} ${top+h/2}) rotate(${i?90:-90})" text-anchor="middle">${escape(label)}</text>`));
 parts.push('<g clip-path="url(#plot)">');plot.curves.forEach((c,index)=>{const color=colors[index%colors.length];parts.push(`<g data-curve-label="${escape(c.label)}">`);if(c.style==='points'){for(let i=0;i<c.times.length;i++)parts.push(`<circle cx="${x(c.times[i]).toFixed(3)}" cy="${y(c.values[i],c.axis).toFixed(3)}" r="1.6" fill="${color}"/>`);}else if(c.times.length){const path=c.times.map((time,i)=>`${i?'L':'M'}${x(time).toFixed(3)},${y(c.values[i],c.axis).toFixed(3)}`).join('');parts.push(`<path d="${path}" stroke="${color}" stroke-width="1.4" fill="none"/>`);if(c.times.length===1)parts.push(`<circle cx="${x(c.times[0])}" cy="${y(c.values[0],c.axis)}" r="2" fill="${color}"/>`);}parts.push('</g>');});parts.push('</g>');
 let offset=0;plot.curves.forEach((c,i)=>{const px=fullLegend?left:left+(i%3)*(width-left-25)/3,py=top+h+66+(fullLegend?offset:Math.floor(i/3)*20),lines=fullLegend?labels[i]:[Array.from(c.label).slice(0,25).join('')];parts.push(`<g><title>${escape(c.label)}</title><path d="M${px} ${py-4}h14" stroke="${colors[i%colors.length]}" stroke-width="2"/>`);lines.forEach((line,j)=>parts.push(`<text x="${px+20}" y="${py+j*16}">${escape(line)}</text>`));parts.push('</g>');offset+=lines.length*16+4;});parts.push('</svg>');const output=parts.join('');if(Buffer.byteLength(output)>64*1024**2)throw new RangeError('SVG output capacity exceeded');return output;
}

export interface StatsPanel {plot:StatsPlot;xAxis:PlotXAxis;yRanges?:readonly (readonly [number,number])[];fullLegend?:boolean;reserveRightAxis?:boolean;}
/** Stack independently clipped plots into one standalone document. */
export function renderStatsPanels(panels:readonly StatsPanel[]):string{
 if(!panels.length||panels.length>8)throw new RangeError('Expected 1 to 8 plot panels');
 let count=0;for(const panel of panels)for(const curve of panel.plot.curves){count+=curve.times.length;if(count>500000)throw new RangeError('Combined plot point capacity exceeded');}
 let height=0;const parts:string[]=[];panels.forEach((panel,i)=>{let svg=renderStatsSvg(panel.plot,panel.xAxis,panel.yRanges,panel.fullLegend,panel.reserveRightAxis);const match=/^<svg [^>]*height="(\d+)"/.exec(svg);if(!match)throw new Error('Missing generated SVG dimensions');const h=Number(match[1]);svg=svg.replace('<svg ',`<svg x="0" y="${height}" `).replaceAll('id="plot"',`id="panel${i}"`).replaceAll('clip-path="url(#plot)"',`clip-path="url(#panel${i})"`);parts.push(svg);height+=h;});
 const output=`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="${height}" viewBox="0 0 800 ${height}" role="img"><title>Diagnostic plots</title>${parts.join('')}</svg>`;if(Buffer.byteLength(output)>64*1024**2)throw new RangeError('SVG output capacity exceeded');return output;
}
