import unicode from '../../contracts/unicode-numeric-space-15.json' with {type:'json'};
import {pythonLower} from './python-lower.ts';
const charClass=(ranges:number[][])=>`[${ranges.map(([a,b])=>`\\u{${a.toString(16)}}${a===b?'':`-\\u{${b.toString(16)}}`}`).join('')}]`;
const decimal=charClass(unicode.decimal),space=charClass(unicode.space),digit=new RegExp(`^${charClass(unicode.digit)}`,'u');
/** Translate only the fixed patterns below, not arbitrary Python regular expressions.
 * Python dot excludes LF alone, unlike JavaScript dot. Unicode tables pin Python 3.12. */
export function metadataPattern(pattern:string,flags=''):RegExp{
 let result='',inClass=false;
 for(let i=0;i<pattern.length;i++){
  const char=pattern[i];
  if(char==='\\'){const next=pattern[++i];result+=next==='d'?decimal:next==='s'?space:'\\'+next;continue;}
  if(char==='[')inClass=true;else if(char===']')inClass=false;
  result+=char==='.'&&!inClass&&!flags.includes('s')?'[^\\n]':char;
 }
 return new RegExp(result,'u'+flags);
}
export type SlicerFamily='UnknownSlicer'|'PrusaSlicer'|'Slic3rPE'|'Slic3r'|'BambuStudio'|'Cura'|'Simplify3D'|'KISSlicer'|'IdeaMaker'|'IceSL'|'KiriMoto';
export interface SlicerIdentity {readonly family:SlicerFamily;readonly name:string;readonly version:string;}
const identity=(family:SlicerFamily,name:string,version:string):SlicerIdentity=>Object.freeze({family,name,version});
const pe=metadataPattern(String.raw`Slic3r\sPrusa\sEdition\s(.*)\son`),slic3r=metadataPattern(String.raw`Slic3r\s(\d.*)\son`),bambu=/; BambuStudio[^ ]* ([^\n]+)/u;
const generated=metadataPattern(String.raw`; generated by (.+?) on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}`);
const fallback=metadataPattern(String.raw`(PrusaSlicer|SuperSlicer|OrcaSlicer|MomentSlicer|SliCR-3D|A3dp-Slicer|QIDISlicer)\s(.*)\son`);
const patterns:[SlicerFamily,string,RegExp][]=[['Cura','Cura',metadataPattern(String.raw`Cura_SteamEngine\s(.*)`)],['Simplify3D','Simplify3D',metadataPattern(String.raw`Simplify3D\(R\)\sVersion\s(.*)`)]];
const kiss=metadataPattern(String.raw`;\sKISSlicer`),kissVersion=metadataPattern(String.raw`;\sversion\s(.*)`),idea=metadataPattern(String.raw`\sideaMaker\s(.*),`),ice=metadataPattern(String.raw`<IceSL\s(.*)>`);
const kiri=metadataPattern(String.raw`; Generated by Kiri:Moto (\d.+)`),simply=metadataPattern(String.raw`; Generated by Kiri:Moto \(SimplyPrint\) (.+)`);
/** Pass the decoded first byte window, not the constructor's codepoint header. */
export function identifySlicer(header:string):SlicerIdentity{
 let match=pe.exec(header);if(match)return identity('Slic3rPE','Slic3r PE',match[1]);
 match=slic3r.exec(header);if(match)return identity('Slic3r','Slic3r',match[1]);
 match=bambu.exec(header);if(match)return identity('BambuStudio','BambuStudio',match[1]);
 match=generated.exec(header);
 if(match){const split=match[1].lastIndexOf(' '),name=split<0?'':match[1].slice(0,split),version=match[1].slice(split+1);if(!['slic3r prusa edition','slic3r','bambustudio'].includes(pythonLower(name)))return identity('PrusaSlicer',name,version);}
 else {match=fallback.exec(header);if(match)return identity('PrusaSlicer',match[1],match[2]);}
 for(const [family,name,pattern] of patterns){match=pattern.exec(header);if(match)return identity(family,name,match[1]);}
 if(kiss.test(header))return identity('KISSlicer','KISSlicer',kissVersion.exec(header)?.[1].replaceAll(' ','-')??'?');
 match=idea.exec(header);if(match)return identity('IdeaMaker','IdeaMaker',match[1]);
 match=ice.exec(header);if(match){if(!match[1])throw new Error('Empty IceSL version');return identity('IceSL','IceSL',digit.test(match[1])?match[1]:'-');}
 match=kiri.exec(header);if(match)return identity('KiriMoto','Kiri:Moto',match[1]);
 match=simply.exec(header);if(match)return identity('KiriMoto','SimplyPrint',match[1]);
 return identity('UnknownSlicer','Unknown','?');
}
