import test from 'node:test';
import {once} from 'node:events';
import WebSocket from 'ws';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {setTimeout as delay} from 'node:timers/promises';
import {buildProductHost} from '../scripts/build-product-host.ts';
import {installProductDependencies} from '../test/helpers/product-install.ts';
import {configuredPrinterFixture} from '../test/helpers/configured-printer.ts';
import {productTransports} from '../test/helpers/product-transports.ts';
import {Thermistor} from '../src/thermal/thermistor.ts';
import {FrameDecoder} from '../src/protocol/codec.ts';

async function checkedFetch(input:string,options?:RequestInit){try{return await fetch(input,options);}catch(error){throw new Error((options?.method??'GET')+' '+new URL(input).pathname+' failed',{cause:error});}}
// The child loads only emitted JS, bundled addons and installed dependencies.
// PTY firmware stays in the parent; all product operations cross authenticated HTTP.
for(const loaded of [false,true])test(`load=${loaded}: compiled process uploads sealed file, heats, prints, reinitializes and stops on ADC fault without Python or TS loading`,{timeout:180000},async t=>{
 const dir=await mkdtemp(join(tmpdir(),'compiled-journey-')),app=join(dir,'app'),f=await configuredPrinterFixture(false,false);
 const transports:Awaited<ReturnType<typeof productTransports>>[]=[],timers=new Set<ReturnType<typeof setTimeout>>();
 const printerConfig=join(dir,'printer.cfg'),configPath=join(dir,'moonraker.conf'),manifest=join(dir,'machine.json'),trace=join(dir,'events.jsonl');
 let poll:ReturnType<typeof setInterval>|undefined,child:ReturnType<typeof spawn>|undefined,ended:Promise<{code:number|null;signal:NodeJS.Signals|null}>|undefined,watchdog:ReturnType<typeof setTimeout>|undefined,homed=0,stderr='',base='';
 const lifecycleEvents:{role:string;method:string}[]=[],eventSockets:WebSocket[]=[],fileEvents:{role:string;event:any;at:number}[]=[],eventStarts=new Map<string,number>(),eventLatencies:number[]=[];
 const wire:{firstStepLeadUs:number;steps:number}[]=[];
 const ready:Array<string>=[];let hot=false,thermal:ReturnType<typeof setInterval>|undefined;
 let stopLoad:()=>Promise<void>=async()=>{};const latencies:number[]=[],uploadTimes:number[]=[],directoryTimes:number[]=[],downloadTimes:number[]=[],metadataTimes:number[]=[],thumbnailTimes:number[]=[],deleteTimes:number[]=[];let loadGeneration=0;
 const converter=new Thermistor(4700,0,{points:[[25,100000],[150,1770],[250,230]]});
 async function nextTransport(){
  if(poll)clearInterval(poll);if(thermal)clearInterval(thermal);hot=false;assert.equal(timers.size,0);const transport=await productTransports(f.reader);transports.push(transport);
  await writeFile(printerConfig,Object.entries(transport.reader.source.original).map(([section,options])=>'['+section+']\n'+Object.entries(options).map(([key,value])=>key+': '+value.replaceAll('\n','\n  ')).join('\n')).join('\n\n'));
  const firmware=transport.firmware[0],decoder=new FrameDecoder(),stepClocks=new Map<number,number>();let cursor=0,sequence=1;
  firmware.peer.on('data',chunk=>{for(const frame of decoder.push(typeof chunk==='string'?Buffer.from(chunk):chunk)){
   if((frame[1]&15)!==sequence)continue;sequence=(sequence+1)&15;
   for(const command of firmware.dictionary.parseFrame(frame)){const p=command.parameters;
    if(command.name==='trsync_start'&&p.report_ticks===0)firmware.setTriggerReason(2,Number(p.oid));
    if(command.name==='reset_step_clock')stepClocks.set(Number(p.oid),Number(p.clock));
    if(command.name==='queue_step'){const oid=Number(p.oid),previous=stepClocks.get(oid);assert.notEqual(previous,undefined);const interval=Number(p.interval),count=Number(p.count),add=Number(p.add);wire.push({firstStepLeadUs:previous!+interval-firmware.currentClock(),steps:count});stepClocks.set(oid,previous!+count*interval+add*count*(count-1)/2);}
   }
  }});
  poll=setInterval(()=>{for(;cursor<firmware.outputs.length;cursor++){const entry=firmware.outputs[cursor],p=entry.parameters;if(entry.name!=='endstop_home'||!Number(p.sample_count))continue;const timer=setTimeout(()=>{timers.delete(timer);homed++;const clock=Number(p.clock),oid=Number(p.trsync_oid);firmware.setTriggerReason(1,oid);firmware.setEndstopState({homing:0,pin_value:0,next_clock:clock+Number(p.rest_ticks)},Number(p.oid));firmware.emit('trsync_state',{oid,can_trigger:0,trigger_reason:1,clock});},150);timers.add(timer);}},2);
  const aux=transport.firmware[1];thermal=setInterval(()=>{for(const entry of aux.outputs.filter(e=>e.name==='query_analog_in')){const p=entry.parameters,config=aux.outputs.find(e=>e.name==='config_analog_in'&&e.parameters.oid===p.oid);if(!config)continue;const temperature=hot?(config.parameters.pin==='PA2'||config.parameters.pin===2?220:80):25,raw=Math.round(converter.adc(temperature)*4095*Number(p.sample_count)),next=aux.currentClock()+Number(p.rest_ticks)-Number(p.sample_ticks)*Number(p.sample_count);aux.emit('analog_in_state',{oid:Number(p.oid),next_clock:next>>>0,values:Buffer.from([raw&255,raw>>8])});}},100);
  return transport;
 }
 try{
  await buildProductHost(app);const installation=await installProductDependencies(app);t.diagnostic(JSON.stringify({installation}));
  const png=await sharp({create:{width:80,height:40,channels:3,background:'#123456'}}).png().toBuffer(),encoded=png.toString('base64'),preview=`; thumbnail_png begin 80x40 ${encoded.length}\n; ${encoded}\n; thumbnail_png end\n`;
  const loadGcode=preview+';'+('x'.repeat(256*1024-Buffer.byteLength(preview)-2))+'\n';
  await writeFile(configPath,'[server]\nhost=127.0.0.1\nport=0');const gcode=preview+'G92 E0\n'+Array.from({length:1000},(_,i)=>`G1 X${(i+1)/100} E${(i+1)/1000} F600\n`).join(''),sha256=createHash('sha256').update(gcode).digest('hex');
  const transport=await nextTransport(),{output:discardOutput,open:discardOpen,lifecycle:discardLifecycle,...print}=f.options.print;
  await writeFile(manifest,JSON.stringify({version:1,deviceId:'printer',printerConfig,moonrakerConfig:configPath,journalPath:join(dir,'jobs.db'),mcus:Object.fromEntries([...transport.policies].map(([id,{stopDevice,...policy}])=>[id,policy])),machine:{enableLeadTime:.001,fanMinimumScheduleTime:.001},hardware:{heaterGcodeIds:f.options.hardware.heaterGcodeIds},print,limits:{maxNozzle:300,maxBed:130}}));
  const profile=join(dir,'machine.mjs');await writeFile(profile,`import {appendFile} from 'node:fs/promises';
import {monitorEventLoopDelay} from 'node:perf_hooks';
import {loadNativeProductMachineProfile} from ${JSON.stringify(pathToFileURL(join(app,'host/src/runtime/native-product-machine.js')).href)};
import {ApiError} from ${JSON.stringify(pathToFileURL(join(app,'host/src/moonraker/rpc.js')).href)};
let generation=0;
const record=event=>appendFile(${JSON.stringify(trace)},JSON.stringify(event)+'\\n');
export async function createProductHostProfile(signal){
 const current=++generation,loop=monitorEventLoopDelay({resolution:1}),cpu=process.cpuUsage();loop.enable();await record({event:'factory',generation:current});
 try{
  const profile=await loadNativeProductMachineProfile(${JSON.stringify(manifest)},{filesRoot:${JSON.stringify(join(dir,'files'))},metadataRoot:${JSON.stringify(join(dir,'metadata'))},uploads:{stagingRoot:${JSON.stringify(dir)}},standardPrint:{nozzle:200,bed:60},createAdapter:async()=>({
   stops:new Map(['mcu','aux'].map(id=>[id,async cause=>{await record({event:'stop',generation:current,id,cause:String(cause)});} ])),
   output(){},lifecycle:{async prepare(){},async start(){},async finishOutputs(){},async stopOutputs(){}},
   async authorizePrintFile(id,signal){signal.throwIfAborted();if(id!=='authorized-file')throw new ApiError(403,'Print source denied');},
   server:{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'compiled-journey',missingRequirements:[]},notificationLimits:{perClient:2,pending:128,timeoutMs:20},authorizeNotification:async(method,params,context)=>{if(method!=='notify_filelist_changed'&&!method.startsWith('notify_klippy_'))throw new ApiError(403,'Not subscribed');if(context.request.headers['x-observer']==='slow')await new Promise(resolve=>setTimeout(resolve,50));if(context.request.headers['x-observer']!=='allowed')throw new ApiError(403,'File observation denied');},authorize:(_m,_p,context)=>{if(context.request.headers['x-api-key']!=='test')throw new ApiError(401,'Denied');return {username:'operator'};}},
   async release(){loop.disable();await record({event:'released',generation:current,loop:{p99Ms:loop.percentile(99)/1e6,maxMs:loop.max/1e6},cpu:process.cpuUsage(cpu),rss:process.memoryUsage().rss});}
  })},signal);
  const open=profile.options.print.open;profile.options.print.open=async(id,signal)=>{await record({event:'open',generation:current});return open(id,signal);};return profile;
 }catch(error){loop.disable();throw error;}
}
`);
  const env:NodeJS.ProcessEnv={...process.env,PATH:'/no-programs',NODE_PATH:'',NODE_OPTIONS:'--no-experimental-strip-types',NODE_DISABLE_COMPILE_CACHE:'1'};for(const key of Object.keys(env))if(key.startsWith('ANYRAID_')&&key.endsWith('_ADDON'))delete env[key];
  function spawnHost(){if(watchdog)clearTimeout(watchdog);stderr='';child=spawn(process.execPath,[join(app,'scripts/product-host.js'),'--profile',profile],{cwd:'/',env,stdio:['ignore','pipe','pipe']});let unread='';
  child.stdout!.on('data',chunk=>{unread+=chunk;for(let at=unread.indexOf('\n');at>=0;at=unread.indexOf('\n')){const line=unread.slice(0,at);unread=unread.slice(at+1);try{const event=JSON.parse(line);if(event.event==='ready')ready.push(`http://127.0.0.1:${event.address.port}`);}catch{}}});child.stderr!.on('data',chunk=>{stderr+=chunk;});
  ended=new Promise((resolve,reject)=>{child!.once('error',reject);child!.once('exit',(code,signal)=>resolve({code,signal}));});void ended.catch(()=>{});
  watchdog=setTimeout(()=>child!.kill('SIGKILL'),45000);}
  spawnHost();
  async function waitReady(count:number){const until=performance.now()+10000;while(ready.length<count){assert(child!.exitCode===null&&child!.signalCode===null,stderr);assert(performance.now()<until,'ready timeout: '+stderr);await delay(5);}base=ready[count-1];}
  async function connectFileEvents(){for(const role of ['allowed','allowed','allowed','allowed','denied','slow']){const socket=new WebSocket(base.replace('http:','ws:')+'/websocket',{headers:{'x-api-key':'test','x-observer':role}});socket.on('message',data=>{const event=JSON.parse(data.toString());if(event.method?.startsWith('notify_klippy_'))lifecycleEvents.push({role,method:event.method});if(event.method==='notify_filelist_changed'){const at=performance.now();fileEvents.push({role,event:event.params[0],at});const start=eventStarts.get(event.params[0].action+':'+event.params[0].item.file_id);if(start!==undefined)eventLatencies.push(at-start);}});eventSockets.push(socket);await once(socket,'open');}}
  const headers={'x-api-key':'test','content-type':'application/json'};
  async function get(path='/printer/print/status'){const response=await checkedFetch(base+path,{headers,signal:AbortSignal.timeout(5000)});assert.equal(response.status,200);return (await response.json() as any).result;}
  async function post(action:string,params:unknown,authorized=true){const response=await checkedFetch(base+'/printer/print/'+action,{method:'POST',headers:authorized?headers:{'content-type':'application/json'},body:JSON.stringify(params),signal:AbortSignal.timeout(10000)});return {code:response.status,body:await response.json() as any};}
  async function wait(state:string){const until=performance.now()+12000;for(;;){const current=await get();if(state!=='failed')assert.notEqual(current.state,'failed',JSON.stringify(current)+' '+stderr);if(current.state===state)return current;if(performance.now()>=until)assert.fail(JSON.stringify({current,thermal:await get('/printer/objects/query?extruder&heater_bed'),stderr}));await delay(5);}}
  function beginLoad(){
   if(!loaded)return;const abort=new AbortController(),generation=++loadGeneration;let failure:unknown;
   const own=(work:()=>Promise<void>)=>work().catch(error=>{if(!abort.signal.aborted){failure??=error;abort.abort();}});
   const tasks=Array.from({length:4},()=>own(async()=>{while(!abort.signal.aborted){const begin=performance.now(),response=await checkedFetch(base+'/printer/objects/query?toolhead&extruder&heater_bed&virtual_sdcard&print_stats&pause_resume',{headers,signal:abort.signal});assert.equal(response.status,200);const body=await response.json() as any;assert(body.result.status.toolhead);latencies.push(performance.now()-begin);await delay(5,undefined,{signal:abort.signal});}}));
   tasks.push(own(async()=>{for(;;){const response=await checkedFetch(base+'/printer/print/status',{headers,signal:abort.signal});assert.equal(response.status,200);if(((await response.json()) as any).result.state==='printing')break;await delay(5,undefined,{signal:abort.signal});}for(let i=0;i<8;i++){const form=new FormData();form.append('file',new Blob([loadGcode]),'load.gcode');form.append('file_id','load-'+generation+'-'+i);eventStarts.set('create_file:load-'+generation+'-'+i,performance.now());const begin=performance.now(),response=await checkedFetch(base+'/server/files/upload',{method:'POST',headers:{'x-api-key':'test'},body:form,signal:abort.signal});assert.equal(response.status,200);const body=await response.json() as any;assert.equal(body.result.print_started,false);uploadTimes.push(performance.now()-begin);const downloadBegin=performance.now(),download=await checkedFetch(base+'/server/files/gcodes/'+body.result.file.id+'.gcode',{headers,signal:abort.signal});assert.equal(download.status,200);const downloaded=Buffer.from(await download.arrayBuffer());assert.equal(downloaded.length,256*1024);assert.equal(createHash('sha256').update(downloaded).digest('hex'),body.result.file.sha256);downloadTimes.push(performance.now()-downloadBegin);const metadataBegin=performance.now(),metadata=await checkedFetch(base+'/server/files/metadata?filename='+body.result.file.id+'.gcode',{headers,signal:abort.signal});assert.equal(metadata.status,200);const extracted=(await metadata.json() as any).result;assert.equal(extracted.sha256,body.result.file.sha256);assert.equal(extracted.size,256*1024);metadataTimes.push(performance.now()-metadataBegin);assert.equal(extracted.thumbnails.length,2);const thumbnailBegin=performance.now(),image=await checkedFetch(base+'/server/files/gcodes/'+extracted.thumbnails[1].relative_path,{headers,signal:abort.signal});assert.equal(image.status,200);assert.deepEqual(Buffer.from(await image.arrayBuffer()),png);thumbnailTimes.push(performance.now()-thumbnailBegin);eventStarts.set('delete_file:'+body.result.file.id,performance.now());const deleteBegin=performance.now(),deleted=await checkedFetch(base+'/server/files/gcodes/'+body.result.file.id+'.gcode',{method:'DELETE',headers,signal:abort.signal});assert.equal(deleted.status,200);assert.equal((await deleted.json() as any).result.action,'delete_file');deleteTimes.push(performance.now()-deleteBegin);assert.equal((await checkedFetch(base+'/server/files/gcodes/'+extracted.thumbnails[1].relative_path,{headers,signal:abort.signal})).status,404);await delay(25,undefined,{signal:abort.signal});}}));
   tasks.push(own(async()=>{while(!abort.signal.aborted){const begin=performance.now(),response=await checkedFetch(base+'/server/files/directory?extended=true',{headers,signal:abort.signal});assert.equal(response.status,200);const entries=(await response.json() as any).result.files;assert.equal(entries.find((entry:any)=>entry.file_id==='authorized-file')?.sha256,sha256);assert.equal(new Set(entries.map((entry:any)=>entry.filename)).size,entries.length);directoryTimes.push(performance.now()-begin);await delay(5,undefined,{signal:abort.signal});}}));
   stopLoad=async()=>{abort.abort();await Promise.all(tasks);if(failure)throw failure;};
  }
  const request=(id:string)=>({version:1,request_id:id,file_id:'authorized-file',nozzle:200,bed:60,expires_at:Date.now()+60000});
  async function action(name:string,id:string){const current=await get(),result=await post(name,{request_id:id,state_token:current.state_token});assert.equal(result.code,200,JSON.stringify(result.body));}
  await waitReady(1);await connectFileEvents();const hostToken=(await get('/printer/host/status')).state_token;
  const hostPost=async(params:unknown,authorized=true)=>{const response=await checkedFetch(base+'/printer/host/reinitialize',{method:'POST',headers:authorized?headers:{'content-type':'application/json'},body:JSON.stringify(params)});return {code:response.status,body:await response.json() as any};};
  const recovery={version:1,request_id:'recover',state_token:hostToken};assert.equal((await hostPost(recovery,false)).code,401);
  const multipart=()=>{const form=new FormData();form.append('file',new Blob([gcode]),'journey.gcode');form.append('file_id','authorized-file');form.append('checksum',sha256);return form;};
  const deniedUpload=await checkedFetch(base+'/server/files/upload',{method:'POST',body:multipart()});assert.equal(deniedUpload.status,401);await deniedUpload.arrayBuffer();
  const uploaded=await checkedFetch(base+'/server/files/upload',{method:'POST',headers:{'x-api-key':'test'},body:multipart()});assert.equal(uploaded.status,200);const receipt=(await uploaded.json() as any).result;assert.equal(receipt.file.sha256,sha256);assert.equal(receipt.print_started,false);assert.equal(receipt.print_queued,false);assert.equal((await get()).state,'idle');
  const discoveredHost=await get('/server/info'),printerInfo=await get('/printer/info');assert.equal(discoveredHost.klippy_connected,true);assert.equal(discoveredHost.klippy_state,'ready');assert.equal(printerInfo.state,'ready');assert.equal(printerInfo.host_type,'node');assert.equal(printerInfo.python_path,'');assert.equal(printerInfo.config_file,printerConfig);assert.equal((await get('/printer/objects/query?webhooks')).status.webhooks.state,'ready');
  const discovered=await get('/server/files/list');assert.equal(discovered.length,1);assert.equal(discovered[0].file_id,'authorized-file');assert.equal(discovered[0].name,'journey.gcode');assert.equal(discovered[0].sha256,sha256);
  assert.equal((await get('/printer/files/info?file_id='+discovered[0].file_id)).sha256,sha256);
  const metadata=await get('/server/files/metadata?filename='+discovered[0].path);assert.equal(metadata.file_id,'authorized-file');assert.equal(metadata.sha256,sha256);assert.equal(metadata.size,Buffer.byteLength(gcode));
  const previews=await get('/server/files/thumbnails?filename='+discovered[0].path);assert.equal(previews.length,2);const previewUrl=base+'/server/files/gcodes/'+previews[1].thumbnail_path;assert.equal((await checkedFetch(previewUrl)).status,401);const previewResponse=await checkedFetch(previewUrl,{headers});assert.equal(previewResponse.status,200);assert.deepEqual(Buffer.from(await previewResponse.arrayBuffer()),png);
  const downloaded=await checkedFetch(base+'/server/files/gcodes/'+discovered[0].path,{headers});assert.equal(downloaded.status,200);assert.equal(await downloaded.text(),gcode);
  assert.equal((await post('start',request('complete'),false)).code,401);assert(transport.firmware.every(f=>f.motion.length===0));
  assert.equal((await checkedFetch(base+'/server/files/gcodes/authorized-file.gcode',{method:'DELETE'})).status,401);
  beginLoad();let result=await post('start',request('complete'));assert.equal(result.code,200,JSON.stringify(result.body));await wait('preparing');assert.equal((await checkedFetch(base+'/server/files/gcodes/authorized-file.gcode',{method:'DELETE',headers})).status,409);const heatDeadline=performance.now()+5000;for(;;){const temperatures=(await get('/printer/objects/query?extruder=target&heater_bed=target')).status;if(temperatures.extruder.target===200&&temperatures.heater_bed.target===60)break;assert(performance.now()<heatDeadline,JSON.stringify(temperatures));await delay(10);}assert.equal(homed,3);const beforeHeat=transport.firmware[0].motion.length;await delay(200);assert.equal((await get()).state,'preparing');assert.equal(transport.firmware[0].motion.length,beforeHeat);assert.equal((await get('/printer/objects/query?virtual_sdcard')).status.virtual_sdcard.file_position,0);const pwmDeadline=performance.now()+3000;while(new Set(transport.firmware[1].outputs.filter(e=>e.name==='queue_digital_out_generation'&&Number(e.parameters.on_ticks)>0).map(e=>e.parameters.oid)).size!==2){assert(performance.now()<pwmDeadline,JSON.stringify(transport.firmware[1].outputs));await delay(10);}assert.equal((await get()).state,'preparing');hot=true;await wait('printing');assert.equal((await hostPost(recovery)).code,409);assert.equal((await post('pause',{})).body.result,'ok');const paused=await wait('paused');const pausedObjects=(await get('/printer/objects/query?pause_resume&print_stats=filename,total_duration,filament_used,print_duration')).status;assert.equal(pausedObjects.pause_resume.is_paused,true);assert.equal(pausedObjects.print_stats.filename,'authorized-file.gcode');assert(pausedObjects.print_stats.total_duration>0);const pausedDuration=pausedObjects.print_stats.total_duration;assert(pausedObjects.print_stats.print_duration>=0);await delay(20);assert.equal((await get('/printer/objects/query?print_stats=print_duration')).status.print_stats.print_duration,pausedObjects.print_stats.print_duration);assert.equal((await checkedFetch(base+'/server/files/gcodes/authorized-file.gcode',{method:'DELETE',headers})).status,409);assert.equal((await post('resume',{})).body.result,'ok');assert.equal((await get('/printer/objects/query?pause_resume')).status.pause_resume.is_paused,false);assert.equal((await post('resume',{request_id:'complete',state_token:paused.state_token})).code,409);await wait('completed');
  const completedRecord=(await get('/printer/print/status?request_id=complete')).record;assert.equal(completedRecord.state,'completed');assert(completedRecord.timestamps.reserved_at>0);assert(completedRecord.timestamps.started_at>=completedRecord.timestamps.reserved_at);assert(completedRecord.timestamps.ended_at>=completedRecord.timestamps.started_at);assert.equal(homed,3);assert(transport.firmware[0].motion.some(m=>m.name==='queue_step'));
  const objects=(await get('/printer/objects/query?toolhead=position&virtual_sdcard&print_stats=filename,total_duration,filament_used,print_duration&pause_resume')).status;assert.equal(objects.print_stats.filename,'authorized-file.gcode');assert(objects.print_stats.total_duration>=pausedDuration);assert.equal((await get('/printer/objects/query?print_stats=total_duration')).status.print_stats.total_duration,objects.print_stats.total_duration);assert.equal(objects.pause_resume.is_paused,false);assert.deepEqual(objects.toolhead.position,[10,0,0,1]);assert(Math.abs(objects.print_stats.filament_used-1)<1e-12);assert(objects.print_stats.print_duration>0);assert(objects.print_stats.print_duration<=objects.print_stats.total_duration);assert.equal((await get('/printer/objects/query?print_stats=print_duration')).status.print_stats.print_duration,objects.print_stats.print_duration);const completedStatistics={total_duration:objects.print_stats.total_duration,print_duration:objects.print_stats.print_duration,filament_used:objects.print_stats.filament_used};assert.deepEqual((await get('/printer/print/status?request_id=complete')).record.statistics,completedStatistics);assert.deepEqual((await get('/printer/print/status?request_id=complete')).record.timestamps,completedRecord.timestamps);assert.equal(objects.virtual_sdcard.is_active,false);const off=(await get('/printer/objects/query?extruder=target&heater_bed=target')).status;assert.equal(off.extruder.target,0);assert.equal(off.heater_bed.target,0);
  await action('reset','complete');assert.equal((await get('/printer/objects/query?print_stats=filename,total_duration,filament_used,print_duration')).status.print_stats.filename,'');result=await post('start',request('cancel'));assert.equal(result.code,200,JSON.stringify(result.body));await wait('printing');assert.equal((await post('cancel',{})).body.result,'ok');await wait('cancelled');assert.equal((await get('/printer/print/status?request_id=cancel')).record.state,'cancelled');assert.equal((await get('/server/info')).native_host.ready,false);assert.equal((await get('/server/info')).klippy_state,'shutdown');assert.equal((await get('/printer/info')).state,'shutdown');
  await stopLoad();const next=await nextTransport();if(loaded){const receipt=await hostPost(recovery);assert.equal(receipt.code,200,JSON.stringify(receipt.body));assert.equal(receipt.body.result.accepted,true);assert.equal(receipt.body.result.operation.state,'queued');}else child!.kill('SIGHUP');await waitReady(2);await connectFileEvents();if(loaded){const recoveryDeadline=performance.now()+5000;while((await get('/printer/host/status?request_id=recover')).operation.state!=='succeeded'){assert(performance.now()<recoveryDeadline,'recovery receipt not durable');await delay(5);}assert.equal((await get('/printer/host/status')).durable,true);assert.notEqual((await get('/printer/host/status')).state_token,hostToken);assert.equal((await hostPost(recovery)).body.result.operation.state,'succeeded');assert.equal((await hostPost({...recovery,request_id:'stale'})).code,409);}assert.equal((await get()).state,'idle');assert.equal((await get('/printer/files/info?file_id=authorized-file')).sha256,sha256);assert.equal((await get('/printer/print/status?request_id=cancel')).record.state,'cancelled');assert.deepEqual((await get('/printer/print/status?request_id=complete')).record.statistics,completedStatistics);assert.deepEqual((await get('/printer/print/status?request_id=complete')).record.timestamps,completedRecord.timestamps);assert(next.firmware.every(f=>f.motion.length===0));
  const restoredPreview=await checkedFetch(base+'/server/files/gcodes/'+previews[1].thumbnail_path,{headers});assert.equal(restoredPreview.status,200);assert.deepEqual(Buffer.from(await restoredPreview.arrayBuffer()),png);assert.equal((await get('/server/files/metadata?filename=authorized-file.gcode')).sha256,sha256);beginLoad();hot=true;result=await post('start',{filename:'authorized-file.gcode'});assert.equal(result.code,200,JSON.stringify(result.body));assert.equal(result.body.result,'ok');const freshId=(await get()).request.request_id;assert.match(freshId,/^compat-/);await wait('completed');assert.equal(homed,9);assert.equal((await get('/printer/print/status?request_id='+freshId)).record.state,'completed');
  await action('reset',freshId);result=await post('start',request('sensor-fault'));assert.equal(result.code,200,JSON.stringify(result.body));await wait('printing');const adc=next.firmware[1].outputs.find(e=>e.name==='query_analog_in')!;next.firmware[1].emit('analog_in_state',{oid:Number(adc.parameters.oid),next_clock:next.firmware[1].currentClock()>>>0,values:Buffer.from([1])});await wait('failed');assert.equal((await get('/server/info')).native_host.ready,false);const durableDeadline=performance.now()+5000;while((await get('/printer/print/status?request_id=sensor-fault')).record.state!=='failed'){assert(performance.now()<durableDeadline,'fault was not persisted');await delay(5);}assert.equal((await post('start',request('after-fault'))).code,409);
  await stopLoad();child!.kill('SIGTERM');assert.deepEqual(await ended,{code:0,signal:null});
  const events=(await readFile(trace,'utf8')).trim().split('\n').map(line=>JSON.parse(line));assert.equal(events.filter(e=>e.event==='open').length,4);assert.equal(events.filter(e=>e.event==='factory').length,2);assert(events.findIndex(e=>e.event==='released'&&e.generation===1)<events.findIndex(e=>e.event==='factory'&&e.generation===2));assert.equal(events.filter(e=>e.event==='released').length,2);assert.equal(events.filter(e=>e.event==='stop').length,4);
  if(loaded){const freshTransport=await nextTransport();spawnHost();await waitReady(3);const restartedPreview=await checkedFetch(base+'/server/files/gcodes/'+previews[1].thumbnail_path,{headers});assert.equal(restartedPreview.status,200);assert.deepEqual(Buffer.from(await restartedPreview.arrayBuffer()),png);const restored=await get('/printer/host/status?request_id=recover');assert.equal(restored.durable,true);assert.equal(restored.operation.state,'succeeded');assert.notEqual(restored.state_token,hostToken);assert.equal((await hostPost(recovery)).body.result.operation.state,'succeeded');assert.equal((await hostPost({...recovery,request_id:'after-process-restart'})).code,409);assert.equal((await get()).state,'idle');assert.deepEqual((await get('/printer/print/status?request_id=complete')).record.statistics,completedStatistics);assert.deepEqual((await get('/printer/print/status?request_id=complete')).record.timestamps,completedRecord.timestamps);assert(freshTransport.firmware.every(f=>f.motion.length===0));child!.kill('SIGTERM');assert.deepEqual(await ended,{code:0,signal:null});const restartedEvents=(await readFile(trace,'utf8')).trim().split('\n').map(line=>JSON.parse(line)).slice(events.length);assert.equal(restartedEvents.filter(e=>e.event==='factory').length,1);assert.equal(restartedEvents.filter(e=>e.event==='open').length,0);}
  latencies.sort((a,b)=>a-b);uploadTimes.sort((a,b)=>a-b);directoryTimes.sort((a,b)=>a-b);downloadTimes.sort((a,b)=>a-b);metadataTimes.sort((a,b)=>a-b);thumbnailTimes.sort((a,b)=>a-b);deleteTimes.sort((a,b)=>a-b);eventLatencies.sort((a,b)=>a-b);const shutdownEvents=lifecycleEvents.filter(event=>event.method==='notify_klippy_shutdown');assert.equal(shutdownEvents.length,8);assert(shutdownEvents.every(event=>event.role==='allowed'));const metrics={loaded,lifecycleShutdowns:shutdownEvents.length,fileNotifications:fileEvents.length,fileNotificationP95Ms:eventLatencies[Math.floor(eventLatencies.length*.95)]??null,deleteRequests:deleteTimes.length,deleteP95Ms:deleteTimes[Math.floor(deleteTimes.length*.95)]??null,thumbnailRequests:thumbnailTimes.length,thumbnailP95Ms:thumbnailTimes[Math.floor(thumbnailTimes.length*.95)]??null,metadataRequests:metadataTimes.length,metadataP95Ms:metadataTimes[Math.floor(metadataTimes.length*.95)]??null,downloads:downloadTimes.length,downloadP95Ms:downloadTimes[Math.floor(downloadTimes.length*.95)]??null,wireCommands:wire.length,wireSteps:wire.reduce((n,m)=>n+m.steps,0),minimumStepLeadMs:Math.min(...wire.map(m=>m.firstStepLeadUs))/1000,directoryRequests:directoryTimes.length,directoryP99Ms:directoryTimes[Math.floor(directoryTimes.length*.99)]??null,statusRequests:latencies.length,uploads:uploadTimes.length,statusP99Ms:latencies[Math.floor(latencies.length*.99)]??null,uploadP95Ms:uploadTimes[Math.floor(uploadTimes.length*.95)]??null,generations:events.filter(e=>e.event==='released').map(e=>({loop:e.loop,cpu:e.cpu,rss:e.rss}))};t.diagnostic(JSON.stringify(metrics));
  assert.equal(fileEvents.length,loaded?132:4);assert(fileEvents.every(entry=>entry.role==='allowed'));if(loaded)for(let generation=1;generation<=2;generation++)for(let i=0;i<8;i++){const changes=fileEvents.filter(entry=>entry.event.item.file_id==='load-'+generation+'-'+i);assert.equal(changes.filter(entry=>entry.event.action==='create_file').length,4);assert.equal(changes.filter(entry=>entry.event.action==='delete_file').length,4);}
  assert(wire.length>0);assert(metrics.minimumStepLeadMs>0,'step commands must arrive before their first step');
  if(loaded){assert.equal(deleteTimes.length,16);assert.equal(thumbnailTimes.length,16);assert.equal(metadataTimes.length,16);assert.equal(downloadTimes.length,16);assert(directoryTimes.length>=100);assert(latencies.length>=100);assert.equal(uploadTimes.length,16);}
  for(const generation of metrics.generations){assert(generation.loop.p99Ms<50);assert(generation.loop.maxMs<100);}
 }catch(error){t.diagnostic(JSON.stringify({failureContext:{loaded,loadGeneration,homed,exitCode:child?.exitCode,signalCode:child?.signalCode,stderr,events:await readFile(trace,'utf8').catch(()=>null)}}));throw error;}finally{for(const socket of eventSockets)socket.terminate();await stopLoad().catch(()=>{});if(watchdog)clearTimeout(watchdog);if(child&&child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');await ended?.catch(()=>{});if(poll)clearInterval(poll);if(thermal)clearInterval(thermal);for(const timer of timers)clearTimeout(timer);for(const transport of transports)await transport.close();await f.close();await rm(dir,{recursive:true,force:true});}
});
