#!/usr/bin/env node
// Headless statistics graph export, GPL-3.0-or-later.
import {parseArgs} from 'node:util';
import {resolve} from 'node:path';
import {readStatsFile,writeStatsPlot} from '../host/src/diagnostics/graphstats-file.ts';
import {mcuStatsPlot,systemStatsPlot,frequencyStatsPlot,temperatureStatsPlot} from '../host/src/diagnostics/graphstats.ts';
const help='Usage: node scripts/graphstats.ts [options] <logfile>\n  -o, --output FILE       PDF, SVG, PNG, JPEG, WebP, TIFF or JSON (required)\n  -f, --frequency         MCU frequency\n  -s, --system            System load\n  -t, --temperature LIST  Comma-separated heaters\n  -m, --mcu NAME          Select MCU\n  -h, --help              Show help\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Statistics export cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},frequency:{type:'boolean',short:'f'},system:{type:'boolean',short:'s'},temperature:{type:'string',short:'t'},mcu:{type:'string',short:'m'},help:{type:'boolean',short:'h'}}});if(values.help)process.stdout.write(help);else{if(positionals.length!==1||!values.output)throw new Error(help);if(resolve(positionals[0])===resolve(values.output))throw new Error('Output must not replace the input log');const data=await readStatsFile(positionals[0],values.mcu,controller.signal);if(data.length){const plot=values.temperature!==undefined?temperatureStatsPlot(data,values.temperature):values.frequency?frequencyStatsPlot(data,values.mcu):values.system?systemStatsPlot(data):mcuStatsPlot(data);await writeStatsPlot(plot,values.output,controller.signal);}}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
