#!/usr/bin/env node
// GPL-3.0-or-later. Offline Node 26 input shaper simulation.
import {parseArgs} from 'node:util';
import {simulateShaper} from '../host/src/diagnostics/graph-shaper.ts';
import {writeStatsPanels} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_shaper.ts -o FILE [options]\n  -o, --output FILE           PDF, SVG, PNG, JPEG, WebP, TIFF or JSON\n  --shaper NAME              Default mzv; parameterized names supported\n  --shaper_freq HZ           Default 50\n  --damping_ratio RATIO      Default 0.1\n  --test_damping_ratios LIST Default 0.075,0.1,0.15\n  --system_freq HZ           Default 60\n  --system_damping_ratio R   Default 0.15\n  -h, --help                 Show help\n';
const number=(s:string|undefined):number|undefined=>{if(s===undefined)return undefined;if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(s.trim()))throw new Error('Invalid numeric option');const n=Number(s);if(!Number.isFinite(n))throw new Error('Nonfinite numeric option');return n;};
const controller=new AbortController(),stop=()=>controller.abort(new Error('Shaper graph cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},shaper:{type:'string'},shaper_freq:{type:'string'},damping_ratio:{type:'string'},test_damping_ratios:{type:'string'},system_freq:{type:'string'},system_damping_ratio:{type:'string'},help:{type:'boolean',short:'h'}}});if(values.help)process.stdout.write(help);else{if(positionals.length||!values.output)throw new Error(help);const result=simulateShaper({shaper:values.shaper,frequency:number(values.shaper_freq),damping:number(values.damping_ratio),testDamping:values.test_damping_ratios?.split(',').map(s=>number(s)!),systemFrequency:number(values.system_freq),systemDamping:number(values.system_damping_ratio)});await writeStatsPanels([{plot:result.frequency,xAxis:{label:'Resonance frequency (Hz)',format:'number'}},{plot:result.step,xAxis:{label:'Time (s)',format:'number'}}],values.output,controller.signal);}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
