#!/usr/bin/env node
// GPL-3.0-or-later. Offline bed-mesh analysis; no device configuration writes.
import {parseArgs} from 'node:util';
import {resolve} from 'node:path';
import {requestMeshDump} from '../host/src/diagnostics/mesh-source.ts';
import {analyzeMeshDump,formatMeshReport} from '../host/src/diagnostics/mesh-report.ts';
import {meshPathPlot,renderMeshPathSvg,type MeshPathType} from '../host/src/diagnostics/mesh-path.ts';
import {meshSurfacePlot,renderMeshSurfaceSvg,type MeshSurfaceType} from '../host/src/diagnostics/mesh-surface.ts';
import {writeDiagnosticText,writePlotDocument} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_mesh.ts analyze [--json] [-o REPORT.json] INPUT\n       node scripts/graph_mesh.ts dump [-o SNAPSHOT.json] INPUT\nINPUT: local JSON, Unix socket, or HTTP(S)/WS(S) server URL.\n--timeout MS: remote acquisition deadline (default 20000).\nplot TYPE [-s] [-p PROFILE] -o IMAGE INPUT: static path/surface graphs.\nIMAGE formats: PDF, SVG, PNG, JPEG, WebP, TIFF and JSON.\nlist: show supported plots. Animation is not yet supported.\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Mesh analysis cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},json:{type:'boolean'},help:{type:'boolean',short:'h'},timeout:{type:'string'},'scale-plot':{type:'boolean',short:'s'},'profile-name':{type:'string',short:'p'}}});if(values.help)process.stdout.write(help);else{if(positionals[0]==='list'&&positionals.length===1){process.stdout.write('points  Generated Probe Points\npath    Probe Travel Path\nrapid   Rapid Scan Travel Path\nprobedz Probed mesh height\nmeshz   Interpolated mesh height\noverlay Current and saved profile\ndelta   Current minus saved profile\n');}else{const plotting=positionals[0]==='plot';if(positionals.length!==(plotting?3:2)||!['analyze','dump','plot'].includes(positionals[0]))throw new Error(help);if(plotting&&(!values.output||!['points','path','rapid','probedz','meshz','overlay','delta'].includes(positionals[1])))throw new Error('Path plots require supported type and -o output');const input=positionals[plotting?2:1];if(values.output!==undefined&&(!values.output||resolve(values.output)===resolve(input)))throw new Error('Output must not replace input');if(values.timeout!==undefined&&!/^\d+$/.test(values.timeout))throw new Error('Invalid timeout');const data=await requestMeshDump(input,controller.signal,{timeoutMs:values.timeout===undefined?undefined:Number(values.timeout)});if(plotting&&['probedz','meshz','overlay','delta'].includes(positionals[1])){const plot=meshSurfacePlot(data,positionals[1] as MeshSurfaceType,values['profile-name'],values['scale-plot']);await writePlotDocument(plot,()=>renderMeshSurfaceSvg(plot),values.output!,controller.signal);}else if(plotting){const plot=meshPathPlot(data,positionals[1] as MeshPathType,values['scale-plot']);await writePlotDocument(plot,()=>renderMeshPathSvg(plot),values.output!,controller.signal);}else if(positionals[0]==='dump'){const output=values.output??`klipper-bedmesh-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;if(resolve(output)===resolve(input))throw new Error('Output must not replace input');await writeDiagnosticText(JSON.stringify(data,null,2)+'\n',output,controller.signal);process.stdout.write(`Saved mesh snapshot to ${output}\n`);}else{const report=analyzeMeshDump(data),json=JSON.stringify(report,null,2)+'\n';if(values.output)await writeDiagnosticText(json,values.output,controller.signal);process.stdout.write(values.json?json:formatMeshReport(report));}}}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
