#!/usr/bin/env node
// GPL-3.0-or-later. Offline legacy motion demonstration.
import {parseArgs} from 'node:util';
import {legacyMotionShapers,type LegacyMotionShaper} from '../host/src/diagnostics/legacy-motion-shaper.ts';
import {motionFilters,type MotionFilter} from '../host/src/diagnostics/motion-filters.ts';
import {motionPlots} from '../host/src/diagnostics/graph-motion.ts';
import {writeStatsPanels} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_motion.ts -o FILE\n  -o, --output FILE  HTML, PDF, SVG, PNG, JPEG, WebP, TIFF or JSON\n  --filter NAME      average, smooth, weighted, weighted2/3/4, spring_raw, spring_double_weighted\n  --smooth_time SEC  Default (2/3)/40; fixed 50 ms margin applies\n  --legacy_shaper N  zv, zvd, mzv, ei, 2hump_ei, 3hump_ei; exclusive with --filter\n  --accel_order N    2, 4 or 6 (default 2)\n  --jerk_limit       Use original fixed jerk limit\n  -h, --help         Show help\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Motion graph cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},help:{type:'boolean',short:'h'},filter:{type:'string'},smooth_time:{type:'string'},accel_order:{type:'string'},jerk_limit:{type:'boolean'},legacy_shaper:{type:'string'}}});if(values.help)process.stdout.write(help);else{if(positionals.length||!values.output)throw new Error(help);if(values.filter!==undefined&&!motionFilters.includes(values.filter as MotionFilter))throw new Error('Unknown motion filter');if(values.smooth_time!==undefined&&(!values.filter||values.filter==='spring_raw'||!/^[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(values.smooth_time)))throw new Error('Smoothing time requires a smoothing filter and numeric seconds');if(values.accel_order!==undefined&&!['2','4','6'].includes(values.accel_order))throw new Error('Acceleration order must be 2, 4 or 6');if(values.legacy_shaper!==undefined&&!legacyMotionShapers.includes(values.legacy_shaper as LegacyMotionShaper))throw new Error('Unknown legacy diagnostic shaper');await writeStatsPanels(motionPlots(values.filter as MotionFilter|undefined,values.smooth_time===undefined?undefined:Number(values.smooth_time),{order:values.accel_order===undefined?undefined:Number(values.accel_order) as 2|4|6,jerkLimit:values.jerk_limit,legacyShaper:values.legacy_shaper as LegacyMotionShaper|undefined}),values.output,controller.signal);}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
