#!/usr/bin/env node
// GPL-3.0-or-later. Independent Node 26 diagnostic process.
import {parseArgs} from 'node:util';
import {resolve} from 'node:path';
import {readAccelerometerLog} from '../host/src/calibration/accelerometer-file.ts';
import type {AccelerometerLog} from '../host/src/calibration/accelerometer-log.ts';
import {accelerometerPlots,type AccelerometerAxis} from '../host/src/diagnostics/graph-accelerometer.ts';
import {writeStatsPanels} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_accelerometer.ts -o FILE [options] LOG...\n  -r, --raw          Plot mean-centered raw XYZ acceleration\n  -a, --axis NAME    all, x, y or z (frequency graphs)\n  -f, --max_freq HZ  Default 200\n  -o, --output FILE  SVG, PNG, JPEG, WebP, TIFF or JSON\n  -h, --help         Show help\nSpectrogram and CSV export are not yet supported.\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Accelerometer graph cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},raw:{type:'boolean',short:'r'},axis:{type:'string',short:'a'},max_freq:{type:'string',short:'f'},help:{type:'boolean',short:'h'}}});if(values.help)process.stdout.write(help);else{if(!values.output||!positionals.length||positionals.length>16)throw new Error(help);if(positionals.some(p=>resolve(p)===resolve(values.output!)))throw new Error('Output must not replace an input log');if(values.max_freq!==undefined&&!/^[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(values.max_freq))throw new Error('Invalid maximum frequency');const logs:AccelerometerLog[]=[];let cells=0;for(const filename of positionals){const log=await readAccelerometerLog(filename,controller.signal);cells+=log.kind==='raw'?log.samples.length:log.datasets.reduce((n,d)=>n+d.frequencies.length*(d.axes?5:2),0);if(cells>4000000)throw new RangeError('Combined accelerometer input limit exceeded');logs.push(log);}await writeStatsPanels(accelerometerPlots(logs,{raw:values.raw,axis:values.axis as AccelerometerAxis|undefined,maxFrequency:values.max_freq===undefined?undefined:Number(values.max_freq)}),values.output,controller.signal);}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
