#!/usr/bin/env node
// GPL-3.0-or-later. Offline bed-mesh analysis; no device configuration writes.
import {parseArgs} from 'node:util';
import {resolve} from 'node:path';
import {requestMeshDump} from '../host/src/diagnostics/mesh-source.ts';
import {analyzeMeshDump,formatMeshReport} from '../host/src/diagnostics/mesh-report.ts';
import {writeDiagnosticText} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_mesh.ts analyze [--json] [-o REPORT.json] INPUT\n       node scripts/graph_mesh.ts dump [-o SNAPSHOT.json] INPUT\nINPUT: local JSON, Unix socket, or HTTP(S)/WS(S) server URL.\n--timeout MS: remote acquisition deadline (default 20000).\nPlots and animation are not yet supported.\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Mesh analysis cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},json:{type:'boolean'},help:{type:'boolean',short:'h'},timeout:{type:'string'}}});if(values.help)process.stdout.write(help);else{if(positionals.length!==2||!['analyze','dump'].includes(positionals[0]))throw new Error(help);if(values.output!==undefined&&(!values.output||resolve(values.output)===resolve(positionals[1])))throw new Error('Output must not replace input');if(values.timeout!==undefined&&!/^\d+$/.test(values.timeout))throw new Error('Invalid timeout');const data=await requestMeshDump(positionals[1],controller.signal,{timeoutMs:values.timeout===undefined?undefined:Number(values.timeout)});if(positionals[0]==='dump'){const output=values.output??`klipper-bedmesh-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;if(resolve(output)===resolve(positionals[1]))throw new Error('Output must not replace input');await writeDiagnosticText(JSON.stringify(data,null,2)+'\n',output,controller.signal);process.stdout.write(`Saved mesh snapshot to ${output}\n`);}else{const report=analyzeMeshDump(data),json=JSON.stringify(report,null,2)+'\n';if(values.output)await writeDiagnosticText(json,values.output,controller.signal);process.stdout.write(values.json?json:formatMeshReport(report));}}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
