#!/usr/bin/env node
// GPL-3.0-or-later. Offline legacy motion demonstration.
import {parseArgs} from 'node:util';
import {motionFilters,type MotionFilter} from '../host/src/diagnostics/motion-filters.ts';
import {motionPlots} from '../host/src/diagnostics/graph-motion.ts';
import {writeStatsPanels} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_motion.ts -o FILE\n  -o, --output FILE  SVG, PNG, JPEG, WebP, TIFF or JSON\n  --filter NAME      average, smooth, weighted, weighted2/3/4, spring_raw, spring_double_weighted\n  --smooth_time SEC  Default (2/3)/40; fixed 50 ms margin applies\n  -h, --help         Show help\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Motion graph cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},help:{type:'boolean',short:'h'},filter:{type:'string'},smooth_time:{type:'string'}}});if(values.help)process.stdout.write(help);else{if(positionals.length||!values.output)throw new Error(help);if(values.filter!==undefined&&!motionFilters.includes(values.filter as MotionFilter))throw new Error('Unknown motion filter');if(values.smooth_time!==undefined&&(!values.filter||values.filter==='spring_raw'||!/^[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(values.smooth_time)))throw new Error('Smoothing time requires a smoothing filter and numeric seconds');await writeStatsPanels(motionPlots(values.filter as MotionFilter|undefined,values.smooth_time===undefined?undefined:Number(values.smooth_time)),values.output,controller.signal);}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
