#!/usr/bin/env node
// GPL-3.0-or-later. Independent Node 26 diagnostic process.
import {parseArgs} from 'node:util';
import {resolve,extname} from 'node:path';
import {readAccelerometerLog} from '../host/src/calibration/accelerometer-file.ts';
import {accelerometerDatasets,type AccelerometerLog} from '../host/src/calibration/accelerometer-log.ts';
import {accelerometerPlots,type AccelerometerAxis} from '../host/src/diagnostics/graph-accelerometer.ts';
import {calculateSpectrogram} from '../host/src/calibration/spectrogram.ts';
import {spectrogramCsv} from '../host/src/calibration/spectrogram-csv.ts';
import {writeSpectrogram} from '../host/src/diagnostics/spectrogram-plot.ts';
import {spectrumCsv} from '../host/src/calibration/spectrum-csv.ts';
import {writeStatsPanels,writeDiagnosticText} from '../host/src/diagnostics/graphstats-file.ts';
const help='Usage: node scripts/graph_accelerometer.ts -o FILE [options] LOG...\n  -r, --raw          Plot mean-centered raw XYZ acceleration\n  -s, --specgram     Export one raw log as a spectrogram\n  -c, --compare      Plot input datasets separately (default for multiple logs)\n  -a, --axis NAME    all, x, y or z (frequency graphs and spectrograms)\n  -f, --max_freq HZ  Default 200\n  -o, --output FILE  HTML, PDF, SVG, PNG, JPEG, WebP, TIFF, JSON or CSV\n  -h, --help         Show help\nSpectrogram CSV exports every frequency, independent of -f.\n';
const controller=new AbortController(),stop=()=>controller.abort(new Error('Accelerometer graph cancelled'));process.once('SIGINT',stop);process.once('SIGTERM',stop);
try{const {values,positionals}=parseArgs({allowPositionals:true,options:{output:{type:'string',short:'o'},raw:{type:'boolean',short:'r'},specgram:{type:'boolean',short:'s'},axis:{type:'string',short:'a'},compare:{type:'boolean',short:'c'},max_freq:{type:'string',short:'f'},help:{type:'boolean',short:'h'}}});if(values.help)process.stdout.write(help);else{if(!values.output||!positionals.length||positionals.length>16)throw new Error(help);if(positionals.some(p=>resolve(p)===resolve(values.output!)))throw new Error('Output must not replace an input log');if(values.max_freq!==undefined&&!/^[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(values.max_freq))throw new Error('Invalid maximum frequency');if(values.specgram&&(values.raw||positionals.length!==1))throw new Error('Spectrogram mode requires one raw log and no --raw flag');if(!['all','x','y','z'].includes(values.axis??'all'))throw new Error('Invalid accelerometer axis');if(values.max_freq!==undefined&&(!Number.isFinite(Number(values.max_freq))||Number(values.max_freq)<0))throw new Error('Invalid maximum frequency');const logs:AccelerometerLog[]=[];let cells=0;for(const filename of positionals){const log=await readAccelerometerLog(filename,controller.signal);cells+=log.kind==='raw'?log.samples.length:log.datasets.reduce((n,d)=>n+d.frequencies.length*(d.axes?5:2),0);if(cells>4000000)throw new RangeError('Combined accelerometer input limit exceeded');logs.push(log);}if(values.specgram){const log=logs[0];if(log.kind!=='raw')throw new Error('Spectrogram requires raw acceleration data');const data=calculateSpectrogram(log.samples,(values.axis??'all') as AccelerometerAxis);if(extname(values.output).toLowerCase()==='.csv')await writeDiagnosticText(spectrogramCsv(data),values.output,controller.signal);else await writeSpectrogram(data,`Spectrogram ${values.axis??'all'} (${log.name})`,values.max_freq===undefined?200:Number(values.max_freq),values.output,controller.signal);}else if(extname(values.output).toLowerCase()==='.csv'){if(values.raw)throw new Error('Raw mode does not support CSV output');await writeDiagnosticText(spectrumCsv(logs.flatMap(log=>accelerometerDatasets(log)),values.max_freq===undefined?undefined:Number(values.max_freq)),values.output,controller.signal);}else await writeStatsPanels(accelerometerPlots(logs,{raw:values.raw,axis:values.axis as AccelerometerAxis|undefined,maxFrequency:values.max_freq===undefined?undefined:Number(values.max_freq)}),values.output,controller.signal);}}catch(error){process.stderr.write((error instanceof Error?error.message:String(error))+'\n');process.exitCode=1;}finally{process.removeListener('SIGINT',stop);process.removeListener('SIGTERM',stop);}
