[package]
name = "anyraid-template"
version = "0.1.0"
edition = "2021"
rust-version = "1.89"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
minijinja = { version = "=2.24.0", features = ["custom_syntax", "fuel", "json", "preserve_order"] }
minijinja-contrib = { version = "=2.24.0", features = ["pycompat"] }
napi = { version = "=2.16.17", default-features = false, features = ["napi8"] }
napi-derive = "=2.16.13"
serde_json = { version = "=1.0.145", features = ["arbitrary_precision", "preserve_order"] }

num-bigint = "=0.4.6"
num-traits = "=0.2.19"

[build-dependencies]
napi-build = "=2.1.3"

[profile.release]
lto = true
codegen-units = 1
