import {open,realpath,stat} from 'node:fs/promises';
import {constants} from 'node:fs';
import {isAbsolute,join,relative,extname} from 'node:path';
import {randomBytes} from 'node:crypto';
import {pipeline} from 'node:stream/promises';
import type {ProductClientGatewayOptions} from './product-client-gateway.ts';
const colors=':root{--surface:#eef2f4;--panel:#fff;--ink:#1d2930;--muted:#53636c;--accent:#215d78;--danger:#a53f16;--border:#c3cdd3}';
const styles=colors+`*{box-sizing:border-box}body{margin:0;background:var(--surface);color:var(--ink);font-family:system-ui,"Noto Sans CJK SC",sans-serif;line-height:1.5}button,input{font:inherit}button{cursor:pointer;min-height:48px;border-radius:6px;border:0;padding:0 22px;background:var(--accent);color:white;font-weight:650}button:disabled{cursor:wait;opacity:.6}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.login{min-height:100svh;display:grid;place-items:center;padding:32px}.panel{width:min(840px,100%);display:grid;grid-template-columns:1fr 1fr;background:var(--panel);border:1px solid var(--border);border-radius:12px;overflow:hidden}.intro{background:#dde7ec;padding:44px;display:flex;flex-direction:column;justify-content:space-between;gap:40px}.brand{font-size:22px;font-weight:800;letter-spacing:.04em}.intro h1{font-size:30px;line-height:1.25;margin:12px 0}.intro p{font-size:15px;margin:0;color:var(--muted)}.bed{width:100%;max-height:155px;color:var(--accent)}form{padding:44px;display:flex;flex-direction:column;justify-content:center;gap:16px}form h2{font-size:24px;margin:0 0 4px}label{display:grid;gap:7px;font-size:15px;font-weight:600}input{width:100%;height:48px;border:1px solid var(--border);border-radius:6px;padding:10px 12px;color:var(--ink);background:var(--panel)}.error{min-height:24px;margin:0;font-size:14px;color:var(--danger)}.toolbar{height:56px;background:var(--panel);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:18px;padding:0 20px}.toolbar .brand{font-size:18px}.account{margin-left:auto;max-width:40%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;color:var(--muted)}.toolbar button{background:transparent;color:var(--accent);min-height:44px;padding:0 12px}iframe{border:0;width:100%;height:calc(100svh - 56px);display:block}.connection{position:fixed;top:60px;left:20px;right:20px;margin:0;padding:12px;background:#fff0e7;color:var(--danger);z-index:2;border:1px solid var(--danger);border-radius:6px}.connection[hidden]{display:none}@media(max-width:650px){.login{padding:16px}.panel{grid-template-columns:1fr}.intro{padding:26px;gap:16px}.intro h1{font-size:25px}.bed{display:none}form{padding:26px}.toolbar{gap:10px;padding:0 12px}.toolbar .brand{font-size:16px}}`;
const loginScript=`const form=document.querySelector('form'),error=document.querySelector('[role=alert]'),button=form.querySelector('button');form.addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;button.textContent='正在登录';error.textContent='';try{const fields=new FormData(form),r=await fetch('/_client/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:fields.get('username'),password:fields.get('password')}),credentials:'same-origin'});if(!r.ok){error.textContent=r.status===401?'账号或密码不正确，请重新输入。':r.status===429?'登录会话已满，请稍后再试。':'暂时无法登录，请检查服务连接。';return;}form.reset();window.location.replace('/_client/control');}catch{error.textContent='无法连接打印服务，请检查连接后重试。';}finally{button.disabled=false;button.textContent='登录打印控制台';}});`;
const shellScript=`const account=document.querySelector('.account'),error=document.querySelector('[role=alert]'),button=document.querySelector('button');let stopped=false;async function identity(){try{const r=await fetch('/_client/session',{credentials:'same-origin',cache:'no-store'});if(r.status===401){stopped=true;window.location.replace('/_client/login');return;}if(!r.ok)throw Error();const data=await r.json();account.textContent=data.result.username;error.hidden=true;}catch{error.textContent='暂时无法确认登录状态，请检查服务连接。';error.hidden=false;}}void identity();const timer=setInterval(()=>{if(!stopped)void identity();},15000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});button.addEventListener('click',async()=>{button.disabled=true;try{const r=await fetch('/_client/session',{method:'DELETE',credentials:'same-origin'});if(r.ok||r.status===401){stopped=true;window.location.replace('/_client/login');return;}throw Error();}catch{error.textContent='未能完成退出，请检查连接后重试。';error.hidden=false;button.disabled=false;}});`;
function html(nonce:string,login:boolean){const body=login?`<main class="login"><section class="panel" aria-label="打印控制台登录"><div class="intro"><div><div class="brand">ANYRAID</div><h1>打印控制台</h1><p>Cycnumbris 500 系列</p></div><svg class="bed" viewBox="0 0 240 155" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2"><path d="M25 120 110 149 215 110 130 82Z M55 108 139 137 M85 96 169 125 M115 85 200 115 M67 134 171 95 M94 144 199 106" opacity=".35"/><path d="M93 24h45v30H93z M103 54v12l12 10 12-10V54 M115 76v19 M80 107h20v-7h28v-7h25"/><path d="M24 25V9h193v100 M24 9v110" opacity=".55"/></svg><p>登录后查看打印任务、管理文件和设备配置。</p></div><form><h2>登录账号</h2><label>用户名<input name="username" autocomplete="username" required maxlength="128" autofocus></label><label>密码<input name="password" type="password" autocomplete="current-password" required maxlength="1024"></label><p class="error" role="alert" aria-live="polite"></p><button type="submit">登录打印控制台</button></form></section></main>`:`<header class="toolbar"><span class="brand">ANYRAID</span><span class="account" aria-live="polite">正在确认账号</span><button type="button">退出登录</button></header><p class="connection" role="alert" aria-live="polite" hidden></p><iframe src="/" title="Mainsail 打印控制台"></iframe>`;return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ANYRAID 打印控制台</title><style nonce="${nonce}">${styles}</style></head><body>${body}<script nonce="${nonce}">${login?loginScript:shellScript}</script></body></html>`;}
const mime:Record<string,string>={'.html':'text/html; charset=UTF-8','.js':'text/javascript; charset=UTF-8','.css':'text/css; charset=UTF-8','.json':'application/json; charset=UTF-8','.png':'image/png','.ico':'image/x-icon','.svg':'image/svg+xml','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.txt':'text/plain; charset=UTF-8','.map':'application/json; charset=UTF-8'};
// The unchanged official worker has root navigation fallback. Establish the
// product's session/API boundary before importing it, so a cached client index
// cannot replace login/logout or answer an offline API/navigation request.
const workerBoundary=`self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(url.origin===self.location.origin&&(url.pathname==='/'||/^\\/(?:_client|server|printer|machine|access|websocket)(?:\\/|$)/.test(url.pathname))){event.respondWith(fetch(event.request));event.stopImmediatePropagation();}});importScripts('/_client/upstream-worker.js');\n`;
/** Assets are installed trusted frontend resources, never the writable G-code,
 * config or metadata roots. Existing client bytes remain unchanged. */
export async function productClientAssets(path:string):Promise<NonNullable<ProductClientGatewayOptions['client']>>{
 if(!isAbsolute(path))throw new TypeError('Client assets require an absolute installed directory');const root=await realpath(path),info=await stat(root);if(!info.isDirectory()||!(await stat(join(root,'index.html'))).isFile())throw new Error('Client assets need a readable index.html');
 return async(request,response,signal,authenticated)=>{
  signal.throwIfAborted();const route=request.url?.split('?')[0];response.setHeader('x-content-type-options','nosniff');response.setHeader('referrer-policy','same-origin');
  if(route==='/_client/login'||route==='/_client/control'){
   if(request.method!=='GET'||route==='/_client/control'&&!authenticated){response.writeHead(405);response.end();return;}const nonce=randomBytes(18).toString('base64url');response.setHeader('content-security-policy',`default-src 'self'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; frame-src 'self'; frame-ancestors 'self'; object-src 'none'; base-uri 'none'; form-action 'self'`);response.writeHead(200,{'content-type':'text/html; charset=UTF-8','cache-control':'no-store'});response.end(html(nonce,route==='/_client/login'));return;
  }
  if(!authenticated||!['GET','HEAD'].includes(request.method??'')){response.writeHead(405);response.end();return;}
  if(route==='/sw.js'){response.writeHead(200,{'content-type':'text/javascript; charset=UTF-8','cache-control':'no-store','service-worker-allowed':'/'});response.end(request.method==='HEAD'?'':workerBoundary);return;}
  let name:string;try{name=decodeURIComponent(route??'');}catch{response.writeHead(400);response.end();return;}
  if(['/', '/allPrinters', '/cam', '/console', '/heightmap', '/files', '/viewer', '/history', '/timelapse', '/config', '/settings/machine'].includes(name))name='/index.html';
  if(name==='/_client/upstream-worker.js')name='/sw.js';
  if(!name.startsWith('/')||name.includes('\\')||name.includes('\0')||name.split('/').some(p=>p==='.'||p==='..')||name.startsWith('//')){response.writeHead(400);response.end();return;}
  let file:Awaited<ReturnType<typeof open>>|undefined;
  try{
   const candidate=await realpath(join(root,name.slice(1))),rel=relative(root,candidate);if(rel.startsWith('..')||isAbsolute(rel))throw Error('Asset outside installed root');file=await open(candidate,constants.O_RDONLY|constants.O_NOFOLLOW);const info=await file.stat();if(!info.isFile()||info.size>32*1024*1024)throw Error('Invalid installed asset');
   response.setHeader('content-security-policy',"frame-ancestors 'self'; object-src 'none'; base-uri 'self'");response.writeHead(200,{'content-type':mime[extname(name)]??'application/octet-stream','content-length':info.size,'cache-control':'private, no-cache'});
   if(request.method==='HEAD'||info.size===0){response.end();return;}await pipeline(file.createReadStream({autoClose:false,start:0,end:info.size-1,highWaterMark:65536}),response,{signal});
  }catch{if(!response.headersSent){response.writeHead(404);response.end();}else response.destroy();}finally{await file?.close();}
 };
}
