import test from 'node:test';
import assert from 'node:assert/strict';
import {BedMeshMovePort,type BedMeshPortOptions} from '../src/motion/bed-mesh-port.ts';
import {BedMesh} from '../src/motion/bed-mesh.ts';
import {BedMeshFade} from '../src/motion/bed-mesh-fade.ts';
import {motionLimits} from '../src/motion/lookahead.ts';
import {GCodeMove} from '../src/gcode/move.ts';
function options():BedMeshPortOptions{return {mesh:new BedMesh({min_x:0,max_x:20,min_y:0,max_y:20,x_count:2,y_count:2,mesh_x_pps:0,mesh_y_pps:0,algo:'direct',tension:.2},[[0,.2],[0,.2]]),fade:new BedMeshFade({start:1,end:10,target:0}),physicalPosition:[0,0,0,0],limits:motionLimits(300,3000),validate:()=>{}};}
test('abort drops pending host motion, preserves first cause and permanently closes admission',()=>{const control=new AbortController(),port=new BedMeshMovePort({...options(),signal:control.signal});port.move([20,0,0,0],100);assert.equal(port.pending,4);const cause=new Error('heater fault');control.abort(cause);assert.equal(port.pending,0);assert.equal(port.flushDue,false);assert.equal(port.fault,cause);port.shutdown(new Error('secondary'));for(const action of [()=>port.position(),()=>port.move([0,0,0,0],100),()=>port.flush()])assert.throws(action,error=>error===cause);assert.deepEqual(port.plannedPosition,[20,0,.2,0]);});
test('stop during validation prevents late commit and logical coordinate advancement',()=>{const control=new AbortController();let count=0;const cause=new Error('temperature shutdown');const port=new BedMeshMovePort({...options(),signal:control.signal,validate:()=>{if(++count===3)control.abort(cause);}}),g=new GCodeMove(port);assert.throws(()=>g.execute('G1',{X:20}),error=>error===cause);assert.equal(port.pending,0);assert.deepEqual(port.plannedPosition,[0,0,0,0]);assert.deepEqual(g.state.position,[0,0,0,0]);});
test('stop inside junction calculation discards the batch and earlier pending motion',()=>{let port:BedMeshMovePort;let stop=false;const cause=new Error('stop in junction'),o=options();o.limits.extraAxes=[()=>{if(stop)port.shutdown(cause);return Infinity;}];port=new BedMeshMovePort(o);port.move([5,0,0,0],100);stop=true;assert.throws(()=>port.move([20,0,0,0],100),error=>error===cause);assert.equal(port.pending,0);assert.deepEqual(port.plannedPosition,[5,0,.05,0]);});
test('pre-aborted construction fails and stop cannot retract previously flushed trajectories',()=>{const control=new AbortController(),cause=new Error('already stopped');control.abort(cause);assert.throws(()=>new BedMeshMovePort({...options(),signal:control.signal}),error=>error===cause);const port=new BedMeshMovePort(options());port.move([20,0,0,0],100);const exported=port.flush();port.shutdown();assert.equal(exported.length,4);assert.ok(exported.every(m=>m.profile));assert.equal(port.pending,0);});
