import test from 'node:test';
import assert from 'node:assert/strict';
import {BedMesh,type BedMeshParameters} from '../src/motion/bed-mesh.ts';
const params:BedMeshParameters={min_x:0,max_x:100,min_y:10,max_y:210,x_count:3,y_count:3,mesh_x_pps:2,mesh_y_pps:3,algo:'lagrange',tension:.2},plane=[[1,2,3],[3,4,5],[5,6,7]];
test('bed mesh reproduces probe knots, linear planes and clamped/offset lookups',()=>{const mesh=new BedMesh(params,plane);assert.equal(mesh.width,7);assert.equal(mesh.height,9);for(let y=0;y<3;y++)for(let x=0;x<3;x++)assert.equal(mesh.calcZ(x*50,10+y*100),plane[y][x]);assert.ok(Math.abs(mesh.calcZ(25,60)-2.5)<1e-14);assert.equal(mesh.calcZ(-100,-100),1);assert.equal(mesh.calcZ(1000,1000),7);mesh.setOffsets(25,50);assert.ok(Math.abs(mesh.calcZ(0,10)-2.5)<1e-14);assert.throws(()=>mesh.setOffsets(0,NaN));assert.ok(Math.abs(mesh.calcZ(0,10)-2.5)<1e-14);const copy=mesh.meshValues();copy.fill(99);assert.notEqual(mesh.calcZ(0,10),99);});
test('direct zero reference subtracts once and updates both owned tables atomically',()=>{const mesh=new BedMesh({...params,mesh_x_pps:0,mesh_y_pps:0},plane);assert.equal(mesh.params.algo,'direct');mesh.setZeroReference(50,110);assert.equal(mesh.calcZ(50,110),0);assert.deepEqual(Array.from(mesh.probedValues()),[-3,-2,-1,-1,0,1,1,2,3]);assert.deepEqual(mesh.range(),[-3,3]);assert.equal(plane[0][0],1);const huge=new BedMesh({...params,mesh_x_pps:0,mesh_y_pps:0},[[1e308,-1e308,0],[0,0,0],[0,0,0]]),before=huge.meshValues();assert.throws(()=>huge.setZeroReference(0,10),/overflow/);assert.deepEqual(huge.meshValues(),before);});
test('mesh algorithm admission rejects unsafe grids and falls back as configured by Klipper',()=>{assert.equal(new BedMesh({...params,algo:'bicubic'},plane).params.algo,'lagrange');for(const p of [{...params,x_count:7},{...params,algo:'direct' as const},{...params,max_y:10},{...params,mesh_x_pps:-1},{...params,tension:Infinity}])assert.throws(()=>new BedMesh(p,plane));assert.throws(()=>new BedMesh(params,[[1,2],[3,NaN]]));assert.throws(()=>new BedMesh({...params,min_x:1e20,max_x:1e20+100},plane));assert.throws(()=>new BedMesh(params,plane).calcZ(Infinity,0));});
test('bicubic cardinal boundary controls preserve knots and configured overshoot',()=>{const p:BedMeshParameters={...params,min_x:0,max_x:3,min_y:0,max_y:3,x_count:4,y_count:4,mesh_x_pps:1,mesh_y_pps:1,algo:'bicubic'},values=Array.from({length:4},(_,y)=>Array.from({length:4},(_,x)=>x*x+y*y));const mesh=new BedMesh(p,values);for(let y=0;y<4;y++)for(let x=0;x<4;x++)assert.equal(mesh.calcZ(x,y),values[y][x]);assert.ok(Math.abs(mesh.calcZ(.5,0)-.425)<1e-15);assert.ok(Math.abs(mesh.calcZ(.5,.5)-.85)<1e-15);assert.equal(new BedMesh({...p,tension:0},values).calcZ(.5,0),.5);assert.equal(new BedMesh({...p,tension:2},values).calcZ(.5,0),-.25);});
test('mesh average uses Python rounding on binary floats and compensated row sums',()=>{const create=(values:number[][])=>new BedMesh({min_x:0,max_x:1,min_y:0,max_y:1,x_count:values[0].length,y_count:values.length,mesh_x_pps:0,mesh_y_pps:0,algo:'direct',tension:.2},values);for(const [value,expected] of [[.125,.12],[.375,.38],[2.675,2.67],[-.125,-.12],[-2.675,-2.67]])assert.equal(create([[value,value],[value,value]]).average(),expected);assert.ok(Object.is(create([[-.001,-.001],[-.001,-.001]]).average(),-0));assert.equal(create([[1e16,1,-1e16],[1e16,1,-1e16]]).average(),.33);assert.throws(()=>create([[1e308,1e308],[1e308,1e308]]).average(),/overflow/);});
