import test from 'node:test';
import assert from 'node:assert/strict';
import {BedMesh} from '../src/motion/bed-mesh.ts';
import {BedMeshFade} from '../src/motion/bed-mesh-fade.ts';
import {BedMeshMovePort} from '../src/motion/bed-mesh-port.ts';
import {motionLimits} from '../src/motion/lookahead.ts';
import {GCodeMove} from '../src/gcode/move.ts';
const mesh=()=>new BedMesh({min_x:0,max_x:20,min_y:0,max_y:20,x_count:2,y_count:2,mesh_x_pps:0,mesh_y_pps:0,algo:'direct',tension:.2},[[0,.2],[0,.2]]);
const options=()=>({mesh:mesh(),fade:new BedMeshFade({start:1,end:10,target:0}),physicalPosition:[0,0,0,0],limits:motionLimits(300,3000),validate:()=>{}});
test('pressure requests anchor after all mesh splits without flushing lookahead',()=>{
 const port=new BedMeshMovePort(options());assert.equal(port.markPendingPressureBoundary({stepper:'e',advance:.1}),false);port.move([20,0,0,1],100);const count=port.pending;assert(count>1);assert.equal(port.markPendingPressureBoundary({stepper:'e',advance:.08}),true);port.markPendingPressureBoundary({stepper:'e',advance:.1});assert.equal(port.pending,count);const moves=port.flush();assert(moves.slice(0,-1).every(m=>m.pressureBoundaries===undefined));assert.deepEqual(moves.at(-1)!.pressureBoundaries,[{stepper:'e',advance:.1}]);
});
test('G-code mesh adapter plans compensated segments and preserves independent mesh state',()=>{const o=options(),port=new BedMeshMovePort(o),gcode=new GCodeMove(port);o.mesh.setOffsets(100,0);gcode.execute('G1',{X:20,E:1,F:6000});assert.equal(port.pending,4);assert.deepEqual(port.plannedPosition,[20,0,.2,1]);assert.deepEqual(gcode.state.position,[20,0,0,1]);const planned=port.flush();planned.forEach((m,i)=>assert.ok(Math.abs(m.endPos[2]-[.05,.1,.15,.2][i])<1e-15));assert.ok(planned.every(m=>m.profile));assert.deepEqual(port.position(),[20,0,0,1]);gcode.execute('G1',{Z:10});assert.deepEqual(port.plannedPosition,[20,0,10,1]);});
test('late safety failure leaves lookahead and G-code coordinates unchanged and retry succeeds',()=>{let fail=true,count=0;const port=new BedMeshMovePort({...options(),validate:()=>{if(++count===3&&fail)throw new Error('limit');}}),gcode=new GCodeMove(port);assert.throws(()=>gcode.execute('G1',{X:20,E:1}),/limit/);assert.equal(port.pending,0);assert.deepEqual(port.plannedPosition,[0,0,0,0]);assert.deepEqual(gcode.state.position,[0,0,0,0]);fail=false;gcode.execute('G1',{X:20,E:1});assert.equal(port.pending,4);});
test('mesh port rejects reentry and invalid fade, passes through without a mesh',()=>{let port:BedMeshMovePort;port=new BedMeshMovePort({...options(),validate:()=>{port.flush();}});assert.throws(()=>port.move([20,0,0,0],100),/admission active/);assert.equal(port.pending,0);assert.throws(()=>new BedMeshMovePort({...options(),fade:new BedMeshFade({start:0,end:.1,target:0})}),/fade range/);const direct=new BedMeshMovePort({...options(),mesh:null});direct.move([2,3,4,5],100);assert.deepEqual(direct.position(),[2,3,4,5]);assert.equal(direct.flush().length,1);});
test('asynchronous validators cannot admit motion',async()=>{assert.throws(()=>new BedMeshMovePort({...options(),validate:async()=>{}}),/configuration/);const port=new BedMeshMovePort({...options(),validate:()=>Promise.reject(new Error('async failure'))});assert.throws(()=>port.move([20,0,0,0],100),/synchronously/);await new Promise(resolve=>setImmediate(resolve));assert.equal(port.pending,0);assert.deepEqual(port.plannedPosition,[0,0,0,0]);});
