import {test} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {WebSocket} from 'ws';
import {ClientRequests,ClientResponseError} from '../src/moonraker/client-requests.ts';
import {MoonrakerNetwork} from '../src/moonraker/server.ts';
import {JsonRpcDispatcher,ApiError} from '../src/moonraker/rpc.ts';
import {parseRequestJson} from '../src/moonraker/json.ts';
const frame=(v:unknown)=>Buffer.from(JSON.stringify(v));
const status=(n:number)=>(e:unknown)=>e instanceof ApiError&&e.status===n;
async function until(fn:()=>boolean){for(let i=0;i<500;i++){if(fn())return;await delay(2);}throw new Error('Condition timed out');}
test('outbound replies correlate only to their connection and preserve falsy values',async()=>{
 const queue=new ClientRequests(),sent:any[]=[];for(const id of [1,2])queue.add(id,{signal:new AbortController().signal,authorize(){},send(s){sent.push(JSON.parse(s));return true;}});
 for(const result of [null,false,0,'',{position:[1,2,3]}]){const task=queue.request(1,'read',[]),id=sent.at(-1).id;assert.equal(Object.hasOwn(sent.at(-1),'params'),false);assert.equal(queue.receive(2,id,{result}),false);assert.equal(queue.receive(1,String(id),{result}),false);assert.equal(queue.receive(1,id,{result,error:null}),false);assert.equal(queue.receive(1,id,{result}),true);assert.deepEqual(await task,result);assert.equal(queue.receive(1,id,{result}),false);}
 const failed=queue.request(1,'read');queue.receive(1,sent.at(-1).id,{error:{code:42,message:'remote'}});await assert.rejects(failed,(e:unknown)=>e instanceof ClientResponseError&&e.status===424&&JSON.stringify(e.data)==='{"code":42,"message":"remote"}');assert.equal(queue.status.pending,0);assert.equal(queue.status.bytes,0);await queue.close();
});
test('authorization sees immutable wire payload and large floating quantities keep exponent syntax',async()=>{
 const queue=new ClientRequests();let release!:()=>void,encoded='';const gate=new Promise<void>(r=>release=r);queue.add(1,{signal:new AbortController().signal,authorize(_m,p){assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen((p as any).position));return gate;},send(s){encoded=s;return true;}});const params={position:[1,2],large:1e20,exact:'9007199254740993'},task=queue.request(1,'move',params);params.position[0]=9;release();await until(()=>!!encoded);const wire:any=parseRequestJson(encoded);assert.deepEqual(wire.params,{position:[1,2],large:1e20,exact:'9007199254740993'});assert.match(encoded,/1e\+20/);queue.receive(1,wire.id,{result:true});assert.equal(await task,true);await queue.close();
});
test('cancel wins over reentrant replies and retains ignored authorization until completion',async()=>{
 const queue=new ClientRequests({pending:1}),caller=new AbortController();let release!:()=>void,sends=0;const gate=new Promise<void>(r=>release=r);queue.add(1,{signal:new AbortController().signal,authorize(_m,_p,signal){signal.addEventListener('abort',()=>queue.receive(1,1,{result:'too late'}));return gate;},send(){sends++;return true;}});const task=queue.request(1,'work',null,{signal:caller.signal});caller.abort();await assert.rejects(task,status(499));assert.equal(queue.status.pending,1);assert.throws(()=>queue.request(1,'other'),status(429));let closed=false;const closing=queue.close().then(()=>closed=true);await delay(2);assert.equal(closed,false);release();await closing;assert.equal(queue.status.pending,0);assert.equal(queue.status.bytes,0);assert.equal(sends,0);
});
test('timeouts and disconnects reject pending replies and release capacity',async()=>{
 const queue=new ClientRequests({timeoutMs:10}),peer=new AbortController();queue.add(1,{signal:peer.signal,authorize(){},send(){return true;}});await assert.rejects(queue.request(1,'slow'),status(504));assert.equal(queue.status.pending,0);const pending=queue.request(1,'disconnect');peer.abort();await assert.rejects(pending,status(503));assert.equal(queue.status.pending,0);assert.throws(()=>queue.request(1,'gone'),status(503));await queue.close();
});
test('denial, transport failure, budgets and invalid values do not leak pending jobs',async()=>{
 for(const kind of ['deny','reject','false','throw']){const queue=new ClientRequests();queue.add(1,{signal:new AbortController().signal,authorize(){if(kind==='deny')throw new Error('secret');if(kind==='reject')return Promise.reject(new ApiError(403,'Denied'));},send(){if(kind==='throw')throw new Error('secret');return false;}});await assert.rejects(queue.request(1,'work'),status(kind==='deny'?401:kind==='reject'?403:503));assert.equal(queue.status.pending,0);await queue.close();}
 const queue=new ClientRequests({bytes:40});queue.add(1,{signal:new AbortController().signal,authorize(){},send(){return true;}});assert.throws(()=>queue.request(1,'request-with-large-name'),status(429));assert.throws(()=>queue.request(1,'bad',true as any));assert.throws(()=>queue.request(1,'bad',{n:Infinity}));assert.throws(()=>queue.request(1,'bad',['x'.repeat(1024*1024)]),status(413));assert.equal(queue.status.pending,0);await queue.close();
});
test('mixed frames prioritize replies and retain request batch shape without float reencoding',async()=>{
 const queue=new ClientRequests();let id=0;queue.add(1,{signal:new AbortController().signal,authorize(){},send(s){id=JSON.parse(s).id;return true;}});const task=queue.request(1,'work');const input=Buffer.from(`[{"jsonrpc":"2.0","method":"echo","params":{"n":1e20},"id":99},{"jsonrpc":"2.0","id":${id},"result":null}]`);assert.deepEqual(queue.acceptFrame(1,input),{value:[{jsonrpc:'2.0',method:'echo',params:{n:1e20},id:99}]});assert.equal(await task,null);
 const again=queue.request(1,'work');assert.equal(queue.acceptFrame(1,Buffer.from(`{"jsonrpc":"2.0","id":${id},"result":9007199254740993}`)),undefined);assert.equal(queue.status.awaiting,1);assert.deepEqual(queue.acceptFrame(1,frame({jsonrpc:'2.0',id,result:'9007199254740993'})),{});assert.equal(await again,'9007199254740993');await queue.close();
});
test('old authorization cannot send after its connection is replaced',async()=>{
 const queue=new ClientRequests();let release!:()=>void;const gate=new Promise<void>(r=>release=r);queue.add(1,{signal:new AbortController().signal,authorize:()=>gate,send(){throw new Error('old send');}});const old=queue.request(1,'old');queue.remove(1);await assert.rejects(old,status(503));queue.add(1,{signal:new AbortController().signal,authorize(){},send(s){queue.receive(1,JSON.parse(s).id,{result:'new'});return true;}});release();assert.equal(await queue.request(1,'new'),'new');await queue.close();assert.equal(queue.status.pending,0);
});
test('live server receives agent replies even with its only incoming request slot occupied',async()=>{
 const rpc=new JsonRpcDispatcher();let network:MoonrakerNetwork;rpc.register('relay',['websocket'],(_p,c)=>network.requestClient(c.connectionId!,'agent.read',{value:1},{signal:c.signal}));network=new MoonrakerNetwork(rpc,{authorize(){},authorizeClientRequest(){},maxRequests:1,maxRequestsPerSocket:1});const address=await network.listen(),ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);try{await once(ws,'open');const result=new Promise<any>(resolve=>ws.on('message',m=>{const value=JSON.parse(String(m));if(value.method==='agent.read')ws.send(JSON.stringify({jsonrpc:'2.0',id:value.id,result:null}));else resolve(value);}));ws.send(JSON.stringify({jsonrpc:'2.0',method:'relay',id:7}));assert.deepEqual(await result,{jsonrpc:'2.0',result:null,id:7});assert.equal(network.status.clientRequests?.pending,0);assert.equal(ws.readyState,WebSocket.OPEN);}finally{ws.terminate();await network.close();}
});
test('network requires explicit outbound policy and waits for ignored authorization on shutdown',async()=>{
 const disabled=new MoonrakerNetwork(new JsonRpcDispatcher(),{authorize(){}});try{await disabled.listen();assert.throws(()=>disabled.requestClient(1,'read'),/authorization/);}finally{await disabled.close();}
 let release!:()=>void;const gate=new Promise<void>(r=>release=r),network=new MoonrakerNetwork(new JsonRpcDispatcher(),{authorize(){},authorizeClientRequest:()=>gate,shutdownTimeoutMs:20});const address=await network.listen(),ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);try{await once(ws,'open');const task=network.requestClient(network.clients[0].id,'read');const rejected=assert.rejects(task,status(503));await assert.rejects(network.close(),/shutdown deadline/);await rejected;assert.equal(network.status.phase,'closing');assert.equal(network.status.clientRequests?.pending,1);release();await network.close();assert.equal(network.status.clientRequests?.pending,0);}finally{release?.();ws.terminate();await network.close();}
});
test('sent request cancellation rejects before abort hooks can inject a reply',async()=>{
 const queue=new ClientRequests(),caller=new AbortController();let id=0;queue.add(1,{signal:new AbortController().signal,authorize(_m,_p,signal){signal.addEventListener('abort',()=>assert.equal(queue.receive(1,id,{result:'late'}),false));},send(s){id=JSON.parse(s).id;return true;}});const task=queue.request(1,'read',null,{signal:caller.signal});caller.abort();await assert.rejects(task,status(499));assert.equal(queue.status.awaiting,0);assert.equal(queue.status.pending,0);await queue.close();
});
test('per-client and global limits count requests waiting for replies independently',async()=>{
 const queue=new ClientRequests({pending:2,perClient:1}),ids=new Map<number,number>();for(const id of [1,2,3])queue.add(id,{signal:new AbortController().signal,authorize(){},send(s){ids.set(id,JSON.parse(s).id);return true;}});const a=queue.request(1,'read');assert.throws(()=>queue.request(1,'read'),status(429));const b=queue.request(2,'read');assert.throws(()=>queue.request(3,'read'),status(429));queue.receive(1,ids.get(1)!,{result:1});assert.equal(await a,1);const c=queue.request(3,'read');queue.receive(3,ids.get(3)!,{result:3});queue.receive(2,ids.get(2)!,{result:2});assert.deepEqual(await Promise.all([b,c]),[2,3]);assert.equal(queue.status.bytes,0);await queue.close();
});
