import test from 'node:test';
import assert from 'node:assert/strict';
import {MCUGroup} from '../src/runtime/mcu-group.ts';
import {SerialSession} from '../src/protocol/serial-session.ts';
import {serialFirmware} from './helpers/serial-firmware.ts';
import {TrapQueue} from '../src/motion/trap-queue.ts';
import {MotionCoordinator} from '../src/motion/coordinator.ts';
import {MoveQueueSink} from '../src/motion/move-queue-sink.ts';
import {CoordinatedMotionDrain} from '../src/motion/coordinated-drain.ts';
async function fixture(run:(drain:CoordinatedMotionDrain,g:MCUGroup,c:MotionCoordinator,q:TrapQueue,fw:Awaited<ReturnType<typeof serialFirmware>>,end:number)=>Promise<void>,retainHistory:()=>Promise<void>=async()=>{}){const fw=await serialFirmware(),signal=new AbortController().signal;let session!:SerialSession;const g=new MCUGroup([{id:'m',async connect(s,stopDevice){session=new SerialSession(fw.fd,{stopDevice});await session.initialize(s);return session;},async stopDevice(){}}]);try{await g.start(signal);await session.configure({oidCount:4,commands:[]},signal);const start=Number(session.clock.sync.lastClock)/1e6+.1,end=start+.1;using q=new TrapQueue();q.appendRaw(new Float64Array([start,0,.1,0,0,0,0,1,0,0,10,10,0]));using step=q.createStepper({frequency:1e6,timeOffset:0,oid:3,maxError:0,queueStepTag:8,directionTag:9},'x',.01);const sink=new MoveQueueSink([g.motionQueue('m',['x'],t=>step.clockAt(t))],retainHistory),c=new MotionCoordinator([{id:'x',queue:q,stepper:step}],sink,16*1024*1024,0,[session.clock]);await run(new CoordinatedMotionDrain(c,sink,g),g,c,q,fw,end);}finally{await g.stop();await fw.close();}}
test('native generation routes to serial firmware then waits beyond the complete motion boundary',async()=>fixture(async(d,g,c,q,fw,end)=>{const result=await d.drain(end,new Map([[q,[1,0,0] as const]]),new AbortController().signal,3000);assert.ok(g.session('m').clock.sync.lastClock>result.targets.m);assert.equal(c.status.committedTime,result.generatedUntil);assert.ok(result.sourceUntil>result.generatedUntil);assert.equal(fw.motion.filter(m=>m.name==='queue_step').reduce((sum,m)=>sum+Number(m.parameters.count),0),100);assert.equal(g.status.state,'ready');}));
test('cancellation fences native generation and the entire MCU group',async()=>fixture(async(d,g,c,q,_fw,end)=>{const controller=new AbortController(),cause=new Error('cancel unified drain'),running=d.drain(end,new Map([[q,[1,0,0] as const]]),controller.signal,3000);const rejected=assert.rejects(running,/cancel|stopped|closed/);controller.abort(cause);await rejected;assert.equal(c.status.failed,true);assert.equal(g.status.state,'stopped');}));
test('concurrent drains are rejected and one deadline covers the complete operation',async()=>fixture(async(d,g,c,q,_fw,end)=>{const p=d.drain(end,new Map([[q,[1,0,0] as const]]),new AbortController().signal,20);const failed=assert.rejects(p,/timed out/);await assert.rejects(d.drain(end,new Map([[q,[1,0,0] as const]]),new AbortController().signal),/already active/);await failed;assert.equal(c.status.failed,true);assert.equal(g.status.state,'stopped');}));

test('deadline rejects an unresponsive history hook and late completion cannot send packets',async()=>{let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});await fixture(async(d,g,c,q,fw,end)=>{await assert.rejects(d.drain(end,new Map([[q,[1,0,0] as const]]),new AbortController().signal,20),/timed out/);assert.equal(g.status.state,'stopped');assert.equal(c.status.failed,true);assert.equal(fw.motion.length,0);release();await new Promise<void>(r=>setImmediate(r));assert.equal(fw.motion.length,0);},()=>gate);});
test('streaming commit shares cancellation deadline and fences an unresponsive history hook',async()=>{let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});await fixture(async(d,g,c,q,fw,end)=>{const pending=d.advanceSource(end,new AbortController().signal,20),rejected=assert.rejects(pending,/timed out/);await assert.rejects(d.drain(end,new Map([[q,[1,0,0] as const]]),new AbortController().signal),/already active/);await rejected;assert.equal(g.status.state,'stopped');assert.equal(c.status.failed,true);assert.equal(fw.motion.length,0);release();await new Promise<void>(r=>setImmediate(r));assert.equal(fw.motion.length,0);},()=>gate);});
