import {test} from 'node:test';
import assert from 'node:assert/strict';
import {compileDigital,DigitalOutput} from '../src/outputs/digital.ts';
import {PrinterPins} from '../src/protocol/pins.ts';
import {MessageDictionary} from '../src/protocol/dictionary.ts';
import {serialFirmware} from './helpers/serial-firmware.ts';
import {SerialSession} from '../src/protocol/serial-session.ts';
import {serialClock} from '../src/protocol/serial-queue.ts';
const signal=()=>new AbortController().signal;
function dictionary(frequency=1e6){const d=new MessageDictionary();d.identify(Buffer.from(JSON.stringify({commands:{'config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u':21,'update_digital_out oid=%c value=%c':22,'queue_digital_out oid=%c clock=%u on_ticks=%u':23},responses:{},config:{CLOCK_FREQ:frequency}})),false);return d;}
function binding(){const chip={},pins=new PrinterPins<object>();pins.register('mcu',chip);return {chip,pin:pins.lookup('!PA0',{canInvert:true})};}
test('digital output configuration preserves inverted defaults and reserves a move slot',()=>{
 const {chip,pin}=binding(),config=compileDigital(chip,dictionary(),{oid:3,pin});assert.equal(config.config,'config_digital_out oid=3 pin=PA0 value=1 default_value=1 max_duration=2000000');assert.equal(config.restart,'update_digital_out oid=3 value=1');assert.equal(config.reservedMoves,1);assert.ok(Object.isFrozen(config));assert.throws(()=>compileDigital(chip,dictionary(),{oid:3,pin,start:true}),/equal/);assert.throws(()=>compileDigital(chip,dictionary(),{oid:3,pin,maxDuration:1e-9}),/tick/);assert.throws(()=>compileDigital(chip,dictionary(),{oid:3,pin,maxDuration:2148}),/tick/);assert.throws(()=>compileDigital({},dictionary(),{oid:3,pin}),/binding/);assert.equal(compileDigital(chip,dictionary(),{oid:3,pin,start:true,maxDuration:0}).maxDurationTicks,0);
});
test('scheduled output retains 64-bit FIFO clocks and encodes only low 32 wire bits',async()=>{
 const {chip,pin}=binding(),d=dictionary(),config=compileDigital(chip,d,{oid:3,pin}),sent:{data:Uint8Array;min:bigint;req:bigint}[]=[];const output=new DigitalOutput(config,d,{async send(data,min,req){sent.push({data,min,req});},async stop(){}},t=>BigInt(t));await output.setDigital(0xffffffff,false,signal());await output.setDigital(0x100000001,true,signal());assert.deepEqual(sent.map(p=>[p.min,p.req]),[[0n,0xffffffffn],[0xffffffffn,0x100000001n]]);assert.deepEqual(sent[1].data,d.encode('queue_digital_out',{oid:3,clock:1,on_ticks:0}));await assert.rejects(output.setDigital(0,true,signal()),/rewind/);assert.equal(sent.length,2);
});
test('output transport failure is terminal and cannot replay subsequent values',async()=>{
 const {chip,pin}=binding(),d=dictionary();let stops=0;const output=new DigitalOutput(compileDigital(chip,d,{oid:3,pin}),d,{async send(){throw new Error('wire failed');},async stop(){stops++;}},t=>BigInt(t));await assert.rejects(output.setDigital(1,true,signal()),/wire failed/);await assert.rejects(output.setDigital(2,false,signal()),/faulted/);assert.equal(stops,1);assert.equal(output.status.lastClock,1n);
});
test('configured digital updates pass through a dedicated FIFO and reserved move capacity',async()=>{
 const fw=await serialFirmware(),s=new SerialSession(fw.fd,{async stopDevice(){}});try{await s.initialize(signal());const {chip,pin}=binding(),compiled=compileDigital(chip,s.dictionary,{oid:3,pin});await s.configure({oidCount:4,commands:[compiled.config],restart:[compiled.restart],reservedMoves:compiled.reservedMoves},signal());assert.equal(s.configuration.moveSlots,511);const output=new DigitalOutput(compiled,s.dictionary,s.commandQueue(),t=>s.clock.sync.getClock(t));const now=serialClock.now();const first=output.setDigital(now+.04,true,signal()),second=output.setDigital(now+.08,false,signal());await Promise.all([first,second]);const updates=fw.outputs.filter(x=>x.name==='queue_digital_out');assert.equal(updates.length,2);assert.deepEqual(updates.map(x=>x.parameters.on_ticks),[0,1]);assert.equal(fw.outputs[0].name,'config_digital_out');}finally{await s.stop();await fw.close();}
});
test('future motion backpressure does not block output commands or control queries',async()=>{
 const fw=await serialFirmware();let stops=0;const s=new SerialSession(fw.fd,{async stopDevice(){stops++;}});try{await s.initialize(signal());await s.configure({oidCount:4,commands:[],reservedMoves:1},signal());const motion=s.motionTransport(['x']),future=s.clock.sync.getClock(serialClock.now()+10),data=Buffer.from(s.dictionary.encode('set_next_step_dir',{oid:3,dir:1}));const moving=motion.send(Array.from({length:5000},()=>({id:'x',data,minClock:future,reqClock:future}))),rejected=assert.rejects(moving,/closed/);const output=s.commandQueue();await output.send(s.dictionary.encode('queue_digital_out',{oid:2,clock:0,on_ticks:0}),0n,0n,signal());assert.equal(fw.outputs.length,1);const echo=await s.query(s.dictionary.encode('echo',{value:9}),'echo_response',signal());assert.equal(echo.message.parameters.value,9);assert.equal(fw.motion.length,0);await s.stop();await rejected;assert.equal(stops,1);}finally{await s.stop();await fw.close();}
});
test('peripheral command budget leaves room for clock/control traffic and future clock limits apply',async()=>{
 const fw=await serialFirmware(),s=new SerialSession(fw.fd,{async stopDevice(){}});try{await s.initialize(signal());await s.configure({oidCount:4,commands:[]},signal());const q=s.commandQueue(),future=s.clock.sync.getClock(serialClock.now()+10),payload=s.dictionary.encode('queue_digital_out',{oid:2,clock:Number(BigInt.asUintN(32,future)),on_ticks:0});await assert.rejects(q.send(payload,0n,s.clock.sync.getClock(serialClock.now()+61),signal()),/horizon/);await assert.rejects(q.send(payload,2n,1n,signal()),/clocks/);for(let i=0;i<125;i++)s.commandQueue();assert.throws(()=>s.commandQueue(),/available/);const requests=Array.from({length:64},()=>assert.rejects(q.send(payload,future,future,signal()),/stop outputs/));await assert.rejects(q.send(payload,future,future,signal()),/capacity/);const echo=await s.query(s.dictionary.encode('echo',{value:12}),'echo_response',signal());assert.equal(echo.message.parameters.value,12);await s.stop(new Error('stop outputs'));await Promise.all(requests);}finally{await s.stop();await fw.close();}
});
import {MCUGroup} from '../src/runtime/mcu-group.ts';
test('cancelling a scheduled group output closes both MCUs and preserves the cause',async()=>{
 const fws=await Promise.all([serialFirmware(),serialFirmware()]),sessions:SerialSession[]=[],stops=[0,0];const group=new MCUGroup(fws.map((fw,i)=>({id:`mcu${i}`,async connect(signal:AbortSignal,stopDevice:(cause:unknown)=>Promise<void>){const s=new SerialSession(fw.fd,{stopDevice});sessions[i]=s;await s.initialize(signal);return s;},async stopDevice(){stops[i]++;}})));
 try{await group.start(signal());for(const s of sessions)await s.configure({oidCount:4,commands:[]},signal());const s=sessions[0],future=s.clock.sync.getClock(serialClock.now()+10),abort=new AbortController();const pending=group.commandQueue('mcu0').send(s.dictionary.encode('queue_digital_out',{oid:2,clock:Number(BigInt.asUintN(32,future)),on_ticks:0}),future,future,abort.signal),rejected=assert.rejects(pending,/cancel output/);abort.abort(new Error('cancel output'));await rejected;assert.deepEqual(stops,[1,1]);assert.ok(sessions.every(s=>s.status.state==='closed'));assert.equal(group.status.state,'stopped');}finally{await group.stop();await Promise.all(fws.map(fw=>fw.close()));}
});
