import test from 'node:test';
import assert from 'node:assert/strict';
import {createGuardedBedMeshPort} from '../src/motion/guarded-bed-mesh-port.ts';
import {BedMesh} from '../src/motion/bed-mesh.ts';
import {BedMeshFade} from '../src/motion/bed-mesh-fade.ts';
import {motionLimits} from '../src/motion/lookahead.ts';
import {ExtrusionGuard} from '../src/motion/extrusion.ts';
import {LinearKinematics} from '../src/kinematics/linear.ts';
import {TemperatureState} from '../src/thermal/state.ts';
import {GCodeMove} from '../src/gcode/move.ts';
function setup(maxZ=20){const kinematics=new LinearKinematics({kind:'cartesian',ranges:[[0,20],[0,20],[0,maxZ]],maxVelocity:300,maxAccel:3000,maxZVelocity:5,maxZAccel:100});const extrusion=new ExtrusionGuard({nozzleDiameter:.4,filamentDiameter:1.75,maxCrossSection:.64,maxVelocity:25,maxAccel:500,maxDistance:50,instantCornerVelocity:1});return {kinematics,extrusion,mesh:new BedMesh({min_x:0,max_x:20,min_y:0,max_y:20,x_count:2,y_count:2,mesh_x_pps:0,mesh_y_pps:0,algo:'direct',tension:.2},[[0,.2],[0,.2]]),fade:new BedMeshFade({start:1,end:10,target:0}),physicalPosition:[0,0,0,0],limits:motionLimits(300,3000),canExtrude:()=>true};}
test('compensated segments require homing and physical Z limits before any admission',()=>{const o=setup(.12),port=createGuardedBedMeshPort(o),g=new GCodeMove(port);assert.throws(()=>g.execute('G1',{X:20}),/home/);o.kinematics.markHomed([0,1,2]);assert.throws(()=>g.execute('G1',{X:20}),/range/);assert.equal(port.pending,0);assert.deepEqual(g.state.position,[0,0,0,0]);});
test('thermal permission is live on every extruding segment and failure is atomic',()=>{const o=setup();o.kinematics.markHomed([0,1,2]);const state=new TemperatureState({minimum:0,maximum:300,minimumExtrude:170,smoothTime:1});state.sample(1,200);let now=1,calls=0;const port=createGuardedBedMeshPort({...o,canExtrude:()=>{if(++calls===3)now=9;return state.status(now).canExtrude;}}),g=new GCodeMove(port);assert.throws(()=>g.execute('G1',{X:20,E:1}),/temperature/);assert.equal(calls,3);assert.equal(port.pending,0);assert.deepEqual(port.plannedPosition,[0,0,0,0]);assert.deepEqual(g.state.position,[0,0,0,0]);});
test('guarded port enforces extrusion magnitude, cold retraction, and axis speed limits',()=>{const o=setup();o.kinematics.markHomed([0,1,2]);let hot=true;const port=createGuardedBedMeshPort({...o,canExtrude:()=>hot});assert.throws(()=>port.move([0,0,0,51],100),/too long/);assert.throws(()=>port.move([20,0,0,100],100),/maximum extrusion/);hot=false;assert.throws(()=>port.move([0,0,0,-1],100),/temperature/);hot=true;port.move([0,0,0,1],100);let moves=port.flush();assert.equal(moves[0].maxCruiseV2,625);port.move([0,0,10,1],100);moves=port.flush();assert.equal(moves[0].maxCruiseV2,25);assert.equal(moves[0].accel,100);});
test('permission truthiness and conflicting junction configuration cannot bypass guards',()=>{const o=setup();o.kinematics.markHomed([0,1,2]);assert.throws(()=>createGuardedBedMeshPort({...o,limits:{...o.limits,extraAxes:[()=>Infinity]}}),/owns/);const port=createGuardedBedMeshPort({...o,canExtrude:(()=>1) as unknown as ()=>boolean});assert.throws(()=>port.move([0,0,0,1],10),/temperature/);assert.equal(port.pending,0);});
