import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer,type Socket} from 'node:net';
import {once} from 'node:events';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {KlippyLifecycle,type KlippySnapshot} from '../src/moonraker/klippy-lifecycle.ts';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import {ApiError} from '../src/moonraker/rpc.ts';
const wire=(v:unknown)=>JSON.stringify(v)+'\x03';
async function until(fn:()=>boolean){for(let i=0;i<500;i++){if(fn())return;await delay(2);}throw new Error('Condition timed out');}
const endpoints=['info','emergency_stop','list_endpoints','objects/query','objects/list','objects/subscribe','gcode/subscribe_output','register_remote_method'];
function response(m:any){switch(m.method){case 'info':return {state:'ready',state_message:'Printer ready',software_version:'test'};case 'list_endpoints':return {endpoints};case 'objects/subscribe':return {eventtime:1,status:{webhooks:{state:'ready',state_message:'Printer ready'}}};case 'objects/list':return {objects:['virtual_sdcard','display_status','pause_resume']};case 'objects/query':return {status:{toolhead:{position:[1,2,3]}}};default:return {};}}
async function peer(run:(path:string,requests:any[],sockets:Socket[],dir:string)=>Promise<void>,handle:(m:any,s:Socket,requests:any[])=>boolean|void=()=>{}){const dir=await mkdtemp(join(tmpdir(),'klippy-init-test-')),path=join(dir,'api.sock'),sockets:Socket[]=[],seen:any[]=[],server=createServer(socket=>{sockets.push(socket);socket.on('error',()=>{});let tail='';socket.on('data',data=>{tail+=data.toString();for(let end;(end=tail.indexOf('\x03'))>=0;){const m=JSON.parse(tail.slice(0,end));tail=tail.slice(end+1);seen.push(m);if(handle(m,socket,seen)!==false)socket.write(wire({id:m.id,result:response(m)}));}});});server.listen(path);await once(server,'listening');try{await run(path,seen,sockets,dir);}finally{for(const socket of sockets)socket.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}}
test('initialization follows identification, startup polling, discovery, subscriptions and requirement checks',()=>peer(async(path,seen)=>{
 const states:KlippySnapshot[]=[],runtime=new KlippyLifecycle({version:'node-test',pollIntervalMs:1,onSnapshot:s=>states.push(s)});try{const opening=runtime.initialize(path);assert.equal(runtime.initialize(path),opening);const result=await opening;assert.equal(result.connected,true);assert.equal(result.initialized,true);assert.equal(result.state,'ready');assert.equal(result.requirementsChecked,true);assert.deepEqual(result.missingRequirements,[]);assert.deepEqual(seen.map(m=>m.method),['info','list_endpoints','info','objects/subscribe','gcode/subscribe_output','list_endpoints','objects/list']);assert.deepEqual(seen[0].params,{client_info:{program:'Moonraker',version:'node-test'}});assert.deepEqual(seen[2].params,{});assert.deepEqual(seen[3].params,{objects:{webhooks:null},response_template:{method:'process_status_update'}});assert.deepEqual(seen[4].params,{response_template:{method:'process_gcode_response'}});assert.ok(Object.isFrozen(result.info));assert.ok(Object.isFrozen(result.endpoints));assert.equal(states[0].state,'startup');}finally{await runtime.close();}assert.equal(runtime.snapshot.connected,false);assert.equal(runtime.snapshot.state,'disconnected');
},(m,s,seen)=>{if(m.method==='info'&&seen.filter(r=>r.method==='info').length===1){s.write(wire({id:m.id,result:{state:'startup',state_message:'Loading'}}));return false;}}));
test('live shutdown wins over an older info response and cannot be overwritten by initialization',()=>peer(async(path,seen)=>{
 const runtime=new KlippyLifecycle({version:'test'});try{const snapshot=await runtime.initialize(path);assert.equal(snapshot.state,'shutdown');assert.equal(snapshot.stateMessage,'Stopped');assert.equal(snapshot.initialized,true);assert.equal(snapshot.requirementsChecked,false);assert.equal(seen.some(m=>m.method==='objects/list'),false);}finally{await runtime.close();}
},(m,s)=>{if(m.method==='info'){s.write(wire({method:'process_status_update',params:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Stopped'}}}})+wire({id:m.id,result:response(m)}));return false;}if(m.method==='objects/subscribe'){s.write(wire({id:m.id,result:{eventtime:3,status:{webhooks:{state:'shutdown',state_message:'Stopped'}}}}));return false;}}));
test('live shutdown wins over an older initial subscription response',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test'});try{assert.equal((await runtime.initialize(path)).state,'shutdown');assert.equal(runtime.snapshot.stateMessage,'Emergency');assert.equal(runtime.cachedStatus.webhooks.state,'shutdown');}finally{await runtime.close();}
},(m,s)=>{if(m.method==='objects/subscribe'){s.write(wire({method:'process_status_update',params:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Emergency'}}}})+wire({id:m.id,result:response(m)}));return false;}}));
test('missing required printer objects are reported without inventing ready capabilities',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test'});try{const state=await runtime.initialize(path);assert.equal(state.state,'ready');assert.equal(state.requirementsChecked,true);assert.deepEqual(state.missingRequirements,['virtual_sdcard','pause_resume']);}finally{await runtime.close();}
},(m,s)=>{if(m.method==='objects/list'){s.write(wire({id:m.id,result:{objects:['display_status']}}));return false;}}));
test('GCode/status callbacks are delivered and a connection loss invalidates the snapshot',()=>peer(async(path,_seen,sockets)=>{
 const output:string[]=[],statuses:number[]=[],runtime=new KlippyLifecycle({version:'test',onGcode:line=>{output.push(line);},onStatus:(_s,t)=>{statuses.push(t);}});try{await runtime.initialize(path);sockets[0].write(wire({method:'process_gcode_response',params:{response:'ok T:20'}})+wire({method:'process_status_update',params:{eventtime:9,status:{toolhead:{position:[1,2,3]}}}}));await until(()=>output.length===1&&statuses.length===1);assert.deepEqual(output,['ok T:20']);assert.deepEqual(statuses,[9]);sockets[0].destroy();await until(()=>runtime.signal.aborted);assert.equal(runtime.snapshot.connected,false);assert.equal(runtime.snapshot.initialized,false);assert.deepEqual(runtime.snapshot.endpoints,[]);}finally{await runtime.close();}
}));
test('startup timeout and malformed handshake close the transport without claiming initialization',async()=>{
 await peer(async(path)=>{const runtime=new KlippyLifecycle({version:'test',startupTimeoutMs:15,pollIntervalMs:1});await assert.rejects(runtime.initialize(path),e=>e instanceof ApiError&&e.status===504);assert.equal(runtime.snapshot.initialized,false);assert.equal(runtime.snapshot.state,'disconnected');await runtime.close();},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:{state:'startup'}}));return false;}});
 for(const malformed of [{state:'unknown'}, {state:'ready',state_message:3}])await peer(async(path)=>{const runtime=new KlippyLifecycle({version:'test'});await assert.rejects(runtime.initialize(path),/Invalid Klippy/);assert.equal(runtime.snapshot.connected,false);await runtime.close();},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:malformed}));return false;}});
});
test('observer failures cannot escape abort event dispatch or return a successful initialization',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test',onSnapshot:s=>{if(s.initialized||!s.connected)throw new Error('observer');}});await assert.rejects(runtime.initialize(path),/observer failed/);assert.equal(runtime.snapshot.connected,false);await runtime.close();
}));
test('configured server forwards discovered authorized endpoints and publishes actual lifecycle metadata',()=>peer(async(path,_seen,sockets,dir)=>{
 const config=join(dir,'moonraker.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(_m,_p,c){if(c.request.headers['x-key']!=='test')throw new ApiError(401,'Denied');}});try{const address=await server.start(),url=`http://127.0.0.1:${address.port}`,headers={'x-key':'test'};assert.equal(Boolean(server.klippy),false);await server.attachKlippy(path);assert.equal(server.klippy?.initialized,true);const info:any=await(await fetch(url+'/server/info',{headers})).json();assert.equal(info.result.klippy_connected,true);assert.equal(info.result.klippy_state,'ready');server.setInformation({connected:false,state:'error',components:['test'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:['wrong']});const preserved:any=await(await fetch(url+'/server/info',{headers})).json();assert.equal(preserved.result.klippy_state,'ready');assert.deepEqual(preserved.result.missing_klippy_requirements,[]);assert.equal((await fetch(url+'/printer/objects/query')).status,401);assert.deepEqual(await(await fetch(url+'/printer/objects/query?toolhead=position',{headers})).json(),{result:{status:{toolhead:{position:[1,2,3]}}}});assert.equal((await fetch(url+'/printer/list_endpoints',{headers})).status,404);assert.equal((await fetch(url+'/printer/objects/subscribe',{headers})).status,404);sockets[0].destroy();await until(()=>server.klippy?.connected===false);assert.equal((await fetch(url+'/printer/info',{headers})).status,404);const disconnected:any=await(await fetch(url+'/server/info',{headers})).json();assert.equal(disconnected.result.klippy_state,'disconnected');}finally{await server.close();}
}));
test('discovered endpoint collisions roll back new routes and preserve existing owners',()=>peer(async(path,_seen,_sockets,dir)=>{
 const config=join(dir,'main.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){}});server.endpoints.register({endpoint:'emergency_stop',methods:['GET','POST'],remote:true},()=> 'existing');try{await assert.rejects(server.attachKlippy(path),/observer failed/);assert.equal(server.rpc.has('printer.info'),false);assert.equal(server.rpc.has('printer.emergency_stop'),true);assert.equal(server.klippy?.connected,false);}finally{await server.close();}
},(m,s,seen)=>{if(m.method==='list_endpoints'&&seen.filter(r=>r.method==='list_endpoints').length===1){s.write(wire({id:m.id,result:{endpoints:['info']}}));return false;}}));
test('closing during startup polling cancels initialization and cannot publish ready later',()=>peer(async(path,seen)=>{
 const runtime=new KlippyLifecycle({version:'test',pollIntervalMs:1000});const opening=runtime.initialize(path),rejected=assert.rejects(opening);await until(()=>seen.some(m=>m.method==='list_endpoints'));await runtime.close();await rejected;assert.equal(runtime.snapshot.state,'disconnected');assert.equal(runtime.snapshot.initialized,false);assert.equal(runtime.transportStatus.phase,'closed');
},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:{state:'startup'}}));return false;}}));
test('live status cache merges deltas, isolates callbacks and clears when Klippy disconnects',()=>peer(async(path,_seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test',onStatus:s=>{assert.ok(Object.isFrozen(s));if(s.toolhead&&typeof s.toolhead==='object'&&'position' in s.toolhead)assert.throws(()=>{(s.toolhead as any).position?.push(9);});}});try{await runtime.initialize(path);assert.equal(runtime.cachedStatus.webhooks.state,'ready');sockets[0].write(wire({method:'process_status_update',params:{eventtime:2,status:{toolhead:{position:[1,2,3],velocity:100}}}}));await until(()=>!!runtime.cachedStatus.toolhead);assert.deepEqual(runtime.cachedStatus.toolhead.position,[1,2,3]);sockets[0].write(wire({method:'process_status_update',params:{eventtime:3,status:{toolhead:{velocity:120}}}}));await until(()=>runtime.cachedStatus.toolhead?.velocity===120);assert.deepEqual(runtime.cachedStatus.toolhead.position,[1,2,3]);sockets[0].destroy();await until(()=>runtime.signal.aborted);assert.deepEqual(JSON.parse(JSON.stringify(runtime.cachedStatus)),{});}finally{await runtime.close();}
}));
test('cache capacity failure invalidates the link and does not leave partially merged state',()=>peer(async(path,_seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test',statusCacheLimits:{fields:2}});try{await runtime.initialize(path);sockets[0].write(wire({method:'process_status_update',params:{eventtime:2,status:{toolhead:{position:[1,2,3]}}}}));await until(()=>runtime.signal.aborted);assert.equal(runtime.snapshot.connected,false);assert.equal(runtime.cacheMetrics.fields,0);assert.deepEqual(JSON.parse(JSON.stringify(runtime.cachedStatus)),{});}finally{await runtime.close();}
}));
test('lifecycle aggregates subscriber requests, preserves webhooks and filters live delivery',()=>peer(async(path,seen,sockets)=>{
 const delivered:any[]=[],runtime=new KlippyLifecycle({version:'test',onSubscriptionStatus:(client,status,eventtime)=>delivered.push({client,status,eventtime})});await assert.rejects(runtime.subscribe(1,{}),/unavailable/);await runtime.initialize(path);const first=await runtime.subscribe(1,{toolhead:['position']}),second=await runtime.subscribe(2,{toolhead:['velocity']});assert.deepEqual(first.status,{toolhead:{position:[1,2,3]}});assert.deepEqual(second.status,{toolhead:{velocity:100}});const requests=seen.filter(m=>m.method==='objects/subscribe');assert.deepEqual(requests.at(-1).params.objects,{webhooks:null,toolhead:['velocity','position']});sockets[0].write(wire({method:'process_status_update',params:{eventtime:5,status:{toolhead:{position:[2,3,4],velocity:110}}}}));await until(()=>delivered.length===2);assert.deepEqual(delivered,[{client:1,status:{toolhead:{position:[2,3,4]}},eventtime:5},{client:2,status:{toolhead:{velocity:110}},eventtime:5}]);runtime.removeSubscription(1);sockets[0].write(wire({method:'process_status_update',params:{eventtime:6,status:{toolhead:{position:[3,4,5],velocity:120}}}}));await until(()=>delivered.length===3);assert.equal(delivered[2].client,2);await runtime.close();assert.deepEqual(runtime.cachedStatus,{});
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({id:m.id,result:{eventtime:2,status:{webhooks:{state:'ready',state_message:'Printer ready'},toolhead:{position:[1,2,3],velocity:100}}}}));return false;}}));
test('subscription snapshot differences update internal webhooks state without subscribing a client to it',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test',onSubscriptionStatus(){}});await runtime.initialize(path);await runtime.subscribe(1,{toolhead:null});assert.equal(runtime.snapshot.state,'shutdown');assert.equal(runtime.snapshot.stateMessage,'Stopped');await runtime.close();
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({id:m.id,result:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Stopped'},toolhead:{position:[1,2,3]}}}}));return false;}}));
