import {WebSocket} from 'ws';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer,type Socket} from 'node:net';
import {once} from 'node:events';
import {mkdtemp,rm,writeFile,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {KlippyLifecycle,type KlippySnapshot} from '../src/moonraker/klippy-lifecycle.ts';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import {ApiError} from '../src/moonraker/rpc.ts';
const wire=(v:unknown)=>JSON.stringify(v)+'\x03';
async function until(fn:()=>boolean){for(let i=0;i<500;i++){if(fn())return;await delay(2);}throw new Error('Condition timed out');}
const endpoints=['info','emergency_stop','list_endpoints','objects/query','objects/list','objects/subscribe','gcode/subscribe_output','register_remote_method'];
function response(m:any){switch(m.method){case 'info':return {state:'ready',state_message:'Printer ready',software_version:'test'};case 'list_endpoints':return {endpoints};case 'objects/subscribe':return {eventtime:1,status:{webhooks:{state:'ready',state_message:'Printer ready'}}};case 'objects/list':return {objects:['virtual_sdcard','display_status','pause_resume']};case 'objects/query':return {status:{toolhead:{position:[1,2,3]}}};default:return {};}}
async function peer(run:(path:string,requests:any[],sockets:Socket[],dir:string)=>Promise<void>,handle:(m:any,s:Socket,requests:any[])=>boolean|void=()=>{}){const dir=await mkdtemp(join(tmpdir(),'klippy-init-test-')),path=join(dir,'api.sock'),sockets:Socket[]=[],seen:any[]=[],server=createServer(socket=>{sockets.push(socket);socket.on('error',()=>{});let tail='';socket.on('data',data=>{tail+=data.toString();for(let end;(end=tail.indexOf('\x03'))>=0;){const m=JSON.parse(tail.slice(0,end));tail=tail.slice(end+1);seen.push(m);if(handle(m,socket,seen)!==false)socket.write(wire({id:m.id,result:response(m)}));}});});server.listen(path);await once(server,'listening');try{await run(path,seen,sockets,dir);}finally{for(const socket of sockets)socket.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}}
test('initialization follows identification, startup polling, discovery, subscriptions and requirement checks',()=>peer(async(path,seen)=>{
 const states:KlippySnapshot[]=[],runtime=new KlippyLifecycle({version:'node-test',pollIntervalMs:1,onSnapshot:s=>states.push(s)});try{const opening=runtime.initialize(path);assert.equal(runtime.initialize(path),opening);const result=await opening;assert.equal(result.connected,true);assert.equal(result.initialized,true);assert.equal(result.state,'ready');assert.equal(result.requirementsChecked,true);assert.deepEqual(result.missingRequirements,[]);assert.deepEqual(seen.map(m=>m.method),['info','list_endpoints','info','objects/subscribe','gcode/subscribe_output','list_endpoints','objects/list']);assert.deepEqual(seen[0].params,{client_info:{program:'Moonraker',version:'node-test'}});assert.deepEqual(seen[2].params,{});assert.deepEqual(seen[3].params,{objects:{webhooks:null},response_template:{method:'process_status_update'}});assert.deepEqual(seen[4].params,{response_template:{method:'process_gcode_response'}});assert.ok(Object.isFrozen(result.info));assert.ok(Object.isFrozen(result.endpoints));assert.equal(states[0].state,'startup');}finally{await runtime.close();}assert.equal(runtime.snapshot.connected,false);assert.equal(runtime.snapshot.state,'disconnected');
},(m,s,seen)=>{if(m.method==='info'&&seen.filter(r=>r.method==='info').length===1){s.write(wire({id:m.id,result:{state:'startup',state_message:'Loading'}}));return false;}}));
test('live shutdown wins over an older info response and cannot be overwritten by initialization',()=>peer(async(path,seen)=>{
 const runtime=new KlippyLifecycle({version:'test'});try{const snapshot=await runtime.initialize(path);assert.equal(snapshot.state,'shutdown');assert.equal(snapshot.stateMessage,'Stopped');assert.equal(snapshot.initialized,true);assert.equal(snapshot.requirementsChecked,false);assert.equal(seen.some(m=>m.method==='objects/list'),false);}finally{await runtime.close();}
},(m,s)=>{if(m.method==='info'){s.write(wire({method:'process_status_update',params:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Stopped'}}}})+wire({id:m.id,result:response(m)}));return false;}if(m.method==='objects/subscribe'){s.write(wire({id:m.id,result:{eventtime:3,status:{webhooks:{state:'shutdown',state_message:'Stopped'}}}}));return false;}}));
test('live shutdown wins over an older initial subscription response',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test'});try{assert.equal((await runtime.initialize(path)).state,'shutdown');assert.equal(runtime.snapshot.stateMessage,'Emergency');assert.equal(runtime.cachedStatus.webhooks.state,'shutdown');}finally{await runtime.close();}
},(m,s)=>{if(m.method==='objects/subscribe'){s.write(wire({method:'process_status_update',params:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Emergency'}}}})+wire({id:m.id,result:response(m)}));return false;}}));
test('missing required printer objects are reported without inventing ready capabilities',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test'});try{const state=await runtime.initialize(path);assert.equal(state.state,'ready');assert.equal(state.requirementsChecked,true);assert.deepEqual(state.missingRequirements,['virtual_sdcard','pause_resume']);}finally{await runtime.close();}
},(m,s)=>{if(m.method==='objects/list'){s.write(wire({id:m.id,result:{objects:['display_status']}}));return false;}}));
test('GCode/status callbacks are delivered and a connection loss invalidates the snapshot',()=>peer(async(path,_seen,sockets)=>{
 const output:string[]=[],statuses:number[]=[],runtime=new KlippyLifecycle({version:'test',onGcode:line=>{output.push(line);},onStatus:(_s,t)=>{statuses.push(t);}});try{await runtime.initialize(path);sockets[0].write(wire({method:'process_gcode_response',params:{response:'ok T:20'}})+wire({method:'process_status_update',params:{eventtime:9,status:{toolhead:{position:[1,2,3]}}}}));await until(()=>output.length===1&&statuses.length===1);assert.deepEqual(output,['ok T:20']);assert.deepEqual(statuses,[9]);sockets[0].destroy();await until(()=>runtime.signal.aborted);assert.equal(runtime.snapshot.connected,false);assert.equal(runtime.snapshot.initialized,false);assert.deepEqual(runtime.snapshot.endpoints,[]);}finally{await runtime.close();}
}));
test('startup timeout and malformed handshake close the transport without claiming initialization',async()=>{
 await peer(async(path)=>{const runtime=new KlippyLifecycle({version:'test',startupTimeoutMs:15,pollIntervalMs:1});await assert.rejects(runtime.initialize(path),e=>e instanceof ApiError&&e.status===504);assert.equal(runtime.snapshot.initialized,false);assert.equal(runtime.snapshot.state,'disconnected');await runtime.close();},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:{state:'startup'}}));return false;}});
 for(const malformed of [{state:'unknown'}, {state:'ready',state_message:3}])await peer(async(path)=>{const runtime=new KlippyLifecycle({version:'test'});await assert.rejects(runtime.initialize(path),/Invalid Klippy/);assert.equal(runtime.snapshot.connected,false);await runtime.close();},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:malformed}));return false;}});
});
test('observer failures cannot escape abort event dispatch or return a successful initialization',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test',onSnapshot:s=>{if(s.initialized||!s.connected)throw new Error('observer');}});await assert.rejects(runtime.initialize(path),/observer failed/);assert.equal(runtime.snapshot.connected,false);await runtime.close();
}));
test('configured server forwards discovered authorized endpoints and publishes actual lifecycle metadata',()=>peer(async(path,_seen,sockets,dir)=>{
 const config=join(dir,'moonraker.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(_m,_p,c){if(c.request.headers['x-key']!=='test')throw new ApiError(401,'Denied');}});try{const address=await server.start(),url=`http://127.0.0.1:${address.port}`,headers={'x-key':'test'};assert.equal(Boolean(server.klippy),false);await server.attachKlippy(path);assert.equal(server.klippy?.initialized,true);const info:any=await(await fetch(url+'/server/info',{headers})).json();assert.equal(info.result.klippy_connected,true);assert.equal(info.result.klippy_state,'ready');server.setInformation({connected:false,state:'error',components:['test'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:['wrong']});const preserved:any=await(await fetch(url+'/server/info',{headers})).json();assert.equal(preserved.result.klippy_state,'ready');assert.deepEqual(preserved.result.missing_klippy_requirements,[]);assert.equal((await fetch(url+'/printer/objects/query')).status,401);assert.deepEqual(await(await fetch(url+'/printer/objects/query?toolhead=position',{headers})).json(),{result:{status:{toolhead:{position:[1,2,3]}}}});assert.equal((await fetch(url+'/printer/list_endpoints',{headers})).status,404);assert.equal((await fetch(url+'/printer/objects/subscribe',{headers})).status,503);sockets[0].destroy();await until(()=>server.klippy?.connected===false);assert.equal((await fetch(url+'/printer/info',{headers})).status,404);const disconnected:any=await(await fetch(url+'/server/info',{headers})).json();assert.equal(disconnected.result.klippy_state,'disconnected');}finally{await server.close();}
}));
test('discovered endpoint collisions roll back new routes and preserve existing owners',()=>peer(async(path,_seen,_sockets,dir)=>{
 const config=join(dir,'main.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){}});server.endpoints.register({endpoint:'emergency_stop',methods:['GET','POST'],remote:true},()=> 'existing');try{await assert.rejects(server.attachKlippy(path),/observer failed/);assert.equal(server.rpc.has('printer.info'),false);assert.equal(server.rpc.has('printer.emergency_stop'),true);assert.equal(server.klippy?.connected,false);}finally{await server.close();}
},(m,s,seen)=>{if(m.method==='list_endpoints'&&seen.filter(r=>r.method==='list_endpoints').length===1){s.write(wire({id:m.id,result:{endpoints:['info']}}));return false;}}));
test('closing during startup polling cancels initialization and cannot publish ready later',()=>peer(async(path,seen)=>{
 const runtime=new KlippyLifecycle({version:'test',pollIntervalMs:1000});const opening=runtime.initialize(path),rejected=assert.rejects(opening);await until(()=>seen.some(m=>m.method==='list_endpoints'));await runtime.close();await rejected;assert.equal(runtime.snapshot.state,'disconnected');assert.equal(runtime.snapshot.initialized,false);assert.equal(runtime.transportStatus.phase,'closed');
},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:{state:'startup'}}));return false;}}));
test('live status cache merges deltas, isolates callbacks and clears when Klippy disconnects',()=>peer(async(path,_seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test',onStatus:s=>{assert.ok(Object.isFrozen(s));if(s.toolhead&&typeof s.toolhead==='object'&&'position' in s.toolhead)assert.throws(()=>{(s.toolhead as any).position?.push(9);});}});try{await runtime.initialize(path);assert.equal(runtime.cachedStatus.webhooks.state,'ready');sockets[0].write(wire({method:'process_status_update',params:{eventtime:2,status:{toolhead:{position:[1,2,3],velocity:100}}}}));await until(()=>!!runtime.cachedStatus.toolhead);assert.deepEqual(runtime.cachedStatus.toolhead.position,[1,2,3]);sockets[0].write(wire({method:'process_status_update',params:{eventtime:3,status:{toolhead:{velocity:120}}}}));await until(()=>runtime.cachedStatus.toolhead?.velocity===120);assert.deepEqual(runtime.cachedStatus.toolhead.position,[1,2,3]);sockets[0].destroy();await until(()=>runtime.signal.aborted);assert.deepEqual(JSON.parse(JSON.stringify(runtime.cachedStatus)),{});}finally{await runtime.close();}
}));
test('cache capacity failure invalidates the link and does not leave partially merged state',()=>peer(async(path,_seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test',statusCacheLimits:{fields:2}});try{await runtime.initialize(path);sockets[0].write(wire({method:'process_status_update',params:{eventtime:2,status:{toolhead:{position:[1,2,3]}}}}));await until(()=>runtime.signal.aborted);assert.equal(runtime.snapshot.connected,false);assert.equal(runtime.cacheMetrics.fields,0);assert.deepEqual(JSON.parse(JSON.stringify(runtime.cachedStatus)),{});}finally{await runtime.close();}
}));
test('lifecycle aggregates subscriber requests, preserves webhooks and filters live delivery',()=>peer(async(path,seen,sockets)=>{
 const delivered:any[]=[],runtime=new KlippyLifecycle({version:'test',onSubscriptionStatus:(client,status,eventtime)=>delivered.push({client,status,eventtime})});await assert.rejects(runtime.subscribe(1,{}),/unavailable/);await runtime.initialize(path);const first=await runtime.subscribe(1,{toolhead:['position']}),second=await runtime.subscribe(2,{toolhead:['velocity']});assert.deepEqual(first.status,{toolhead:{position:[1,2,3]}});assert.deepEqual(second.status,{toolhead:{velocity:100}});const requests=seen.filter(m=>m.method==='objects/subscribe');assert.deepEqual(requests.at(-1).params.objects,{webhooks:null,toolhead:['velocity','position']});sockets[0].write(wire({method:'process_status_update',params:{eventtime:5,status:{toolhead:{position:[2,3,4],velocity:110}}}}));await until(()=>delivered.length===2);assert.deepEqual(delivered,[{client:1,status:{toolhead:{position:[2,3,4]}},eventtime:5},{client:2,status:{toolhead:{velocity:110}},eventtime:5}]);runtime.removeSubscription(1);sockets[0].write(wire({method:'process_status_update',params:{eventtime:6,status:{toolhead:{position:[3,4,5],velocity:120}}}}));await until(()=>delivered.length===3);assert.equal(delivered[2].client,2);await runtime.close();assert.deepEqual(runtime.cachedStatus,{});
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({id:m.id,result:{eventtime:2,status:{webhooks:{state:'ready',state_message:'Printer ready'},toolhead:{position:[1,2,3],velocity:100}}}}));return false;}}));
test('subscription snapshot differences update internal webhooks state without subscribing a client to it',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test',onSubscriptionStatus(){}});await runtime.initialize(path);await runtime.subscribe(1,{toolhead:null});assert.equal(runtime.snapshot.state,'shutdown');assert.equal(runtime.snapshot.stateMessage,'Stopped');await runtime.close();
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({id:m.id,result:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Stopped'},toolhead:{position:[1,2,3]}}}}));return false;}}));
test('a live Unix status delta preceding a late subscription reply is retained for the new client',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test',onSubscriptionStatus(){}});await runtime.initialize(path);const response=await runtime.subscribe(1,{toolhead:['position','velocity']});assert.deepEqual(response,{status:{toolhead:{position:[9,8,7],velocity:100}},eventtime:12});assert.deepEqual(runtime.cachedStatus.toolhead.position,[9,8,7]);await runtime.close();
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({method:'process_status_update',params:{eventtime:12,status:{toolhead:{position:[9,8,7]}}}})+wire({id:m.id,result:{eventtime:10,status:{webhooks:{state:'ready'},toolhead:{position:[1,2,3],velocity:100}}}}));return false;}}));
test('configured WebSocket subscriptions authorize each request and deliver filtered updates after replies',()=>peer(async(path,seen,klippySockets,dir)=>{
 const file=join(dir,'subscribe.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(_m,_p,c){if(c.request.headers['x-key']!=='yes')throw new ApiError(401,'Denied');},authorizeNotification(_m,_p,c){if(c.request.headers['x-key']!=='yes')throw new ApiError(401,'Denied');}}),sockets:WebSocket[]=[];try{const address=await server.start();await server.attachKlippy(path);const url=`ws://127.0.0.1:${address.port}/websocket`,first=new WebSocket(url,{headers:{'x-key':'yes'}}),second=new WebSocket(url,{headers:{'x-key':'yes'}}),denied=new WebSocket(url);sockets.push(first,second,denied);await Promise.all(sockets.map(s=>once(s,'open')));const received:any[][]=[[],[],[]];sockets.forEach((s,i)=>s.on('message',m=>received[i].push(JSON.parse(String(m)))));const call=(s:WebSocket,id:number,objects:any)=>s.send(JSON.stringify({jsonrpc:'2.0',method:'printer.objects.subscribe',id,params:{objects}}));call(first,1,{toolhead:['position']});await until(()=>received[0].length===1);assert.deepEqual(received[0][0].result.status,{toolhead:{position:[1,2,3]}});call(second,2,{toolhead:['velocity']});await until(()=>received[1].length===1);assert.deepEqual(received[1][0].result.status,{toolhead:{velocity:100}});const before=seen.filter(m=>m.method==='objects/subscribe').length;call(denied,3,{toolhead:null});await until(()=>received[2].length===1);assert.equal(received[2][0].error.code,-32602);assert.equal(seen.filter(m=>m.method==='objects/subscribe').length,before);klippySockets[0].write(wire({method:'process_status_update',params:{eventtime:5,status:{toolhead:{position:[4,5,6],velocity:120}}}}));await until(()=>received[0].length===2&&received[1].length===2);assert.deepEqual(received[0][1].params,[{toolhead:{position:[4,5,6]}},5]);assert.deepEqual(received[1][1].params,[{toolhead:{velocity:120}},5]);first.terminate();await until(()=>server.clients.length===2);call(second,4,{toolhead:['velocity']});await until(()=>received[1].some(m=>m.id===4));assert.deepEqual(seen.filter(m=>m.method==='objects/subscribe').at(-1).params.objects,{webhooks:null,toolhead:['velocity']});assert.equal((await fetch(`http://127.0.0.1:${address.port}/printer/objects/subscribe`)).status,401);}finally{for(const socket of sockets)socket.terminate();await server.close();}
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({id:m.id,result:{status:{webhooks:{state:'ready',state_message:'Printer ready'},toolhead:{position:[1,2,3],velocity:100}},eventtime:2}}));return false;}}));
test('HTTP object subscription binds query/form IDs only after source-to-target authorization',()=>peer(async(path,seen,klippySockets,dir)=>{
 const file=join(dir,'http-subscribe.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');let checks=0;const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeNotification(){},authorizeSubscriptionConnection(source,target){checks++;if(source.request.headers['x-owner']!==target.request.headers['x-owner'])throw new ApiError(403,'Wrong owner');}}),sockets:WebSocket[]=[];try{const address=await server.start();await server.attachKlippy(path);const base=`http://127.0.0.1:${address.port}`,ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`,{headers:{'x-owner':'alice'}});sockets.push(ws);await once(ws,'open');const id=server.clients[0].id,received:any[]=[];ws.on('message',m=>received.push(JSON.parse(String(m))));const before=seen.filter(m=>m.method==='objects/subscribe').length;assert.equal((await fetch(base+`/printer/objects/subscribe?connection_id=${id}&toolhead=position`,{headers:{'x-owner':'bob'}})).status,403);assert.equal(seen.filter(m=>m.method==='objects/subscribe').length,before);const response=await(await fetch(base+`/printer/objects/subscribe?connection_id=${id}&toolhead=position`,{headers:{'x-owner':'alice'}})).json();assert.deepEqual(response.result.status,{toolhead:{position:[1,2,3]}});klippySockets[0].write(wire({method:'process_status_update',params:{eventtime:5,status:{toolhead:{position:[4,5,6],velocity:120}}}}));await until(()=>received.length===1);assert.deepEqual(received[0].params,[{toolhead:{position:[4,5,6]}},5]);const form=await(await fetch(base+'/printer/objects/subscribe',{method:'POST',headers:{'x-owner':'alice','content-type':'application/x-www-form-urlencoded'},body:`connection_id=${id}&toolhead=velocity`})).json();assert.deepEqual(form.result.status,{toolhead:{velocity:100}});const rpc=await(await fetch(base+`/server/jsonrpc?connection_id=${id}`,{method:'POST',headers:{'x-owner':'alice','content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'printer.objects.subscribe',params:{objects:{}},id:9})})).json();assert.deepEqual(rpc.result.status,{});assert.equal(checks,4);assert.equal((await fetch(base+'/printer/objects/subscribe',{method:'POST',headers:{'x-owner':'alice','content-type':'application/json'},body:JSON.stringify({connection_id:id,objects:{}})})).status,400);ws.terminate();await until(()=>server.clients.length===0);assert.equal((await fetch(base+`/printer/objects/subscribe?connection_id=${id}`,{headers:{'x-owner':'alice'}})).status,404);}finally{for(const s of sockets)s.terminate();await server.close();}
},(m,s,seen)=>{if(m.method==='objects/subscribe'&&seen.filter(r=>r.method==='objects/subscribe').length>1){s.write(wire({id:m.id,result:{status:{webhooks:{state:'ready'},toolhead:{position:[1,2,3],velocity:100}},eventtime:seen.filter(r=>r.method==='objects/subscribe').length*2}}));return false;}}));
test('G-code output broadcasts exact text only to authorized clients and preserves local callbacks',()=>peer(async(path,_seen,klippySockets,dir)=>{
 const file=join(dir,'gcode.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const local:string[]=[],server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeNotification(method,_p,c){assert.equal(method,'notify_gcode_response');if(c.request.headers['x-output']!=='yes')throw new ApiError(403,'Denied');}}),sockets:WebSocket[]=[];try{const address=await server.start();await server.attachKlippy(path,{onGcode:response=>{local.push(response);}});for(const allowed of [true,false]){const ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`,{headers:{'x-output':allowed?'yes':'no'}});sockets.push(ws);await once(ws,'open');}const received:any[][]=[[],[]];sockets.forEach((ws,i)=>ws.on('message',m=>received[i].push(JSON.parse(String(m)))));for(const response of ['温度: 200.125\n// ready',''])klippySockets[0].write(wire({method:'process_gcode_response',params:{response}}));await until(()=>received[0].length===2);assert.deepEqual(received[0].map(v=>v.params),[['温度: 200.125\n// ready'],['']]);assert.deepEqual(received[1],[]);assert.deepEqual(local,['温度: 200.125\n// ready','']);assert.deepEqual(server.gcodeNotifications,{received:2,disabled:0,rejected:0,sent:2,denied:2,closed:0,overflow:0,failed:0});}finally{for(const ws of sockets)ws.terminate();await server.close();}
}));
test('slow G-code notification authorization cannot block Klippy status updates and overflow isolates client',()=>peer(async(path,_seen,klippySockets,dir)=>{
 const file=join(dir,'slow-gcode.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');let release!:()=>void;const gate=new Promise<void>(r=>release=r),server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeNotification:()=>gate,notificationLimits:{perClient:1}});let ws:WebSocket|undefined;try{const address=await server.start();await server.attachKlippy(path);ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const closed=once(ws,'close');for(const response of ['first','second'])klippySockets[0].write(wire({method:'process_gcode_response',params:{response}}));klippySockets[0].write(wire({method:'process_status_update',params:{eventtime:9,status:{toolhead:{position:[9,8,7]}}}}));await until(()=>server.cachedKlippyStatus?.toolhead?.position!==undefined);await closed;assert.equal(server.klippy?.connected,true);assert.equal(server.gcodeNotifications.received,2);assert.equal(server.gcodeNotifications.overflow,1);assert.equal(server.status.notifications?.pending,1);release();await until(()=>server.status.notifications?.pending===0);assert.equal(server.gcodeNotifications.closed,1);}finally{release?.();ws?.terminate();await server.close();}
}));
test('oversized G-code output is observable without closing Klippy',()=>peer(async(path,_seen,klippySockets,dir)=>{
 const file=join(dir,'large-gcode.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');let calls=0;const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeNotification(){}});try{await server.start();await server.attachKlippy(path,{onGcode(){calls++;}});klippySockets[0].write(wire({method:'process_gcode_response',params:{response:'x'.repeat(1024*1024)}}));await until(()=>server.gcodeNotifications.rejected===1);assert.equal(server.klippy?.connected,true);assert.equal(calls,1);}finally{await server.close();}
}));
test('G-code network delivery remains disabled without policy while local output still works',()=>peer(async(path,_seen,klippySockets,dir)=>{
 const file=join(dir,'disabled-gcode.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const local:string[]=[],server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){}});let ws:WebSocket|undefined;try{const address=await server.start();await server.attachKlippy(path,{onGcode:response=>{local.push(response);}});ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const messages:any[]=[];ws.on('message',m=>messages.push(m));klippySockets[0].write(wire({method:'process_gcode_response',params:{response:'ok'}}));await until(()=>local.length===1);assert.equal(server.gcodeNotifications.disabled,1);assert.equal(server.gcodeNotifications.sent,0);assert.deepEqual(messages,[]);assert.equal(server.klippy?.connected,true);}finally{ws?.terminate();await server.close();}
}));
test('configured lifecycle notifications follow published state, authorize recipients and deduplicate shutdown',()=>peer(async(path,_seen,klippySockets,dir)=>{
 const file=join(dir,'lifecycle-events.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeNotification(method,_p,c){if(c.request.headers['x-events']!=='yes')throw new ApiError(403,'Denied');if(method==='notify_klippy_ready')assert.equal(server.klippy?.initialized,true);if(method==='notify_klippy_shutdown')assert.equal(server.klippy?.state,'shutdown');if(method==='notify_klippy_disconnected'){assert.equal(server.klippy?.connected,false);assert.equal(server.rpc.has('printer.info'),false);}}}),sockets:WebSocket[]=[];try{const address=await server.start(),received:any[][]=[[],[]];for(const allowed of [true,false]){const ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`,{headers:{'x-events':allowed?'yes':'no'}});sockets.push(ws);await once(ws,'open');ws.on('message',m=>received[allowed?0:1].push(JSON.parse(String(m))));}await server.attachKlippy(path);await until(()=>received[0].length===1);assert.deepEqual(received[0][0],{jsonrpc:'2.0',method:'notify_klippy_ready'});for(const state_message of ['Stopped','Stopped again'])klippySockets[0].write(wire({method:'process_status_update',params:{eventtime:5,status:{webhooks:{state:'shutdown',state_message}}}}));await until(()=>server.klippy?.stateMessage==='Stopped again'&&received[0].length===2);assert.equal(received[0][1].method,'notify_klippy_shutdown');klippySockets[0].destroy();await until(()=>received[0].length===3);assert.equal(received[0][2].method,'notify_klippy_disconnected');assert.deepEqual(received[1],[]);assert.equal(server.klippyNotifications.received,3);assert.equal(server.klippyNotifications.sent,3);assert.equal(server.klippyNotifications.denied,3);}finally{for(const ws of sockets)ws.terminate();await server.close();}
}));
test('initial shutdown does not announce ready or a post-start shutdown transition',()=>peer(async(path,_seen,klippySockets,dir)=>{
 const file=join(dir,'initial-shutdown.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeNotification(){}});let ws:WebSocket|undefined;try{const address=await server.start();ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const received:any[]=[];ws.on('message',m=>received.push(JSON.parse(String(m))));await server.attachKlippy(path);assert.equal(server.klippy?.state,'shutdown');assert.equal(server.klippyNotifications.received,0);klippySockets[0].destroy();await until(()=>received.length===1);assert.equal(received[0].method,'notify_klippy_disconnected');}finally{ws?.terminate();await server.close();}
},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:{state:'shutdown',state_message:'Stopped'}}));return false;}if(m.method==='objects/subscribe'){s.write(wire({id:m.id,result:{eventtime:1,status:{webhooks:{state:'shutdown'}}}}));return false;}}));
test('component remote methods register after requirements, receive precise callbacks and release ownership',()=>peer(async(path,seen,sockets)=>{
 const calls:any[]=[],runtime=new KlippyLifecycle({version:'test',remoteMethods:{'component.report':params=>{calls.push(params);}}});const release=runtime.registerRemoteMethod('temporary',()=>{calls.push('temporary');});release();await runtime.initialize(path);const requests=seen.filter(m=>m.method==='register_remote_method');assert.equal(requests.length,1);assert.deepEqual(requests[0].params,{response_template:{method:'component.report'},remote_method:'component.report'});assert.ok(seen.findIndex(m=>m.method==='objects/list')<seen.findIndex(m=>m.method==='register_remote_method'));assert.deepEqual(runtime.remoteMethods,{configured:['component.report'],registered:['component.report']});sockets[0].write('{"method":"component.report","params":{"coordinate":-0,"large":1e20,"exact":"9007199254740993"}}\x03');await until(()=>calls.length===1);assert.ok(Object.is(calls[0].coordinate,-0));assert.equal(calls[0].large,1e20);assert.equal(calls[0].exact,'9007199254740993');assert.throws(()=>runtime.registerRemoteMethod('late',()=>{}),/before initialization/);await runtime.close();assert.deepEqual(runtime.remoteMethods.registered,[]);
}));
test('remote method release is idempotent and cannot remove a later owner with the same function',async()=>{const runtime=new KlippyLifecycle({version:'test'}),fn=()=>{},old=runtime.registerRemoteMethod('same',fn);old();const current=runtime.registerRemoteMethod('same',fn);old();assert.deepEqual(runtime.remoteMethods.configured,['same']);assert.throws(()=>runtime.registerRemoteMethod('same',fn),/duplicate/);for(const name of ['', '__mr_private', 'process_status_update','process_gcode_response','bad\0name','x'.repeat(257)])assert.throws(()=>runtime.registerRemoteMethod(name,fn));current();for(let i=0;i<256;i++)runtime.registerRemoteMethod('method'+i,fn);assert.throws(()=>runtime.registerRemoteMethod('overflow',fn),/capacity/);await runtime.close();assert.throws(()=>runtime.registerRemoteMethod('closed',fn));});
test('failed remote registration cannot publish initialized ready and stops the connection',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test',remoteMethods:{method(){}}});await assert.rejects(runtime.initialize(path),/Registration denied/);assert.equal(runtime.snapshot.initialized,false);assert.equal(runtime.snapshot.connected,false);assert.deepEqual(runtime.remoteMethods.registered,[]);await runtime.close();
},(m,s)=>{if(m.method==='register_remote_method'){s.write(wire({id:m.id,error:{message:'Registration denied'}}));return false;}}));
test('shutdown initialization never advertises configured component callbacks to Klippy',()=>peer(async(path,seen)=>{
 const runtime=new KlippyLifecycle({version:'test',remoteMethods:{method(){}}});await runtime.initialize(path);assert.equal(runtime.snapshot.state,'shutdown');assert.equal(seen.some(m=>m.method==='register_remote_method'),false);assert.deepEqual(runtime.remoteMethods.registered,[]);await runtime.close();
},(m,s)=>{if(m.method==='info'){s.write(wire({id:m.id,result:{state:'shutdown'}}));return false;}if(m.method==='objects/subscribe'){s.write(wire({id:m.id,result:{status:{webhooks:{state:'shutdown'}},eventtime:1}}));return false;}}));
test('release while peer registration is in flight cannot resurrect its local callback',()=>peer(async(path,seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test'});let calls=0;const release=runtime.registerRemoteMethod('cancelled',()=>{calls++;}),opening=runtime.initialize(path);await until(()=>seen.some(m=>m.method==='register_remote_method'));assert.equal(runtime.snapshot.initialized,false);release();const request=seen.find(m=>m.method==='register_remote_method');sockets[0].write(wire({id:request.id,result:'ok'})+wire({method:'cancelled',params:{value:1}}));await opening;assert.deepEqual(runtime.remoteMethods,{configured:[],registered:[]});assert.equal(calls,0);await runtime.close();
},m=>m.method==='register_remote_method'?false:undefined));
test('live remote methods use unique wire generations and owner disconnect cannot affect replacements',()=>peer(async(path,seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test'}),owner=new AbortController(),calls:string[]=[];await assert.rejects(runtime.registerLiveRemoteMethod('agent.task',()=>{},owner.signal),/unavailable/);await runtime.initialize(path);const old=await runtime.registerLiveRemoteMethod('agent.task',()=>{calls.push('old');},owner.signal),first=seen.at(-1).params.response_template.method;assert.notEqual(first,'agent.task');owner.abort();const release=await runtime.registerLiveRemoteMethod('agent.task',()=>{calls.push('new');},new AbortController().signal),second=seen.at(-1).params.response_template.method;assert.notEqual(first,second);old();sockets[0].write(wire({method:first,params:{}})+wire({method:second,params:{}}));await until(()=>calls.length===1);assert.deepEqual(calls,['new']);assert.deepEqual(runtime.remoteMethods.registered,['agent.task']);release();assert.deepEqual(runtime.remoteMethods.registered,[]);await runtime.close();
}));
test('live registration caller cancellation removes callback before late peer confirmation',()=>peer(async(path,seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test'}),owner=new AbortController(),request=new AbortController();let calls=0;await runtime.initialize(path);const pending=runtime.registerLiveRemoteMethod('agent.task',()=>{calls++;},owner.signal,{signal:request.signal}),rejected=assert.rejects(pending);await until(()=>seen.some(m=>m.method==='register_remote_method'));const registration=seen.at(-1);request.abort();assert.deepEqual(runtime.remoteMethods.configured,[]);sockets[0].write(wire({id:registration.id,result:'ok'})+wire({method:registration.params.response_template.method,params:{}}));await rejected;await runtime.request('info');assert.equal(calls,0);assert.equal(runtime.snapshot.connected,true);await runtime.close();
},m=>m.method==='register_remote_method'?false:undefined));
test('release aborts active remote callback cooperatively without faulting Klippy',()=>peer(async(path,seen,sockets)=>{
 const runtime=new KlippyLifecycle({version:'test'});let entered=false,cancelled=false;await runtime.initialize(path);const release=await runtime.registerLiveRemoteMethod('agent.wait',(_params,signal)=>new Promise<void>((_resolve,reject)=>{entered=true;signal.addEventListener('abort',()=>{cancelled=true;reject(signal.reason);},{once:true});}),new AbortController().signal),method=seen.at(-1).params.response_template.method;sockets[0].write(wire({method,params:{}}));await until(()=>entered);release();await until(()=>cancelled&&runtime.transportStatus.callbacks===0);assert.equal(runtime.snapshot.connected,true);await runtime.close();
}));
test('failed live remote registration releases its name and preserves the initialized connection',()=>peer(async(path)=>{
 const runtime=new KlippyLifecycle({version:'test'});await runtime.initialize(path);await assert.rejects(runtime.registerLiveRemoteMethod('agent.denied',()=>{},new AbortController().signal),/Denied/);assert.deepEqual(runtime.remoteMethods,{configured:[],registered:[]});assert.equal(runtime.snapshot.initialized,true);assert.equal(runtime.snapshot.connected,true);await runtime.close();
},(m,s)=>{if(m.method==='register_remote_method'){s.write(wire({id:m.id,error:{message:'Denied'}}));return false;}}));
test('public agent registration enforces inbound policy and identity, delivers callbacks and isolates replacement owners',()=>peer(async(path,seen,sockets,dir)=>{
 const config=join(dir,'agents.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(method,_p,c){if(method==='server.connection.register_remote_method'&&c.request.headers['x-allowed']!=='yes')throw new ApiError(403,'Denied');},authorizeClientCall(){}}),clients:WebSocket[]=[];
 try{const address=await server.start();await server.attachKlippy(path);
 async function connect(allowed=true){const ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`,{headers:{'x-allowed':allowed?'yes':'no'}}),messages:any[]=[];clients.push(ws);await once(ws,'open');ws.on('message',m=>messages.push(JSON.parse(String(m))));let next=1;return {ws,messages,async rpc(method:string,params:Record<string,any>={}){const id=next++;ws.send(JSON.stringify({jsonrpc:'2.0',method,params,id}));await until(()=>messages.some(m=>m.id===id));return messages.find(m=>m.id===id);}};}
 const old=await connect(),denied=await connect(false);assert.ok((await denied.rpc('server.connection.register_remote_method',{method_name:'forbidden'})).error);assert.ok((await old.rpc('server.connection.register_remote_method',{method_name:'anonymous'})).error);assert.equal(seen.filter(m=>m.method==='register_remote_method').length,0);
 const identify={client_name:'worker',version:'1',type:'agent',url:''};await old.rpc('server.connection.identify',identify);assert.equal((await old.rpc('server.connection.register_remote_method',{method_name:'agent.report'})).result,'ok');const first=seen.at(-1).params.response_template.method;assert.ok((await old.rpc('server.connection.register_remote_method',{method_name:'agent.report'})).error);
 sockets[0].write(wire({method:first,params:{position:[1.25,2,3],exact:'9007199254740993'}}));await until(()=>old.messages.some(m=>m.method==='agent.report'));assert.deepEqual(old.messages.find(m=>m.method==='agent.report'),{jsonrpc:'2.0',method:'agent.report',params:{position:[1.25,2,3],exact:'9007199254740993'}});
 old.ws.terminate();await until(()=>server.klippyRemoteMethods?.configured.length===0);const replacement=await connect();await replacement.rpc('server.connection.identify',identify);assert.equal((await replacement.rpc('server.connection.register_remote_method',{method_name:'agent.report'})).result,'ok');const second=seen.at(-1).params.response_template.method;assert.notEqual(first,second);
 sockets[0].write(wire({method:first,params:{old:true}})+wire({method:second,params:{current:true}}));await until(()=>replacement.messages.some(m=>m.method==='agent.report'));assert.deepEqual(replacement.messages.filter(m=>m.method==='agent.report'),[{jsonrpc:'2.0',method:'agent.report',params:{current:true}}]);assert.equal(server.agentMethodDeliveries.sent,2);
 }finally{for(const ws of clients)ws.terminate();await server.close();}
}));
test('slow outbound agent authorization cannot block Klippy and generation loss cancels queued callbacks',()=>peer(async(path,seen,sockets,dir)=>{
 const config=join(dir,'slow-agent.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');let release!:()=>void,authorizationSignal:AbortSignal|undefined;const gate=new Promise<void>(r=>release=r),server=await ConfiguredMoonraker.load(config,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeClientCall(_m,_p,c){authorizationSignal=c.signal;return gate;}});let ws:WebSocket|undefined;
 try{const address=await server.start();await server.attachKlippy(path);ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const messages:any[]=[];ws.on('message',m=>messages.push(JSON.parse(String(m))));ws.send(JSON.stringify({jsonrpc:'2.0',method:'server.connection.identify',params:{client_name:'slow',version:'1',type:'agent',url:''},id:1}));await until(()=>messages.some(m=>m.id===1));ws.send(JSON.stringify({jsonrpc:'2.0',method:'server.connection.register_remote_method',params:{method_name:'agent.wait'},id:2}));await until(()=>messages.some(m=>m.id===2));assert.equal(messages.find(m=>m.id===2).result,'ok');const method=seen.at(-1).params.response_template.method;
 sockets[0].write(wire({method,params:{i:1}})+wire({method,params:{i:2}})+wire({method:'process_status_update',params:{eventtime:2,status:{webhooks:{state:'shutdown',state_message:'Independent status'}}}}));await until(()=>server.klippy?.stateMessage==='Independent status'&&server.status.clientCalls?.pending===2);assert.equal(authorizationSignal?.aborted,false);
 sockets[0].destroy();await until(()=>authorizationSignal?.aborted===true);assert.equal(server.status.clientCalls?.pending,1);release();await until(()=>server.status.clientCalls?.pending===0);assert.equal(messages.filter(m=>m.method==='agent.wait').length,0);assert.equal(server.agentMethodDeliveries.closed,2);
 }finally{release();ws?.terminate();await server.close();}
}));
test('pre-start agent registrations publish before ready and disconnected pending owners are removed',()=>peer(async(path,seen,sockets,dir)=>{
 const file=join(dir,'pending-agents.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeClientCall(){},authorizeNotification(){}}),clients:WebSocket[]=[];
 try{const address=await server.start();async function agent(name:string){const ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`),messages:any[]=[];clients.push(ws);await once(ws,'open');ws.on('message',m=>messages.push(JSON.parse(String(m))));ws.send(JSON.stringify({jsonrpc:'2.0',id:1,method:'server.connection.identify',params:{client_name:name,type:'agent',version:'1',url:''}}));await until(()=>messages.some(m=>m.id===1));ws.send(JSON.stringify({jsonrpc:'2.0',id:2,method:'server.connection.register_remote_method',params:{method_name:name+'.report'}}));await until(()=>messages.some(m=>m.id===2));assert.equal(messages.find(m=>m.id===2).result,'ok');return {ws,messages};}
 const active=await agent('active'),gone=await agent('gone');assert.equal(server.agentRemoteMethods.length,2);assert.ok(server.agentRemoteMethods.every(r=>r.state==='pending'));gone.ws.terminate();await until(()=>server.agentRemoteMethods.length===1);
 const opening=server.attachKlippy(path);await until(()=>seen.some(m=>m.method==='register_remote_method'));assert.equal(server.klippy?.initialized,false);assert.equal(active.messages.some(m=>m.method==='notify_klippy_ready'),false);const request=seen.find(m=>m.method==='register_remote_method');assert.equal(request.params.remote_method,'active.report');sockets[0].write(wire({id:request.id,result:'ok'}));await opening;await until(()=>active.messages.some(m=>m.method==='notify_klippy_ready'));assert.equal(server.agentRemoteMethods[0].state,'registered');assert.equal(seen.filter(m=>m.method==='register_remote_method').length,1);
 sockets[0].write(wire({method:request.params.response_template.method,params:{x:5}}));await until(()=>active.messages.some(m=>m.method==='active.report'));assert.deepEqual(active.messages.find(m=>m.method==='active.report').params,{x:5});
 }finally{for(const ws of clients)ws.terminate();await server.close();}
},m=>m.method==='register_remote_method'?false:undefined));
test('queued agent registration failures remain visible without announcing a successful method',()=>peer(async(path,_seen,_sockets,dir)=>{
 const file=join(dir,'failed-pending.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeClientCall(){}});let ws:WebSocket|undefined;
 try{const address=await server.start();ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const messages:any[]=[];ws.on('message',m=>messages.push(JSON.parse(String(m))));for(const [id,method,params] of [[1,'server.connection.identify',{client_name:'worker',type:'agent',version:'1',url:''}],[2,'server.connection.register_remote_method',{method_name:'agent.failed'}]] as const){ws.send(JSON.stringify({jsonrpc:'2.0',id,method,params}));await until(()=>messages.some(m=>m.id===id));assert.equal(messages.find(m=>m.id===id).error,undefined);}
 await server.attachKlippy(path);assert.equal(server.klippy?.initialized,true);assert.equal(server.agentRemoteMethods[0].state,'failed');assert.match(server.agentRemoteMethods[0].error!,/Denied/);assert.deepEqual(server.klippyRemoteMethods?.registered,[]);
 }finally{ws?.terminate();await server.close();}
},(m,s)=>{if(m.method==='register_remote_method'){s.write(wire({id:m.id,error:{message:'Denied queued registration'}}));return false;}}));
test('explicit Klippy recovery restores online agent registrations and never replays uncertain requests',()=>peer(async(path,seen,sockets,dir)=>{
 const file=join(dir,'recover.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeClientCall(){},authorizeNotification(){}});let ws:WebSocket|undefined;
 try{const address=await server.start();await server.attachKlippy(path);await assert.rejects(server.reconnectKlippy(),/disconnected/);ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const messages:any[]=[];ws.on('message',m=>messages.push(JSON.parse(String(m))));
 for(const [id,method,params] of [[1,'server.connection.identify',{client_name:'survivor',type:'agent',version:'1',url:''}],[2,'server.connection.register_remote_method',{method_name:'agent.report'}]] as const){ws.send(JSON.stringify({jsonrpc:'2.0',id,method,params}));await until(()=>messages.some(m=>m.id===id));assert.equal(messages.find(m=>m.id===id).error,undefined);}
 ws.send(JSON.stringify({jsonrpc:'2.0',id:3,method:'printer.objects.query',params:{objects:{toolhead:null}}}));await until(()=>seen.some(m=>m.method==='objects/query'));const boundary=seen.length;sockets[0].destroy();await until(()=>server.klippy?.connected===false&&messages.some(m=>m.id===3));assert.ok(messages.find(m=>m.id===3).error);assert.equal(server.agentRemoteMethods[0].state,'pending');
 const recovering=server.reconnectKlippy();await assert.rejects(server.reconnectKlippy(),/disconnected/);await recovering;assert.equal(sockets.length,2);assert.equal(server.agentRemoteMethods[0].state,'registered');assert.equal(seen.slice(boundary).some(m=>m.method==='objects/query'),false);const registration=seen.slice(boundary).find(m=>m.method==='register_remote_method');assert.equal(registration.params.remote_method,'agent.report');sockets[1].write(wire({method:registration.params.response_template.method,params:{generation:2}}));await until(()=>messages.some(m=>m.method==='agent.report'));assert.deepEqual(messages.find(m=>m.method==='agent.report').params,{generation:2});await until(()=>messages.some(m=>m.method==='notify_klippy_ready'));assert.equal(messages.filter(m=>m.method==='notify_klippy_disconnected').length,1);
 }finally{ws?.terminate();await server.close();}
},m=>m.method==='objects/query'?false:undefined));
test('server shutdown during recovery cannot open another Klippy generation',()=>peer(async(path,_seen,sockets,dir)=>{
 const file=join(dir,'cancel-recovery.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){}});await server.start();await server.attachKlippy(path);sockets[0].destroy();await until(()=>server.klippy?.connected===false);const recovery=server.reconnectKlippy(),rejected=assert.rejects(recovery,/stopping/);await server.close();await rejected;assert.equal(sockets.length,1);assert.equal(server.status.phase,'closed');
}));
test('recovery preserves bounded old authorization accounting but never delivers its stale callback',()=>peer(async(path,seen,sockets,dir)=>{
 const file=join(dir,'recover-authorization.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');let release!:()=>void,first=true;const gate=new Promise<void>(r=>release=r),server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeClientCall(){if(first){first=false;return gate;}}});let ws:WebSocket|undefined;
 try{const address=await server.start();await server.attachKlippy(path);ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const messages:any[]=[];ws.on('message',m=>messages.push(JSON.parse(String(m))));for(const [id,method,params] of [[1,'server.connection.identify',{client_name:'worker',type:'agent',version:'1',url:''}],[2,'server.connection.register_remote_method',{method_name:'agent.report'}]] as const){ws.send(JSON.stringify({jsonrpc:'2.0',id,method,params}));await until(()=>messages.some(m=>m.id===id));assert.equal(messages.find(m=>m.id===id).error,undefined);}
 const old=seen.at(-1).params.response_template.method;sockets[0].write(wire({method:old,params:{generation:1}}));await until(()=>server.status.clientCalls?.pending===1);sockets[0].destroy();await until(()=>server.klippy?.connected===false);await server.reconnectKlippy();assert.equal(server.status.clientCalls?.pending,1);const current=seen.at(-1).params.response_template.method;sockets[1].write(wire({method:current,params:{generation:2}}));await until(()=>server.status.clientCalls?.pending===2);release();await until(()=>messages.some(m=>m.method==='agent.report'));assert.deepEqual(messages.filter(m=>m.method==='agent.report'),[{jsonrpc:'2.0',method:'agent.report',params:{generation:2}}]);assert.equal(server.agentMethodDeliveries.closed,1);assert.equal(server.agentMethodDeliveries.sent,1);assert.equal(server.status.clientCalls?.pending,0);
 }finally{release();ws?.terminate();await server.close();}
}));
test('automatic supervisor retries an unavailable Unix endpoint then restores an online agent after disconnect',()=>peer(async(path,seen,sockets,dir)=>{
 const file=join(dir,'supervised.conf'),delayedPath=join(dir,'late.sock');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){},authorizeClientCall(){}});let ws:WebSocket|undefined;
 try{const address=await server.start();ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);await once(ws,'open');const messages:any[]=[];ws.on('message',m=>messages.push(JSON.parse(String(m))));for(const [id,method,params] of [[1,'server.connection.identify',{client_name:'persistent',type:'agent',version:'1',url:''}],[2,'server.connection.register_remote_method',{method_name:'agent.report'}]] as const){ws.send(JSON.stringify({jsonrpc:'2.0',id,method,params}));await until(()=>messages.some(m=>m.id===id));assert.equal(messages.find(m=>m.id===id).error,undefined);}
 server.superviseKlippy(delayedPath,{},5);assert.throws(()=>server.attachKlippy(path),/supervisor/);await assert.rejects(server.reconnectKlippy(),/supervisor/);assert.throws(()=>server.superviseKlippy(path),/owned/);await until(()=>server.klippySupervisor!.failures>=2);assert.equal(server.agentRemoteMethods[0].state,'pending');await symlink(path,delayedPath);await until(()=>server.klippySupervisor?.connections===1);assert.equal(server.agentRemoteMethods[0].state,'registered');sockets[0].destroy();await until(()=>server.klippySupervisor?.connections===2);assert.equal(sockets.length,2);const request=seen.filter(m=>m.method==='register_remote_method').at(-1);sockets[1].write(wire({method:request.params.response_template.method,params:{generation:2}}));await until(()=>messages.some(m=>m.method==='agent.report'));assert.deepEqual(messages.find(m=>m.method==='agent.report').params,{generation:2});
 }finally{ws?.terminate();await server.close();}const attempts=server.klippySupervisor!.attempts;await delay(15);assert.equal(server.klippySupervisor?.attempts,attempts);assert.equal(server.klippySupervisor?.phase,'stopped');
}));
test('closing supervised initialization cancels the pending Unix request without scheduling a retry',()=>peer(async(path,seen,sockets,dir)=>{
 const file=join(dir,'stop-supervisor.conf');await writeFile(file,'[server]\nhost=127.0.0.1\nport=0');const server=await ConfiguredMoonraker.load(file,{information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){}});await server.start();server.superviseKlippy(path,{},1);await until(()=>seen.some(m=>m.method==='info'));assert.equal(server.klippySupervisor?.phase,'connecting');await server.close();await delay(10);assert.equal(sockets.length,1);assert.equal(server.klippySupervisor?.attempts,1);assert.equal(server.klippySupervisor?.phase,'stopped');
},m=>m.method==='info'?false:undefined));
