import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {prepareKlipperSave} from '../src/config/klipper-save-preflight.ts';
async function fixture(run:(dir:string)=>Promise<void>){const dir=await mkdtemp(join(tmpdir(),'save-preflight-'));try{await run(dir);}finally{await rm(dir,{recursive:true,force:true});}}
test('candidate validates real includes, retains other values and never writes any file',()=>fixture(async dir=>{const path=join(dir,'printer.cfg'),current='[x]\na: old\n[include extra.cfg]\n';await writeFile(path,current);await writeFile(join(dir,'extra.cfg'),'[y]\nb: keep\n');const result=await prepareKlipperSave(path,current,{x:{a:'new'}});assert.equal(result!.source.original.x.a,'new');assert.equal(result!.source.original.y.b,'keep');assert.equal(await readFile(path,'utf8'),current);assert.deepEqual((await readdir(dir)).sort(),['extra.cfg','printer.cfg']);}));
test('direct and inherited included values reject even when equal to saved value',()=>fixture(async dir=>{const path=join(dir,'printer.cfg'),current='[x]\na: old\n[include extra.cfg]\n';await writeFile(path,current);for(const child of ['[x]\na: new\n','[DEFAULT]\na: new\n[x]\nb: 1\n']){await writeFile(join(dir,'extra.cfg'),child);await assert.rejects(prepareKlipperSave(path,current,{x:{a:'new'}}),/conflicts with included value/);}assert.equal(await readFile(path,'utf8'),current);}));
test('changed main source, missing include, cancellation and combined byte budget reject',()=>fixture(async dir=>{const path=join(dir,'printer.cfg'),current='[x]\na: old\n';await writeFile(path,current);await assert.rejects(prepareKlipperSave(path,current+'#stale\n',{x:{a:'new'}}),/changed/);await assert.rejects(prepareKlipperSave(path,current,{x:{a:'new'}},{bytes:100}),/byte budget/);const control=new AbortController();control.abort(new Error('cancelled'));await assert.rejects(prepareKlipperSave(path,current,{x:{a:'new'}},{signal:control.signal}),/cancelled/);const missing='[include missing.cfg]\n';await writeFile(path,missing);await assert.rejects(prepareKlipperSave(path,missing,{x:{a:'new'}}),/Missing/);}));
