import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,readdir,open,unlink,rm,type FileHandle} from 'node:fs/promises';
import {join,basename} from 'node:path';
import {tmpdir} from 'node:os';
import {prepareKlipperSave} from '../src/config/klipper-save-preflight.ts';
import {commitKlipperSave,KlipperSaveCommitError} from '../src/config/klipper-save-commit.ts';
async function fixture(run:(dir:string,path:string,current:string,prototype:FileHandle)=>Promise<void>){const dir=await mkdtemp(join(tmpdir(),'save-fault-')),path=join(dir,'printer.cfg'),current='[x]\na: original\n';try{await writeFile(path,current);const handle=await open(path,'r'),prototype=Object.getPrototypeOf(handle) as FileHandle;await handle.close();await run(dir,path,current,prototype);}finally{await rm(dir,{recursive:true,force:true});}}
test('backup, temporary-file and pre-replace directory sync failures leave the main file unchanged',async t=>{
 for(const failedSync of [1,2,3])await fixture(async(dir,path,current,prototype)=>{const prepared=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!,original=prototype.sync,cause=new Error(`sync ${failedSync}`);let calls=0;const injected=t.mock.method(prototype,'sync',async function(this:FileHandle){if(++calls===failedSync)throw cause;return original.call(this);});try{await assert.rejects(commitKlipperSave(prepared),error=>error instanceof KlipperSaveCommitError&&error.phase==='before-replace'&&error.cause===cause);assert.equal(await readFile(path,'utf8'),current);assert.deepEqual(await readdir(dir),['printer.cfg']);}finally{injected.mock.restore();}});
});
test('post-replace directory sync failure reports replaced state and keeps exact backup',async t=>fixture(async(dir,path,current,prototype)=>{const prepared=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!,original=prototype.sync,cause=new Error('post-rename fsync');let directories=0,reported:KlipperSaveCommitError|undefined;const injected=t.mock.method(prototype,'sync',async function(this:FileHandle){if((await this.stat()).isDirectory()&&++directories===2)throw cause;return original.call(this);});try{await assert.rejects(commitKlipperSave(prepared),error=>{if(!(error instanceof KlipperSaveCommitError))return false;reported=error;return error.phase==='replaced'&&error.cause===cause;});assert.equal(await readFile(path,'utf8'),prepared.text);assert.ok(reported!.backupPath);assert.equal(await readFile(reported!.backupPath!,'utf8'),current);assert.deepEqual((await readdir(dir)).sort(),[basename(reported!.backupPath!),'printer.cfg'].sort());}finally{injected.mock.restore();}}));
test('cancellation before replacement aborts, cancellation after replacement still completes sync',async t=>{
 for(const boundary of [1,2])await fixture(async(dir,path,current,prototype)=>{const prepared=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!,original=prototype.sync,controller=new AbortController();let directories=0;const injected=t.mock.method(prototype,'sync',async function(this:FileHandle){if((await this.stat()).isDirectory()&&++directories===boundary)controller.abort(new Error('cancel boundary'));return original.call(this);});try{if(boundary===1){await assert.rejects(commitKlipperSave(prepared,{signal:controller.signal}),error=>error instanceof KlipperSaveCommitError&&error.phase==='before-replace');assert.equal(await readFile(path,'utf8'),current);assert.deepEqual(await readdir(dir),['printer.cfg']);}else{const result=await commitKlipperSave(prepared,{signal:controller.signal});assert.equal(result.fileAndDirectorySynced,true);assert.equal(await readFile(path,'utf8'),prepared.text);assert.equal(directories,2);}}finally{injected.mock.restore();}});
});
test('include edit after backup is caught by final revalidation',async t=>fixture(async(dir,path,_current,prototype)=>{const current='[x]\na: original\n[include child.cfg]\n',child=join(dir,'child.cfg');await writeFile(path,current);await writeFile(child,'[y]\nb: old\n');const prepared=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!,original=prototype.sync;let changed=false;const injected=t.mock.method(prototype,'sync',async function(this:FileHandle){if(!changed&&(await this.stat()).isDirectory()){changed=true;await writeFile(child,'[y]\nb: externally changed\n');}return original.call(this);});try{await assert.rejects(commitKlipperSave(prepared),error=>error instanceof KlipperSaveCommitError&&error.phase==='before-replace');assert.equal(await readFile(path,'utf8'),current);assert.equal(await readFile(child,'utf8'),'[y]\nb: externally changed\n');assert.deepEqual((await readdir(dir)).sort(),['child.cfg','printer.cfg']);}finally{injected.mock.restore();}}));
test('cleanup refuses to delete a lock replaced by another owner and preserves both causes',async t=>fixture(async(dir,path,current,prototype)=>{const prepared=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!,original=prototype.sync,cause=new Error('injected failure'),lock=join(dir,'.printer.cfg.save.lock');let replaced=false;const injected=t.mock.method(prototype,'sync',async function(this:FileHandle){if(!replaced&&(await this.stat()).isDirectory()){replaced=true;await unlink(lock);await writeFile(lock,'replacement owner');throw cause;}return original.call(this);});try{await assert.rejects(commitKlipperSave(prepared),error=>error instanceof KlipperSaveCommitError&&error.phase==='before-replace'&&error.cause instanceof AggregateError&&error.cause.errors[0]===cause);assert.equal(await readFile(lock,'utf8'),'replacement owner');assert.equal(await readFile(path,'utf8'),current);assert.deepEqual((await readdir(dir)).sort(),['.printer.cfg.save.lock','printer.cfg']);}finally{injected.mock.restore();}}));
