import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,symlink,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {loadKlipperConfiguration} from '../src/config/klipper-files.ts';
import {AUTOSAVE_HEADER} from '../src/config/klipper-autosave.ts';
async function fixture(run:(dir:string)=>Promise<void>){const dir=await mkdtemp(join(tmpdir(),'klipper-files-'));try{await run(dir);}finally{await rm(dir,{recursive:true,force:true});}}
test('include order, sorted wildcard, repeated files and autosave precedence match Klipper',()=>fixture(async dir=>{await mkdir(join(dir,'parts'));await writeFile(join(dir,'parts','b.cfg'),'[x]\na: b\n');await writeFile(join(dir,'parts','a.cfg'),'[x]\na: a\nb: child\n');await writeFile(join(dir,'parts','.hidden.cfg'),'[x]\na: hidden\n');await writeFile(join(dir,'printer.cfg'),'[x]\na: root\n[include parts/*.cfg]\n[include absent*.cfg]\n[include parts/a.cfg]\n[x]\nc: after\n'+AUTOSAVE_HEADER+'#*# [x]\n#*# b: saved\n#*# d: saved\n');const result=await loadKlipperConfiguration(join(dir,'printer.cfg'));assert.deepEqual({...result.original.x},{a:'a',b:'child',c:'after',d:'saved'});assert.equal(result.files.length,4);}));
test('missing literal includes and symlink cycles fail without publication',()=>fixture(async dir=>{const main=join(dir,'printer.cfg');await writeFile(main,'[include missing.cfg]\n');await assert.rejects(loadKlipperConfiguration(main),/Missing/);await symlink(main,join(dir,'alias.cfg'));await writeFile(main,'[include alias.cfg]\n');await assert.rejects(loadKlipperConfiguration(main),/Recursive/);}));
test('bounded reads reject invalid UTF-8, directories, excessive bytes/depth/files and cancellation',()=>fixture(async dir=>{const main=join(dir,'printer.cfg');await writeFile(main,Buffer.from([255]));await assert.rejects(loadKlipperConfiguration(main));await assert.rejects(loadKlipperConfiguration(dir),/regular file/);await writeFile(main,'[x]\na: value\n');await assert.rejects(loadKlipperConfiguration(main,{bytes:3}),/byte budget/);const control=new AbortController();control.abort(new Error('cancelled'));await assert.rejects(loadKlipperConfiguration(main,{signal:control.signal}),/cancelled/);await writeFile(join(dir,'child.cfg'),'[include next.cfg]\n');await writeFile(join(dir,'next.cfg'),'[x]\na: 1\n');await writeFile(main,'[include child.cfg]\n');await assert.rejects(loadKlipperConfiguration(main,{files:1}),/budget/);await assert.rejects(loadKlipperConfiguration(main,{depth:1}),/depth|budget/);}));
test('child saves remain comments while corrupted main save blocks loading',()=>fixture(async dir=>{const main=join(dir,'printer.cfg');await writeFile(join(dir,'child.cfg'),'[x]\na: child\n'+AUTOSAVE_HEADER+'#*# [x]\n#*# a: ignored\n');await writeFile(main,'[include child.cfg]\n');assert.equal((await loadKlipperConfiguration(main)).original.x.a,'child');await writeFile(main,'[x]\na: 1\n'+AUTOSAVE_HEADER+'edited');await assert.rejects(loadKlipperConfiguration(main),/Corrupt/);}));
test('wildcard matches newline characters in legal filenames',()=>fixture(async dir=>{await writeFile(join(dir,'line\nbreak.cfg'),'[x]\na: matched\n');await writeFile(join(dir,'printer.cfg'),'[include line*.cfg]\n');assert.equal((await loadKlipperConfiguration(join(dir,'printer.cfg'))).original.x.a,'matched');}));
