import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,stat,readdir,symlink,rm} from 'node:fs/promises';
import {join,basename} from 'node:path';
import {tmpdir} from 'node:os';
import {prepareKlipperSave} from '../src/config/klipper-save-preflight.ts';
import {commitKlipperSave,KlipperSaveCommitError} from '../src/config/klipper-save-commit.ts';
async function fixture(run:(dir:string,path:string,current:string)=>Promise<void>){const dir=await mkdtemp(join(tmpdir(),'save-commit-')),path=join(dir,'printer.cfg'),current='[x]\na: old\r\n';try{await writeFile(path,current,{mode:0o640});await run(dir,path,current);}finally{await rm(dir,{recursive:true,force:true});}}
test('durable save retains exact original backup and permissions without a restart',()=>fixture(async(dir,path,current)=>{const p=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!,r=await commitKlipperSave(p);assert.equal(await readFile(path,'utf8'),p.text);assert.equal(await readFile(r.backupPath,'utf8'),current);assert.equal((await stat(path)).mode&0o777,0o640);assert.equal((await stat(r.backupPath)).mode&0o777,0o600);assert.equal(r.fileAndDirectorySynced,true);assert.deepEqual((await readdir(dir)).sort(),[basename(r.backupPath),'printer.cfg'].sort());}));
test('stale preparation fails before replacement and cleans its own artifacts',()=>fixture(async(dir,path,current)=>{const p=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!;await writeFile(path,'[x]\na: edited\n');await assert.rejects(commitKlipperSave(p),e=>e instanceof KlipperSaveCommitError&&e.phase==='before-replace');assert.equal(await readFile(path,'utf8'),'[x]\na: edited\n');assert.deepEqual(await readdir(dir),['printer.cfg']);}));
test('existing lock is preserved and forged or cancelled preparations cannot write',()=>fixture(async(dir,path,current)=>{const p=(await prepareKlipperSave(path,current,{x:{a:'new'}}))!;await writeFile(join(dir,'.printer.cfg.save.lock'),'other owner');await assert.rejects(commitKlipperSave(p),KlipperSaveCommitError);assert.equal(await readFile(join(dir,'.printer.cfg.save.lock'),'utf8'),'other owner');await assert.rejects(commitKlipperSave({...p}),/Unrecognized/);const controller=new AbortController();controller.abort(new Error('cancelled'));await assert.rejects(commitKlipperSave(p,{signal:controller.signal}),/cancelled/);assert.equal(await readFile(path,'utf8'),current);}));
test('saving through a symlink is refused before replacing either link or target',()=>fixture(async(dir,path,current)=>{const alias=join(dir,'alias.cfg');await symlink(path,alias);const p=(await prepareKlipperSave(alias,current,{x:{a:'new'}}))!;await assert.rejects(commitKlipperSave(p),e=>e instanceof KlipperSaveCommitError&&e.phase==='before-replace');assert.equal(await readFile(path,'utf8'),current);assert.equal(await readFile(alias,'utf8'),current);}));
