import test from 'node:test';
import assert from 'node:assert/strict';
import {LookAheadQueue,Move,motionLimits} from '../src/motion/lookahead.ts';
const limits=motionLimits(300,3000);
const moves=()=>Array.from({length:20},(_,i)=>new Move(limits,[i*10,0,0,i],[i*10+10,Math.sin(i)*.2,0,i+1],100));
test('batch admission matches sequential junctions, flush hints and profiles',()=>{for(const preexisting of [false,true]){const a=new LookAheadQueue(),b=new LookAheadQueue();if(preexisting){a.add(new Move(limits,[-10,0,0,0],[0,0,0,0],100));b.add(new Move(limits,[-10,0,0,0],[0,0,0,0],100));}const ma=moves(),mb=moves();let hint=false;for(const m of ma)hint=a.add(m)||hint;assert.equal(b.addBatch(mb),hint);assert.equal(b.length,a.length);assert.deepEqual(mb.map(m=>[m.maxStartV2,m.maxMcrStartV2]),ma.map(m=>[m.maxStartV2,m.maxMcrStartV2]));assert.deepEqual(b.flush().map(m=>m.profile),a.flush().map(m=>m.profile));}});
test('late junction failure restores staged fields, prior queue and flush budget',()=>{let fail=true;const guarded={...limits,extraAxes:[()=>{if(fail)throw new Error('injected');return 10;}]};const q=new LookAheadQueue(),first=new Move(limits,[0,0,0,0],[10,0,0,0],100);q.add(first);q.setFlushTime(1);const m1=new Move(limits,[10,0,0,0],[20,0,0,0],100),m2=new Move(guarded,[20,0,0,0],[30,0,0,0],100);assert.throws(()=>q.addBatch([m1,m2]),/injected/);assert.equal(q.length,1);assert.equal(q.last,first);assert.equal(m1.maxStartV2,0);assert.equal(m1.maxMcrStartV2,0);fail=false;assert.equal(q.addBatch([m1,m2]),false);assert.equal(q.length,3);});
test('batch rejects aliasing and reentrant queue mutation; skips zero moves',()=>{const q=new LookAheadQueue(),m=moves()[0];assert.throws(()=>q.addBatch([m,m]),/Duplicate/);assert.equal(q.length,0);q.add(m);assert.throws(()=>q.addBatch([m]),/Duplicate/);for(const action of [()=>q.reset(),()=>q.flush(),()=>q.add(moves()[1]),()=>q.setFlushTime(.1),()=>q.addBatch([])]){const bad=new Move({...limits,extraAxes:[()=>{action();return 1;}]},[10,0,0,0],[20,0,0,0],100);assert.throws(()=>q.addBatch([bad]),/admission active/);assert.equal(q.length,1);}assert.equal(q.addBatch([new Move(limits,[0,0,0,0],[0,0,0,0],100)]),false);assert.equal(q.length,1);});
test('membership follows lazy flush, full flush and reset without retaining released moves',()=>{
 const q=new LookAheadQueue(),all=moves();q.addBatch(all);const flushed=q.flush(true);assert(flushed.length>0&&flushed.length<all.length);
 assert.throws(()=>q.addBatch([all.at(-1)!]),/Duplicate/);q.addBatch([flushed[0]]);
 q.flush();q.addBatch(all);assert.equal(q.length,all.length);q.reset();q.addBatch(all);assert.equal(q.length,all.length);
});
