import {test} from 'node:test';
import assert from 'node:assert/strict';
import {crc32} from 'node:zlib';
import {MessageDictionary} from '../src/protocol/dictionary.ts';
import {configureMCU,MCUConfigurationFault,type MCUConfigPlan} from '../src/protocol/mcu-config.ts';
import {encodeFrame} from '../src/protocol/codec.ts';
const signal=()=>new AbortController().signal;
function fixture(initialCRC?:number){const dictionary=new MessageDictionary();dictionary.identify(Buffer.from(JSON.stringify({commands:{get_config:2,'allocate_oids count=%c':3,'finalize_config crc=%u':4,'config_stepper oid=%c pin=%u':5,'reset_step_clock oid=%c clock=%u':6},responses:{'config is_config=%c crc=%u is_shutdown=%c move_count=%hu':7},enumerations:{pin:{PA0:8}}})),false);let crc=initialCRC??0,configured=initialCRC===undefined?0:1,stops=0,reads=0,shutdown=0,moves=64;const sent:string[]=[];return {dictionary,sent,get stops(){return stops;},get reads(){return reads;},shutdown(){shutdown=1;},setMoves(n:number){moves=n;},transport:{async query(){reads++;return {message:{name:'config',parameters:{is_config:configured,crc,is_shutdown:shutdown,move_count:moves}},sentTime:1,receiveTime:1};},async send(payload:Uint8Array){const msg=dictionary.parseFrame(encodeFrame(0,payload))[0];sent.push(msg.name);if(msg.name==='finalize_config'){crc=msg.parameters.crc as number;configured=1;}},async stop(){stops++;}}};}
const plan:MCUConfigPlan={oidCount:1,commands:['config_stepper oid=0 pin=PA0'],init:['reset_step_clock oid=0 clock=0x100'],restart:['reset_step_clock oid=0 clock=0'],reservedMoves:4};
const expectedCRC=crc32(Buffer.from('allocate_oids count=1\nconfig_stepper oid=0 pin=PA0'));
test('new configuration hashes exact resolved text and verifies final status',async()=>{const f=fixture();const result=await configureMCU(f.dictionary,f.transport,plan,signal());assert.deepEqual(result,{crc:expectedCRC,moveCount:64,moveSlots:60,reused:false});assert.deepEqual(f.sent,['allocate_oids','config_stepper','finalize_config','reset_step_clock']);assert.equal(f.reads,2);assert.equal(f.stops,0);});
test('matching configuration sends only restart/init and mismatch sends no writes',async()=>{const f=fixture(expectedCRC);assert.equal((await configureMCU(f.dictionary,f.transport,plan,signal())).reused,true);assert.deepEqual(f.sent,['reset_step_clock','reset_step_clock']);const bad=fixture(1);await assert.rejects(configureMCU(bad.dictionary,bad.transport,plan,signal()),error=>error instanceof MCUConfigurationFault&&error.code==='crc_mismatch');assert.equal(bad.sent.length,0);assert.equal(bad.stops,1);});
test('shutdown, failed firmware restart, insufficient slots and malformed plan stop configuration',async()=>{const a=fixture();a.shutdown();await assert.rejects(configureMCU(a.dictionary,a.transport,plan,signal()),error=>error instanceof MCUConfigurationFault&&error.code==='shutdown');assert.equal(a.sent.length,0);const b=fixture(expectedCRC);await assert.rejects(configureMCU(b.dictionary,b.transport,{...plan,firmwareRestart:true},signal()),/restart/);assert.equal(b.sent.length,0);const c=fixture();c.setMoves(3);await assert.rejects(configureMCU(c.dictionary,c.transport,plan,signal()),/Too few/);const d=fixture();await assert.rejects(configureMCU(d.dictionary,d.transport,{...plan,init:['unknown value=1']},signal()),/Unknown/);assert.equal(d.reads,0);assert.equal(d.sent.length,0);});
test('configuration rejects a changed CRC after finalization and preserves stop failure',async()=>{const f=fixture();const transport={...f.transport,async query(){const result=await f.transport.query();if(f.reads===2)result.message.parameters.crc=123;return result;},async stop(){throw new Error('device stop failed');}};await assert.rejects(configureMCU(f.dictionary,transport,plan,signal()),AggregateError);});
test('configuration may leave zero slots for a sensor-only MCU',async()=>{const f=fixture();f.setMoves(4);assert.equal((await configureMCU(f.dictionary,f.transport,plan,signal())).moveSlots,0);});
test('command text supports integer bases and enumerations but rejects ambiguous encodings',()=>{const f=fixture();assert.deepEqual(f.dictionary.encodeCommand('reset_step_clock clock=0b100 oid=+0'),f.dictionary.encode('reset_step_clock',{oid:0,clock:4}));assert.throws(()=>f.dictionary.encodeCommand('reset_step_clock oid=0 clock=03'),/literal/);assert.throws(()=>f.dictionary.encodeCommand('reset_step_clock oid=0 oid=1 clock=3'),/parameter/);assert.throws(()=>f.dictionary.encodeCommand('config_stepper oid=0 pin=BAD'),/enumeration/);});
test('cancellation after partial configuration never sends or replays the remaining commands',async()=>{const f=fixture(),abort=new AbortController();const transport={...f.transport,async send(payload:Uint8Array){await f.transport.send(payload);abort.abort(new Error('cancel partial configuration'));}};await assert.rejects(configureMCU(f.dictionary,transport,plan,abort.signal),/cancel partial/);assert.deepEqual(f.sent,['allocate_oids']);assert.equal(f.stops,1);});
