import test from 'node:test';
import assert from 'node:assert/strict';
import {ClockSync} from '../src/timing/clock-sync.ts';
import {waitForMcuClocks} from '../src/timing/mcu-clock-barrier.ts';
function fixture(initial=0n){let now=1,callback:(()=>void)|undefined,healthy=true,sync=new ClockSync(1000000,initial,1);const timing={now:()=>now,schedule(fn:()=>void,_seconds:number){callback=fn;return ()=>{callback=undefined;};}};const clock={assertActive(){if(!healthy)throw new Error('stale clock');},get sync(){return sync;}};return {clock,timing,tick(v:bigint){sync.accept({clock32:Number(v&0xffffffffn),sentTime:1,receiveTime:1});},poll(time=now+.01){now=time;const fn=callback;callback=undefined;fn?.();},get waiting(){return !!callback;},stale(){healthy=false;},replace(){sync=new ClockSync(1000000,initial,1);}};}
test('all MCU sampled clocks must strictly pass their target, retaining bigint precision',async()=>{const base=1n<<54n,a=fixture(base),b=fixture(base),c=new AbortController();let done=false;const waiting=waitForMcuClocks([{clock:a.clock,tick:base+1n},{clock:b.clock,tick:base+2n}],c.signal,{scheduler:a.timing}).then(()=>{done=true;});a.tick(base+2n);b.tick(base+2n);a.poll();await Promise.resolve();assert.equal(done,false);b.tick(base+3n);a.poll();await waiting;assert.equal(a.waiting,false);});
test('clock expiry, generation replacement and monotonic regression reject and remove polling',async()=>{for(const fault of ['stale','replace','backward']){const a=fixture(),waiting=waitForMcuClocks([{clock:a.clock,tick:100n}],new AbortController().signal,{scheduler:a.timing});if(fault==='stale')a.stale();if(fault==='replace')a.replace();a.poll(fault==='backward'?.5:1.1);await assert.rejects(waiting,/stale|generation|regressed/);assert.equal(a.waiting,false);}});
test('timeout and cancellation do not pass a clock barrier or retain a timer',async()=>{for(const mode of ['timeout','cancel']){const a=fixture(),c=new AbortController(),cause=new Error('emergency'),waiting=waitForMcuClocks([{clock:a.clock,tick:100n}],c.signal,{scheduler:a.timing,timeoutSeconds:.1});if(mode==='timeout')a.poll(1.1);else c.abort(cause);await assert.rejects(waiting,mode==='timeout'?/timed out/:e=>e===cause);assert.equal(a.waiting,false);}});
test('invalid targets and pre-cancellation reject before scheduling',async()=>{const a=fixture();for(const targets of [[],[{clock:a.clock,tick:-1n}],[{clock:a.clock,tick:0xffffffffffffffffn}]])await assert.rejects(waitForMcuClocks(targets,new AbortController().signal,{scheduler:a.timing}),/Invalid/);await assert.rejects(waitForMcuClocks([{clock:a.clock,tick:0n}],AbortSignal.abort(new Error('cancel')),{scheduler:a.timing}),/cancel/);assert.equal(a.waiting,false);});
test('even an undefined health failure rejects rather than satisfying the barrier',async()=>{const a=fixture();a.clock.assertActive=()=>{throw undefined;};let rejected=false;await waitForMcuClocks([{clock:a.clock,tick:0n}],new AbortController().signal,{scheduler:a.timing}).then(()=>assert.fail('accepted failed health check'),()=>{rejected=true;});assert.equal(rejected,true);assert.equal(a.waiting,false);});
