import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,readdir,readFile,writeFile,open,chmod,symlink} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {MetadataVersions,MetadataVersionWriteError,type MetadataVersion} from '../src/moonraker/metadata-versions.ts';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
import {PrintSnapshotBudget} from '../src/gcode/snapshot-budget.ts';
import {sealedBuffer} from '../src/storage/sealed-buffer.ts';
const signal=new AbortController().signal,hash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const headName=(filename:string)=>'.metadata-head-'+hash(filename)+'.json';
const event=(sequence:string,filename='part.gcode',state:MetadataVersion['state']='invalidated'):MetadataVersion=>({version:1,id:'mv-'+sequence,sequence,filename,state,scanId:state==='invalidated'?null:'scan-'+randomUUID()});
const envelope=(value:MetadataVersion)=>JSON.stringify({version:2,sha256:hash(JSON.stringify(value)),record:value});
async function directory(){const path=await mkdtemp(join(tmpdir(),'metadata-heads-'));return {path,close:()=>rm(path,{recursive:true,force:true})};}
async function seed(path:string,values:MetadataVersion[]){const store=await PublishedPrintFiles.open(path);try{for(const value of values){const stage=await sealedBuffer(Buffer.from(JSON.stringify(value)),signal,new PrintSnapshotBudget({maxBytes:65536,maxSnapshots:1}));try{await store.publish(value.id,'metadata-version',stage.file,signal);}finally{await stage.close();}}}finally{await store.close();}}
async function inventory(path:string){return Object.fromEntries(await Promise.all((await readdir(path)).sort().map(async name=>[name,(await readFile(join(path,name))).toString('base64')])));}
async function prototype(){const file=await open('/dev/null','r');try{return Object.getPrototypeOf(file);}finally{await file.close();}}
test('legacy migration validates all events and preserves the selected head, tombstone and exact high water',async()=>{
 const f=await directory();let owner:MetadataVersions|undefined;try{const old=event('1','a.gcode','selected'),newer=event('9007199254740993','a.gcode'),b=event('9007199254740994','b.gcode','selected');await seed(f.path,[old,newer,b]);owner=await MetadataVersions.open(f.path);assert.deepEqual(owner.current('a.gcode'),newer);assert.deepEqual(owner.current('b.gcode'),b);assert.equal(owner.status.sequence,b.sequence);assert.deepEqual((await readdir(f.path)).sort(),[headName('a.gcode'),headName('b.gcode')].sort());assert.equal((await owner.invalidate('a.gcode',signal)).sequence,'9007199254740995');await owner.close();owner=await MetadataVersions.open(f.path);assert.equal(owner.status.sequence,'9007199254740995');}finally{await owner?.close();await f.close();}
});
test('corrupt legacy data prevents any migration or garbage deletion',async()=>{
 const f=await directory();try{await seed(f.path,[event('1','a.gcode'),event('2','b.gcode')]);const blob=(await readdir(f.path)).find(name=>name.endsWith('.gcode'))!,p=join(f.path,blob),bytes=await readFile(p);bytes[0]^=1;await chmod(p,0o600);await writeFile(p,bytes);await writeFile(join(f.path,'.metadata-stage-'+randomUUID()),'incomplete',{mode:0o600});const before=await inventory(f.path);await assert.rejects(MetadataVersions.open(f.path),/digest/);assert.deepEqual(await inventory(f.path),before);}finally{await f.close();}
});
test('partially migrated mixed formats resume only after matching all authorities',async()=>{
 const f=await directory();let owner:MetadataVersions|undefined;try{const a=event('1','a.gcode'),b=event('2','b.gcode');await seed(f.path,[a,b]);await writeFile(join(f.path,headName(a.filename)),envelope(a),{mode:0o600});await writeFile(join(f.path,'.metadata-stage-'+randomUUID()),'incomplete',{mode:0o600});owner=await MetadataVersions.open(f.path);assert.deepEqual(owner.entries().map(v=>v.id).sort(),['mv-1','mv-2']);assert.equal((await readdir(f.path)).length,2);}finally{await owner?.close();await f.close();}
});
test('a valid conflicting sequence across formats is rejected without cleanup',async()=>{
 const f=await directory();try{const a=event('7','a.gcode'),conflict=event('7','b.gcode');await seed(f.path,[a]);await writeFile(join(f.path,headName(conflict.filename)),envelope(conflict),{mode:0o600});const before=await inventory(f.path);await assert.rejects(MetadataVersions.open(f.path),/Conflicting/);assert.deepEqual(await inventory(f.path),before);}finally{await f.close();}
});
test('head checksum corruption and unknown entries retain all evidence',async()=>{
 const f=await directory();let owner=await MetadataVersions.open(f.path);try{await owner.invalidate('part.gcode',signal);await owner.close();const path=join(f.path,headName('part.gcode')),value=JSON.parse(await readFile(path,'utf8'));value.record.sequence='9';await writeFile(path,JSON.stringify(value));const before=await inventory(f.path);await assert.rejects(MetadataVersions.open(f.path),/digest/);assert.deepEqual(await inventory(f.path),before);await writeFile(path,envelope(event('1')));await writeFile(join(f.path,'unknown'),'x',{mode:0o600});await assert.rejects(MetadataVersions.open(f.path),/Unknown/);assert.equal(await readFile(join(f.path,'unknown'),'utf8'),'x');}finally{await owner.close();await f.close();}
});
test('symlinks, permissive heads and mismatched hashed names cannot become recovered authorities',async()=>{
 const f=await directory();try{const path=join(f.path,headName('part.gcode'));await symlink('/dev/null',path);await assert.rejects(MetadataVersions.open(f.path),/entry/);await rm(path);await writeFile(path,envelope(event('1')),{mode:0o644});await assert.rejects(MetadataVersions.open(f.path),/entry/);await chmod(path,0o600);await writeFile(path,envelope(event('1','different.gcode')));await assert.rejects(MetadataVersions.open(f.path),/filename mismatch/);}finally{await f.close();}
});
test('exclusive ownership and close drain accepted version writes',async()=>{
 const f=await directory(),owner=await MetadataVersions.open(f.path);try{await assert.rejects(MetadataVersions.open(f.path),/lock|busy|temporarily/i);const write=owner.invalidate('part.gcode',signal),closing=owner.close(),value=await write;await closing;await assert.rejects(owner.invalidate('part.gcode',signal),/closed/);const reopened=await MetadataVersions.open(f.path);try{assert.deepEqual(reopened.current('part.gcode'),value);}finally{await reopened.close();}}finally{await owner.close();await f.close();}
});
test('escaped 4096-byte names fit the bounded head and a maximum uint64 cannot advance',async()=>{
 const f=await directory();let owner=await MetadataVersions.open(f.path);try{const filename='\u0001'.repeat(4096);await owner.invalidate(filename,signal);await owner.close();owner=await MetadataVersions.open(f.path);assert.equal(owner.current(filename)?.filename,filename);await owner.close();const max=event('18446744073709551615','max.gcode');await writeFile(join(f.path,headName(max.filename)),envelope(max),{mode:0o600});owner=await MetadataVersions.open(f.path);await assert.rejects(owner.invalidate(filename,signal),/exhausted/);assert.equal(owner.status.faulted,false);assert.equal(owner.status.sequence,max.sequence);}finally{await owner.close();await f.close();}
});
test('replacement uses two ordered sync barriers and drains late cancellation',async()=>{
 const f=await directory(),owner=await MetadataVersions.open(f.path),p=await prototype(),original=p.sync,controller=new AbortController(),order:string[]=[];try{await owner.invalidate('part.gcode',signal);p.sync=async function(...args:unknown[]){const directory=(await this.stat()).isDirectory();order.push(directory?'directory':'data');if(directory)controller.abort(new Error('late cancel'));return Reflect.apply(original,this,args);};let value:MetadataVersion;try{value=await owner.invalidate('part.gcode',controller.signal);}finally{p.sync=original;}assert.deepEqual(order,['data','directory']);assert.equal(controller.signal.aborted,true);assert.equal(owner.status.faulted,false);assert.equal(owner.status.staging.reservations,0);await owner.close();const recovered=await MetadataVersions.open(f.path);try{assert.deepEqual(recovered.current('part.gcode'),value);}finally{await recovered.close();}}finally{p.sync=original;await owner.close();await f.close();}
});
test('data-sync failure fences the owner and preserves the preceding head',async()=>{
 const f=await directory(),owner=await MetadataVersions.open(f.path),p=await prototype(),original=p.sync;try{const old=await owner.invalidate('part.gcode',signal);p.sync=()=>Promise.reject(new Error('data sync fault'));try{await assert.rejects(owner.invalidate('part.gcode',signal),MetadataVersionWriteError);}finally{p.sync=original;}assert.equal(owner.status.faulted,true);assert.equal(owner.status.staging.reservations,0);await assert.rejects(owner.invalidate('part.gcode',signal),/recovery/);await owner.close();const recovered=await MetadataVersions.open(f.path);try{assert.deepEqual(recovered.current('part.gcode'),old);assert.equal((await readdir(f.path)).length,1);}finally{await recovered.close();}}finally{p.sync=original;await owner.close();await f.close();}
});
test('changed current head is rejected before replacement',async()=>{
 const f=await directory(),owner=await MetadataVersions.open(f.path);try{await owner.invalidate('part.gcode',signal);await writeFile(join(f.path,headName('part.gcode')),envelope(event('4')));await assert.rejects(owner.invalidate('part.gcode',signal),MetadataVersionWriteError);assert.equal(owner.status.faulted,true);assert.equal(JSON.parse(await readFile(join(f.path,headName('part.gcode')),'utf8')).record.sequence,'4');}finally{await owner.close();await f.close();}
});
for(const phase of ['data','directory'] as const)test(`actual SIGKILL after ${phase} sync recovers the committed generation only`,async()=>{
 const f=await directory();let owner=await MetadataVersions.open(f.path);try{await owner.invalidate('part.gcode',signal);await owner.close();
  const moduleUrl=new URL(import.meta.url.endsWith('.js')?'../src/moonraker/metadata-versions.js':'../src/moonraker/metadata-versions.ts',import.meta.url).href,code=`import {open} from 'node:fs/promises';import {MetadataVersions} from ${JSON.stringify(moduleUrl)};const owner=await MetadataVersions.open(process.argv[1]),probe=await open('/dev/null','r'),p=Object.getPrototypeOf(probe),original=p.sync;await probe.close();p.sync=async function(...args){const directory=(await this.stat()).isDirectory();await Reflect.apply(original,this,args);if(directory===${phase==='directory'}){await new Promise(resolve=>process.stdout.write('${phase}',resolve));process.kill(process.pid,'SIGKILL');}};await owner.invalidate('part.gcode',new AbortController().signal);throw new Error('missing kill boundary');`;
  const result=await new Promise<{signal:NodeJS.Signals|null;output:string}>((resolve,reject)=>{const child=spawn(process.execPath,['--input-type=module','-e',code,f.path],{stdio:['ignore','pipe','pipe'],timeout:10000});let output='',errors='';child.stdout.on('data',data=>output+=data);child.stderr.on('data',data=>errors+=data);child.on('error',reject);child.on('close',(exit,signal)=>{if(exit!==null)reject(new Error(errors));else resolve({signal,output});});});assert.equal(result.signal,'SIGKILL');assert.equal(result.output,phase);owner=await MetadataVersions.open(f.path);assert.equal(owner.current('part.gcode')?.sequence,phase==='data'?'1':'2');assert.equal((await readdir(f.path)).length,1);assert.equal((await owner.invalidate('part.gcode',signal)).sequence,phase==='data'?'2':'3');
 }finally{await owner.close();await f.close();}
});
test('cancellation after staged data sync retains the old head and removes private staging',async()=>{
 const f=await directory(),owner=await MetadataVersions.open(f.path),p=await prototype(),original=p.sync,controller=new AbortController();try{const old=await owner.invalidate('part.gcode',signal);p.sync=async function(...args:unknown[]){await Reflect.apply(original,this,args);if(!(await this.stat()).isDirectory())controller.abort(new Error('before rename'));};try{await assert.rejects(owner.invalidate('part.gcode',controller.signal),MetadataVersionWriteError);}finally{p.sync=original;}assert.equal(owner.status.faulted,true);assert.equal(owner.status.staging.reservations,0);await owner.close();const recovered=await MetadataVersions.open(f.path);try{assert.deepEqual(recovered.current('part.gcode'),old);assert.equal((await readdir(f.path)).length,1);}finally{await recovered.close();}}finally{p.sync=original;await owner.close();await f.close();}
});
test('actual SIGKILL during migration preserves both formats for deterministic recovery',async()=>{
 const f=await directory();try{const a=event('1','a.gcode'),b=event('2','b.gcode');await seed(f.path,[a,b]);const moduleUrl=new URL(import.meta.url.endsWith('.js')?'../src/moonraker/metadata-versions.js':'../src/moonraker/metadata-versions.ts',import.meta.url).href,code=`import {open} from 'node:fs/promises';import {MetadataVersions} from ${JSON.stringify(moduleUrl)};const probe=await open('/dev/null','r'),p=Object.getPrototypeOf(probe),original=p.sync;await probe.close();p.sync=async function(...args){await Reflect.apply(original,this,args);if((await this.stat()).isDirectory()){await new Promise(resolve=>process.stdout.write('migration-head-durable',resolve));process.kill(process.pid,'SIGKILL');}};await MetadataVersions.open(process.argv[1]);throw new Error('missing migration kill');`;
  const result=await new Promise<{signal:NodeJS.Signals|null;output:string}>((resolve,reject)=>{const child=spawn(process.execPath,['--input-type=module','-e',code,f.path],{stdio:['ignore','pipe','pipe'],timeout:10000});let output='',errors='';child.stdout.on('data',data=>output+=data);child.stderr.on('data',data=>errors+=data);child.on('error',reject);child.on('close',(exit,signal)=>{if(exit!==null)reject(new Error(errors));else resolve({signal,output});});});assert.equal(result.signal,'SIGKILL');assert.equal(result.output,'migration-head-durable');const before=await readdir(f.path);assert.equal(before.filter(name=>name.startsWith('.metadata-head-')).length,1);assert.equal(before.filter(name=>name.startsWith('mv-')).length,2);const owner=await MetadataVersions.open(f.path);try{assert.deepEqual(owner.current(a.filename),a);assert.deepEqual(owner.current(b.filename),b);assert.equal((await readdir(f.path)).length,2);assert.equal((await owner.invalidate(a.filename,signal)).sequence,'3');}finally{await owner.close();}
 }finally{await f.close();}
});
test('migration cleanup sync failure retains every durable new head for recovery',async()=>{
 const f=await directory(),p=await prototype(),original=p.sync;try{const a=event('1','a.gcode'),b=event('2','b.gcode');await seed(f.path,[a,b]);let calls=0;p.sync=function(...args:unknown[]){if(++calls===5)return Promise.reject(new Error('legacy receipt cleanup sync fault'));return Reflect.apply(original,this,args);};try{await assert.rejects(MetadataVersions.open(f.path),/cleanup sync fault/);}finally{p.sync=original;}const remaining=await readdir(f.path);assert.equal(remaining.filter(name=>name.startsWith('.metadata-head-')).length,2);assert.equal(remaining.filter(name=>name.startsWith('mv-')).length,0);assert.equal(remaining.filter(name=>name.endsWith('.gcode')).length,2);const owner=await MetadataVersions.open(f.path);try{assert.deepEqual(owner.current(a.filename),a);assert.deepEqual(owner.current(b.filename),b);assert.equal((await readdir(f.path)).length,2);}finally{await owner.close();}}finally{p.sync=original;await f.close();}
});
test('maximum historical filename capacity recovers without a whole-catalog rewrite',async()=>{
 const f=await directory();let owner:MetadataVersions|undefined;try{for(let offset=0;offset<4096;offset+=32)await Promise.all(Array.from({length:32},(_,i)=>{const value=event(String(offset+i+1),`part-${offset+i}.gcode`);return writeFile(join(f.path,headName(value.filename)),envelope(value),{mode:0o600});}));owner=await MetadataVersions.open(f.path,{maxFiles:4096});assert.equal(owner.status.files,4096);assert.equal(owner.status.sequence,'4096');const preserved=join(f.path,headName('part-1.gcode')),before=await readFile(preserved);const next=await owner.invalidate('part-0.gcode',signal);assert.equal(next.sequence,'4097');assert.deepEqual(await readFile(preserved),before);await assert.rejects(owner.invalidate('over-capacity.gcode',signal),/capacity/);assert.equal(owner.status.faulted,false);assert.equal((await readdir(f.path)).length,4096);await owner.close();owner=await MetadataVersions.open(f.path,{maxFiles:4096});assert.equal(owner.status.sequence,'4097');assert.deepEqual(owner.current('part-0.gcode'),next);}finally{await owner?.close();await f.close();}
});
