import {MetadataMonitor} from '../src/moonraker/metadata-watch.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,symlink,rename,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {setTimeout as delay} from 'node:timers/promises';
import {MetadataFiles,registerFileMetascan} from '../src/moonraker/metadata-files.ts';
import {MetadataLifecycle} from '../src/moonraker/metadata-lifecycle.ts';
import {MetadataScanIntents} from '../src/moonraker/metadata-intents.ts';
import {MetadataSnapshots} from '../src/moonraker/metadata-snapshots.ts';
import {MetadataVersions} from '../src/moonraker/metadata-versions.ts';
import {ThumbnailStorage} from '../src/moonraker/thumbnail-storage.ts';
import {MetadataExtractor} from '../src/moonraker/metadata-extractor.ts';
import {ThumbnailProcessor} from '../src/moonraker/thumbnail-process.ts';
import {FileMetadataStore,registerFileMetadata} from '../src/moonraker/file-metadata.ts';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import {ApiError} from '../src/moonraker/rpc.ts';
const signal=new AbortController().signal;
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'metadata-files-')),root=join(dir,'gcodes');await mkdir(root);await mkdir(join(root,'层'));await writeFile(join(root,'层/part.gcode'),'; generated by PrusaSlicer 2.9.0 on 2026-09-21 at 12:00:00\n; layer_height = 0.2\nG1 X1\n');
 const extractor=await MetadataExtractor.open(),processor=await ThumbnailProcessor.open(),images=await ThumbnailStorage.open(join(dir,'images')),intents=await MetadataScanIntents.open(join(dir,'intents')),snapshots=await MetadataSnapshots.open(join(dir,'snapshots')),versions=await MetadataVersions.open(join(dir,'versions')),cache=new FileMetadataStore(),owner=new MetadataLifecycle({extractor,processor,images,intents,snapshots,versions,cache}),files=await MetadataFiles.open({root,lifecycle:owner,maxPending:1});
 return {dir,root,extractor,processor,images,intents,snapshots,versions,cache,owner,files,close:async()=>{await files.close();await owner.close();await extractor.close();await processor.close();await images.close();await intents.close();await snapshots.close();await versions.close();await rm(dir,{recursive:true,force:true});}};
}
test('configured HTTP and JSON-RPC metascan authenticate and publish durable metadata',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;const release:(()=>void)[]=[];
 try{const config=join(f.dir,'moonraker.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0\n');server=await ConfiguredMoonraker.load(config,{authorize(_m,_p,{request}){if(request.headers['x-api-key']!=='test')throw new ApiError(401,'Unauthorized');},information:{connected:false,state:'disconnected',components:['application'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]}});release.push(registerFileMetascan(server.endpoints,f.files),registerFileMetadata(server.endpoints,f.cache));const address=await server.start(),base=`http://127.0.0.1:${address.port}`,body=JSON.stringify({filename:'层/part.gcode'}),headers={'x-api-key':'test','content-type':'application/json'};
  assert.equal((await fetch(base+'/server/files/metascan',{method:'POST',body})).status,401);assert.equal(f.intents.unresolved().length,0);
  const scanned=await fetch(base+'/server/files/metascan',{method:'POST',headers,body});assert.equal(scanned.status,200);const value:any=await scanned.json();assert.equal(value.result.filename,'层/part.gcode');assert.equal(value.result.layer_height,.2);assert.equal(f.versions.current('层/part.gcode')?.state,'selected');
  const read=await fetch(base+'/server/files/metadata?filename='+encodeURIComponent('层/part.gcode'),{headers});assert.deepEqual((await read.json() as any).result,value.result);
  const rpc=await fetch(base+'/server/jsonrpc',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'server.files.metascan',params:{filename:'层/part.gcode'}})});assert.equal((await rpc.json() as any).result.layer_height,.2);assert.equal(await f.owner.retireSuperseded(signal),1);
  assert.equal((await fetch(base+'/server/files/metascan',{headers})).status,405);
  assert.equal((await fetch(base+'/server/files/metascan',{method:'POST',headers,body:'{}'})).status,400);
 }finally{await server?.close();for(const detach of release)detach();await f.close();}
});
test('anchored opens reject traversal, symlinks and unsupported UFP without writing intents',async()=>{
 const f=await fixture();try{
  await symlink(join(f.root,'层'),join(f.root,'link'));await symlink(join(f.root,'层/part.gcode'),join(f.root,'file.gcode'));await mkdir(join(f.root,'folder.gcode'));
  const before=(await readdir('/proc/self/fd')).length;
  for(const [name,code] of [['../part.gcode',400],['/part.gcode',400],['层//part.gcode',400],['.git/part.gcode',403],['part.ufp',501],['part.GCODE',400],['missing.gcode',404],['link/part.gcode',404],['file.gcode',404],['folder.gcode',400]] as const)await assert.rejects(f.files.rescan(name,signal),(e:any)=>e.status===code);
  assert.equal(f.intents.unresolved().length,0);assert.equal(f.files.status.pending,0);assert.equal((await readdir('/proc/self/fd')).length,before);
  assert.equal((await f.files.rescan('层/part.gcode',signal)).layer_height,.2);
 }finally{await f.close();}
});
test('capacity includes opening and rejected requests leave active cache tickets intact',async()=>{
 const f=await fixture();try{const first=f.files.rescan('层/part.gcode',signal);assert.equal(f.files.status.pending,1);await assert.rejects(f.files.rescan('层/part.gcode',signal),/queue is full/);assert.equal((await first).layer_height,.2);const cancelled=new AbortController();cancelled.abort(new Error('cancelled'));await assert.rejects(f.files.rescan('层/part.gcode',cancelled.signal),/cancelled/);assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);}finally{await f.close();}
});
test('source replacement after opening cannot select metadata from the detached old file',async()=>{
 const f=await fixture();try{const original=f.versions.select.bind(f.versions);f.versions.select=async(...args)=>{const result=await original(...args);await rename(join(f.root,'层/part.gcode'),join(f.root,'old.gcode'));await writeFile(join(f.root,'层/part.gcode'),'G1 X999\n');return result;};await assert.rejects(f.files.rescan('层/part.gcode',signal));assert.equal(f.versions.current('层/part.gcode')?.state,'invalidated');assert.equal(f.cache.peek('层/part.gcode'),undefined);}finally{await f.close();}
});
test('close cancels active work and drains descriptor admission before returning',async()=>{
 const f=await fixture();try{const original=f.intents.begin.bind(f.intents),entered=Promise.withResolvers<void>();f.intents.begin=async(...args)=>{entered.resolve();await delay(10);return original(...args);};const pending=f.files.rescan('层/part.gcode',signal),rejected=assert.rejects(pending);await entered.promise;await f.files.close();await rejected;assert.equal(f.files.status.pending,0);assert.equal(f.owner.status.closed,false);await assert.rejects(f.files.rescan('层/part.gcode',signal),/closed/);assert.equal(f.cache.peek('层/part.gcode'),undefined);}finally{await f.close();}
});
test('selected startup recovery restores valid files and refuses changed or deleted sources',async()=>{
 const f=await fixture();try{
  await writeFile(join(f.root,'changed.gcode'),'G1 X1\n');await writeFile(join(f.root,'deleted.gcode'),'G1 X2\n');
  for(const name of ['层/part.gcode','changed.gcode','deleted.gcode'])await f.files.rescan(name,signal);
  await writeFile(join(f.root,'changed.gcode'),'G1 X999\n');await rm(join(f.root,'deleted.gcode'));f.cache.clear();
  assert.deepEqual(await f.files.restoreSelected(signal),{restored:1,unavailable:2});assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);assert.equal(f.cache.peek('changed.gcode'),undefined);assert.equal(f.cache.peek('deleted.gcode'),undefined);
  assert.equal(await f.files.recover('unknown.gcode',signal),false);assert.equal(f.versions.current('changed.gcode')?.state,'selected');
 }finally{await f.close();}
});
test('startup recovery propagates snapshot corruption instead of treating it as a source change',async()=>{
 const f=await fixture();try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();const read=f.snapshots.read.bind(f.snapshots);f.snapshots.read=async()=>{throw new Error('corrupt snapshot');};await assert.rejects(f.files.restoreSelected(signal),/corrupt snapshot/);assert.equal(f.cache.peek('层/part.gcode'),undefined);f.snapshots.read=read;assert.deepEqual(await f.files.restoreSelected(signal),{restored:1,unavailable:0});}finally{await f.close();}
});
test('startup recovery obeys admission and cancellation before any cache mutation',async()=>{
 const f=await fixture();try{await f.files.rescan('层/part.gcode',signal);const cancelled=new AbortController();cancelled.abort(new Error('cancel startup'));await assert.rejects(f.files.restoreSelected(cancelled.signal),/cancel startup/);assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);const recovery=f.files.restoreSelected(signal);await assert.rejects(f.files.rescan('层/part.gcode',signal),/queue is full/);assert.deepEqual(await recovery,{restored:1,unavailable:0});await f.files.close();await assert.rejects(f.files.restoreSelected(signal),/closed/);}finally{await f.close();}
});
async function configured(f:Awaited<ReturnType<typeof fixture>>,discoverMetadataOnStart=false,metadataMonitor?:import('../src/moonraker/metadata-watch.ts').MetadataMonitorOptions){const config=join(f.dir,'owned.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0\n');return ConfiguredMoonraker.load(config,{metadataFiles:f.files,discoverMetadataOnStart,metadataMonitor,authorize(){},information:{connected:false,state:'disconnected',components:['application'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]}});}
test('configured owner restores before listening and closes only its file admission component',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;
 try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();server=await configured(f);assert.equal(server.metadataRecovery,null);assert.equal(server.status.phase,'new');await assert.rejects(configured(f),/already have/);
  const opening=server.start();assert.equal(server.start(),opening);const address=await opening;assert.deepEqual(server.metadataRecovery,{restored:1,unavailable:0});const response=await fetch(`http://127.0.0.1:${address.port}/server/files/metadata?filename=${encodeURIComponent('层/part.gcode')}`);assert.equal(response.status,200);assert.equal((await response.json() as any).result.layer_height,.2);assert.equal(server.rpc.has('server.files.metascan'),true);assert.equal(server.rpc.has('server.files.thumbnails'),true);
  await server.close();assert.equal(f.files.status.closed,true);assert.equal(f.owner.status.closed,false);assert.equal(f.extractor.closed,false);assert.equal(server.rpc.has('server.files.metadata'),false);assert.equal(server.rpc.has('server.files.metascan'),false);
 }finally{await server?.close();await f.close();}
});
test('configured startup fails closed when metadata recovery is corrupt',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();f.snapshots.read=async()=>{throw new Error('broken metadata');};server=await configured(f);await assert.rejects(server.start(),/broken metadata/);assert.equal(server.metadataRecovery,null);assert.equal(server.status.phase,'closed');assert.equal(f.files.status.closed,true);assert.equal(server.rpc.has('server.files.metadata'),false);assert.equal(f.owner.status.closed,false);}finally{await server?.close();await f.close();}
});
test('closing configured server during recovery drains work without starting a listener',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;const entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>();
 try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();const read=f.snapshots.read.bind(f.snapshots);f.snapshots.read=async(...args)=>{entered.resolve();await resume.promise;return read(...args);};server=await configured(f);const opening=server.start(),rejected=assert.rejects(opening);await entered.promise;let closed=false;const closing=server.close().then(()=>{closed=true;});await delay(10);assert.equal(closed,false);resume.resolve();await rejected;await closing;assert.equal(server.status.phase,'closed');assert.equal(f.files.status.pending,0);assert.equal(f.cache.peek('层/part.gcode'),undefined);}finally{resume.resolve();await server?.close();await f.close();}
});
test('configured metadata owns the full scan, thumbnail query and authenticated binary download chain',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;
 try{
  const {default:sharp}=await import('sharp'),png=await sharp({create:{width:64,height:32,channels:3,background:'#3478ab'}}).png().toBuffer(),b64=png.toString('base64');await writeFile(join(f.root,'层/part.gcode'),`; thumbnail begin 64 32 ${b64.length}\n; ${b64}\n; thumbnail end\nG1 X1\n`);
  const config=join(f.dir,'images.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0\n');const calls:{method:string;filename?:unknown}[]=[];
  const options={metadataFiles:f.files,authorize(method:string,params:any,{request}:any){calls.push({method,filename:params.filename});if(request.headers['x-api-key']!=='test')throw new ApiError(401,'Unauthorized');if(params.filename&&request.headers['x-deny-file'])throw new ApiError(403,'Forbidden');},information:{connected:false,state:'disconnected' as const,components:['application'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]}};
  await assert.rejects(ConfiguredMoonraker.load(config,{...options,thumbnails:f.files.downloads}),/cannot be overridden/);assert.equal(f.files.status.closed,false);
  server=await ConfiguredMoonraker.load(config,options);const address=await server.start(),base=`http://127.0.0.1:${address.port}`,headers={'x-api-key':'test','content-type':'application/json'};
  const scan=await fetch(base+'/server/files/metascan',{method:'POST',headers,body:JSON.stringify({filename:'层/part.gcode'})});assert.equal(scan.status,200);
  const thumbs:any=await (await fetch(base+'/server/files/thumbnails?filename='+encodeURIComponent('层/part.gcode'),{headers})).json();assert.equal(thumbs.result.length,2);const path='/server/files/gcodes/'+encodeURI(thumbs.result[1].thumbnail_path);
  assert.equal((await fetch(base+path)).status,401);assert.equal((await fetch(base+path,{headers:{...headers,'x-deny-file':'1'}})).status,403);
  const response=await fetch(base+path,{headers});assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await response.arrayBuffer()),png);assert.ok(calls.some(call=>call.method==='server.files.download'&&call.filename==='层/part.gcode'));
  const head=await fetch(base+path,{method:'HEAD',headers});assert.equal(head.status,200);assert.equal(Number(head.headers.get('content-length')),png.length);assert.equal((await head.arrayBuffer()).byteLength,0);
  const cached=await fetch(base+path,{headers:{...headers,'if-none-match':response.headers.get('etag')!}});assert.equal(cached.status,304);
  await f.owner.invalidate('层/part.gcode',signal);assert.equal((await fetch(base+path,{headers})).status,404);
 }finally{await server?.close();await f.close();}
});
test('bounded discovery scans new nested files, restores unchanged files and reports unsupported UFP',async()=>{
 const f=await fixture();try{
  await writeFile(join(f.root,'new.nc'),'G1 X9\n');await writeFile(join(f.root,'unsupported.ufp'),'not a gcode');await writeFile(join(f.root,'ignored.txt'),'ignore');await symlink(join(f.root,'层'),join(f.root,'linked'));await mkdir(join(f.root,'.git'));await writeFile(join(f.root,'.git/hidden.gcode'),'G1 X999\n');
  const before=(await readdir('/proc/self/fd')).length;assert.deepEqual(await f.files.scanDiscovered(signal),{restored:0,scanned:2,unavailable:0,unsupported:1});assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);assert.equal(f.cache.peek('.git/hidden.gcode'),undefined);assert.equal(f.cache.peek('linked/part.gcode'),undefined);assert.equal((await readdir('/proc/self/fd')).length,before);
  assert.deepEqual(await f.files.scanDiscovered(signal),{restored:2,scanned:0,unavailable:0,unsupported:1});assert.equal(f.intents.unresolved().length,2);await writeFile(join(f.root,'new.nc'),'G1 X12345\n');assert.deepEqual(await f.files.scanDiscovered(signal),{restored:1,scanned:1,unavailable:0,unsupported:1});
 }finally{await f.close();}
});
test('discovery limits and pre-cancellation fail before beginning any scan and close directory handles',async()=>{
 const f=await fixture();try{await writeFile(join(f.root,'second.gcode'),'G1 X2\n');const before=(await readdir('/proc/self/fd')).length;for(const limits of [{maxEntries:1},{maxFiles:1},{maxBytes:1}])await assert.rejects(f.files.scanDiscovered(signal,limits),(e:any)=>e.status===413);assert.equal(f.intents.unresolved().length,0);assert.equal((await readdir('/proc/self/fd')).length,before);const controller=new AbortController();controller.abort(new Error('stop discovery'));await assert.rejects(f.files.scanDiscovered(controller.signal),/stop discovery/);assert.equal(f.cache.status.entries,0);}finally{await f.close();}
});
test('configured discovery scans previously unknown G-code before opening HTTP',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;try{server=await configured(f,true);const address=await server.start();assert.deepEqual(server.metadataRecovery,{restored:0,unavailable:0});assert.deepEqual(server.metadataDiscovery,{restored:0,scanned:1,unavailable:0,unsupported:0});const reply=await fetch(`http://127.0.0.1:${address.port}/server/files/metadata?filename=${encodeURIComponent('层/part.gcode')}`);assert.equal(reply.status,200);assert.equal((await reply.json() as any).result.layer_height,.2);}finally{await server?.close();await f.close();}
});
test('file refresh revokes deleted metadata durably, retires artifacts and supports recreation',async()=>{
 const f=await fixture();try{
  await f.files.rescan('层/part.gcode',signal);const previous=f.intents.unresolved()[0];await rm(join(f.root,'层/part.gcode'));
  assert.deepEqual(await f.files.refresh('层/part.gcode',signal),{state:'unavailable'});assert.equal(f.cache.peek('层/part.gcode'),undefined);assert.equal(f.versions.current('层/part.gcode')?.state,'invalidated');assert.equal(f.intents.unresolved().length,0);assert.equal((await f.snapshots.listIds(signal)).includes('meta-'+previous.id.slice(5)),false);assert.equal(await f.files.recover('层/part.gcode',signal),false);
  await writeFile(join(f.root,'层/part.gcode'),'G1 X123\n');const result=await f.files.refresh('层/part.gcode',signal);assert.equal(result.state,'updated');assert.equal(f.versions.current('层/part.gcode')?.state,'selected');assert.equal(f.intents.unresolved().length,1);
 }finally{await f.close();}
});
test('repeated refresh reclaims only that filename and retains no superseded generations',async()=>{
 const f=await fixture();try{
  await writeFile(join(f.root,'other.gcode'),'G1 X1\n');await f.files.rescan('other.gcode',signal);await f.files.rescan('other.gcode',signal);const others=f.intents.unresolved().filter(value=>value.filename==='other.gcode');
  for(let i=0;i<8;i++){await writeFile(join(f.root,'层/part.gcode'),`G1 X${i}\n`);assert.equal((await f.files.refresh('层/part.gcode',signal)).state,'updated');assert.equal(f.intents.unresolved().filter(value=>value.filename==='层/part.gcode').length,1);}
  assert.deepEqual(f.intents.unresolved().filter(value=>value.filename==='other.gcode'),others);assert.equal((await f.snapshots.listIds(signal)).length,3);
 }finally{await f.close();}
});
test('refresh errors and cancellation cannot restore stale metadata or acknowledge uncertain cleanup',async()=>{
 const f=await fixture();try{
  await f.files.rescan('层/part.gcode',signal);const cancelled=new AbortController();cancelled.abort(new Error('cancel refresh'));await assert.rejects(f.files.refresh('层/part.gcode',cancelled.signal),/cancel refresh/);assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);
  const remove=f.snapshots.remove.bind(f.snapshots);f.snapshots.remove=async()=>{throw new Error('snapshot cleanup failed');};await assert.rejects(f.files.refresh('层/part.gcode',signal),/snapshot cleanup failed/);assert.equal(f.cache.peek('层/part.gcode'),undefined);assert.equal(f.versions.current('层/part.gcode')?.state,'invalidated');assert.equal(f.intents.unresolved().length,1);f.snapshots.remove=remove;
  assert.equal((await f.files.refresh('层/part.gcode',signal)).state,'updated');assert.equal(f.intents.unresolved().length,1);
 }finally{await f.close();}
});
test('directory reconciliation invalidates deleted durable names and recovers interrupted pending scans',async()=>{
 const f=await fixture();try{
  await f.files.rescan('层/part.gcode',signal);await writeFile(join(f.root,'pending.gcode'),'G1 X3\n');const pending=await f.intents.begin('pending.gcode',signal);await f.versions.begin(pending,signal);await rm(join(f.root,'层/part.gcode'));
  assert.deepEqual(await f.files.scanDiscovered(signal),{restored:0,scanned:1,unavailable:1,unsupported:0});assert.equal(f.versions.current('层/part.gcode')?.state,'invalidated');assert.equal(f.cache.peek('层/part.gcode'),undefined);assert.equal(f.versions.current('pending.gcode')?.state,'selected');assert.equal(f.intents.unresolved().length,1);assert.notEqual(f.intents.unresolved()[0].id,pending.id);
  assert.deepEqual(await f.files.scanDiscovered(signal),{restored:1,scanned:0,unavailable:0,unsupported:0});assert.equal((await f.snapshots.listIds(signal)).length,1);
 }finally{await f.close();}
});
test('reconciliation finishes proven retirement but preserves unknown unversioned intents',async()=>{
 const f=await fixture();try{
  await f.files.rescan('层/part.gcode',signal);await f.owner.invalidate('层/part.gcode',signal);await rm(join(f.root,'层/part.gcode'));const unknown=await f.intents.begin('unknown.gcode',signal);
  assert.deepEqual(await f.files.scanDiscovered(signal),{restored:0,scanned:0,unavailable:0,unsupported:0});assert.deepEqual(f.intents.unresolved(),[unknown]);assert.deepEqual(await f.snapshots.listIds(signal),[]);
 }finally{await f.close();}
});
test('reconciliation capacity includes durable missing names before any retirement or new scan',async()=>{
 const f=await fixture();try{
  await f.files.rescan('层/part.gcode',signal);const old=f.intents.unresolved()[0];await rm(join(f.root,'层/part.gcode'));await writeFile(join(f.root,'new.gcode'),'G1 X1\n');
  await assert.rejects(f.files.scanDiscovered(signal,{maxFiles:1}),(e:any)=>e.status===413);assert.deepEqual(f.intents.unresolved(),[old]);assert.equal(f.versions.current('层/part.gcode')?.state,'selected');assert.equal(f.versions.current('new.gcode'),undefined);
  assert.deepEqual(await f.files.scanDiscovered(signal,{maxFiles:2}),{restored:0,scanned:1,unavailable:1,unsupported:0});
 }finally{await f.close();}
});
async function eventually(check:()=>boolean){for(let i=0;i<5000;i++){if(check())return;await delay(1);}assert.equal(check(),true);}
test('native directory events update nested metadata, discover new directories and reconcile deletions',async()=>{
 const f=await fixture(),monitor=new MetadataMonitor(f.files,{debounceMs:5,intervalMs:60000});try{
  await monitor.start();assert.equal(monitor.status.phase,'running');await writeFile(join(f.root,'层/part.gcode'),'G1 X98765\n');await eventually(()=>f.cache.peek('层/part.gcode')?.size===10);
  await mkdir(join(f.root,'new'));await writeFile(join(f.root,'new/created.gcode'),'G1 X1\n');await eventually(()=>!!f.cache.peek('new/created.gcode'));await rm(join(f.root,'new/created.gcode'));await eventually(()=>f.versions.current('new/created.gcode')?.state==='invalidated');assert.equal(f.cache.peek('new/created.gcode'),undefined);assert.equal(monitor.status.phase,'running');await rename(join(f.root,'层'),join(f.root,'renamed'));await eventually(()=>!!f.cache.peek('renamed/part.gcode')&&f.versions.current('层/part.gcode')?.state==='invalidated');assert.equal(monitor.status.phase,'running');
 }finally{await monitor.close();await f.close();}
});
test('monitor bounds directory watches and reports capacity failure without leaving its observer owned',async()=>{
 const f=await fixture(),monitor=new MetadataMonitor(f.files,{maxDirectories:1});try{await assert.rejects(monitor.start(),/watch capacity/);assert.equal(monitor.status.phase,'faulted');const replacement=new MetadataMonitor(f.files);try{await replacement.start();assert.equal(replacement.status.phase,'running');}finally{await replacement.close();}}finally{await monitor.close();await f.close();}
});
test('monitor coalesces changes during active reconciliation and close drains it',async()=>{
 const f=await fixture(),monitor=new MetadataMonitor(f.files,{debounceMs:5,intervalMs:60000});const resume=Promise.withResolvers<void>();try{
  await monitor.start();const read=f.snapshots.read.bind(f.snapshots),entered=Promise.withResolvers<void>();let active=0,maxActive=0;f.snapshots.read=async(...args)=>{active++;maxActive=Math.max(active,maxActive);entered.resolve();try{await resume.promise;return await read(...args);}finally{active--;}};
  await writeFile(join(f.root,'trigger.txt'),'1');await entered.promise;for(let i=0;i<20;i++)await writeFile(join(f.root,'trigger.txt'),String(i));assert.equal(maxActive,1);let closed=false;const closing=monitor.close().then(()=>{closed=true;});await delay(10);assert.equal(closed,false);resume.resolve();await closing;assert.equal(monitor.status.phase,'closed');assert.equal(monitor.status.active,false);assert.equal(f.files.status.closed,false);
 }finally{resume.resolve();await monitor.close();await f.close();}
});
test('periodic reconciliation covers missing event delivery',async()=>{
 const f=await fixture();f.files.observe=()=>Object.assign(()=>{},{healthy(){},fault(){}});const monitor=new MetadataMonitor(f.files,{debounceMs:1,intervalMs:20});try{await monitor.start();await writeFile(join(f.root,'层/part.gcode'),'G1 X76543\n');await eventually(()=>f.cache.peek('层/part.gcode')?.size===10);assert.equal(monitor.status.phase,'running');assert.ok(monitor.status.passes>=2);}finally{await monitor.close();await f.close();}
});
test('configured monitor starts before listening and stops with its server',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;try{server=await configured(f,false,{debounceMs:5,intervalMs:60000});await server.start();assert.equal(server.metadataMonitor?.phase,'running');assert.ok(f.cache.peek('层/part.gcode'));await writeFile(join(f.root,'层/part.gcode'),'G1 X54321\n');await eventually(()=>f.cache.peek('层/part.gcode')?.size===10);await server.close();assert.equal(server.metadataMonitor?.phase,'closed');assert.equal(server.metadataMonitor?.active,false);assert.equal(f.files.status.closed,true);}finally{await server?.close();await f.close();}
});
test('monitor retries a transient admission conflict without overlapping reconciliation',async()=>{
 const f=await fixture(),original=f.files.scanDiscovered.bind(f.files);let calls=0;f.files.scanDiscovered=async(...args)=>{if(++calls===1)throw new ApiError(503,'Metadata file queue is full');return original(...args);};const monitor=new MetadataMonitor(f.files);try{await monitor.start();assert.equal(calls,2);assert.equal(monitor.status.phase,'running');assert.equal(monitor.status.watchedDirectories,2);}finally{await monitor.close();assert.equal(f.files.watchedDirectories,0);await f.close();}
});
test('background monitoring failure marks server health and blocks metadata and image reads',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;try{
  const {default:sharp}=await import('sharp'),png=await sharp({create:{width:32,height:32,channels:3,background:'blue'}}).png().toBuffer(),b64=png.toString('base64');await writeFile(join(f.root,'层/part.gcode'),`; thumbnail begin 32 32 ${b64.length}\n; ${b64}\n; thumbnail end\nG1 X1\n`);
  server=await configured(f,false,{debounceMs:5,intervalMs:60000});const address=await server.start(),base=`http://127.0.0.1:${address.port}`,metadataPath='/server/files/metadata?filename='+encodeURIComponent('层/part.gcode'),thumbsPath='/server/files/thumbnails?filename='+encodeURIComponent('层/part.gcode');
  const thumbs:any=await(await fetch(base+thumbsPath)).json(),imagePath='/server/files/gcodes/'+encodeURI(thumbs.result[0].thumbnail_path);assert.equal((await fetch(base+imagePath)).status,200);
  const pending=await f.files.downloads.resolve(imagePath,{transport:'http',signal,authorize(){}});f.files.scanDiscovered=async()=>{throw new Error('injected corrupt snapshot');};await writeFile(join(f.root,'trigger.txt'),'event');await eventually(()=>server!.metadataMonitor?.phase==='faulted');
  for(const path of [metadataPath,thumbsPath,imagePath])assert.equal((await fetch(base+path)).status,503);assert.equal((await fetch(base+imagePath,{method:'HEAD'})).status,503);await assert.rejects(pending.read(),(e:any)=>e.status===503);
  const info:any=await(await fetch(base+'/server/info')).json();assert.ok(info.result.failed_components.includes('metadata_monitor'));assert.ok(info.result.warnings.some((value:string)=>value.includes('File metadata monitoring failed')));assert.equal(f.files.watchedDirectories,0);
 }finally{await server?.close();await f.close();}
});
test('only the current observer can enable reads after a successful reconciliation',async()=>{
 const f=await fixture();try{await f.files.rescan('层/part.gcode',signal);const first=f.files.observe(()=>{},()=>{});assert.throws(()=>f.files.metadata('层/part.gcode'),(e:any)=>e.status===503);first.healthy();assert.equal(f.files.metadata('层/part.gcode').layer_height,.2);first();assert.throws(()=>f.files.thumbnails('层/part.gcode'),(e:any)=>e.status===503);const next=f.files.observe(()=>{},()=>{});try{first.healthy();assert.throws(()=>f.files.metadata('层/part.gcode'),(e:any)=>e.status===503);next.healthy();first.fault();assert.equal(f.files.metadata('层/part.gcode').layer_height,.2);}finally{next();}}finally{await f.close();}
});
test('configured history captures real selected file metadata and refuses a replacement scan',async()=>{
 const f=await fixture(),{DatabaseStore}=await import('../src/moonraker/database.ts'),{HistoryRepository}=await import('../src/moonraker/history-repository.ts'),{createServer}=await import('node:net'),{once}=await import('node:events');
 const db=await DatabaseStore.open({path:join(f.dir,'history.db')}),history=await HistoryRepository.open(db);let server:ConfiguredMoonraker|undefined,peer:import('node:net').Socket|undefined;
 const wire=(value:unknown)=>JSON.stringify(value)+'\x03',socketPath=join(f.dir,'klippy.sock');
 const backend=createServer(socket=>{peer=socket;let tail='';socket.on('error',()=>{});socket.on('data',chunk=>{tail+=chunk.toString();for(let end;(end=tail.indexOf('\x03'))>=0;){const request=JSON.parse(tail.slice(0,end));tail=tail.slice(end+1);let result:unknown={};
  if(request.method==='info')result={state:'ready',state_message:'Ready'};
  if(request.method==='list_endpoints')result={endpoints:['info','list_endpoints','objects/query','objects/list','objects/subscribe','gcode/subscribe_output','register_remote_method']};
  if(request.method==='objects/list')result={objects:['virtual_sdcard','display_status','pause_resume','print_stats']};
  if(request.method==='objects/subscribe')result={eventtime:1,status:{webhooks:{state:'ready'},print_stats:{state:'standby',filename:'',total_duration:0}}};
  socket.write(wire({id:request.id,result}));
 }});});
 const wait=async(check:()=>boolean)=>{for(let i=0;i<1000;i++){if(check())return;await delay(2);}throw new Error('History event did not arrive');};
 try{
  await f.files.rescan('层/part.gcode',signal);backend.listen(socketPath);await once(backend,'listening');const config=join(f.dir,'history-files.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0');
  server=await ConfiguredMoonraker.load(config,{database:db,metadataFiles:f.files,history:{repository:history,fileExists:()=>true},information:{connected:false,state:'disconnected',components:[],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]},authorize(){}});
  const address=await server.start();await server.attachKlippy(socketPath);
  const readMetadata=async()=>{const response=await fetch('http://127.0.0.1:'+address.port+'/server/files/metadata?filename='+encodeURIComponent('层/part.gcode'));assert.equal(response.status,200);return (await response.json() as any).result;};
  const update=(state:string,eventtime:number)=>peer!.write(wire({method:'process_status_update',params:{eventtime,status:{print_stats:{state,filename:'层/part.gcode',total_duration:eventtime,print_duration:eventtime-1,filament_used:2.675}}}}));
  update('printing',2);await wait(()=>server!.jobState?.event==='started');await server.drainHistory();assert.equal((await history.get('1')).metadata.layer_height,.2);const firstMarker=await readMetadata();assert.equal(firstMarker.job_id,'000001');assert.equal(firstMarker.print_start_time,(await history.get('1')).start_time);assert.equal(f.files.metadata('层/part.gcode').job_id,undefined);
  await writeFile(join(f.root,'层/part.gcode'),'; generated by PrusaSlicer 2.9.0 on 2026-09-21 at 12:00:00\n; layer_height = 0.4\nG1 X9\n');await f.files.rescan('层/part.gcode',signal);assert.equal(f.files.metadata('层/part.gcode').layer_height,.4);assert.equal((await readMetadata()).job_id,undefined);
  update('complete',3);await wait(()=>server!.jobState?.event==='complete');await server.drainHistory();assert.equal((await history.get('1')).metadata.layer_height,.2);assert.equal((await history.get('1')).status,'completed');assert.equal(server.historyStatus?.metadataError,null);assert.equal((await readMetadata()).job_id,undefined);
  update('printing',4);await wait(()=>server!.jobState?.event==='started');await server.drainHistory();assert.equal((await readMetadata()).job_id,'000002');
 }finally{await server?.close();await db.close();peer?.destroy();await new Promise<void>(resolve=>backend.close(()=>resolve()));await f.close();}
});
