import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,open,rm} from 'node:fs/promises';
import {fstatSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {MetadataExtractor,scanMetadataFields} from '../src/moonraker/metadata-extractor.ts';
import {FileMetadataStore} from '../src/moonraker/file-metadata.ts';
async function fixture(text='; generated by PrusaSlicer 2.8 on 2026-01-01 at 12:34:56\n; layer_height = .2\n; first_layer_height = 150%\nG1 X1\n'){const directory=await mkdtemp(join(tmpdir(),'metadata-worker-')),path=join(directory,'file.gcode');await writeFile(path,text);return {path,close:()=>rm(directory,{recursive:true,force:true})};}
async function drained(extractor:MetadataExtractor){for(let i=0;i<400&&extractor.pendingRequests;i++)await delay(5);assert.equal(extractor.pendingRequests,0);}
test('metadata worker transfers and closes descriptors before delivering parsed fields',async()=>{
 const f=await fixture(),extractor=await MetadataExtractor.open();try{const source=await open(f.path,'r'),fd=source.fd;const promise=extractor.extract(source,new AbortController().signal);assert.equal(source.fd,-1);const result=await promise;assert.equal(result.fields.slicer,'PrusaSlicer');assert.equal(result.fields.first_layer_height,.3);assert.equal(typeof result.source.ino,'bigint');assert.deepEqual(result.objects,{hasObjects:false,hasM486Objects:false});assert.throws(()=>fstatSync(fd),/EBADF/);assert.equal(extractor.pendingRequests,0);}finally{await extractor.close();await f.close();}
});
test('cancelled requests retain admission capacity until source close acknowledgment',async()=>{
 const f=await fixture(),extractor=await MetadataExtractor.open({maxPending:1});try{const first=await open(f.path,'r'),second=await open(f.path,'r'),fd=first.fd,controller=new AbortController();try{const request=extractor.extract(first,controller.signal);controller.abort(new Error('cancel scan'));await assert.rejects(request,/cancel scan/);assert.equal(extractor.pendingRequests,1);await assert.rejects(extractor.extract(second,new AbortController().signal),/queue is full/);assert.ok(second.fd>=0);await drained(extractor);assert.throws(()=>fstatSync(fd),/EBADF/);assert.equal((await extractor.extract(second,new AbortController().signal)).fields.slicer,'PrusaSlicer');}finally{await second.close();}}finally{await extractor.close();await f.close();}
});
test('pre-abort, invalid configuration and rejection do not transfer caller handles',async()=>{
 const f=await fixture(),extractor=await MetadataExtractor.open();try{const source=await open(f.path,'r');try{await assert.rejects(extractor.extract(source,AbortSignal.abort(new Error('preabort'))),/preabort/);assert.ok(source.fd>=0);await extractor.close();await assert.rejects(extractor.extract(source,new AbortController().signal),/closed/);assert.ok(source.fd>=0);}finally{await source.close();}await assert.rejects(MetadataExtractor.open({maxPending:0}),/capacity/);}finally{await extractor.close();await f.close();}
});
test('worker file and output limits fail without leaking descriptors or poisoning later requests',async()=>{
 const f=await fixture();try{for(const options of [{maxFileBytes:1},{maxOutputBytes:1}]){const extractor=await MetadataExtractor.open(options);try{const source=await open(f.path,'r'),fd=source.fd;await assert.rejects(extractor.extract(source,new AbortController().signal),/limit|budget/i);assert.throws(()=>fstatSync(fd),/EBADF/);assert.equal(extractor.closed,false);}finally{await extractor.close();}}}finally{await f.close();}
});
test('timeout fences the instance and termination releases active and queued sources',async()=>{
 const f=await fixture('G1 Z.2 X1\n'.repeat(200000)),extractor=await MetadataExtractor.open({timeoutMs:1});try{const a=await open(f.path,'r'),b=await open(f.path,'r'),identity=fstatSync(a.fd,{bigint:true});const requests=[extractor.extract(a,new AbortController().signal),extractor.extract(b,new AbortController().signal)];assert.equal(a.fd,-1);assert.equal(b.fd,-1);const results=await Promise.allSettled(requests);assert.ok(results.every(r=>r.status==='rejected'));assert.equal(extractor.closed,true);await extractor.close();
 // Descriptor numbers can be reused by concurrent runtime I/O. Check that no
 // descriptor still owns this source inode, including transferred/queued ones.
 for(const name of readdirSync('/proc/self/fd')){let stat;try{stat=fstatSync(Number(name),{bigint:true});}catch(error){if((error as NodeJS.ErrnoException).code==='EBADF')continue;throw error;}assert.ok(stat.dev!==identity.dev||stat.ino!==identity.ino,'Metadata source remains open after worker termination');}}finally{await extractor.close();await f.close();}
});
test('close joins all transferred sources at full capacity before reporting cleanup',async()=>{
 const f=await fixture('G1 Z.2 X1\n'.repeat(200000)),extractor=await MetadataExtractor.open({maxPending:64}),sources=await Promise.all(Array.from({length:64},()=>open(f.path,'r')));
 try{
  const identity=fstatSync(sources[0].fd,{bigint:true}),requests=sources.map(source=>extractor.extract(source,new AbortController().signal));
  const settled=Promise.allSettled(requests);assert(sources.every(source=>source.fd===-1));const closing=extractor.close();assert.equal(extractor.close(),closing);
  assert.equal(extractor.pendingRequests,64,'Rejected jobs retain ownership until the worker acknowledges source closure');
  const results=await settled;assert(results.every(result=>result.status==='rejected'));
  await closing;assert.equal(extractor.pendingRequests,0);assert.equal(extractor.closed,true);
  for(const name of readdirSync('/proc/self/fd')){let stat;try{stat=fstatSync(Number(name),{bigint:true});}catch(error){if((error as NodeJS.ErrnoException).code==='EBADF')continue;throw error;}assert.ok(stat.dev!==identity.dev||stat.ino!==identity.ino,'Full-capacity metadata source remains open after cleanup');}
 }finally{await Promise.all(sources.map(source=>source.close()));await extractor.close();await f.close();}
});
test('cache tickets reject stale scans and failure does not invalidate a newer result',async()=>{
 const f=await fixture(),extractor=await MetadataExtractor.open(),store=new FileMetadataStore();try{const source=await open(f.path,'r');const old=scanMetadataFields(extractor,store,'file.gcode',source,new AbortController().signal),newer=store.begin('file.gcode');store.commit(newer,{size:777});assert.equal(await old,false);assert.equal(store.metadata('file.gcode').size,777);
  assert.equal(await scanMetadataFields(extractor,store,'file.gcode',await open(f.path,'r'),new AbortController().signal),true);assert.equal(store.metadata('file.gcode').slicer,'PrusaSlicer');
  const failedSource=await open(f.path,'r'),failed=scanMetadataFields(extractor,store,'file.gcode',failedSource,AbortSignal.abort(new Error('cancelled'))),ticket=store.begin('file.gcode');store.commit(ticket,{size:888});await assert.rejects(failed,/cancelled/);await failedSource.close();assert.equal(store.metadata('file.gcode').size,888);
 }finally{await extractor.close();await f.close();}
});
test('mutating a source throughout parsing rejects publication',async()=>{
 const f=await fixture('G1 Z.2 X1\n'.repeat(200000)),extractor=await MetadataExtractor.open();const writer=await open(f.path,'r+');let stop=false;const mutate=(async()=>{while(!stop){await writer.write(Buffer.from('G'),0,1,0);await delay(1);}})();try{await assert.rejects(extractor.extract(await open(f.path,'r'),new AbortController().signal),/changed/);}finally{stop=true;await mutate;await writer.close();await extractor.close();await f.close();}
});

test('verified byte windows match descriptor extraction and keep cancelled jobs bounded',async()=>{
 const f=await fixture(),extractor=await MetadataExtractor.open({maxPending:1});try{
  const source=await open(f.path,'r'),bytes=await source.readFile(),modified=Number((await source.stat({bigint:true})).mtimeNs)/1e9,window={head:bytes,tail:Buffer.alloc(0),size:bytes.length,modified};
  const expected=await extractor.extract(source,new AbortController().signal),actual=await extractor.extractWindows(window,new AbortController().signal);assert.deepEqual({...actual.fields,modified:expected.fields.modified},expected.fields);assert.deepEqual(actual.objects,expected.objects);assert.equal('source' in actual,false);
  await assert.rejects(extractor.extractWindows({...window,head:Buffer.alloc(0)},new AbortController().signal),/Invalid/);
  const abort=new AbortController(),pending=extractor.extractWindows(window,abort.signal);abort.abort(new Error('cancel window'));await assert.rejects(pending,/cancel window/);assert.equal(extractor.pendingRequests,1);await assert.rejects(extractor.extractWindows(window,new AbortController().signal),/queue is full/);await drained(extractor);assert.equal((await extractor.extractWindows(window,new AbortController().signal)).fields.first_layer_height,.3);
 }finally{await extractor.close();await f.close();}
});
