import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,symlink,rename,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {setTimeout as delay} from 'node:timers/promises';
import {MetadataFiles,registerFileMetascan} from '../src/moonraker/metadata-files.ts';
import {MetadataLifecycle} from '../src/moonraker/metadata-lifecycle.ts';
import {MetadataScanIntents} from '../src/moonraker/metadata-intents.ts';
import {MetadataSnapshots} from '../src/moonraker/metadata-snapshots.ts';
import {MetadataVersions} from '../src/moonraker/metadata-versions.ts';
import {ThumbnailStorage} from '../src/moonraker/thumbnail-storage.ts';
import {MetadataExtractor} from '../src/moonraker/metadata-extractor.ts';
import {ThumbnailProcessor} from '../src/moonraker/thumbnail-process.ts';
import {FileMetadataStore,registerFileMetadata} from '../src/moonraker/file-metadata.ts';
import {ConfiguredMoonraker} from '../src/moonraker/configured-server.ts';
import {ApiError} from '../src/moonraker/rpc.ts';
const signal=new AbortController().signal;
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'metadata-files-')),root=join(dir,'gcodes');await mkdir(root);await mkdir(join(root,'层'));await writeFile(join(root,'层/part.gcode'),'; generated by PrusaSlicer 2.9.0 on 2026-09-21 at 12:00:00\n; layer_height = 0.2\nG1 X1\n');
 const extractor=await MetadataExtractor.open(),processor=await ThumbnailProcessor.open(),images=await ThumbnailStorage.open(join(dir,'images')),intents=await MetadataScanIntents.open(join(dir,'intents')),snapshots=await MetadataSnapshots.open(join(dir,'snapshots')),versions=await MetadataVersions.open(join(dir,'versions')),cache=new FileMetadataStore(),owner=new MetadataLifecycle({extractor,processor,images,intents,snapshots,versions,cache}),files=await MetadataFiles.open({root,lifecycle:owner,maxPending:1});
 return {dir,root,extractor,processor,images,intents,snapshots,versions,cache,owner,files,close:async()=>{await files.close();await owner.close();await extractor.close();await processor.close();await images.close();await intents.close();await snapshots.close();await versions.close();await rm(dir,{recursive:true,force:true});}};
}
test('configured HTTP and JSON-RPC metascan authenticate and publish durable metadata',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;const release:(()=>void)[]=[];
 try{const config=join(f.dir,'moonraker.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0\n');server=await ConfiguredMoonraker.load(config,{authorize(_m,_p,{request}){if(request.headers['x-api-key']!=='test')throw new ApiError(401,'Unauthorized');},information:{connected:false,state:'disconnected',components:['application'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]}});release.push(registerFileMetascan(server.endpoints,f.files),registerFileMetadata(server.endpoints,f.cache));const address=await server.start(),base=`http://127.0.0.1:${address.port}`,body=JSON.stringify({filename:'层/part.gcode'}),headers={'x-api-key':'test','content-type':'application/json'};
  assert.equal((await fetch(base+'/server/files/metascan',{method:'POST',body})).status,401);assert.equal(f.intents.unresolved().length,0);
  const scanned=await fetch(base+'/server/files/metascan',{method:'POST',headers,body});assert.equal(scanned.status,200);const value:any=await scanned.json();assert.equal(value.result.filename,'层/part.gcode');assert.equal(value.result.layer_height,.2);assert.equal(f.versions.current('层/part.gcode')?.state,'selected');
  const read=await fetch(base+'/server/files/metadata?filename='+encodeURIComponent('层/part.gcode'),{headers});assert.deepEqual((await read.json() as any).result,value.result);
  const rpc=await fetch(base+'/server/jsonrpc',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'server.files.metascan',params:{filename:'层/part.gcode'}})});assert.equal((await rpc.json() as any).result.layer_height,.2);assert.equal(await f.owner.retireSuperseded(signal),1);
  assert.equal((await fetch(base+'/server/files/metascan',{headers})).status,405);
  assert.equal((await fetch(base+'/server/files/metascan',{method:'POST',headers,body:'{}'})).status,400);
 }finally{await server?.close();for(const detach of release)detach();await f.close();}
});
test('anchored opens reject traversal, symlinks and unsupported UFP without writing intents',async()=>{
 const f=await fixture();try{
  await symlink(join(f.root,'层'),join(f.root,'link'));await symlink(join(f.root,'层/part.gcode'),join(f.root,'file.gcode'));await mkdir(join(f.root,'folder.gcode'));
  const before=(await readdir('/proc/self/fd')).length;
  for(const [name,code] of [['../part.gcode',400],['/part.gcode',400],['层//part.gcode',400],['.git/part.gcode',403],['part.ufp',501],['part.GCODE',400],['missing.gcode',404],['link/part.gcode',404],['file.gcode',404],['folder.gcode',400]] as const)await assert.rejects(f.files.rescan(name,signal),(e:any)=>e.status===code);
  assert.equal(f.intents.unresolved().length,0);assert.equal(f.files.status.pending,0);assert.equal((await readdir('/proc/self/fd')).length,before);
  assert.equal((await f.files.rescan('层/part.gcode',signal)).layer_height,.2);
 }finally{await f.close();}
});
test('capacity includes opening and rejected requests leave active cache tickets intact',async()=>{
 const f=await fixture();try{const first=f.files.rescan('层/part.gcode',signal);assert.equal(f.files.status.pending,1);await assert.rejects(f.files.rescan('层/part.gcode',signal),/queue is full/);assert.equal((await first).layer_height,.2);const cancelled=new AbortController();cancelled.abort(new Error('cancelled'));await assert.rejects(f.files.rescan('层/part.gcode',cancelled.signal),/cancelled/);assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);}finally{await f.close();}
});
test('source replacement after opening cannot select metadata from the detached old file',async()=>{
 const f=await fixture();try{const original=f.versions.select.bind(f.versions);f.versions.select=async(...args)=>{const result=await original(...args);await rename(join(f.root,'层/part.gcode'),join(f.root,'old.gcode'));await writeFile(join(f.root,'层/part.gcode'),'G1 X999\n');return result;};await assert.rejects(f.files.rescan('层/part.gcode',signal));assert.equal(f.versions.current('层/part.gcode')?.state,'invalidated');assert.equal(f.cache.peek('层/part.gcode'),undefined);}finally{await f.close();}
});
test('close cancels active work and drains descriptor admission before returning',async()=>{
 const f=await fixture();try{const original=f.intents.begin.bind(f.intents),entered=Promise.withResolvers<void>();f.intents.begin=async(...args)=>{entered.resolve();await delay(10);return original(...args);};const pending=f.files.rescan('层/part.gcode',signal),rejected=assert.rejects(pending);await entered.promise;await f.files.close();await rejected;assert.equal(f.files.status.pending,0);assert.equal(f.owner.status.closed,false);await assert.rejects(f.files.rescan('层/part.gcode',signal),/closed/);assert.equal(f.cache.peek('层/part.gcode'),undefined);}finally{await f.close();}
});
test('selected startup recovery restores valid files and refuses changed or deleted sources',async()=>{
 const f=await fixture();try{
  await writeFile(join(f.root,'changed.gcode'),'G1 X1\n');await writeFile(join(f.root,'deleted.gcode'),'G1 X2\n');
  for(const name of ['层/part.gcode','changed.gcode','deleted.gcode'])await f.files.rescan(name,signal);
  await writeFile(join(f.root,'changed.gcode'),'G1 X999\n');await rm(join(f.root,'deleted.gcode'));f.cache.clear();
  assert.deepEqual(await f.files.restoreSelected(signal),{restored:1,unavailable:2});assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);assert.equal(f.cache.peek('changed.gcode'),undefined);assert.equal(f.cache.peek('deleted.gcode'),undefined);
  assert.equal(await f.files.recover('unknown.gcode',signal),false);assert.equal(f.versions.current('changed.gcode')?.state,'selected');
 }finally{await f.close();}
});
test('startup recovery propagates snapshot corruption instead of treating it as a source change',async()=>{
 const f=await fixture();try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();const read=f.snapshots.read.bind(f.snapshots);f.snapshots.read=async()=>{throw new Error('corrupt snapshot');};await assert.rejects(f.files.restoreSelected(signal),/corrupt snapshot/);assert.equal(f.cache.peek('层/part.gcode'),undefined);f.snapshots.read=read;assert.deepEqual(await f.files.restoreSelected(signal),{restored:1,unavailable:0});}finally{await f.close();}
});
test('startup recovery obeys admission and cancellation before any cache mutation',async()=>{
 const f=await fixture();try{await f.files.rescan('层/part.gcode',signal);const cancelled=new AbortController();cancelled.abort(new Error('cancel startup'));await assert.rejects(f.files.restoreSelected(cancelled.signal),/cancel startup/);assert.equal(f.cache.metadata('层/part.gcode').layer_height,.2);const recovery=f.files.restoreSelected(signal);await assert.rejects(f.files.rescan('层/part.gcode',signal),/queue is full/);assert.deepEqual(await recovery,{restored:1,unavailable:0});await f.files.close();await assert.rejects(f.files.restoreSelected(signal),/closed/);}finally{await f.close();}
});
async function configured(f:Awaited<ReturnType<typeof fixture>>){const config=join(f.dir,'owned.conf');await writeFile(config,'[server]\nhost=127.0.0.1\nport=0\n');return ConfiguredMoonraker.load(config,{metadataFiles:f.files,authorize(){},information:{connected:false,state:'disconnected',components:['application'],failedComponents:[],directories:[],warnings:[],version:'test',missingRequirements:[]}});}
test('configured owner restores before listening and closes only its file admission component',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;
 try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();server=await configured(f);assert.equal(server.metadataRecovery,null);assert.equal(server.status.phase,'new');await assert.rejects(configured(f),/already have/);
  const opening=server.start();assert.equal(server.start(),opening);const address=await opening;assert.deepEqual(server.metadataRecovery,{restored:1,unavailable:0});const response=await fetch(`http://127.0.0.1:${address.port}/server/files/metadata?filename=${encodeURIComponent('层/part.gcode')}`);assert.equal(response.status,200);assert.equal((await response.json() as any).result.layer_height,.2);assert.equal(server.rpc.has('server.files.metascan'),true);assert.equal(server.rpc.has('server.files.thumbnails'),true);
  await server.close();assert.equal(f.files.status.closed,true);assert.equal(f.owner.status.closed,false);assert.equal(f.extractor.closed,false);assert.equal(server.rpc.has('server.files.metadata'),false);assert.equal(server.rpc.has('server.files.metascan'),false);
 }finally{await server?.close();await f.close();}
});
test('configured startup fails closed when metadata recovery is corrupt',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();f.snapshots.read=async()=>{throw new Error('broken metadata');};server=await configured(f);await assert.rejects(server.start(),/broken metadata/);assert.equal(server.metadataRecovery,null);assert.equal(server.status.phase,'closed');assert.equal(f.files.status.closed,true);assert.equal(server.rpc.has('server.files.metadata'),false);assert.equal(f.owner.status.closed,false);}finally{await server?.close();await f.close();}
});
test('closing configured server during recovery drains work without starting a listener',async()=>{
 const f=await fixture();let server:ConfiguredMoonraker|undefined;const entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>();
 try{await f.files.rescan('层/part.gcode',signal);f.cache.clear();const read=f.snapshots.read.bind(f.snapshots);f.snapshots.read=async(...args)=>{entered.resolve();await resume.promise;return read(...args);};server=await configured(f);const opening=server.start(),rejected=assert.rejects(opening);await entered.promise;let closed=false;const closing=server.close().then(()=>{closed=true;});await delay(10);assert.equal(closed,false);resume.resolve();await rejected;await closing;assert.equal(server.status.phase,'closed');assert.equal(f.files.status.pending,0);assert.equal(f.cache.peek('层/part.gcode'),undefined);}finally{resume.resolve();await server?.close();await f.close();}
});
