import {MetadataScanIntents} from '../src/moonraker/metadata-intents.ts';
import {scanFileMetadataWithIntent,MetadataIntentScanError} from '../src/moonraker/metadata-intent-scan.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,open,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import sharp from 'sharp';
import {setTimeout as delay} from 'node:timers/promises';
async function until(check:()=>boolean){for(let i=0;i<2000&&!check();i++)await delay(1);assert.equal(check(),true,'scan did not reach expected state');}
import {MetadataExtractor} from '../src/moonraker/metadata-extractor.ts';
import {ThumbnailProcessor} from '../src/moonraker/thumbnail-process.ts';
import {ThumbnailStorage} from '../src/moonraker/thumbnail-storage.ts';
import {FileMetadataStore} from '../src/moonraker/file-metadata.ts';
import {scanFileMetadata} from '../src/moonraker/metadata-scan.ts';
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'metadata-scan-')),bytes=await sharp({create:{width:32,height:32,channels:3,background:'#321abc'}}).png().toBuffer(),base64=bytes.toString('base64');
 const data=`; generated by PrusaSlicer 2.9.0 on 2026-09-21 at 12:00:00\n; thumbnail begin 32 32 ${base64.length}\n; ${base64}\n; thumbnail end\nG1 X1 Z0.2 F600\n; layer_height = 0.2\n`;
 const path=join(dir,'part.gcode');await writeFile(path,data);
 const extractor=await MetadataExtractor.open(),processor=await ThumbnailProcessor.open(),storage=await ThumbnailStorage.open(join(dir,'thumbs')),cache=new FileMetadataStore();
 const options=async(filename='part.gcode')=>({extractor,processor,storage,cache,ticket:cache.begin(filename),source:await open(path,'r'),signal:new AbortController().signal,bundleId:ThumbnailStorage.newId(),validateSource:async(source:{dev:bigint;ino:bigint;mtimeNs:bigint;ctimeNs:bigint})=>{const handle=await open(path,'r');try{const current=await handle.stat({bigint:true});return current.dev===source.dev&&current.ino===source.ino&&current.mtimeNs===source.mtimeNs&&current.ctimeNs===source.ctimeNs;}finally{await handle.close();}}});
 return {bytes,data,path,extractor,processor,storage,cache,options,close:async()=>{await extractor.close();await processor.close();await storage.close();await rm(dir,{recursive:true,force:true});}};
}
test('one source extraction publishes fields and exact original thumbnail bytes together',async()=>{
 const f=await fixture();try{const options=await f.options(),result=await scanFileMetadata(options);assert.equal(result.committed,true);assert.equal(result.bundleId,options.bundleId);assert.equal(options.source.fd,-1);assert.equal(result.extraction?.fields.slicer,'PrusaSlicer');assert.equal('thumbnailData' in result.extraction!,false);assert.deepEqual((await f.storage.read(options.bundleId,0,options.signal)).bytes,f.bytes);assert.equal(f.cache.metadata('part.gcode').layer_height,.2);assert.equal(f.cache.thumbnails('part.gcode').length,1);}finally{await f.close();}
});
test('stale and pre-aborted scans close untransferred handles without touching newer metadata',async()=>{
 const f=await fixture();try{
  const stale=await f.options();f.cache.commit(f.cache.begin('part.gcode'),{size:999});assert.equal((await scanFileMetadata(stale)).committed,false);assert.equal(stale.source.fd,-1);assert.equal(f.cache.metadata('part.gcode').size,999);
  const aborted=await f.options();aborted.signal=AbortSignal.abort(new Error('cancel scan'));await assert.rejects(scanFileMetadata(aborted),/cancel scan/);assert.equal(aborted.source.fd,-1);assert.equal(f.cache.peek('part.gcode'),undefined);assert.equal(f.processor.status.closed,false);assert.equal(f.storage.status.storage.publishedFiles,0);
 }finally{await f.close();}
});
test('source revalidation rejects changed binding and ticket changes during validation cannot publish',async()=>{
 const f=await fixture();try{
  const changed=await f.options();changed.validateSource=async()=>false;await assert.rejects(scanFileMetadata(changed),(e:any)=>e.status===409);assert.equal(f.storage.status.storage.publishedFiles,0);assert.equal(f.cache.peek('part.gcode'),undefined);
  const stale=await f.options();stale.validateSource=async()=>{f.cache.commit(f.cache.begin('part.gcode'),{size:777});return true;};assert.equal((await scanFileMetadata(stale)).committed,false);assert.equal(f.cache.metadata('part.gcode').size,777);assert.equal(f.storage.status.storage.publishedFiles,0);
 }finally{await f.close();}
});
test('legacy Slic3r families suppress thumbnail extraction while other families retain it',async()=>{
 const f=await fixture();try{for(const header of ['; Slic3r 1.3.0 on today','; Slic3r Prusa Edition 1.42 on today']){await writeFile(f.path,header+'\n'+f.data.slice(f.data.indexOf('\n')+1));const result=await scanFileMetadata(await f.options());assert.equal(result.committed,true);assert.equal(result.bundleId,null);assert.deepEqual(f.cache.thumbnails('part.gcode'),[]);}assert.equal(f.storage.status.storage.publishedFiles,0);}finally{await f.close();}
});
test('failed extractor admission closes the source, bad images fail the current ticket only',async()=>{
 const f=await fixture();try{
  await writeFile(f.path,f.data.replace('; '+f.bytes.toString('base64'),'; '+Buffer.alloc(f.bytes.length).toString('base64')));await assert.rejects(scanFileMetadata(await f.options()));assert.equal(f.cache.peek('part.gcode'),undefined);assert.equal(f.storage.status.storage.publishedFiles,0);
  await f.extractor.close();const options=await f.options();await assert.rejects(scanFileMetadata(options),/closed/);assert.equal(options.source.fd,-1);
 }finally{await f.close();}
});
test('extractor thumbnail payload is opt-in and includes footer windows',async()=>{
 const f=await fixture();try{
  const without=await f.extractor.extract(await open(f.path,'r'),new AbortController().signal);assert.equal(without.thumbnailData,undefined);
  await writeFile(f.path,'G1 X1 F600\n'.repeat(200000)+f.data);const result=await scanFileMetadata(await f.options());assert.equal(result.committed,true);assert.ok(result.bundleId);assert.deepEqual((await f.storage.read(result.bundleId,0,new AbortController().signal)).bytes,f.bytes);
  await writeFile(f.path,'G1 X1 F600\n'.repeat(200000));const empty=await f.extractor.extract(await open(f.path,'r'),new AbortController().signal,true);assert.equal(empty.thumbnailData,'');await f.processor.close();assert.equal((await scanFileMetadata(await f.options())).committed,true);
 }finally{await f.close();}
});

test('cancelling an active image scan fences the process, releases resources and permits image-free scans',async()=>{
 const f=await fixture();try{
  const pid=f.processor.status.pid!,controller=new AbortController(),options=await f.options();options.signal=controller.signal;process.kill(pid,'SIGSTOP');
  const pending=scanFileMetadata(options),rejected=assert.rejects(pending,/active cancellation/);await until(()=>f.processor.status.active);controller.abort(new Error('active cancellation'));await rejected;await f.processor.close();
  assert.equal(options.source.fd,-1);assert.equal(f.extractor.pendingRequests,0);assert.equal(f.processor.status.pending,0);assert.equal(f.processor.status.bytes,0);assert.equal(f.cache.peek('part.gcode'),undefined);assert.equal(f.storage.status.storage.publishedFiles,0);assert.equal(f.storage.status.pending,0);
  assert.throws(()=>process.kill(pid,0),(e:any)=>e.code==='ESRCH');await writeFile(f.path,'G1 X1 F600\n');assert.equal((await scanFileMetadata(await f.options())).committed,true);
 }finally{await f.close();}
});
test('cancelling a queued image scan leaves the active scan and its process usable',async()=>{
 const f=await fixture();try{
  const pid=f.processor.status.pid!;process.kill(pid,'SIGSTOP');const first=scanFileMetadata(await f.options());const firstSettled=first.then(value=>({value}),error=>({error}));await until(()=>f.processor.status.active);
  const controller=new AbortController(),second=await f.options('second.gcode');second.signal=controller.signal;
  const queued=scanFileMetadata(second),rejected=assert.rejects(queued,/queued cancellation/);await until(()=>f.processor.status.pending===2);controller.abort(new Error('queued cancellation'));await rejected;
  assert.equal(f.processor.status.closed,false);assert.equal(f.processor.status.pending,1);assert.equal(second.source.fd,-1);assert.equal(f.cache.peek('second.gcode'),undefined);
  process.kill(pid,'SIGCONT');const result=await firstSettled;assert.ok('value' in result);assert.equal(result.value.committed,true);assert.equal((await scanFileMetadata(await f.options('third.gcode'))).committed,true);
 }finally{await f.close();}
});
test('source mutation while image processing is paused rejects the combined scan',async()=>{
 const f=await fixture();try{
  const pid=f.processor.status.pid!;process.kill(pid,'SIGSTOP');const pending=scanFileMetadata(await f.options()),rejected=assert.rejects(pending,(e:any)=>e.status===409);
  await until(()=>f.processor.status.active);await writeFile(f.path,'G1 X999 F600\n');process.kill(pid,'SIGCONT');await rejected;
  assert.equal(f.cache.peek('part.gcode'),undefined);assert.equal(f.storage.status.storage.publishedFiles,0);assert.equal(f.processor.status.closed,false);
 }finally{await f.close();}
});

test('intent is durable before scanning and success retains it until explicit reconciliation',async()=>{
 const f=await fixture(),dir=await mkdtemp(join(tmpdir(),'scan-intent-owner-'));let journal=await MetadataScanIntents.open(dir);try{
  const options=await f.options(),check=options.validateSource;options.validateSource=async(source)=>{assert.equal(journal.unresolved().length,1);return check(source);};
  const result=await scanFileMetadataWithIntent(journal,options);assert.equal(result.result.committed,true);assert.equal(result.result.bundleId,result.intent.bundleId);await journal.close();journal=await MetadataScanIntents.open(dir);assert.deepEqual(journal.unresolved(),[result.intent]);assert.deepEqual(await f.storage.listIds(options.signal),[result.intent.bundleId]);
 }finally{await journal.close();await f.close();await rm(dir,{recursive:true,force:true});}
});
test('failed scans retain their durable intent while rejected intent admission closes source',async()=>{
 const f=await fixture(),dir=await mkdtemp(join(tmpdir(),'scan-intent-failed-')),journal=await MetadataScanIntents.open(dir);try{
  const options=await f.options();options.validateSource=async()=>false;
  await assert.rejects(scanFileMetadataWithIntent(journal,options),(error:any)=>error instanceof MetadataIntentScanError&&(error.cause as any).status===409&&error.intent.id===journal.unresolved()[0].id);
  assert.equal(journal.unresolved().length,1);assert.deepEqual(await f.storage.listIds(options.signal),[]);await journal.close();const rejected=await f.options();await assert.rejects(scanFileMetadataWithIntent(journal,rejected),/closed/);assert.equal(rejected.source.fd,-1);assert.equal(f.cache.peek('part.gcode'),undefined);
 }finally{await journal.close();await f.close();await rm(dir,{recursive:true,force:true});}
});
