import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,open,readdir,readlink,type FileHandle} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {MetadataVersions} from '../src/moonraker/metadata-versions.ts';
import {MetadataScanIntents} from '../src/moonraker/metadata-intents.ts';
const signal=new AbortController().signal;
async function fixture(maxFiles=2){const dir=await mkdtemp(join(tmpdir(),'metadata-version-retirement-')),root=join(dir,'versions'),intents=await MetadataScanIntents.open(join(dir,'intents')),versions=await MetadataVersions.open(root,{maxFiles});return {dir,root,intents,versions,async close(){await versions.close();await intents.close();await rm(dir,{recursive:true,force:true});}};}
test('bounded pending retention preserves generation identity and drains on selection or close',async()=>{
 const f=await fixture(1);try{await f.versions.invalidate('a.gcode',signal);const pending=await f.versions.begin(await f.intents.begin('a.gcode',signal),signal);assert.equal(f.versions.status.retainedVersions,1);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.json')).length,2);assert.equal(f.versions.current('a.gcode'),pending);await f.versions.select(pending,signal);assert.equal(f.versions.status.retainedVersions,0);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.json')).length,1);const next=await f.versions.begin(await f.intents.begin('a.gcode',signal),signal);assert.equal(f.versions.status.retainedVersions,1);await assert.rejects(f.versions.begin(await f.intents.begin('b.gcode',signal),signal),/capacity/);await f.versions.close();assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.json')).length,1);const recovered=await MetadataVersions.open(f.root,{maxFiles:1});try{assert.deepEqual(recovered.current('a.gcode'),next);assert.equal(recovered.status.sequence,'4');assert.equal(recovered.status.retainedVersions,0);}finally{await recovered.close();}}finally{await f.close();}
});
test('cross-file transitions keep at most one obsolete record and never remove another current head',async()=>{
 const f=await fixture(2);try{await f.versions.invalidate('a.gcode',signal);const a=await f.versions.begin(await f.intents.begin('a.gcode',signal),signal),b=await f.versions.begin(await f.intents.begin('b.gcode',signal),signal);assert.equal(f.versions.status.retainedVersions,1);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.json')).length,3);const b2=await f.versions.begin(await f.intents.begin('b.gcode',signal),signal);assert.equal(f.versions.status.retainedVersions,0);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.json')).length,2);assert.equal(f.versions.current('a.gcode'),a);assert.equal(f.versions.current('b.gcode'),b2);assert.equal(await f.versions.select(b,signal),null);await f.versions.close();const recovered=await MetadataVersions.open(f.root,{maxFiles:2});try{assert.deepEqual(recovered.current('a.gcode'),a);assert.deepEqual(recovered.current('b.gcode'),b2);}finally{await recovered.close();}}finally{await f.close();}
});
test('close waits for retained reclamation and reports its failure without losing the durable pending head',async t=>{
 const f=await fixture(),probe=await open('/dev/null','r'),prototype=Object.getPrototypeOf(probe) as FileHandle,original=prototype.sync;await probe.close();const entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>(),failure=new Error('close compaction failed');let closing:Promise<void>|undefined,closed=false;
 try{await f.versions.invalidate('a.gcode',signal);const pending=await f.versions.begin(await f.intents.begin('a.gcode',signal),signal);t.mock.method(prototype,'sync',async function(this:FileHandle){if(await readlink('/proc/self/fd/'+this.fd)===f.root){entered.resolve();await resume.promise;throw failure;}return original.call(this);});closing=f.versions.close();const rejected=assert.rejects(closing,error=>error===failure).then(()=>{closed=true;});await entered.promise;assert.equal(closed,false);resume.resolve();await rejected;t.mock.restoreAll();const recovered=await MetadataVersions.open(f.root);try{assert.deepEqual(recovered.current('a.gcode'),pending);assert.equal(recovered.status.retainedVersions,0);}finally{await recovered.close();}
 }finally{resume.resolve();t.mock.restoreAll();await closing?.catch(()=>{});await f.intents.close();await rm(f.dir,{recursive:true,force:true});}
});
for(const phase of [3,4])test(`SIGKILL at reclamation barrier ${phase} retains the fully published selected generation`,{timeout:15000},async()=>{
 const f=await fixture();let child:ReturnType<typeof spawn>|undefined,exited:Promise<unknown>|undefined;
 try{await f.versions.invalidate('a.gcode',signal);const initial=await f.versions.begin(await f.intents.begin('a.gcode',signal),signal);await f.versions.select(initial,signal);await f.versions.close();await f.intents.close();
  const ext=import.meta.url.endsWith('.ts')?'ts':'js',versionsURL=new URL('../src/moonraker/metadata-versions.'+ext,import.meta.url).href,intentsURL=new URL('../src/moonraker/metadata-intents.'+ext,import.meta.url).href;
  const code=`import {open,readlink} from 'node:fs/promises';import {MetadataVersions} from ${JSON.stringify(versionsURL)};import {MetadataScanIntents} from ${JSON.stringify(intentsURL)};process.on('message',()=>{});const root=process.argv[1],phase=Number(process.argv[3]),signal=new AbortController().signal,intents=await MetadataScanIntents.open(process.argv[2]),versions=await MetadataVersions.open(root),pending=await versions.begin(await intents.begin('a.gcode',signal),signal),probe=await open('/dev/null','r'),prototype=Object.getPrototypeOf(probe),original=prototype.sync;await probe.close();let roots=0;prototype.sync=async function(){if(await readlink('/proc/self/fd/'+this.fd)===root&&++roots===phase){await new Promise(resolve=>process.send({barrier:phase,candidate:versions.current('a.gcode')},resolve));return new Promise(()=>{});}return original.call(this);};await versions.select(pending,signal);throw Error('Retirement must remain blocked');`;
  child=spawn(process.execPath,['--input-type=module','-e',code,f.root,join(f.dir,'intents'),String(phase)],{stdio:['ignore','ignore','pipe','ipc']});let stderr='';const current=child;child.stderr!.on('data',data=>{stderr+=data;if(stderr.length>65536)current.kill('SIGKILL');});exited=once(child,'exit');const [message]=await Promise.race([once(child,'message',{signal:AbortSignal.timeout(10000)}),exited.then(()=>{throw new Error('Crash control exited before barrier: '+stderr);})]);assert.equal(message.barrier,phase);assert.equal(message.candidate.state,'selected');assert.equal(message.candidate.sequence,'5');assert((await readdir(f.root)).includes('mv-5.json'));assert(current.kill('SIGKILL'));await exited;assert.equal(current.signalCode,'SIGKILL');const recovered=await MetadataVersions.open(f.root);try{assert.deepEqual(recovered.current('a.gcode'),message.candidate);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.json')).length,1);const reopenedIntents=await MetadataScanIntents.open(join(f.dir,'intents'));try{const next=await recovered.begin(await reopenedIntents.begin('a.gcode',signal),signal);assert.equal(next.sequence,'6');assert.equal(next.state,'pending');}finally{await reopenedIntents.close();}}finally{await recovered.close();}
 }finally{if(child&&child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');await exited;await f.close();}
});
