import {test} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import {ServerInformation,ServerConfiguration,registerServerMetadata,type InformationSnapshot} from '../src/moonraker/metadata.ts';
import {JsonRpcDispatcher,ApiError} from '../src/moonraker/rpc.ts';
import {EndpointRegistry} from '../src/moonraker/endpoints.ts';
import {MoonrakerNetwork} from '../src/moonraker/server.ts';
const information=():InformationSnapshot=>({connected:false,state:'disconnected',components:['application','jsonrpc','websockets'],failedComponents:[],directories:[],warnings:['Migration incomplete\nNo printer connection'],version:'anyraid-node-test',missingRequirements:[]});
const configuration=()=>({primaryFile:'/config/moonraker.conf',parsed:{server:{port:7125,debug:false}},original:{server:{port:'7125',debug:'false'}},files:[{filename:'/config/moonraker.conf',sections:['server']},{filename:'/config/includes/devices.conf',sections:['devices']},{filename:'/external/shared.conf',sections:['shared']}]});
test('server info preserves upstream fields, warning modes and explicit disconnected state',()=>{
 const s=new ServerInformation(information()),result=s.read(false,2);assert.equal(result.klippy_connected,false);assert.equal(result.klippy_state,'disconnected');assert.deepEqual(result.api_version,[1,5,0]);assert.equal(result.api_version_string,'1.5.0');assert.deepEqual(result.warnings,['Migration incomplete<br/>No printer connection']);assert.deepEqual(s.read(true,0).warnings,['Migration incomplete\nNo printer connection']);assert.equal(result.websocket_count,2);assert.deepEqual(result.registered_directories,[]);assert.equal(result.moonraker_version,'anyraid-node-test');
});
test('lifecycle snapshots replace atomically and cannot be changed through callers or response arrays',()=>{
 const snapshot=information(),s=new ServerInformation(snapshot);(snapshot.components as string[]).push('invented');assert.equal((s.read(false,0).components as string[]).includes('invented'),false);assert.throws(()=>(s.read(false,0).components as string[]).push('mutated'));assert.throws(()=>s.replace({...snapshot,state:'invalid' as any}));assert.equal(s.read(false,0).klippy_state,'disconnected');s.replace({...information(),connected:true,state:'shutdown',failedComponents:['mqtt'],missingRequirements:['virtual_sdcard']});assert.equal(s.read(true,0).klippy_state,'shutdown');assert.deepEqual(s.read(true,0).failed_components,['mqtt']);assert.throws(()=>s.read(false,-1));
});
test('configuration views preserve originals and normalize only paths inside the canonical config directory',()=>{
 const source=configuration(),s=new ServerConfiguration(source);assert.deepEqual(s.read().files,[{filename:'moonraker.conf',sections:['server']},{filename:'includes/devices.conf',sections:['devices']},{filename:'/external/shared.conf',sections:['shared']}]);source.parsed.server.port=99;assert.equal((s.read().config as any).server.port,7125);assert.equal((s.read().orig as any).server.port,'7125');assert.throws(()=>{(s.read().config as any).server.port=2;});assert.throws(()=>s.replace({...configuration(),primaryFile:'relative.conf'}));assert.equal((s.read().config as any).server.port,7125);
});
test('server metadata registration rolls back on collision and detaches idempotently',()=>{
 const rpc=new JsonRpcDispatcher(),registry=new EndpointRegistry(rpc),info=new ServerInformation(information()),config=new ServerConfiguration(configuration());const remove=registry.register({endpoint:'/server/config',methods:['GET']},()=>null);assert.throws(()=>registerServerMetadata(registry,info,config,()=>0),/already/);assert.equal(rpc.has('server.info'),false);remove();const detach=registerServerMetadata(registry,info,config,()=>0);assert.ok(rpc.has('server.info'));detach();detach();assert.equal(rpc.has('server.config'),false);
});
test('live HTTP and WebSocket server metadata uses current snapshots and actual connection count',async()=>{
 const rpc=new JsonRpcDispatcher(),registry=new EndpointRegistry(rpc),info=new ServerInformation(information()),config=new ServerConfiguration(configuration());let service!:MoonrakerNetwork;registerServerMetadata(registry,info,config,()=>service.status.connections);service=new MoonrakerNetwork(rpc,{endpoints:registry,authorize(_m,_p,c){if(c.request.headers['x-api-key']!=='key')throw new ApiError(401,'Unauthorized');}});const address=await service.listen(),url=`http://127.0.0.1:${address.port}`;let ws:WebSocket|undefined;
 try{let response=await fetch(url+'/server/info',{headers:{'X-Api-Key':'key'}});let body:any=await response.json();assert.equal(body.result.websocket_count,0);assert.equal(body.result.klippy_state,'disconnected');ws=new WebSocket(url.replace('http:','ws:')+'/websocket',{headers:{'X-Api-Key':'key'}});await once(ws,'open');info.replace({...information(),connected:true,state:'ready',directories:['gcodes','config']});const received=once(ws,'message');ws.send(JSON.stringify({jsonrpc:'2.0',method:'server.info',params:{raw:true},id:1}));body=JSON.parse(String((await received)[0]));assert.equal(body.result.websocket_count,1);assert.equal(body.result.klippy_state,'ready');assert.deepEqual(body.result.warnings,information().warnings);const invalid=once(ws,'message');ws.send(JSON.stringify({jsonrpc:'2.0',method:'server.info',params:{raw:null},id:2}));assert.equal(JSON.parse(String((await invalid)[0])).error.code,400);response=await fetch(url+'/server/info?raw=not-bool',{headers:{'X-Api-Key':'key'}});assert.equal(response.status,400);response=await fetch(url+'/server/config',{headers:{'X-Api-Key':'key'}});body=await response.json();assert.deepEqual(body.result.config,{server:{port:7125,debug:false}});response=await fetch(url+'/server/config');assert.equal(response.status,401);assert.equal((await response.text()).includes('not authorized'),false);
 }finally{ws?.terminate();await service.close();}
});
