import {test} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {WebSocket,type ClientOptions} from 'ws';
import {MoonrakerNetwork,type MoonrakerNetworkOptions} from '../src/moonraker/server.ts';
import {JsonRpcDispatcher,ApiError} from '../src/moonraker/rpc.ts';
const request=(method='echo',id:number|null=1,params:unknown={value:42})=>JSON.stringify({jsonrpc:'2.0',method,id,params});
async function fixture(options:Partial<MoonrakerNetworkOptions>={}){const rpc=new JsonRpcDispatcher();rpc.register('echo',['http','websocket'],p=>p as any);const service=new MoonrakerNetwork(rpc,{authorize:()=>{},...options}),address=await service.listen();return {rpc,service,http:`http://127.0.0.1:${address.port}`,ws:`ws://127.0.0.1:${address.port}/websocket`};}
async function connect(url:string,options:ClientOptions={}){const ws=new WebSocket(url,options);await once(ws,'open');return ws;}
async function call(ws:WebSocket,message=request()){const reply=once(ws,'message');ws.send(message);return JSON.parse(String((await reply)[0]));}
async function until(check:()=>boolean){for(let i=0;i<500;i++){if(check())return;await delay(2);}throw new Error('Condition timed out');}
test('HTTP RPC preserves replies, notification status, content type and error envelopes',async()=>{
 const f=await fixture();try{let r=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request()});assert.equal(r.status,200);assert.deepEqual(await r.json(),{jsonrpc:'2.0',result:{value:42},id:1});r=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request('echo',null)});assert.equal(r.status,200);assert.equal(await r.text(),'');r=await fetch(f.http+'/server/jsonrpc',{method:'POST',body:request()});assert.equal(r.status,400);assert.equal((await r.json() as any).error.code,400);r=await fetch(f.http+'/server/jsonrpc');assert.equal(r.status,405);r=await fetch(f.http+'/not-found');assert.equal(r.status,404);
 }finally{await f.service.close();}
});
test('WebSocket connection IDs, notifications, binary JSON, ordered batches and transport restrictions',async()=>{
 const f=await fixture();let ws:WebSocket|undefined;try{ws=await connect(f.ws);const id=(await call(ws,request('server.websocket.id'))).result.websocket_id;assert.ok(Number.isSafeInteger(id));const notification=once(ws,'message');assert.equal(f.service.notify(id,'notify_status_update',[{toolhead:{position:[1,2,3]}}]),true);assert.deepEqual(JSON.parse(String((await notification)[0])).params,[{toolhead:{position:[1,2,3]}}]);const result=once(ws,'message');ws.send(Buffer.from(request()));assert.deepEqual(JSON.parse(String((await result)[0])).result,{value:42});const order:number[]=[];f.rpc.register('append',['websocket'],async p=>{await delay(1);order.push(p.n as number);return p.n;});const reply=await call(ws,JSON.stringify([{jsonrpc:'2.0',method:'append',params:{n:1}},{jsonrpc:'2.0',method:'append',params:{n:2},id:2}]));assert.deepEqual(order,[1,2]);assert.equal(reply.length,1);const http=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request('server.websocket.id')});assert.equal((await http.json() as any).error.code,-32601);
 }finally{ws?.terminate();await f.service.close();}
});
test('authorization runs for each method and rejected origins cannot upgrade or invoke HTTP methods',async()=>{
 let calls=0;const f=await fixture({authorize(_method,_params,context){calls++;if(context.request.headers['x-api-key']!=='allowed')throw new ApiError(401,'Unauthorized');}});let ws:WebSocket|undefined;try{const r=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request()});assert.equal((await r.json() as any).error.code,-32602);ws=await connect(f.ws,{headers:{'X-Api-Key':'allowed'}});assert.equal((await call(ws)).result.value,42);const before=calls;const denied=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{origin:'https://evil.invalid','content-type':'application/json'},body:request()});assert.equal(denied.status,403);assert.equal(calls,before);const bad=new WebSocket(f.ws,{origin:'https://evil.invalid'});await assert.rejects(once(bad,'open'),/403/);bad.terminate();
 }finally{ws?.terminate();await f.service.close();}
});
test('independent websocket messages run concurrently while disconnect cancels active handlers',async()=>{
 const f=await fixture();let ws:WebSocket|undefined,started=0,cancelled=0;f.rpc.register('wait',['websocket'],async(_p,c)=>{started++;await new Promise<void>(resolve=>c.signal.addEventListener('abort',()=>{cancelled++;resolve();},{once:true}));return null;});try{ws=await connect(f.ws);ws.send(request('wait',1));ws.send(request('wait',2));await until(()=>started===2);ws.terminate();await until(()=>cancelled===2);await until(()=>f.service.status.requests===0);
 }finally{ws?.terminate();await f.service.close();}
});
test('connection and per-socket request limits bound pending work and cancel overloaded peers',async()=>{
 const f=await fixture({maxConnections:1,maxRequestsPerSocket:1});let ws:WebSocket|undefined,started=false,cancelled=false;f.rpc.register('wait',['websocket'],async(_p,c)=>{started=true;await new Promise<void>(resolve=>c.signal.addEventListener('abort',()=>{cancelled=true;resolve();},{once:true}));return null;});try{ws=await connect(f.ws);const extra=new WebSocket(f.ws);await assert.rejects(once(extra,'open'),/503/);extra.terminate();ws.send(request('wait'));await until(()=>started);ws.send(request());await until(()=>cancelled);await until(()=>f.service.status.connections===0);
 }finally{ws?.terminate();await f.service.close();}
});
test('HTTP disconnect cancels its handler and shutdown does not claim ignored cancellation drained',async()=>{
 const f=await fixture({shutdownTimeoutMs:20});let entered=false,released=false,release!:()=>void;f.rpc.register('stuck',['http'],async()=>{entered=true;await new Promise<void>(r=>{release=r;});released=true;return null;});const controller=new AbortController();const pending=fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request('stuck'),signal:controller.signal}).catch(()=>null);try{await until(()=>entered);controller.abort();await pending;await assert.rejects(f.service.close(),/shutdown deadline/);assert.equal(released,false);assert.equal(f.service.status.phase,'closing');assert.equal(f.service.status.requests,1);release();await until(()=>f.service.status.requests===0);await f.service.close();assert.equal(f.service.status.phase,'closed');}finally{release?.();await f.service.close();}
});
test('request deadlines abort cooperative handlers and close the socket',async()=>{
 const f=await fixture({requestTimeoutMs:20});let ws:WebSocket|undefined,cancelled=false;f.rpc.register('wait',['websocket'],async(_p,c)=>{await new Promise<void>(r=>c.signal.addEventListener('abort',()=>{cancelled=true;r();},{once:true}));return null;});try{ws=await connect(f.ws);const closed=once(ws,'close');ws.send(request('wait'));await closed;assert.equal(cancelled,true);}finally{ws?.terminate();await f.service.close();}
});
test('closing during listen does not leave a bound server or permit restart',async()=>{const rpc=new JsonRpcDispatcher(),service=new MoonrakerNetwork(rpc,{authorize(){}});const started=service.listen();const stopped=service.close();await assert.rejects(started,/cancelled/);await stopped;assert.equal(service.status.phase,'closed');await assert.rejects(service.listen(),/state/);});
test('oversized input and output are bounded and forbidden notification names cannot be sent',async()=>{
 const f=await fixture();let ws:WebSocket|undefined;try{const r=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:'x'.repeat(1024*1024+1)});assert.equal(r.status,413);ws=await connect(f.ws);const id=(await call(ws,request('server.websocket.id'))).result.websocket_id;assert.throws(()=>f.service.notify(id,'printer.print.start',[]),/notification name/);const closed=once(ws,'close');f.service.notify(id,'notify_status_update',['x'.repeat(1024*1024)]);await closed;assert.equal(f.service.notify(id,'notify_status_update',[]),false);
 }finally{ws?.terminate();await f.service.close();}
});
test('global request and byte budgets reject excess work without releasing active handlers early',async()=>{
 const f=await fixture({maxRequests:1,maxBufferedBytes:300});let entered=false;f.rpc.register('wait',['http'],async(_p,c)=>{entered=true;await new Promise<void>(r=>c.signal.addEventListener('abort',()=>r(),{once:true}));return null;});const abort=new AbortController();const first=fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request('wait'),signal:abort.signal}).catch(()=>null);try{await until(()=>entered);assert.ok(f.service.status.bufferedBytes>0);const second=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request()});assert.equal(second.status,429);abort.abort();await first;await until(()=>f.service.status.requests===0);assert.equal(f.service.status.bufferedBytes,0);const large=await fetch(f.http+'/server/jsonrpc',{method:'POST',headers:{'content-type':'application/json'},body:request('echo',1,{value:'x'.repeat(500)})});assert.equal(large.status,429);await until(()=>f.service.status.bufferedBytes===0);
 }finally{abort.abort();await f.service.close();}
});
test('Node native browser-compatible WebSocket can use the RPC endpoint',async()=>{
 const f=await fixture();let ws:globalThis.WebSocket|undefined;try{ws=new globalThis.WebSocket(f.ws);await new Promise<void>((resolve,reject)=>{ws!.addEventListener('open',()=>resolve(),{once:true});ws!.addEventListener('error',reject,{once:true});});const result=new Promise<string>(resolve=>ws!.addEventListener('message',e=>resolve(String(e.data)),{once:true}));ws.send(request());assert.equal(JSON.parse(await result).result.value,42);}finally{ws?.close();await f.service.close();}
});
