import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createServer,type Socket} from 'node:net';
import {once} from 'node:events';
import {execFileSync} from 'node:child_process';
import {gunzipSync,inflateRawSync} from 'node:zlib';
import {motanPattern,motanSubscriptions} from '../src/motan/subscriptions.ts';
import {parseMotanJson,encodeMotanJson,MotanCapture} from '../src/motan/capture.ts';
import {captureMotan} from '../src/motan/data-logger.ts';
import {ConsoleFrames} from '../src/diagnostics/webhook-console.ts';
const message=(v:unknown)=>Buffer.from(JSON.stringify(v)+'\x03');
const until=async(f:()=>boolean)=>{const end=Date.now()+3000;while(!f()){assert.ok(Date.now()<end);await new Promise(r=>setTimeout(r,5));}};
test('Motan pattern matching follows Python fnmatchcase including bracket ranges, Unicode and literal slash',()=>{
 let state=419;const random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state;},alphabet=Array.from('ab-!^[]?*\\/😀'),pairs:[string,string][]=[];for(let i=0;i<3000;i++){const text=(max:number)=>Array.from({length:random()%max},()=>alphabet[random()%alphabet.length]).join('');pairs.push([text(12),text(16)]);}pairs.push(['abc','[z-a]*'],['/a','*'],['😀','?'],[']','[]]'],['a','[!z-a]'],['b','[a-c-e]']);const expected=JSON.parse(execFileSync('python3',['-c','import json,sys,fnmatch;print(json.dumps([fnmatch.fnmatchcase(n,p) for n,p in json.load(sys.stdin)]))'],{input:JSON.stringify(pairs),encoding:'utf8'}));pairs.forEach(([name,pattern],i)=>assert.equal(motanPattern(pattern)(name),expected[i],JSON.stringify([name,pattern])));
});
test('Motan exact JSON keeps unsafe integers and signed zero in index serialization',()=>{
 const value=parseMotanJson(Buffer.from('{"clock":9007199254740993,"negative":-0.0,"x":1.0000000000000002}')) as any;assert.equal(value.clock,9007199254740993n);const encoded=encodeMotanJson(value).toString();assert.match(encoded,/9007199254740993/);assert.match(encoded,/-0\.0/);assert.equal(JSON.parse(encoded).x,1.0000000000000002);assert.throws(()=>parseMotanJson(Buffer.from('{"x":1e400}')));
});
test('Motan subscription map preserves all original sensor endpoints and deterministic selection',()=>{
 const types=['adxl345','lis2dw','lis3dh','mpu9250','bmi160','icm20948','angle','probe_eddy_current','load_cell','load_cell_probe','tmc2130','tmc2209','tmc2260','tmc2240','tmc5160'];const status={motion_report:{trapq:['toolhead'],steppers:['stepper_x']},configfile:{settings:Object.fromEntries(types.map(t=>[t+' '+t+' name',{}]))}};const result=motanSubscriptions(status,['*']);assert.equal(result.selected.length,17);assert.equal(result.selected.find(s=>s.name==='accelerometer:lis3dh name')?.method,'lis2dw/dump_lis2dw');assert.deepEqual(result.selected.find(s=>s.name==='loadcell:load_cell name')?.params,{load_cell:'load_cell name'});assert.deepEqual(motanSubscriptions(status,['stepq:*','trapq:*']).selected.map(s=>s.name),['stepq:stepper_x','trapq:toolhead']);
});
test('Motan real Unix capture preserves raw frames and complete index boundaries under batched input',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-capture-')),path=join(dir,'socket'),prefix=join(dir,'capture'),requests:any[]=[],raw:Buffer[]=[];let peer:Socket|undefined;const server=createServer(socket=>{peer=socket;const frames=new ConsoleFrames(3);socket.on('data',chunk=>{for(const frame of frames.push(Buffer.from(chunk))){const req=JSON.parse(frame.toString());requests.push(req);let reply:unknown;if(req.id==='info')reply={id:'info',result:{state:'ready'}};else if(req.id==='list')reply={id:'list',result:{objects:['configfile','motion_report','toolhead']}};else if(req.id==='status')reply={id:'status',result:{eventtime:100,status:{configfile:{settings:{'adxl345 toolhead':{}}},motion_report:{trapq:['toolhead'],steppers:['stepper_x']},toolhead:{position:[0,0,0]}}}};else reply={id:req.id,result:{header:['time','value']}};const encoded=message(reply);raw.push(encoded);socket.write(encoded);if(requests.length===6){const updates=[Buffer.from('{"q":"status","params":{"eventtime":102,"status":{"toolhead":{"clock":9007199254740993,"x":1.0000000000000002}}}}\x03'),message({q:'stepq:stepper_x',params:{data:[[102.1,1,2]]}}),message({q:'status',params:{eventtime:106,status:{toolhead:{y:2}}}}),message({q:'stepq:stepper_x',params:{data:[[106.1,3,4]]}})];raw.push(...updates);socket.end(Buffer.concat(updates));}}});});
 try{server.listen(path);await once(server,'listening');await captureMotan(path,prefix,['*'],new AbortController().signal,()=>{});const compressed=await readFile(prefix+'.json.gz');assert.deepEqual(gunzipSync(compressed),Buffer.concat(raw));const indexes=gunzipSync(await readFile(prefix+'.index.gz')).toString().split('\x03').filter(Boolean).map(v=>parseMotanJson(Buffer.from(v)) as any);assert.equal(indexes.length,2);assert.equal(indexes[1].status.toolhead.clock,9007199254740993n);assert.equal(indexes[1].status.toolhead.y,2);assert.equal(indexes[1].status.toolhead.x,1.0000000000000002);assert.ok(inflateRawSync(compressed.subarray(indexes[0].file_position)).toString().startsWith('{"q":"status"'));assert.equal(inflateRawSync(compressed.subarray(indexes[1].file_position)).toString(),raw.at(-1)!.toString());assert.deepEqual(Object.keys(indexes[0].subscriptions).sort(),['accelerometer:toolhead','stepq:stepper_x','trapq:toolhead']);
 }finally{peer?.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}
});
test('Motan state machine bounds outstanding subscriptions and safely preserves prototype-named status fields',async()=>{
 const sent:any[]=[],logs:Buffer[]=[],indexes:Buffer[]=[],capture=new MotanCapture({log:{async addRecords(records){logs.push(...records.map(r=>Buffer.from(r)));},async flush(){return logs.reduce((n,b)=>n+b.length+1,0);}},index:{async addRecords(records){indexes.push(...records.map(r=>Buffer.from(r)));}}},async req=>{sent.push(req);},['*'],()=>{});
 await capture.start();await capture.accept([message({id:'info',result:{state:'ready'}}).subarray(0,-1),message({id:'list',result:{objects:['configfile','motion_report']}}).subarray(0,-1)]);const initial=JSON.parse('{"configfile":{"settings":{}},"motion_report":{"trapq":[],"steppers":[]},"__proto__":{"polluted":true}}');initial.motion_report.steppers=Array.from({length:40},(_,i)=>'s'+i);await capture.accept([message({id:'status',result:{eventtime:0,status:initial}}).subarray(0,-1)]);assert.equal(capture.status.pendingRequests,16);assert.equal(sent.length,19);for(let i=3;i<sent.length;i++){await capture.accept([message({id:sent[i].id,result:{header:[]}}).subarray(0,-1)]);assert.ok(capture.status.pendingRequests<=16);}assert.equal(capture.status.pendingRequests,0);assert.equal(indexes.length,1);assert.equal(({} as any).polluted,undefined);assert.equal((parseMotanJson(indexes[0]) as any).status.__proto__.polluted,true);
});
test('Motan disconnect during handshake and deadline are failures; cancellation still closes gzip outputs',async()=>{
 for(const mode of ['disconnect','timeout','cancel']){const dir=await mkdtemp(join(tmpdir(),'motan-stop-')),path=join(dir,'socket'),prefix=join(dir,'capture'),control=new AbortController();let peer:Socket|undefined;const server=createServer(socket=>{peer=socket;socket.once('data',()=>{if(mode==='disconnect')socket.end(message({id:'info',result:{state:'ready'}}));if(mode==='cancel')control.abort(new Error('cancelled'));});});try{server.listen(path);await once(server,'listening');await assert.rejects(captureMotan(path,prefix,[],control.signal,()=>{},{requestTimeoutMs:30}),/incomplete|timed out|cancelled/);for(const suffix of ['.json.gz','.index.gz']){const data=await readFile(prefix+suffix);if(data.length)gunzipSync(data);}}finally{peer?.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}}
});
test('Motan CLI starts without Python and closes a not-ready capture with the original status message',async()=>{
 const {spawn}=await import('node:child_process'),dir=await mkdtemp(join(tmpdir(),'motan-cli-')),path=join(dir,'socket'),prefix=join(dir,'capture');let peer:Socket|undefined;const server=createServer(socket=>{peer=socket;socket.once('data',()=>socket.write(message({id:'info',result:{state:'shutdown'}})));});try{server.listen(path);await once(server,'listening');const child=spawn(process.execPath,[new URL('../../scripts/motan/data_logger.ts',import.meta.url).pathname,'--no-default','-s','angle:*',path,prefix],{stdio:['ignore','pipe','pipe'],env:{...process.env,PATH:'/no-programs'}});let output='',errors='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>errors+=b);const result=await once(child,'close');assert.equal(result[0],0,errors);assert.match(output,/Klipper not in ready state/);assert.deepEqual(JSON.parse(gunzipSync(await readFile(prefix+'.json.gz')).toString().slice(0,-1)),{id:'info',result:{state:'shutdown'}});assert.equal((await readFile(prefix+'.index.gz')).length,0);}finally{peer?.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}
});
