import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {gzipSync} from 'node:zlib';
import {execFileSync} from 'node:child_process';
import {MotanLogReader} from '../src/motan/log-reader.ts';
import {MotanLogWriter} from '../src/motan/log-writer.ts';
test('Motan reader streams original Python gzip output, preserves numeric precision and restarts at full-flush indexes',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-read-')),path=join(dir,'log');let reader:MotanLogReader|undefined;
 try{const code="import sys,zlib,json\nf=open(sys.argv[1],'wb');c=zlib.compressobj(wbits=31)\nf.write(c.compress(b'{\"clock\":9007199254740993,\"x\":1.0000000000000002}\\x03'));f.write(c.flush(zlib.Z_FULL_FLUSH));offset=f.tell()\nf.write(c.compress(b'{\"clock\":9007199254740995,\"x\":-0.0}\\x03'));f.write(c.flush());f.close();print(offset)";const offset=Number(execFileSync('python3',['-c',code,path],{encoding:'utf8'}));reader=await MotanLogReader.open(path);assert.deepEqual(await reader.pullMessage(),{clock:9007199254740993n,x:1.0000000000000002});assert.deepEqual(await reader.pullMessage(),{clock:9007199254740995n,x:-0});assert.equal(await reader.pullMessage(),null);assert.equal(reader.status.eof,true);await reader.seek(offset);assert.deepEqual(await reader.pullMessages(),[{clock:9007199254740995n,x:-0}]);await reader.seek(0);assert.equal((await reader.pullMessages()).length,2);await reader.seek(reader.status.fileSize);assert.equal(await reader.pullMessage(),null);
 }finally{await reader?.close();await rm(dir,{recursive:true,force:true});}
});
test('Motan reader bounds messages and decoding while accepting records fragmented across compressed chunks',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-limit-')),path=join(dir,'log'),writer=await MotanLogWriter.open(path);let reader:MotanLogReader|undefined;
 try{const records=Array.from({length:900},(_,i)=>Buffer.from(JSON.stringify({i,value:'x'.repeat(2000)})));for(let i=0;i<records.length;i+=200)await writer.addRecords(records.slice(i,i+200));await writer.close();reader=await MotanLogReader.open(path);const all=[];for(;;){const batch:Record<string,unknown>[]=await reader.pullMessages(127);assert.ok(batch.length<=127);if(!batch.length)break;all.push(...batch);}assert.equal(all.length,900);assert.deepEqual(all[899],{i:899,value:'x'.repeat(2000)});await reader.close();reader=await MotanLogReader.open(path,{maxRecordBytes:100});await assert.rejects(reader.pullMessage(),/frame limit/);assert.equal(reader.status.failed,true);await reader.close();reader=await MotanLogReader.open(path,{maxDecodedBytes:1000});await assert.rejects(reader.pullMessages(),/decompression limit/);await reader.close();reader=undefined;await assert.rejects(MotanLogReader.open(path,{maxFileBytes:1}),/bounded regular/);
 }finally{await reader?.close();await writer.close();await rm(dir,{recursive:true,force:true});}
});
test('Motan unfinished capture is explicit; complete mode rejects truncated gzip and unfinished records',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-prefix-')),path=join(dir,'log'),writer=await MotanLogWriter.open(path);let reader:MotanLogReader|undefined;
 try{await writer.addData(Buffer.from('{"x":1}'));await writer.flush();const prefix=await readFile(path);await writer.close();const incomplete=join(dir,'incomplete');await writeFile(incomplete,prefix);reader=await MotanLogReader.open(incomplete);await assert.rejects(reader.pullMessages(),/unexpected end|premature|buffer error/i);await reader.close();reader=await MotanLogReader.open(incomplete,{allowIncomplete:true});assert.deepEqual(await reader.pullMessages(),[{x:1}]);await reader.close();await writeFile(incomplete,gzipSync('{"x":1}\x03{"unfinished":'));reader=await MotanLogReader.open(incomplete);await assert.rejects(reader.pullMessages(),/incomplete record/);await reader.close();reader=await MotanLogReader.open(incomplete,{allowIncomplete:true});assert.deepEqual(await reader.pullMessages(),[{x:1}]);assert.ok(reader.status.ignoredTailBytes>0);
 }finally{await reader?.close();await writer.close();await rm(dir,{recursive:true,force:true});}
});
test('Motan reader rejects corrupt gzip, invalid JSON/UTF-8 and non-object records without hiding errors',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-bad-'));try{const corrupt=gzipSync('{"x":1}\x03');corrupt[corrupt.length-8]^=1;const variants=[corrupt,gzipSync('oops\x03'),gzipSync('null\x03'),gzipSync(Buffer.from([0xff,3])),gzipSync('{"x":1e400}\x03')];for(const [i,data] of variants.entries()){const path=join(dir,String(i));await writeFile(path,data);const reader=await MotanLogReader.open(path);try{await assert.rejects(reader.pullMessages());assert.equal(reader.status.failed,true);await assert.rejects(reader.pullMessage());}finally{await reader.close();}}}finally{await rm(dir,{recursive:true,force:true});}
});
test('Motan close/abort settle active reads, refuse concurrent operations and retain empty-log compatibility',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-close-')),path=join(dir,'log');let reader:MotanLogReader|undefined;try{await writeFile(path,gzipSync('{"x":1}\x03'));reader=await MotanLogReader.open(path);const pending=reader.pullMessages();await assert.rejects(reader.pullMessage(),/Concurrent/);await assert.rejects(reader.seek(0),/during/);await pending;await assert.rejects(reader.seek(-1),/offset/);const seeking=reader.seek(0);await assert.rejects(reader.pullMessage(),/Concurrent/);await seeking;const reading=reader.pullMessages();const observed=reading.catch(e=>e);await reader.close();await observed;await assert.rejects(reader.pullMessage(),/closed/);const controller=new AbortController();reader=await MotanLogReader.open(path,{signal:controller.signal});const cancelled=reader.pullMessages().catch(e=>e);controller.abort(new Error('analysis cancelled'));assert.match(String(await cancelled),/cancelled|premature|closed/);await reader.close();await writeFile(path,'');reader=await MotanLogReader.open(path);assert.equal(await reader.pullMessage(),null);assert.equal(reader.status.eof,true);}finally{await reader?.close();await rm(dir,{recursive:true,force:true});}
});
test('Motan reader retains split UTF-8 records and reads only the initial extent while rejecting later truncation',async()=>{
 const {appendFile}=await import('node:fs/promises'),dir=await mkdtemp(join(tmpdir(),'motan-extent-')),path=join(dir,'log'),record={text:'𠀀'.repeat(50000),x:1.0000000000000002};let reader:MotanLogReader|undefined;try{await writeFile(path,gzipSync(JSON.stringify(record)+'\x03'));reader=await MotanLogReader.open(path);await appendFile(path,gzipSync('{"appended":true}\x03'));assert.deepEqual(await reader.pullMessages(),[record]);await reader.close();reader=await MotanLogReader.open(path);await writeFile(path,'');await assert.rejects(reader.pullMessages(),/truncated during read/);}finally{await reader?.close();await rm(dir,{recursive:true,force:true});}
});
test('Motan ready reads share framing, exact-byte accounting, failure latch and concurrency rules',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'motan-ready-')),path=join(dir,'log');let reader:MotanLogReader|undefined;try{await writeFile(path,gzipSync('{"i":1}\x03{"clock":9007199254740993}\x03oops\x03'));reader=await MotanLogReader.open(path);assert.equal(reader.pullReadyMessage(),undefined);const pending=reader.pullMessage();assert.throws(()=>reader!.pullReadyMessage(),/Concurrent/);assert.deepEqual(await pending,{i:1});const next=reader.pullReadyMessage();assert.deepEqual(next,{clock:9007199254740993n});assert.equal(reader.encodedSize(next!),26);assert.throws(()=>reader!.pullReadyMessage());assert.equal(reader.status.failed,true);await assert.rejects(reader.pullMessage());await reader.close();assert.throws(()=>reader!.pullReadyMessage(),/closed/);await writeFile(path,gzipSync('{"i":1}\x03'));reader=await MotanLogReader.open(path);await reader.pullMessages();assert.equal(reader.pullReadyMessage(),null);}finally{await reader?.close();await rm(dir,{recursive:true,force:true});}
});
