import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync,spawnSync} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {motionPlots,motionPositions} from '../src/diagnostics/graph-motion.ts';
import {motionGraphReference} from '../bench/motion-graph-reference.ts';
test('all acceleration orders and jerk modes match original sample grid, positions and downstream curves',()=>{for(const order of [2,4,6] as const)for(const jerkLimit of [false,true])for(const filter of [undefined,'weighted4'] as const){const profile={order,jerkLimit},ref=motionGraphReference(filter,undefined,profile),positions=motionPositions(profile),panels=motionPlots(filter,undefined,profile);assert.equal(positions.length,ref.positions.length);positions.forEach((v,i)=>assert.ok(Math.abs(v-ref.positions[i])<=1e-12));panels.forEach((p,i)=>p.plot.curves.forEach((c,j)=>{const r=ref.panels[i].curves[j];assert.deepEqual(c.times,r.times);c.values.forEach((v,k)=>assert.ok(Math.abs(v-r.values[k])<=[1e-8,1e-4,1e-10][i],`${order} ${jerkLimit} ${filter} panel ${i} sample ${k}: ${v-r.values[k]}`));}));}assert.ok(motionPositions({jerkLimit:true}).length>motionPositions().length);});
test('profile options validate and CLI enables higher order plus jerk and filter composition',async()=>{assert.throws(()=>motionPositions({order:3 as 2}),RangeError);assert.throws(()=>motionPositions({jerkLimit:1 as unknown as boolean}),RangeError);const dir=await mkdtemp(join(tmpdir(),'motion-profile-')),cli=fileURLToPath(new URL('../../scripts/graph_motion.ts',import.meta.url)),path=join(dir,'plot.json');try{execFileSync(process.execPath,[cli,'--accel_order','6','--jerk_limit','--filter','weighted4','-o',path]);assert.deepEqual(JSON.parse(await readFile(path,'utf8')),motionPlots('weighted4',undefined,{order:6,jerkLimit:true}));for(const order of ['0','3','NaN','4.0',''])assert.equal(spawnSync(process.execPath,[cli,'--accel_order',order,'-o',path]).status,1);}finally{await rm(dir,{recursive:true,force:true});}});
