import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {ufpFixture} from './helpers/ufp-fixture.ts';
import {externalAcceptanceBundle,assertAcceptanceBundleUnchanged} from './helpers/acceptance-bundle.ts';
import type {MoonrakerNetworkOptions} from '../src/moonraker/server.ts';
const retained=await externalAcceptanceBundle();if(retained)after(()=>assertAcceptanceBundleUnchanged(retained));
const {NativePrintUploads,registerNativeFileInfo}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/native-print-uploads.js')).href) as typeof import('../src/moonraker/native-print-uploads.ts'):await import('../src/moonraker/native-print-uploads.ts');
const {MoonrakerNetwork}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/server.js')).href) as typeof import('../src/moonraker/server.ts'):await import('../src/moonraker/server.ts');
const {JsonRpcDispatcher,ApiError}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/rpc.js')).href) as typeof import('../src/moonraker/rpc.ts'):await import('../src/moonraker/rpc.ts');
const {EndpointRegistry}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/endpoints.js')).href) as typeof import('../src/moonraker/endpoints.ts'):await import('../src/moonraker/endpoints.ts');
const {MaintenanceGate}=retained?await import(pathToFileURL(join(retained.path,'host/src/operations/maintenance-gate.js')).href) as typeof import('../src/operations/maintenance-gate.ts'):await import('../src/operations/maintenance-gate.ts');
const {PublishedPrintFiles}=retained?await import(pathToFileURL(join(retained.path,'host/src/storage/published-files.js')).href) as typeof import('../src/storage/published-files.ts'):await import('../src/storage/published-files.ts');
const {PrintController}=retained?await import(pathToFileURL(join(retained.path,'host/src/operations/print.js')).href) as typeof import('../src/operations/print.ts'):await import('../src/operations/print.ts');
const {ThumbnailProcessor}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/thumbnail-process.js')).href) as typeof import('../src/moonraker/thumbnail-process.ts'):await import('../src/moonraker/thumbnail-process.ts');
const model=Buffer.from('; generated by Cura_SteamEngine 5.10.0\r\n; 中文模型\r\n;Layer height: 0.2\r\nG1 X0.12345678901234567 E0.01 F1200\r\n');
const signal=()=>new AbortController().signal;
const sha=(data:Buffer)=>createHash('sha256').update(data).digest('hex');
const png=()=>sharp({create:{width:64,height:32,channels:4,background:{r:21,g:42,b:99,alpha:0.5}}}).png().toBuffer();
const packed=(data=model,image?:Buffer)=>ufpFixture([{name:'/3D/model.gcode',data},...image?[{name:'/Metadata/thumbnail.png',data:image}]:[]]);
async function fixture(options:{persistent?:boolean;authorize?:MoonrakerNetworkOptions['authorize'];max?:number}={}){
 const dir=await mkdtemp(join(tmpdir(),'native-ufp-')),root=join(dir,'files');let gate=new MaintenanceGate(),files=await PublishedPrintFiles.open(root),uploads=options.persistent?await NativePrintUploads.open(files,gate,{stagingRoot:dir,metadataRoot:join(dir,'metadata'),maxFileBytes:options.max}):new NativePrintUploads(files,gate,{stagingRoot:dir,maxFileBytes:options.max}),starts=0;
 let controller=new PrintController({async prepare(){},async start(){starts++;},async pause(){},async resume(){},async finish(){},async stop(){}},{maxNozzle:300,maxBed:130},{},{maintenanceGate:gate});uploads.bindPrintController(controller);
 const connect=async()=>{const rpc=new JsonRpcDispatcher(),endpoints=new EndpointRegistry(rpc);registerNativeFileInfo(endpoints,uploads);const network=new MoonrakerNetwork(rpc,{endpoints,nativeUploads:uploads,authorize:options.authorize??(()=>{})}),address=await network.listen();return {network,url:`http://127.0.0.1:${address.port}`};};let connection=await connect();
 return {dir,root,get files(){return files;},get uploads(){return uploads;},get starts(){return starts;},get url(){return connection.url;},async post(bytes:Buffer,name='模型.UFP',fields:Record<string,string>={}){const body=new FormData();body.append('file',new Blob([new Uint8Array(bytes)]),name);for(const [key,value] of Object.entries(fields))body.append(key,value);return fetch(connection.url+'/server/files/upload',{method:'POST',body,signal:AbortSignal.timeout(10000)});},async restart(){await connection.network.close();await controller.retire();await uploads.drain();await files.close();files=await PublishedPrintFiles.open(root);gate=new MaintenanceGate();uploads=options.persistent?await NativePrintUploads.open(files,gate,{stagingRoot:dir,metadataRoot:join(dir,'metadata')}):new NativePrintUploads(files,gate,{stagingRoot:dir});controller=new PrintController({async prepare(){},async start(){starts++;},async pause(){},async resume(){},async finish(){},async stop(){}},{maxNozzle:300,maxBed:130},{},{maintenanceGate:gate});uploads.bindPrintController(controller);connection=await connect();},async close(){await connection.network.close();await controller.retire();await uploads.drain();await files.close();await rm(dir,{recursive:true,force:true});}};
}
async function preview(f:Awaited<ReturnType<typeof fixture>>,filename:string){const fields=await f.uploads.metadata({filename},signal()),thumbnails=fields.thumbnails as Record<string,unknown>[];assert.equal(thumbnails.length,2);const path='/server/files/gcodes/'+[...filename.split('/').slice(0,-1),String(thumbnails.at(-1)!.relative_path)].join('/').split('/').map(encodeURIComponent).join('/');const response=await fetch(f.url+path);assert.equal(response.status,200);return {fields,path,bytes:Buffer.from(await response.arrayBuffer())};}
for(const persistent of [false,true])test(`real multipart UFP publishes exact model plus external PNG and recovers metadata (persistent=${persistent})`,async()=>{
 const image=await png(),archive=packed(model,image),f=await fixture({persistent});try{
  const response=await f.post(archive,'模型.UFP',{path:'零件/试验',checksum:sha(archive)});assert.equal(response.status,201);const result=(await response.json()).result;
  assert.equal(response.headers.get('location'),f.url+'/server/files/gcodes/'+result.item.path.split('/').map(encodeURIComponent).join('/'));
  assert.equal(result.item.path,'零件/试验/模型.gcode');assert.equal(result.file.size,model.length);assert.equal(result.file.sha256,sha(model));assert.deepEqual(result.file.preview,{sha256:sha(image),size:image.length});assert.equal(result.print_started,false);assert.equal(f.starts,0);
  assert.deepEqual((await f.files.readBytes(result.file.id,signal())).bytes,model);assert.deepEqual((await f.files.readPreview(result.file.id,signal()))!.bytes,image);
  const first=await preview(f,result.item.path);assert.deepEqual(first.bytes,image);assert.equal(first.fields.file_id,result.file.id);assert.equal(first.fields.sha256,sha(model));
  await f.restart();const second=await preview(f,result.item.path);assert.deepEqual(second.bytes,image);if(persistent){assert.deepEqual(second.fields,first.fields);assert.equal(second.path,first.path);assert('scans' in f.uploads.status.metadata);assert.equal(f.uploads.status.metadata.scans,0);}assert.equal(f.starts,0);assert.deepEqual((await f.files.readBytes(result.file.id,signal())).bytes,model);
  assert.equal((await readdir(f.dir)).filter(name=>name.startsWith('anyraid-upload-')).length,0);
 }finally{await f.close();}
});
for(const kind of ['checksum','crc','truncated-png','missing-model','model-capacity'])test(`UFP ${kind} rejects before publishing or creating requested parents`,async()=>{
 const image=await png(),f=await fixture({max:kind==='model-capacity'?1024:undefined});let archive=packed(model,image),fields:Record<string,string>={path:'must/not/exist'};
 if(kind==='checksum')fields.checksum='0'.repeat(64);
 if(kind==='crc')archive=ufpFixture([{name:'/3D/model.gcode',data:model,crc:1}]);
 if(kind==='truncated-png')archive=packed(model,image.subarray(0,33));
 if(kind==='missing-model')archive=ufpFixture([{name:'/Metadata/thumbnail.png',data:image}]);
 if(kind==='model-capacity')archive=packed(Buffer.alloc(4096,32));
 try{const response=await f.post(archive,'part.ufp',fields);assert.equal(response.status,kind==='model-capacity'?413:422);await response.arrayBuffer();assert.equal(f.files.status.publishedFiles,0);assert.equal(await f.files.hasDirectory('must',signal()),false);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.png')||name.endsWith('.gcode')).length,0);assert.equal((await readdir(f.dir)).filter(name=>name.startsWith('anyraid-upload-')).length,0);assert.equal(f.starts,0);}finally{await f.close();}
});
test('transformed model identity is independently authorized before any visible mutation',async()=>{
 const authorized:any[]=[],f=await fixture({authorize(method,params){if(method==='server.files.upload'){authorized.push(params);if(params.filename==='part.gcode')throw new ApiError(403,'Model destination denied');}}});try{
  const response=await f.post(packed(model,await png()),'part.ufp',{path:'denied/new'});assert.equal(response.status,403);await response.arrayBuffer();assert(authorized.some(row=>row.filename==='part.ufp'));assert(authorized.some(row=>row.filename==='part.gcode'&&row.sha256===sha(model)&&row.size===model.length));assert.equal(f.files.status.publishedFiles,0);assert.equal(await f.files.hasDirectory('denied',signal()),false);assert.equal(f.starts,0);
 }finally{await f.close();}
});
test('plain G-code overwrite retires UFP preview and old download URLs after durable replacement',async()=>{
 const image=await png(),f=await fixture({persistent:true});try{
  const first=await f.post(packed(model,image),'part.ufp');assert.equal(first.status,201);const created=(await first.json()).result,old=await preview(f,'part.gcode');
  const replacement=Buffer.from('G1 X9\r\n'),response=await f.post(replacement,'part.gcode');assert.equal(response.status,201);const next=(await response.json()).result;assert.notEqual(next.file.id,created.file.id);assert.equal(next.file.preview,undefined);assert.deepEqual((await f.files.readBytes(next.file.id,signal())).bytes,replacement);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.png')).length,0);
  assert.equal((await fetch(f.url+old.path)).status,404);await f.restart();assert.equal(((await f.uploads.metadata({filename:'part.gcode'},signal())).thumbnails as unknown[]).length,0);assert.equal(f.starts,0);
 }finally{await f.close();}
});
test('embedded thumbnail wins over separate UFP PNG without modifying print bytes',async()=>{
 const external=await png(),embedded=await sharp({create:{width:32,height:32,channels:3,background:'red'}}).png().toBuffer(),base64=embedded.toString('base64'),data=Buffer.concat([Buffer.from(`; generated by Cura_SteamEngine 5.10.0\n; thumbnail begin 32x32 ${base64.length}\n; ${base64}\n; thumbnail end\n`),model]),f=await fixture();try{
  const response=await f.post(packed(data,external),'inline.ufp');assert.equal(response.status,201);const result=(await response.json()).result;assert.deepEqual((await f.files.readBytes(result.file.id,signal())).bytes,data);
  const fields=await f.uploads.metadata({filename:'inline.gcode'},signal()),images=fields.thumbnails as any[];assert.equal(images.length,1);const path='/server/files/gcodes/'+images[0].relative_path;const thumbnail=await fetch(f.url+path);assert.equal(thumbnail.status,200);assert.deepEqual(Buffer.from(await thumbnail.arrayBuffer()),embedded);assert.equal(f.starts,0);
 }finally{await f.close();}
});
test('explicit UFP print intent preserves a complete receipt when print admission is unavailable',async()=>{
 const image=await png(),f=await fixture();try{const response=await f.post(packed(model,image),'part.ufp',{print:'true'});assert.equal(response.status,201);const result=(await response.json()).result;assert.equal(result.print_started,false);assert.equal(result.print_error.code,503);assert.deepEqual((await f.files.readBytes(result.file.id,signal())).bytes,model);assert.deepEqual((await f.files.readPreview(result.file.id,signal()))!.bytes,image);assert.equal(f.starts,0);assert.equal((await readdir(f.dir)).filter(name=>name.startsWith('anyraid-upload-')).length,0);}finally{await f.close();}
});
test('closing UFP owner drains held image preparation without publishing or replaying',async t=>{
 const f=await fixture(),entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),prepare=ThumbnailProcessor.prototype.prepareUfpPng;let settled=false;
 t.mock.method(ThumbnailProcessor.prototype,'prepareUfpPng',async function(this:Awaited<ReturnType<typeof ThumbnailProcessor.open>>,bytes:Buffer,input:AbortSignal){entered.resolve();await release.promise;return prepare.call(this,bytes,input);});
 try{const posting=f.post(packed(model,await png()),'part.ufp',{path:'held/new'});await entered.promise;const closing=f.uploads.close().then(()=>{settled=true;});await new Promise<void>(resolve=>setImmediate(resolve));assert.equal(settled,false);assert.equal(f.files.status.publishedFiles,0);release.resolve();const response=await posting;assert.equal(response.status,503);await response.arrayBuffer();await closing;assert.equal(await f.files.hasDirectory('held',signal()),false);assert.equal(f.files.status.publishedFiles,0);assert.equal(f.starts,0);assert.equal((await readdir(f.dir)).filter(name=>name.startsWith('anyraid-upload-')).length,0);}finally{release.resolve();t.mock.restoreAll();await f.close();}
});
