import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,open,rm,readdir,access,unlink,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import sharp from 'sharp';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
import {NativePrintUploads} from '../src/moonraker/native-print-uploads.ts';
import {NativeUfpDiskImports,type NativeUfpDiskImportOptions} from '../src/moonraker/native-ufp-disk-imports.ts';
import {MaintenanceGate} from '../src/operations/maintenance-gate.ts';
import {ApiError,type RpcContext} from '../src/moonraker/rpc.ts';
import {ufpFixture} from './helpers/ufp-fixture.ts';
const model=Buffer.from('; generated by Cura_SteamEngine 5.10.0\r\nG1 X12 Y23\r\n'),signal=()=>new AbortController().signal;
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
const packed=async()=>{const png=await sharp({create:{width:32,height:16,channels:4,background:{r:12,g:34,b:56,alpha:.5}}}).png().toBuffer();return {png,bytes:ufpFixture([{name:'/3D/model.gcode',data:model},{name:'/Metadata/thumbnail.png',data:png}])};};
const until=async(check:()=>boolean,owner?:NativeUfpDiskImports)=>{const end=performance.now()+10000;while(!check()){if(owner?.status.fault!==undefined)throw owner.status.fault;assert(performance.now()<end,'Disk import deadline exceeded');await new Promise<void>(resolve=>setTimeout(resolve,5));}};
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'disk-ledger-')),inbox=join(dir,'inbox'),root=join(dir,'files'),metadataRoot=join(dir,'metadata');await mkdir(inbox,{mode:0o700});let files=await PublishedPrintFiles.open(root),uploads=await NativePrintUploads.open(files,new MaintenanceGate(),{stagingRoot:dir,metadataRoot}),owner:NativeUfpDiskImports|undefined;const calls:{method:string;params:any}[]=[];
 const context=(input:AbortSignal):RpcContext=>({signal:input,transport:'unix',authorize:(method,params)=>{calls.push({method,params});}});
 return {dir,inbox,root,calls,get files(){return files;},get uploads(){return uploads;},get owner(){return owner;},async start(options:Partial<NativeUfpDiskImportOptions>={}){return owner=await NativeUfpDiskImports.open(uploads,files,{root:inbox,context,...options});},async reopen(){await owner?.close();owner=undefined;await uploads.drain();await files.close();files=await PublishedPrintFiles.open(root);uploads=await NativePrintUploads.open(files,new MaintenanceGate(),{stagingRoot:dir,metadataRoot});},async close(){await owner?.close();await uploads.drain();await files.close();await rm(dir,{recursive:true,force:true});}};
}
test('real inbox close-write imports its exact model/PNG once, authorizes and removes only the completed original',async()=>{
 const f=await fixture(),archive=await packed(),writer=await open(join(f.inbox,'part.ufp'),'wx');await writer.writeFile(archive.bytes);
 try{const owner=await f.start();await owner.idle();assert.equal(f.files.status.publishedFiles,0);assert(owner.status.busy>0);await new Promise<void>(resolve=>setTimeout(resolve,25));assert.equal(f.files.status.publishedFiles,0);
  await writer.close();await until(()=>owner.status.completed===1,owner);await owner.idle();assert.equal(owner.status.fault,undefined);assert.equal(owner.status.claims,0);assert.equal(owner.status.claimBytes,0);assert.equal(f.files.status.publishedFiles,1);
  const [id]=await f.files.listIds(signal()),file=await f.files.inspect(id);assert.equal(file.path,'part.gcode');assert.equal(file.sha256,hash(model));assert.deepEqual((await f.files.readBytes(id,signal())).bytes,model);assert.deepEqual((await f.files.readPreview(id,signal()))!.bytes,archive.png);await assert.rejects(access(join(f.inbox,'part.ufp')),{code:'ENOENT'});assert.deepEqual(await readdir(join(f.inbox,'.native-ufp-claims')),[]);assert(f.calls.some(row=>row.method==='server.files.upload'&&row.params.sha256===hash(archive.bytes)));
  await f.reopen();const recovered=await f.start();await recovered.idle();assert.equal(f.files.status.publishedFiles,1);assert.equal(recovered.status.completed,0);
 }finally{if(writer.fd>=0)await writer.close();await f.close();}
});
test('startup and nested directory discovery import files that were already closed before watching',async()=>{
 const f=await fixture(),archive=await packed();try{await mkdir(join(f.inbox,'existing'));await writeFile(join(f.inbox,'existing','first.ufp'),archive.bytes);const owner=await f.start();await until(()=>owner.status.completed===1,owner);
  await mkdir(join(f.inbox,'new'));await writeFile(join(f.inbox,'new','second.ufp'),archive.bytes);await until(()=>owner.status.completed===2,owner);await owner.idle();const catalog=await f.files.catalog(signal());assert.deepEqual(catalog.map(row=>row.file.path).sort(),['existing/first.gcode','new/second.gcode']);assert.equal(owner.status.fault,undefined);
 }finally{await f.close();}
});
for(const phase of ['intent','claimed','published','decided','unlinked'] as const)test(`durable ${phase} interruption recovers once after both owners reopen`,async()=>{
 const f=await fixture(),archive=await packed(),cause=new Error('Controlled ledger interruption '+phase);let claimId='';try{await writeFile(join(f.inbox,'part.ufp'),archive.bytes);const owner=await f.start({checkpoint:(current,id)=>{if(current===phase){claimId=id;throw cause;}}});await until(()=>owner.status.fault!==undefined);assert.equal(owner.status.fault,cause);assert(claimId);await assert.rejects(owner.idle());assert.equal(f.files.status.publishedFiles,['published','decided','unlinked'].includes(phase)?1:0);
  await f.reopen();const recovered=await f.start();await recovered.idle();assert.equal(recovered.status.completed,1);assert.equal(recovered.status.claims,0);assert.equal(f.files.status.publishedFiles,1);assert.deepEqual((await f.files.readBytes(claimId,signal())).bytes,model);assert.deepEqual((await f.files.readPreview(claimId,signal()))!.bytes,archive.png);assert.deepEqual(await readdir(join(f.inbox,'.native-ufp-claims')),[]);await assert.rejects(access(join(f.inbox,'part.ufp')),{code:'ENOENT'});
 }finally{await f.close();}
});
test('invalid archive is durably quarantined with its original bytes and never becomes printable',async()=>{
 const f=await fixture(),bytes=Buffer.from('not a ZIP');try{await writeFile(join(f.inbox,'bad.ufp'),bytes);const owner=await f.start();await until(()=>owner.status.rejected===1,owner);await owner.idle();assert.equal(f.files.status.publishedFiles,0);assert.equal(owner.status.claims,1);const [id]=await readdir(join(f.inbox,'.native-ufp-claims'));assert.deepEqual(await readFile(join(f.inbox,'.native-ufp-claims',id,'source.ufp')),bytes);
  await f.reopen();const next=await f.start();await next.idle();assert.equal(next.status.rejected,1);assert.equal(f.files.status.publishedFiles,0);
 }finally{await f.close();}
});
test('denied process policy preserves the unclaimed inbox file',async()=>{
 const f=await fixture(),archive=await packed();try{await writeFile(join(f.inbox,'denied.ufp'),archive.bytes);const owner=await f.start({context:input=>({signal:input,transport:'unix',authorize:()=>{throw new ApiError(403,'Denied local write');}})});await until(()=>owner.status.rejected===1,owner);await owner.idle();assert.deepEqual(await readFile(join(f.inbox,'denied.ufp')),archive.bytes);assert.equal(f.files.status.publishedFiles,0);assert.deepEqual(await readdir(join(f.inbox,'.native-ufp-claims')),[]);}finally{await f.close();}
});
test('closing one of two writer descriptors and moving in an open file cannot admit unfinished input',async()=>{
 const f=await fixture(),archive=await packed(),original=join(f.dir,'staged'),first=await open(original,'wx');await first.writeFile(archive.bytes);const second=await open(original,'r+');try{const owner=await f.start();await rename(original,join(f.inbox,'moved.ufp'));await until(()=>owner.status.busy>0,owner);await first.close();await new Promise<void>(resolve=>setTimeout(resolve,30));assert.equal(f.files.status.publishedFiles,0);await second.close();await until(()=>owner.status.completed===1,owner);assert.equal(f.files.status.publishedFiles,1);}finally{if(first.fd>=0)await first.close();if(second.fd>=0)await second.close();await f.close();}
});
test('cleanup revocation preserves the decided original and never retries the print publication on restart',async()=>{
 const f=await fixture(),archive=await packed();let allowed=true;try{await writeFile(join(f.inbox,'part.ufp'),archive.bytes);const owner=await f.start({checkpoint:phase=>{if(phase==='decided')allowed=false;},context:input=>({signal:input,transport:'unix',authorize:()=>{if(!allowed)throw new ApiError(403,'Revoked cleanup');}})});await until(()=>owner.status.rejected===1,owner);await owner.idle();assert.equal(f.files.status.publishedFiles,1);const [id]=await readdir(join(f.inbox,'.native-ufp-claims'));assert.deepEqual(await readFile(join(f.inbox,'.native-ufp-claims',id,'source.ufp')),archive.bytes);await access(join(f.inbox,'.native-ufp-claims',id,'decision.json'));await f.reopen();const recovered=await f.start();await recovered.idle();assert.equal(recovered.status.rejected,1);assert.equal(recovered.status.completed,0);assert.equal(f.files.status.publishedFiles,1);}finally{await f.close();}
});
test('a decision surviving partial ledger cleanup recovers without its already removed intent file',async()=>{
 const f=await fixture(),archive=await packed();let id='';try{await writeFile(join(f.inbox,'part.ufp'),archive.bytes);const owner=await f.start({checkpoint:(phase,claim)=>{if(phase==='unlinked'){id=claim;throw new Error('Controlled partial cleanup');}}});await until(()=>owner.status.fault!==undefined);await owner.close();await unlink(join(f.inbox,'.native-ufp-claims',id,'intent.json'));await f.reopen();const recovered=await f.start();await recovered.idle();assert.equal(recovered.status.completed,1);assert.equal(f.files.status.publishedFiles,1);assert.deepEqual(await readdir(join(f.inbox,'.native-ufp-claims')),[]);}finally{await f.close();}
});
test('changed claimed bytes prevent recovery cleanup and preserve the conflicting original',async()=>{
 const f=await fixture(),archive=await packed();let id='';try{await writeFile(join(f.inbox,'part.ufp'),archive.bytes);const owner=await f.start({checkpoint:(phase,claim)=>{if(phase==='claimed'){id=claim;throw new Error('Controlled claim hold');}}});await until(()=>owner.status.fault!==undefined);await owner.close();const changed=Buffer.alloc(archive.bytes.length,42);await writeFile(join(f.inbox,'.native-ufp-claims',id,'source.ufp'),changed);await f.reopen();await assert.rejects(f.start(),error=>error instanceof ApiError&&error.status===409);assert.deepEqual(await readFile(join(f.inbox,'.native-ufp-claims',id,'source.ufp')),changed);assert.equal(f.files.status.publishedFiles,0);}finally{await f.close();}
});
test('an unknown claim entry blocks recovery without removing unrelated data',async()=>{
 const f=await fixture();try{await mkdir(join(f.inbox,'.native-ufp-claims'),{mode:0o700});const unrelated=join(f.inbox,'.native-ufp-claims','operator-notes');await writeFile(unrelated,'keep me');await assert.rejects(f.start(),/Unknown/);assert.equal(await readFile(unrelated,'utf8'),'keep me');assert.equal(f.files.status.publishedFiles,0);}finally{await f.close();}
});
test('capacity limits preserve unclaimed input and report the exhausted byte budget',async()=>{
 const f=await fixture(),archive=await packed();try{await writeFile(join(f.inbox,'part.ufp'),archive.bytes);const owner=await f.start({maxClaimBytes:1});await owner.idle();assert.equal(owner.status.blocked,'bytes');assert.equal(owner.status.claims,0);assert.equal(f.files.status.publishedFiles,0);assert.deepEqual(await readFile(join(f.inbox,'part.ufp')),archive.bytes);}finally{await f.close();}
});
test('the immutable published store cannot be reused as the disk inbox',async()=>{
 const f=await fixture();try{await assert.rejects(f.start({root:f.root}),/separate/);await assert.rejects(access(join(f.root,'.native-ufp-claims')),{code:'ENOENT'});}finally{await f.close();}
});
test('startup drains bounded discovery batches beyond 256 denied archives without losing later entries',async()=>{
 const f=await fixture(),archive=await packed(),seen=new Set<string>();try{for(let i=0;i<258;i++)await writeFile(join(f.inbox,`denied-${i}.ufp`),archive.bytes);const owner=await f.start({context:input=>({signal:input,transport:'unix',authorize:(_method,params)=>{seen.add(String(params.path));throw new ApiError(403,'Controlled inbox denial');}})});await owner.idle();assert.equal(owner.status.fault,undefined);assert.equal(owner.status.rejected,258);assert.equal(seen.size,258);assert.equal(owner.status.pending,0);assert.equal(f.files.status.publishedFiles,0);assert.equal((await readdir(f.inbox)).filter(name=>name.endsWith('.ufp')).length,258);}finally{await f.close();}
});
test('a corrupted published PNG prevents original cleanup even after the durable decision',async()=>{
 const f=await fixture(),archive=await packed();let id='';try{await writeFile(join(f.inbox,'part.ufp'),archive.bytes);const owner=await f.start({checkpoint:async(phase,claim)=>{if(phase==='decided'){id=claim;await writeFile(join(f.root,hash(archive.png)+'.png'),Buffer.alloc(archive.png.length,42));}}});await until(()=>owner.status.fault!==undefined);await assert.rejects(owner.idle());assert.equal(owner.status.completed,0);assert.deepEqual(await readFile(join(f.inbox,'.native-ufp-claims',id,'source.ufp')),archive.bytes);await access(join(f.inbox,'.native-ufp-claims',id,'decision.json'));assert.equal(f.files.status.publishedFiles,1);}finally{await f.close();}
});
for(const stoppedPhase of ['claimed','decided'] as const)test(`SIGKILL at ${stoppedPhase} releases process ownership and recovers the same durable identity`,{timeout:20000},async()=>{
 const dir=await mkdtemp(join(tmpdir(),'disk-ledger-kill-')),inbox=join(dir,'inbox'),root=join(dir,'files'),metadataRoot=join(dir,'metadata');await mkdir(inbox,{mode:0o700});const bytes=ufpFixture([{name:'/3D/model.gcode',data:model}]);await writeFile(join(inbox,'part.ufp'),bytes);
 const ext=import.meta.url.endsWith('.ts')?'ts':'js',url=(name:string)=>new URL('../src/'+name+'.'+ext,import.meta.url).href;
 const script=`
  import {PublishedPrintFiles} from ${JSON.stringify(url('storage/published-files'))};
  import {NativePrintUploads} from ${JSON.stringify(url('moonraker/native-print-uploads'))};
  import {NativeUfpDiskImports} from ${JSON.stringify(url('moonraker/native-ufp-disk-imports'))};
  import {MaintenanceGate} from ${JSON.stringify(url('operations/maintenance-gate'))};
  import {readFile} from 'node:fs/promises';
  process.on('message',()=>{});
  const files=await PublishedPrintFiles.open(${JSON.stringify(root)}),uploads=await NativePrintUploads.open(files,new MaintenanceGate(),{stagingRoot:${JSON.stringify(dir)},metadataRoot:${JSON.stringify(metadataRoot)}});
  await NativeUfpDiskImports.open(uploads,files,{root:${JSON.stringify(inbox)},context:signal=>({signal,transport:'unix',authorize(){}}),checkpoint:async(phase,id)=>{if(phase===${JSON.stringify(stoppedPhase)}){process.send({phase,id,children:await readFile('/proc/self/task/'+process.pid+'/children','utf8')});await new Promise(()=>{});}}});`;
 const child=spawn(process.execPath,['--input-type=module','-e',script],{stdio:['ignore','ignore','pipe','ipc']});let stderr='';child.stderr!.on('data',bytes=>{stderr+=bytes;});const exit=once(child,'exit');let files:PublishedPrintFiles|undefined,uploads:NativePrintUploads|undefined,owner:NativeUfpDiskImports|undefined;
 try{const message=await Promise.race([once(child,'message').then(([value])=>value as {phase:string;id:string;children:string}),exit.then(()=>{throw new Error('Import child exited before checkpoint: '+stderr);})]);assert.equal(message.phase,stoppedPhase);assert(message.children.trim());child.kill('SIGKILL');const [,terminated]=await exit;assert.equal(terminated,'SIGKILL');
  files=await PublishedPrintFiles.open(root);uploads=await NativePrintUploads.open(files,new MaintenanceGate(),{stagingRoot:dir,metadataRoot});owner=await NativeUfpDiskImports.open(uploads,files,{root:inbox,context:input=>({signal:input,transport:'unix',authorize(){}})});await owner.idle();assert.equal(owner.status.completed,1);assert.equal(files.status.publishedFiles,1);assert.deepEqual((await files.readBytes(message.id,signal())).bytes,model);assert.deepEqual(await readdir(join(inbox,'.native-ufp-claims')),[]);await assert.rejects(access(join(inbox,'part.ufp')),{code:'ENOENT'});
  for(const pid of message.children.trim().split(/\s+/))await until(()=>!processAlive(pid));
 }finally{if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');await exit;await owner?.close();await uploads?.drain();await files?.close();await rm(dir,{recursive:true,force:true});}
});
function processAlive(pid:string){try{process.kill(Number(pid),0);return true;}catch(error){if((error as NodeJS.ErrnoException).code==='ESRCH')return false;throw error;}}
