import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,open,rm,readdir,chmod,type FileHandle} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
import {NativePrintUploads} from '../src/moonraker/native-print-uploads.ts';
import {MaintenanceGate} from '../src/operations/maintenance-gate.ts';
import {PrintController} from '../src/operations/print.ts';
import {ThumbnailProcessor} from '../src/moonraker/thumbnail-process.ts';
import {ApiError,type RpcContext} from '../src/moonraker/rpc.ts';
import {ufpFixture} from './helpers/ufp-fixture.ts';
const model=Buffer.from('; generated by Cura_SteamEngine 5.10.0\r\nG1 X1 Y2\r\n');
const digest=(value:Buffer)=>createHash('sha256').update(value).digest('hex');
const signal=()=>new AbortController().signal;
const context=(authorize:RpcContext['authorize']=()=>{}):RpcContext=>({transport:'unix',signal:signal(),authorize});
const image=()=>sharp({create:{width:32,height:16,channels:4,background:{r:12,g:34,b:56,alpha:0.5}}}).png().toBuffer();
const packed=(png?:Buffer)=>ufpFixture([{name:'/3D/model.gcode',data:model},...png?[{name:'/Metadata/thumbnail.png',data:png}]:[]]);
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'ufp-descriptor-')),root=join(dir,'files'),gate=new MaintenanceGate(),files=await PublishedPrintFiles.open(root),uploads=await NativePrintUploads.open(files,gate,{stagingRoot:dir,metadataRoot:join(dir,'metadata')});
 let starts=0;const controller=new PrintController({async prepare(){},async start(){starts++;},async pause(){},async resume(){},async finish(){},async stop(){}},{maxNozzle:300,maxBed:130},{},{maintenanceGate:gate});uploads.bindPrintController(controller);
 const handles:FileHandle[]=[];
 return {dir,root,files,uploads,controller,get starts(){return starts;},async source(bytes:Buffer){const path=join(dir,'source-'+handles.length+'.ufp');await writeFile(path,bytes);const fd=await open(path,'r');handles.push(fd);return {path,fd};},async clean(){assert.equal((await readdir(dir)).filter(name=>name.startsWith('anyraid-import-')).length,0);assert.equal(uploads.status.pending,0);assert.equal(uploads.status.mutations,0);},async close(){await controller.retire();await uploads.drain();await files.close();await Promise.all(handles.map(fd=>fd.close()));await rm(dir,{recursive:true,force:true});}};
}
test('descriptor import publishes the exact pair, authorizes both identities and preserves the borrowed source position',async()=>{
 const f=await fixture(),png=await image(),archive=packed(png),calls:{method:string;params:any}[]=[];
 try{
  const source=await f.source(archive),prefix=Buffer.alloc(5);await source.fd.read(prefix,0,5,null);
  const result=await f.uploads.importUfp(source.fd,'子目录/部件.UFP',context((method,params)=>{calls.push({method,params});})) as any;
  assert.equal(result.item.path,'子目录/部件.gcode');assert.equal(result.file.sha256,digest(model));assert.equal(result.file.size,model.length);assert.deepEqual(result.file.preview,{sha256:digest(png),size:png.length});
  assert.deepEqual((await f.files.readBytes(result.file.id,signal())).bytes,model);assert.deepEqual((await f.files.readPreview(result.file.id,signal()))!.bytes,png);
  assert(calls.some(row=>row.method==='server.files.upload'&&row.params.filename==='部件.UFP'&&row.params.sha256===digest(archive)));
  assert(calls.some(row=>row.method==='server.files.upload'&&row.params.filename==='部件.gcode'&&row.params.sha256===digest(model)));
  assert(calls.some(row=>row.method==='server.files.post_directory'&&row.params.path==='gcodes/子目录'));
  const next=Buffer.alloc(1);assert.equal((await source.fd.read(next,0,1,null)).bytesRead,1);assert.equal(next[0],archive[5]);assert.equal((await source.fd.stat()).size,archive.length);
  const metadata=await f.uploads.metadata({filename:result.item.path},signal());assert.equal(metadata.file_id,result.file.id);assert.equal((metadata.thumbnails as any[]).length,2);assert.equal(f.starts,0);assert.equal(result.print_started,false);await f.clean();
 }finally{await f.close();}
});
for(const denied of ['archive','model','parent'])test(`descriptor import denied ${denied} authorization leaves no pair or requested directories`,async()=>{
 const f=await fixture();try{const source=await f.source(packed(await image()));await assert.rejects(f.uploads.importUfp(source.fd,'denied/part.ufp',context((method,params)=>{if(denied==='archive'&&params.filename==='part.ufp'||denied==='model'&&params.filename==='part.gcode'||denied==='parent'&&method==='server.files.post_directory')throw new ApiError(403,'Denied import');})),error=>error instanceof ApiError&&error.status===403);assert.equal(f.files.status.publishedFiles,0);assert.equal(await f.files.hasDirectory('denied',signal()),false);assert.equal(f.starts,0);assert((await source.fd.stat()).size>0);await f.clean();}finally{await f.close();}
});
test('descriptor import detects archive modification while transformed model authorization is held',async()=>{
 const f=await fixture();try{const source=await f.source(packed());await assert.rejects(f.uploads.importUfp(source.fd,'changed/part.ufp',context(async(_method,params)=>{if(params.filename==='part.gcode')await writeFile(source.path,Buffer.from('replacement archive'));})),error=>error instanceof ApiError&&error.status===409);assert.equal(f.files.status.publishedFiles,0);assert.equal(await f.files.hasDirectory('changed',signal()),false);await f.clean();}finally{await f.close();}
});
test('descriptor import replacement uses the existing destination mutation protection and retires the old preview',async()=>{
 const f=await fixture();try{
  const firstSource=await f.source(packed(await image())),first=await f.uploads.importUfp(firstSource.fd,'part.ufp',context()) as any,release=f.controller.beginFileMutation(first.file.id),nextSource=await f.source(packed());
  try{await assert.rejects(f.uploads.importUfp(nextSource.fd,'part.ufp',context()),error=>error instanceof ApiError&&error.status===403);assert.deepEqual((await f.files.describe(first.file.id,signal())).file,first.file);}finally{release();}
  const next=await f.uploads.importUfp(nextSource.fd,'part.ufp',context()) as any;assert.notEqual(first.file.id,next.file.id);assert.equal(next.file.preview,undefined);assert.deepEqual((await f.files.readBytes(next.file.id,signal())).bytes,model);assert.equal((await readdir(f.root)).filter(name=>name.endsWith('.png')).length,0);assert.equal(f.starts,0);await f.clean();
 }finally{await f.close();}
});
test('descriptor import rechecks the archive after replacement authorization and retires its mutation lease on rejection',async()=>{
 const f=await fixture();try{
  const firstSource=await f.source(packed(await image())),first=await f.uploads.importUfp(firstSource.fd,'part.ufp',context()) as any,next=await f.source(packed());
  await assert.rejects(f.uploads.importUfp(next.fd,'part.ufp',context(async(_method,params)=>{if(params.target_file_id)await writeFile(next.path,Buffer.from('changed during replacement authorization'));})),error=>error instanceof ApiError&&error.status===409);
  assert.deepEqual((await f.files.describe(first.file.id,signal())).file,first.file);const release=f.controller.beginFileMutation(first.file.id);release();assert.equal(f.files.status.publishedFiles,1);assert.equal(f.starts,0);await f.clean();
 }finally{await f.close();}
});
test('descriptor import close drains held image validation and keeps the original archive without publication',async t=>{
 const f=await fixture(),entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),prepare=ThumbnailProcessor.prototype.prepareUfpPng;let closed=false;
 t.mock.method(ThumbnailProcessor.prototype,'prepareUfpPng',async function(this:Awaited<ReturnType<typeof ThumbnailProcessor.open>>,bytes:Buffer,input:AbortSignal){entered.resolve();await release.promise;return prepare.call(this,bytes,input);});
 try{const source=await f.source(packed(await image())),importing=f.uploads.importUfp(source.fd,'held/part.ufp',context()),rejected=assert.rejects(importing,error=>error instanceof ApiError&&error.status===503);await entered.promise;const closing=f.uploads.close().then(()=>{closed=true;});await new Promise<void>(resolve=>setImmediate(resolve));assert.equal(closed,false);release.resolve();await rejected;await closing;assert.equal(f.files.status.publishedFiles,0);assert.equal(await f.files.hasDirectory('held',signal()),false);assert((await source.fd.stat()).size>0);await f.clean();}finally{release.resolve();t.mock.restoreAll();await f.close();}
});
test('stable claim replay verifies the durable pair without replacing its identity or starting a print',async()=>{
 const f=await fixture();try{
  const source=await f.source(packed(await image())),first=await f.uploads.importUfp(source.fd,'recovered/part.ufp',context(),'disk-claim-1') as any;
  const replay=await f.uploads.importUfp(source.fd,'recovered/part.ufp',context(),'disk-claim-1') as any;
  assert.deepEqual(replay,first);assert.equal(f.files.status.publishedFiles,1);assert.equal(f.uploads.status.published,1);assert.equal(f.starts,0);
  const different=await f.source(packed());await assert.rejects(f.uploads.importUfp(different.fd,'recovered/part.ufp',context(),'disk-claim-1'),error=>error instanceof ApiError&&error.status===409);
  await assert.rejects(f.uploads.importUfp(source.fd,'other.ufp',context(),'disk-claim-1'),error=>error instanceof ApiError&&error.status===409);
  await assert.rejects(f.uploads.importUfp(source.fd,'recovered/part.ufp',context(()=>{throw new ApiError(403,'Denied replay');}),'disk-claim-1'),error=>error instanceof ApiError&&error.status===403);
  await assert.rejects(f.uploads.importUfp(source.fd,'part.ufp',context(),'../foreign'),error=>error instanceof ApiError&&error.status===400);assert.equal(f.files.status.publishedFiles,1);await f.clean();
 }finally{await f.close();}
});
for(const blob of ['model','preview'])test(`claim replay rejects a same-sized corrupted ${blob} instead of trusting its receipt`,async()=>{
 const f=await fixture();try{
  const source=await f.source(packed(await image())),first=await f.uploads.importUfp(source.fd,'part.ufp',context(),'disk-corrupt-'+blob) as any,identity=blob==='model'?first.file:first.file.preview,path=join(f.root,identity.sha256+(blob==='model'?'.gcode':'.png'));
  await chmod(path,0o600);await writeFile(path,Buffer.alloc(identity.size,42));
  await assert.rejects(f.uploads.importUfp(source.fd,'part.ufp',context(),'disk-corrupt-'+blob),/digest mismatch/);assert.equal(f.files.status.publishedFiles,1);assert.equal(f.starts,0);await f.clean();
 }finally{await f.close();}
});
test('stable claim recovers after both the process upload owner and file store reopen',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'ufp-claim-reopen-')),root=join(dir,'files'),metadataRoot=join(dir,'metadata'),path=join(dir,'original.ufp');await writeFile(path,packed(await image()));const source=await open(path,'r');
 let files:PublishedPrintFiles|undefined,uploads:NativePrintUploads|undefined;const results:any[]=[];
 try{for(let generation=0;generation<2;generation++){
  files=await PublishedPrintFiles.open(root);uploads=await NativePrintUploads.open(files,new MaintenanceGate(),{stagingRoot:dir,metadataRoot});
  results.push(await uploads.importUfp(source,'restored/part.ufp',context(),'disk-restart-identity'));assert.equal(files.status.publishedFiles,1);assert.equal(uploads.status.published,generation===0?1:0);
  assert.deepEqual((await files.readBytes('disk-restart-identity',signal())).bytes,model);await uploads.drain();uploads=undefined;await files.close();files=undefined;
 }assert.deepEqual(results[1].file,results[0].file);assert.equal(results[1].item.modified,results[0].item.modified);assert.equal(results[1].print_started,false);assert.equal((await source.stat()).size,(await open(path,'r').then(async fd=>{try{return (await fd.stat()).size;}finally{await fd.close();}})));}finally{await uploads?.drain();await files?.close();await source.close();await rm(dir,{recursive:true,force:true});}
});
