import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,access} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {createNativeProductHostFactory} from '../src/runtime/native-product-machine.ts';
import {runProductHost} from '../src/runtime/product-host.ts';
import {ProductHostControl} from '../src/runtime/product-host-control.ts';
import {ApiError} from '../src/moonraker/rpc.ts';
import {productMachineFixture} from './helpers/product-machine.ts';
import {ufpFixture} from './helpers/ufp-fixture.ts';
const information={connected:false,state:'disconnected' as const,components:[],failedComponents:[],directories:[],warnings:[],version:'disk-test',missingRequirements:[]};
const model=Buffer.from('; generated by Cura_SteamEngine 5.10.0\r\nG1 X1 Y2\r\n'),archive=ufpFixture([{name:'/3D/model.gcode',data:model}]);
test('configured process factory imports the real inbox across software device generations through one file owner',async()=>{
 const root=await mkdtemp(join(tmpdir(),'native-product-disk-')),inbox=join(root,'inbox'),abort=new AbortController(),control=new ProductHostControl(),ready=Promise.withResolvers<string>();
 const fixture=await productMachineFixture(root);let processOpens=0,processCloses=0,devices=0,allowed=true;const localCalls:string[]=[],instances=[fixture];
 const native=createNativeProductHostFactory(fixture.path,{filesRoot:join(root,'files'),metadataRoot:join(root,'metadata'),diskImports:{root:inbox},
  async createProcess(){processOpens++;return {server:{information,authorize(){},authorizeNotification(){}},diskImportContext:signal=>({signal,transport:'unix',authorize(method,params){assert(['server.files.upload','server.files.post_directory'].includes(method));if(params.root!==undefined)assert.equal(params.root,'gcodes');localCalls.push(method);if(!allowed)throw new ApiError(403,'Controlled local policy revoked');}}),async release(){processCloses++;}};},
  async createAdapter(){const current=devices++?await productMachineFixture(root):fixture;if(current!==fixture)instances.push(current);return {stops:current.bindings.stops,output:current.bindings.print.output,lifecycle:current.bindings.print.lifecycle,async authorizePrintFile(){},release:()=>current.close()};}
 });
 const running=runProductHost(native,abort.signal,address=>ready.resolve(`http://127.0.0.1:${address.port}`),control);void running.catch(error=>ready.reject(error));
 try{const base=await ready.promise,get=async()=>{const result=await fetch(base+'/server/files/list');assert.equal(result.status,200);return (await result.json() as any).result as any[];},until=async(count:number)=>{const end=performance.now()+10000;for(;;){if(native.diskImportStatus?.fault)throw native.diskImportStatus.fault;const files=await get();if(files.length===count)return files;assert(performance.now()<end,'Product disk import deadline');await new Promise<void>(resolve=>setTimeout(resolve,5));}},untilComplete=async(count:number)=>{const end=performance.now()+10000;while(native.diskImportStatus?.completed!==count){if(native.diskImportStatus?.fault)throw native.diskImportStatus.fault;assert(performance.now()<end,'Product disk cleanup deadline');await new Promise<void>(resolve=>setTimeout(resolve,5));}};
  await writeFile(join(inbox,'first.ufp'),archive);const [first]=await until(1);assert.equal(first.path,'first.gcode');assert.equal(first.sha256,createHash('sha256').update(model).digest('hex'));await untilComplete(1);await assert.rejects(access(join(inbox,'first.ufp')),{code:'ENOENT'});
  await writeFile(join(inbox,'first.ufp'),archive);await untilComplete(2);const [replaced]=await get();assert.equal(replaced.path,'first.gcode');assert.notEqual(replaced.file_id,first.file_id);
  await control.reinitialize();await writeFile(join(inbox,'second.ufp'),archive);const files=await until(2);assert.deepEqual(files.map(row=>row.path).sort(),['first.gcode','second.gcode']);await untilComplete(3);assert.equal(processOpens,1);assert.equal(devices,2);assert(localCalls.length>=8);
  allowed=false;await writeFile(join(inbox,'denied.ufp'),archive);await new Promise<void>(resolve=>setTimeout(resolve,50));assert.equal((await get()).length,2);await access(join(inbox,'denied.ufp'));
  const print=await fetch(base+'/printer/objects/query?print_stats');assert.equal(print.status,200);assert.equal((await print.json() as any).result.status.print_stats.state,'standby');
 }finally{abort.abort();await running;await native.close!();for(const current of instances)await current.close();await rm(root,{recursive:true,force:true});}assert.equal(processCloses,1);
});
