import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PinResolver,PrinterPins} from '../src/protocol/pins.ts';
import {MessageDictionary} from '../src/protocol/dictionary.ts';
import {configureMCU} from '../src/protocol/mcu-config.ts';
import {crc32} from 'node:zlib';
test('forward aliases flatten and apply to pin and suffixed pin parameters',()=>{const p=new PinResolver();p.alias('STEP','HEADER');p.alias('HEADER','PA0');assert.deepEqual(p.resolve(['config pin=STEP dir_pin=PB1','init pin=STEP']),['config pin=PA0 dir_pin=PB1','init pin=PA0']);assert.throws(()=>p.resolve(['config pin=HEADER']),/alias/);assert.throws(()=>p.alias('STEP','PB1'),/already/);});
test('reserved aliases, cycles and mixed spellings are rejected atomically',()=>{const p=new PinResolver();p.alias('STEP','PA0');p.reserve('PB1','debug');assert.throws(()=>p.resolve(['config pin=STEP','config pin=PB1']),/reserved/);assert.deepEqual(p.resolve(['config pin=PA0']),['config pin=PA0']);assert.throws(()=>p.reserve('PB1','uart'),/reserved/);assert.throws(()=>p.alias('PA0','STEP'),/Cyclic/);assert.throws(()=>p.alias('bad','!PA0'),/Invalid/);const permissive=new PinResolver(false);permissive.alias('STEP','PA0');assert.deepEqual(permissive.resolve(['c pin=STEP','c pin=PA0']),['c pin=PA0','c pin=PA0']);});
test('chip descriptors preserve pull-down and inversion flags and reject invalid capabilities',()=>{const p=new PrinterPins<object>(),chip={};p.register('mcu',chip);p.register('aux',{});const pin=p.parse(' ~ ! aux:PA0 ',{canInvert:true,canPullup:true});assert.equal(pin.pullup,-1);assert.equal(pin.invert,1);assert.equal(pin.chipName,'aux');assert.throws(()=>p.parse('!PA0'),/Invalid/);assert.throws(()=>p.parse('!^PA0',{canInvert:true,canPullup:true}),/Invalid/);assert.throws(()=>p.parse('missing:PA0'),/Unknown/);assert.throws(()=>p.parse(''),/Invalid/);assert.throws(()=>p.register('mcu',{}),/duplicate/);});
test('sharing requires matching type and polarity unless explicitly allowed',()=>{const p=new PrinterPins<object>();p.register('mcu',{});const first=p.lookup('!PA0',{canInvert:true,shareType:'enable'});assert.equal(p.lookup('!PA0',{canInvert:true,shareType:'enable'}),first);assert.throws(()=>p.lookup('PA0',{shareType:'enable'}),/polarity/);assert.throws(()=>p.lookup('!PA0',{canInvert:true}),/multiple/);p.allowMultiUse('PA0');assert.equal(p.lookup('PA0'),first);assert.throws(()=>p.resetSharing({...first}),/Unknown/);p.resetSharing(first);assert.notEqual(p.lookup('PA0'),first);});
test('configuration resolves aliases before CRC and rejects firmware-reserved pins before I/O',async()=>{
 const d=new MessageDictionary();d.identify(Buffer.from(JSON.stringify({commands:{get_config:2,'allocate_oids count=%c':3,'finalize_config crc=%u':4,'config_stepper oid=%c step_pin=%u':5},responses:{'config is_config=%c crc=%u is_shutdown=%c move_count=%hu':6},enumerations:{pin:{PA0:1,PB1:2}},config:{RESERVE_PINS_debug:'PB1'}})),false);
 const pins=new PinResolver();pins.alias('STEP','PA0');let reads=0,writes=0;const crc=crc32(Buffer.from('allocate_oids count=1\nconfig_stepper oid=0 step_pin=PA0'));
 const transport={async query(){return {message:{name:'config',parameters:{is_config:reads++?1:0,crc,is_shutdown:0,move_count:32}},sentTime:1,receiveTime:1};},async send(){writes++;},async stop(){}};
 assert.equal((await configureMCU(d,transport,{oidCount:1,commands:['config_stepper oid=0 step_pin=STEP'],pins},new AbortController().signal)).crc,crc);assert.equal(writes,3);
 reads=writes=0;pins.alias('DEBUG','PB1');await assert.rejects(configureMCU(d,transport,{oidCount:1,commands:['config_stepper oid=0 step_pin=DEBUG'],pins},new AbortController().signal),/reserved/);assert.equal(reads,0);assert.equal(writes,0);
});
