import test from 'node:test';
import assert from 'node:assert/strict';
import {open,mkdtemp,writeFile,readFile,readlink,readdir,rm,type FileHandle} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import sharp from 'sharp';
import {PublishedPrintFiles} from '../src/storage/published-files.ts';
const signal=new AbortController().signal;
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'published-durability-')),root=join(dir,'files'),model=Buffer.from('G1 X0.12345678901234567 E0.01\r\n'),png=await sharp({create:{width:32,height:32,channels:3,background:'blue'}}).png().toBuffer();await writeFile(join(dir,'model'),model);await writeFile(join(dir,'image'),png);
 const source=await open(join(dir,'model'),'r'),image=await open(join(dir,'image'),'r');let store=await PublishedPrintFiles.open(root);
 return {dir,root,model,png,source,image,get store(){return store;},publish:(id:string,s=signal)=>store.publish(id,id+'.gcode',source,s,undefined,image),async reopen(){await store.close();store=await PublishedPrintFiles.open(root);},async close(){await store.close();await source.close();await image.close();await rm(dir,{recursive:true,force:true});}};
}
for(const held of ['directory','receipt'] as const)test(`publication joins ${held} durability before exposing a receipt`,{timeout:15000},async t=>{
 const f=await fixture(),entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>(),otherDone=Promise.withResolvers<void>();let rootCalls=0,receiptCalls=0,events=0;
 try{const prototype=Object.getPrototypeOf(f.source) as FileHandle,original=prototype.sync;f.store.observeChanges(()=>{events++;});
  t.mock.method(prototype,'sync',async function(this:FileHandle){const path=await readlink('/proc/self/fd/'+this.fd),root=path===f.root,receipt=path.startsWith(f.root+'/.receipt-');if(root)rootCalls++;if(receipt)receiptCalls++;if(root&&rootCalls===1||receipt){const kind=root?'directory':'receipt';if(kind===held){entered.resolve();await resume.promise;}const value=await original.call(this);if(kind!==held)otherDone.resolve();return value;}return original.call(this);});
  let settled=false;const task=f.publish('part');void task.then(()=>{settled=true;},()=>{settled=true;});await Promise.all([entered.promise,otherDone.promise]);assert.equal(settled,false);assert.equal(events,0);assert.equal(f.store.status.publishedFiles,0);assert.equal(rootCalls,1);assert.equal(receiptCalls,1);assert(!(await readdir(f.root)).includes('part.json'));await assert.rejects(f.store.inspect('part'),{code:'ENOENT'});
  resume.resolve();const record=await task;t.mock.restoreAll();assert.equal(events,1);assert.equal(rootCalls,2);assert.equal(receiptCalls,1);assert.deepEqual((await f.store.readBytes('part',signal)).bytes,f.model);assert.deepEqual((await f.store.readPreview('part',signal))!.bytes,f.png);assert.equal(f.store.status.reservedBytes,0);assert(!(await readdir(f.root)).some(name=>name.startsWith('.')));await f.reopen();assert.deepEqual(await f.store.inspect('part'),record);
 }finally{resume.resolve();t.mock.restoreAll();await f.close();}
});
for(const failed of ['directory','receipt'] as const)for(const code of ['EIO','ENOSPC'])test(`${failed} durability ${code} joins the other write before close and preserves prior authority`,{timeout:15000},async t=>{
 const f=await fixture(),entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>(),failure=Object.assign(new Error('Injected '+failed+' durability failure'),{code});let roots=0,events=0;
 try{const prior=await f.publish('prior'),prototype=Object.getPrototypeOf(f.source) as FileHandle,original=prototype.sync;f.store.observeChanges(()=>{events++;});
  t.mock.method(prototype,'sync',async function(this:FileHandle){const path=await readlink('/proc/self/fd/'+this.fd),root=path===f.root,receipt=path.startsWith(f.root+'/.receipt-');if(root)roots++;if(root&&roots===1||receipt){const kind=root?'directory':'receipt';if(kind===failed)throw failure;entered.resolve();await resume.promise;}return original.call(this);});
  let settled=false,closed=false;const task=f.publish('uncommitted'),rejected=assert.rejects(task,error=>error===failure).then(()=>{settled=true;});await entered.promise;const closing=f.store.close().then(()=>{closed=true;});await delay(5);assert.equal(settled,false);assert.equal(closed,false);assert.equal(events,0);assert(!(await readdir(f.root)).includes('uncommitted.json'));assert(f.source.fd>=0&&f.image.fd>=0);resume.resolve();await rejected;await closing;t.mock.restoreAll();assert.equal(events,0);assert.equal(f.store.status.reservedBytes,0);assert(!(await readdir(f.root)).some(name=>name.startsWith('.')));await f.reopen();assert.deepEqual(await f.store.inspect('prior'),prior);assert.deepEqual((await f.store.readBytes('prior',signal)).bytes,f.model);assert.deepEqual((await f.store.readPreview('prior',signal))!.bytes,f.png);await assert.rejects(f.store.inspect('uncommitted'),{code:'ENOENT'});
 }finally{resume.resolve();t.mock.restoreAll();await f.close();}
});
test('both durability failures are retained without a published receipt or event',async t=>{
 const f=await fixture(),directoryError=Object.assign(new Error('directory failed'),{code:'EIO'}),receiptError=Object.assign(new Error('receipt failed'),{code:'ENOSPC'});let events=0;
 try{const prototype=Object.getPrototypeOf(f.source) as FileHandle,original=prototype.sync;f.store.observeChanges(()=>{events++;});t.mock.method(prototype,'sync',async function(this:FileHandle){const path=await readlink('/proc/self/fd/'+this.fd);if(path===f.root)throw directoryError;if(path.startsWith(f.root+'/.receipt-'))throw receiptError;return original.call(this);});await assert.rejects(f.publish('part'),error=>error instanceof AggregateError&&error.errors.length===2&&error.errors[0]===directoryError&&error.errors[1]===receiptError);t.mock.restoreAll();assert.equal(events,0);assert.equal(f.store.status.publishedFiles,0);assert.equal(f.store.status.reservedBytes,0);assert(!(await readdir(f.root)).some(name=>name.startsWith('.')));await f.reopen();assert.deepEqual(await f.store.listIds(signal),[]);assert.deepEqual(await readdir(f.root),[]);
 }finally{t.mock.restoreAll();await f.close();}
});
for(const held of ['directory','receipt'] as const)test(`cancellation while ${held} sync is active drains both barriers before cleanup`,{timeout:15000},async t=>{
 const f=await fixture(),abort=new AbortController(),entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>(),otherDone=Promise.withResolvers<void>();let roots=0,events=0;
 try{const prototype=Object.getPrototypeOf(f.source) as FileHandle,original=prototype.sync;f.store.observeChanges(()=>{events++;});t.mock.method(prototype,'sync',async function(this:FileHandle){const path=await readlink('/proc/self/fd/'+this.fd),root=path===f.root,receipt=path.startsWith(f.root+'/.receipt-');if(root)roots++;if(root&&roots===1||receipt){const kind=root?'directory':'receipt';if(kind===held){entered.resolve();await resume.promise;}const value=await original.call(this);if(kind!==held)otherDone.resolve();return value;}return original.call(this);});let settled=false;const task=f.publish('part',abort.signal),rejected=assert.rejects(task,/cancel before receipt publication/).then(()=>{settled=true;});await Promise.all([entered.promise,otherDone.promise]);abort.abort(new Error('cancel before receipt publication'));await delay(5);assert.equal(settled,false);assert.equal(events,0);assert(!(await readdir(f.root)).includes('part.json'));resume.resolve();await rejected;t.mock.restoreAll();assert.equal(f.store.status.reservedBytes,0);assert.equal(f.store.status.publishedFiles,0);assert(!(await readdir(f.root)).some(name=>name.startsWith('.')));await f.reopen();assert.deepEqual(await f.store.listIds(signal),[]);
 }finally{resume.resolve();t.mock.restoreAll();await f.close();}
});
test('final receipt-link directory sync still precedes success and create notification',{timeout:15000},async t=>{
 const f=await fixture(),entered=Promise.withResolvers<void>(),resume=Promise.withResolvers<void>();let roots=0,events=0;
 try{const prototype=Object.getPrototypeOf(f.source) as FileHandle,original=prototype.sync;f.store.observeChanges(()=>{events++;});t.mock.method(prototype,'sync',async function(this:FileHandle){if(await readlink('/proc/self/fd/'+this.fd)===f.root&&++roots===2){entered.resolve();await resume.promise;}return original.call(this);});let settled=false;const task=f.publish('part');void task.then(()=>{settled=true;},()=>{settled=true;});await entered.promise;assert((await readdir(f.root)).includes('part.json'));assert.equal(settled,false);assert.equal(events,0);resume.resolve();const record=await task;t.mock.restoreAll();assert.equal(events,1);await f.reopen();assert.deepEqual(await f.store.inspect('part'),record);
 }finally{resume.resolve();t.mock.restoreAll();await f.close();}
});
for(const completed of ['directory','receipt'] as const)test(`SIGKILL after only ${completed} preparation preserves prior model and PNG`,{timeout:15000},async()=>{
 const f=await fixture();let child:ReturnType<typeof spawn>|undefined,exited:Promise<unknown>|undefined;
 try{const prior=await f.publish('prior');await f.store.close();const url=new URL('../src/storage/published-files.'+(import.meta.url.endsWith('.ts')?'ts':'js'),import.meta.url).href;
  const code=`import {open,readlink} from 'node:fs/promises';import {PublishedPrintFiles} from ${JSON.stringify(url)};process.on('message',()=>{});const root=process.argv[1],completed=process.argv[4],source=await open(process.argv[2],'r'),image=await open(process.argv[3],'r'),store=await PublishedPrintFiles.open(root),prototype=Object.getPrototypeOf(source),original=prototype.sync;let roots=0;prototype.sync=async function(){const path=await readlink('/proc/self/fd/'+this.fd),directory=path===root,receipt=path.startsWith(root+'/.receipt-');if(directory)roots++;if(directory&&roots===1||receipt){const kind=directory?'directory':'receipt';if(kind!==completed)return new Promise(()=>{});await original.call(this);await new Promise(resolve=>process.send('one-preparation-durable',resolve));return;}return original.call(this);};await store.publish('interrupted','part.gcode',source,new AbortController().signal,undefined,image);throw Error('Publication must remain blocked');`;
  child=spawn(process.execPath,['--input-type=module','-e',code,f.root,join(f.dir,'model'),join(f.dir,'image'),completed],{stdio:['ignore','ignore','pipe','ipc']});let stderr='';const current=child;child.stderr!.on('data',data=>{stderr+=data;if(stderr.length>65536)current.kill('SIGKILL');});exited=once(child,'exit');await Promise.race([once(child,'message',{signal:AbortSignal.timeout(10000)}).then(([value])=>assert.equal(value,'one-preparation-durable')),exited.then(()=>{throw Error('Crash control exited before barrier: '+stderr);})]);assert(!(await readdir(f.root)).includes('interrupted.json'));assert((await readdir(f.root)).some(name=>name.startsWith('.receipt-'))||completed==='directory');assert(current.kill('SIGKILL'));await exited;assert.equal(current.signalCode,'SIGKILL');await f.reopen();assert.deepEqual(await f.store.inspect('prior'),prior);assert.deepEqual((await f.store.readBytes('prior',signal)).bytes,f.model);assert.deepEqual((await f.store.readPreview('prior',signal))!.bytes,f.png);assert.equal(f.store.status.reservedBytes,0);await assert.rejects(f.store.inspect('interrupted'),{code:'ENOENT'});assert(!(await readdir(f.root)).some(name=>name.startsWith('.')));await f.publish('retry');
 }finally{if(child&&child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');await exited;await f.close();}
});
