import {test} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {WebSocket} from 'ws';
import {setTimeout as delay} from 'node:timers/promises';
import {ResponseCompletion} from '../src/moonraker/response-completion.ts';
import {JsonRpcDispatcher} from '../src/moonraker/rpc.ts';
import {MoonrakerNetwork} from '../src/moonraker/server.ts';
async function until(fn:()=>boolean){for(let i=0;i<500;i++){if(fn())return;await delay(2);}throw new Error('Timed out');}
test('completion calls each callback once, bounds registrations and forbids late registration',()=>{const completion=new ResponseCompletion(new AbortController().signal),values:boolean[]=[];for(let i=0;i<256;i++)completion.add(sent=>values.push(sent));assert.throws(()=>completion.add(()=>{}),/capacity/);assert.equal(completion.complete(true),true);completion.complete(false);assert.deepEqual(values,Array(256).fill(true));assert.throws(()=>completion.add(()=>{}),/completed/);});
test('abort fails the barrier and callback errors cannot strand remaining cleanup',()=>{const controller=new AbortController(),completion=new ResponseCompletion(controller.signal),values:boolean[]=[];completion.add(()=>{throw new Error('failed');});completion.add(sent=>values.push(sent));assert.doesNotThrow(()=>controller.abort());assert.deepEqual(values,[false]);assert.ok(completion.error instanceof AggregateError);assert.equal(completion.complete(true),false);});
test('WebSocket batch response precedes notifications registered by each handler',async()=>{const rpc=new JsonRpcDispatcher(),network=new MoonrakerNetwork(rpc,{authorize(){},authorizeNotification(){}});rpc.register('test.subscribe',['websocket'],(p,c)=>{c.afterResponse!(sent=>{if(sent)void network.notifyAuthorized(c.connectionId!,'notify_state',[p.value]);});return {accepted:p.value};});const address=await network.listen(),ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`),received:any[]=[];try{await once(ws,'open');ws.on('message',m=>received.push(JSON.parse(String(m))));ws.send(JSON.stringify([1,2].map(id=>({jsonrpc:'2.0',method:'test.subscribe',id,params:{value:id}}))));await until(()=>received.length===3);assert.deepEqual(received[0].map((r:any)=>r.id),[1,2]);assert.deepEqual(received.slice(1).map(r=>r.params),[[1],[2]]);}finally{ws.terminate();await network.close();}});
test('disconnect invokes false before an uncooperative handler completes',async()=>{const rpc=new JsonRpcDispatcher(),network=new MoonrakerNetwork(rpc,{authorize(){}});let release!:()=>void,entered=false;const gate=new Promise<void>(r=>release=r),values:boolean[]=[];rpc.register('test.wait',['websocket'],async(_p,c)=>{c.afterResponse!(sent=>values.push(sent));entered=true;await gate;return true;});const address=await network.listen(),ws=new WebSocket(`ws://127.0.0.1:${address.port}/websocket`);try{await once(ws,'open');ws.send(JSON.stringify({jsonrpc:'2.0',method:'test.wait',id:1}));await until(()=>entered);ws.terminate();await until(()=>values.length===1);assert.deepEqual(values,[false]);release();await network.close();assert.deepEqual(values,[false]);}finally{release?.();ws.terminate();await network.close();}});
test('HTTP completion fires on finished response and oversized output fails the barrier',async()=>{const rpc=new JsonRpcDispatcher(),network=new MoonrakerNetwork(rpc,{authorize(){}}),values:boolean[]=[];rpc.register('test.reply',['http'],(p,c)=>{c.afterResponse!(sent=>values.push(sent));return p.big?'x'.repeat(1024*1024):'ok';});const address=await network.listen(),url=`http://127.0.0.1:${address.port}/server/jsonrpc`;try{const send=(big:boolean)=>fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',method:'test.reply',params:{big},id:1})});assert.equal((await(await send(false)).json()).result,'ok');await until(()=>values.length===1);assert.deepEqual(values,[true]);await send(true);await until(()=>values.length===2);assert.deepEqual(values,[true,false]);}finally{await network.close();}});
