import {test} from 'node:test';
import assert from 'node:assert/strict';
import {identifySlicer} from '../src/moonraker/slicer-identification.ts';
import {parseCommonMetadata,parseUnknownMetadata} from '../src/moonraker/metadata-common.ts';
test('registered slicer families preserve derived-first precedence and fork exclusions',()=>{
 const cases=[['Slic3r Prusa Edition 1.4 on date','Slic3rPE','Slic3r PE','1.4'],['Slic3r 1.3 on date','Slic3r','Slic3r','1.3'],['; BambuStudio 2.0','BambuStudio','BambuStudio','2.0'],['; generated by Custom Fork 1.0 on 2026-01-01 at 12:34:56','PrusaSlicer','Custom Fork','1.0'],['OrcaSlicer 2.0 on date','PrusaSlicer','OrcaSlicer','2.0'],['Cura_SteamEngine 5.0','Cura','Cura','5.0'],['Simplify3D(R) Version 5.1','Simplify3D','Simplify3D','5.1'],['; KISSlicer\n; version 1 2','KISSlicer','KISSlicer','1-2'],['; ideaMaker 5.0, date','IdeaMaker','IdeaMaker','5.0'],['<IceSL dev>','IceSL','IceSL','-'],['; Generated by Kiri:Moto 3.1','KiriMoto','Kiri:Moto','3.1'],['; Generated by Kiri:Moto (SimplyPrint) beta','KiriMoto','SimplyPrint','beta']];
 for(const [text,family,name,version] of cases)assert.deepEqual(identifySlicer(text),{family,name,version});
 assert.equal(identifySlicer('Cura_SteamEngine 5\nSlic3r 1 on date').family,'Slic3r');
 assert.equal(identifySlicer('; generated by BambuStudio 1 on 2026-01-01 at 12:34:56').family,'UnknownSlicer');
 assert.deepEqual(identifySlicer('; generated by Solo on 2026-01-01 at 12:34:56'),{family:'PrusaSlicer',name:'',version:'Solo'});
 assert.throws(()=>identifySlicer('<IceSL >'),/Empty/);
});
test('identification uses Python Unicode whitespace, digit and dot semantics',()=>{
 assert.equal(identifySlicer('Cura_SteamEngine\u001c5\r\u2028tail').version,'5\r\u2028tail');
 assert.equal(identifySlicer('Cura_SteamEngine\ufeff5').family,'UnknownSlicer');
 assert.equal(identifySlicer('Slic3r ١.٢ on date').family,'Slic3r');
 assert.equal(identifySlicer('Slic3r \u{10d40}.2 on date').family,'UnknownSlicer');
 assert.equal(identifySlicer('<IceSL ²beta>').version,'²beta');
});
test('common byte offsets preserve codepoints, overlapping lines and missing boundary behavior',()=>{
 const text=';😀\nG1 X1\nM2 X3\n;尾\n',size=Buffer.byteLength(text),fields=parseCommonMetadata({header:text,footer:text,size});
 assert.deepEqual(fields,{gcode_start_byte:5,gcode_end_byte:18});
 assert.deepEqual(parseCommonMetadata({header:'G1 X1\n',footer:'G1 X1\n',size:6}),{});
 assert.deepEqual(parseCommonMetadata({header:'\nG1\nM2 X\n',footer:'\nG1\nM2 X\n',size:9}),{gcode_start_byte:0,gcode_end_byte:9});
});
test('unknown parser retains original unsigned decimal matching and rejects nonfinite JSON fields',()=>{
 const header='\nG1 Z.2 X\nG1 Z-1 X\nG1 Z1e2 X\nM109 S210\nM190 S60\nM191 S40\n',footer='\nG1 Z2.5 X\nG1 Z3.0 X\n';
 const fields=parseUnknownMetadata({header,footer,size:100});
 assert.equal(fields.first_layer_height,0.2);assert.equal(fields.object_height,3);assert.equal(fields.first_layer_extr_temp,210);assert.equal(fields.first_layer_bed_temp,60);assert.equal(fields.chamber_temp,40);
 assert.throws(()=>parseUnknownMetadata({header:'M109 S'+'9'.repeat(400),footer:'',size:406}),/not finite/);
});
