import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MessageDictionary} from '../src/protocol/dictionary.ts';
import {PrinterPins} from '../src/protocol/pins.ts';
import {compileStepper} from '../src/motion/stepper-config.ts';
function fixture(caps:Record<string,number|string>={}){const dictionary=new MessageDictionary();dictionary.identify(Buffer.from(JSON.stringify({commands:{'queue_step oid=%c interval=%u count=%hu add=%hi':2,'set_next_step_dir oid=%c dir=%c':3,'reset_step_clock oid=%c clock=%u':4,'stepper_get_position oid=%c':5},responses:{'stepper_position oid=%c pos=%i':6},config:{CLOCK_FREQ:1e6,...caps}})),false);const chip={},pins=new PrinterPins<object>();pins.register('mcu',chip);return {dictionary,chip,options:{oid:3,step:pins.lookup('!PA0',{canInvert:true}),direction:pins.lookup('!PA1',{canInvert:true}),rotationDistance:40,stepsPerRotation:3200}};}
test('stepper configuration preserves normal pulse ticks, inversion and distance',()=>{const f=fixture(),p=compileStepper(f.chip,f.dictionary,f.options);assert.equal(p.config,'config_stepper oid=3 step_pin=PA0 dir_pin=PA1 invert_step=1 step_pulse_ticks=2');assert.equal(p.restart,'reset_step_clock oid=3 clock=0');assert.equal(p.stepDistance,.0125);assert.equal(p.compressor.maxError,25);assert.equal(p.compressor.invertDirection,true);assert.equal(p.compressor.queueStepTag,2);assert.equal(p.legacyFirmware,true);});
test('new and legacy both-edge capability thresholds preserve upstream selection',()=>{
 for(const [caps,duration,both,effective] of [[{STEPPER_STEP_BOTH_EDGE:1},.0000005,true,.0000005],[{STEPPER_STEP_BOTH_EDGE:1},.000000501,false,.000000501],[{STEPPER_BOTH_EDGE:1},.00000015,true,0],[{STEPPER_BOTH_EDGE:1},.000000151,false,.000000151],[{STEPPER_STEP_BOTH_EDGE:1,STEPPER_OPTIMIZED_UNSTEP:1},.0000001,false,.0000001],[{},.0000001,false,.0000001]] as const){const f=fixture(caps),p=compileStepper(f.chip,f.dictionary,{...f.options,pulseDuration:duration,requestBothEdges:true});assert.equal(p.bothEdges,both);assert.equal(p.pulseDuration,effective);assert.match(p.config,both?/invert_step=-1/:/invert_step=1/);}
});
test('invalid device association and numerical settings fail before creating a plan',()=>{const f=fixture();assert.throws(()=>compileStepper({},f.dictionary,f.options),/MCU/);for(const invalid of [{oid:255},{rotationDistance:0},{stepsPerRotation:Infinity},{pulseDuration:NaN},{pulseDuration:-1}])assert.throws(()=>compileStepper(f.chip,f.dictionary,{...f.options,...invalid}));const malformed=fixture({STEPPER_STEP_BOTH_EDGE:.5});assert.throws(()=>compileStepper(malformed.chip,malformed.dictionary,malformed.options),/capabilities/);});
