import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setImmediate as tick} from 'node:timers/promises';
import {SubscriptionDelivery} from '../src/moonraker/subscription-delivery.ts';
import {prepareStatus} from '../src/moonraker/subscription-status.ts';
import type {RpcContext} from '../src/moonraker/rpc.ts';
const sent={sent:1,denied:0,closed:0,overflow:0,failed:0};
function harness(){const controller=new AbortController(),requests:any[]=[],messages:any[]=[],removed:number[]=[],disconnected:number[]=[],completions:((sent:boolean)=>void)[]=[],context:RpcContext={transport:'websocket',connectionId:1,signal:new AbortController().signal,authorize(){},afterResponse:cb=>completions.push(cb)},owner=new SubscriptionDelivery({enabled:()=>true,signal:()=>controller.signal,subscribe:(id,objects,signal)=>new Promise((resolve,reject)=>requests.push({id,objects,signal,resolve,reject})),remove:id=>removed.push(id),disconnect:id=>disconnected.push(id),send:async(id,status,time)=>{messages.push({id,status,time});return sent;}});return {owner,controller,requests,messages,removed,disconnected,completions,context};}
test('delivery holds updates through response handoff and drops fields outside latest selection',async()=>{const h=harness(),pending=h.owner.subscribe({objects:{a:['x']}},h.context);await tick();h.requests[0].resolve({status:prepareStatus({a:{x:1}}),eventtime:10});await pending;h.owner.deliver(1,prepareStatus({a:{x:2,y:9}}),11);assert.deepEqual(h.messages,[]);h.completions[0](true);await tick();assert.deepEqual(h.messages,[{id:1,status:{a:{x:2}},time:11}]);h.controller.abort();assert.equal(h.owner.size,0);assert.deepEqual(h.removed,[1]);});
test('all batch handoffs release together and older buffered updates cannot revert latest reply',async()=>{const h=harness(),a=h.owner.subscribe({objects:{a:['x']}},h.context),b=h.owner.subscribe({objects:{a:['y']}},h.context);await tick();h.requests[0].resolve({status:prepareStatus({a:{x:1}}),eventtime:10});await a;h.owner.deliver(1,prepareStatus({a:{x:2}}),11);h.requests[1].resolve({status:prepareStatus({a:{y:3}}),eventtime:12});await b;h.owner.deliver(1,prepareStatus({a:{x:4,y:5}}),13);h.completions[0](true);assert.equal(h.messages.length,0);h.completions[1](true);await tick();assert.deepEqual(h.messages,[{id:1,status:{a:{y:5}},time:13}]);h.owner.close();});
test('failed response and buffer overflow remove subscription and never send held updates',async()=>{for(const overflow of [false,true]){const h=harness(),p=h.owner.subscribe({objects:{a:null}},h.context);await tick();h.requests[0].resolve({status:prepareStatus({a:{x:0}}),eventtime:0});await p;if(overflow)for(let i=1;i<=257;i++)h.owner.deliver(1,prepareStatus({a:{x:i}}),i);else h.completions[0](false);assert.equal(h.owner.size,0);assert.equal(h.messages.length,0);assert.deepEqual(h.removed,[1]);assert.deepEqual(h.disconnected,overflow?[1]:[]);h.completions[0](true);assert.equal(h.messages.length,0);}});
test('old async delivery settles before the next upstream subscription request',async()=>{let release!:()=>void,requests=0;const completion:((sent:boolean)=>void)[]=[],controller=new AbortController(),owner=new SubscriptionDelivery({enabled:()=>true,signal:()=>controller.signal,remove(){},disconnect(){},subscribe:async()=>{requests++;return {status:prepareStatus({a:{x:0}}),eventtime:requests};},send:()=>new Promise(resolve=>{release=()=>resolve(sent);})}),context:RpcContext={transport:'websocket',connectionId:1,signal:controller.signal,authorize(){},afterResponse:cb=>completion.push(cb)};await owner.subscribe({objects:{a:null}},context);completion[0](true);owner.deliver(1,prepareStatus({a:{x:2}}),2);const pending=owner.subscribe({objects:{a:null}},context);await tick();assert.equal(requests,1);release();await pending;assert.equal(requests,2);completion[1](true);owner.close();});
test('held updates flush by event time and late live timestamps cannot regress delivery',async()=>{const h=harness(),p=h.owner.subscribe({objects:{a:null}},h.context);await tick();h.requests[0].resolve({status:prepareStatus({a:{x:0}}),eventtime:10});await p;for(const [time,fields] of [[13,{x:3}],[12,{x:2}],[13,{y:4}]] as const)h.owner.deliver(1,prepareStatus({a:fields}),time);h.completions[0](true);await tick();assert.deepEqual(h.messages.map(m=>m.time),[12,13,13]);h.owner.deliver(1,prepareStatus({a:{x:1}}),11);assert.equal(h.messages.length,3);h.owner.close();});
test('notification authorization denial removes subscription and disconnects instead of silently stalling',async()=>{const controller=new AbortController(),completions:((sent:boolean)=>void)[]=[],removed:number[]=[],disconnected:number[]=[],owner=new SubscriptionDelivery({enabled:()=>true,signal:()=>controller.signal,subscribe:async()=>({status:prepareStatus({a:{x:0}}),eventtime:0}),remove:id=>removed.push(id),disconnect:id=>disconnected.push(id),send:async()=>({...sent,sent:0,denied:1})});await owner.subscribe({objects:{a:null}},{transport:'websocket',connectionId:1,signal:controller.signal,authorize(){},afterResponse:cb=>completions.push(cb)});completions[0](true);owner.deliver(1,prepareStatus({a:{x:1}}),1);await tick();assert.deepEqual(removed,[1]);assert.deepEqual(disconnected,[1]);assert.equal(owner.size,0);owner.close();});
test('explicit null selection and non-WebSocket contexts reject before creating a subscription',async()=>{const h=harness();await assert.rejects(h.owner.subscribe({objects:null},h.context),/Invalid object subscription/);await assert.rejects(h.owner.subscribe({objects:{}},{...h.context,transport:'http'}),/WebSocket/);assert.equal(h.requests.length,0);assert.equal(h.owner.size,0);h.owner.close();});
