import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setImmediate as tick} from 'node:timers/promises';
import {SubscriptionManager} from '../src/moonraker/subscription-manager.ts';
import {KlippyStatusCache,prepareStatus,type Subscription} from '../src/moonraker/subscription-status.ts';
function harness(limits:{maxPending?:number;maxClients?:number}={}){const calls:{objects:Subscription;signal:AbortSignal;resolve(v:unknown):void;reject(e:unknown):void}[]=[],sent:any[]=[],cache=new KlippyStatusCache(),manager=new SubscriptionManager({...limits,cache,base:{webhooks:null},request:(objects,signal)=>new Promise((resolve,reject)=>calls.push({objects,signal,resolve,reject})),deliver:(id,status,time)=>sent.push({id,status,time})});return {manager,calls,sent,cache};}
const reply=(status:unknown)=>({status,eventtime:10});
test('transactions serialize aggregate changes and only commit successful filtered subscriptions',async()=>{const {manager,calls,sent}=harness();const a=manager.subscribe(1,{toolhead:['x']}),b=manager.subscribe(2,{toolhead:['y']});assert.equal(calls.length,1);assert.deepEqual(calls[0].objects,{webhooks:null,toolhead:['x']});calls[0].resolve(reply({toolhead:{x:1,y:2}}));assert.deepEqual((await a).status,{toolhead:{x:1}});await tick();assert.deepEqual(calls[1].objects,{webhooks:null,toolhead:['y','x']});calls[1].resolve(reply({toolhead:{x:3,y:4}}));assert.deepEqual((await b).status,{toolhead:{y:4}});assert.deepEqual(sent,[{id:1,status:{toolhead:{x:3}},time:10}]);manager.publish(prepareStatus({toolhead:{x:5,y:6}}),11);assert.deepEqual(sent.slice(1),[{id:1,status:{toolhead:{x:5}},time:11},{id:2,status:{toolhead:{y:6}},time:11}]);await tick();await manager.close();});
test('failed replacements retain previous selection; empty successful request unsubscribes',async()=>{const {manager,calls,sent}=harness();const first=manager.subscribe(1,{a:null});calls[0].resolve(reply({a:{x:1}}));await first;await tick();const changed=manager.subscribe(1,{b:null});calls[1].reject(new Error('peer error'));await assert.rejects(changed,/peer error/);manager.publish(prepareStatus({a:{x:2},b:{x:3}}),2);assert.equal(sent[0].status.a.x,2);await tick();const remove=manager.subscribe(1,{});assert.deepEqual(calls[2].objects,{webhooks:null});calls[2].resolve(reply({webhooks:{state:'ready'}}));assert.deepEqual((await remove).status,{});assert.equal(manager.metrics.clients,0);await tick();await manager.close();});
test('queued cancellation releases capacity; active cancellation holds capacity until actual settlement',async()=>{const {manager,calls}=harness({maxPending:2}),a=new AbortController(),b=new AbortController();const first=manager.subscribe(1,{a:null},a.signal),second=manager.subscribe(2,{b:null},b.signal);await assert.rejects(manager.subscribe(3,{}),/queue full/);b.abort();await assert.rejects(second,/cancelled/);assert.equal(manager.metrics.pending,1);a.abort();await assert.rejects(first,/cancelled/);assert.equal(calls[0].signal.aborted,true);assert.equal(manager.metrics.pending,1);const third=manager.subscribe(3,{c:null});assert.equal(calls.length,1);calls[0].resolve(reply({a:{x:1}}));await tick();assert.deepEqual(calls[1].objects,{webhooks:null,c:null});calls[1].resolve(reply({c:{x:1}}));await third;await tick();assert.equal(manager.metrics.clients,1);await manager.close();});
test('disconnect removes committed and pending subscriptions without late resurrection',async()=>{const {manager,calls,cache}=harness();const first=manager.subscribe(1,{a:null}),queued=manager.subscribe(1,{b:null});manager.remove(1);await assert.rejects(first,/removed/);await assert.rejects(queued,/removed/);calls[0].resolve(reply({a:{x:1}}));await tick();assert.equal(calls.length,1);assert.equal(manager.metrics.clients,0);assert.deepEqual(cache.read(),{});await manager.close();});
test('close rejects callers promptly but waits for a transport that ignores cancellation',async()=>{const {manager,calls}=harness();const request=manager.subscribe(1,{a:null});let drained=false;const closing=manager.close().then(()=>{drained=true;});await assert.rejects(request,/closed/);await tick();assert.equal(drained,false);await assert.rejects(manager.subscribe(2,{}),/closed/);assert.equal(manager.metrics.pending,1);calls[0].resolve(reply({a:{x:1}}));await closing;assert.equal(manager.metrics.pending,0);assert.equal(manager.metrics.clients,0);});
test('stale subscription reply does not overwrite newer cache or emit stale differences',async()=>{const {manager,calls,cache,sent}=harness();cache.apply(prepareStatus({a:{x:0}}));const first=manager.subscribe(1,{a:null});cache.apply(prepareStatus({a:{x:2}}));calls[0].resolve(reply({a:{x:1}}));assert.equal((await first).status.a.x,1);assert.equal(cache.read().a.x,2);assert.deepEqual(sent,[]);await tick();await manager.close();});
test('client limit checked at execution time and invalid peer responses do not commit',async()=>{const {manager,calls}=harness({maxClients:1});for(const bad of [null,{}, {status:{a:1},eventtime:0},{status:{a:{}},eventtime:NaN}]){const request=manager.subscribe(1,{a:null});calls.at(-1)!.resolve(bad);await assert.rejects(request);await tick();assert.equal(manager.metrics.clients,0);}const first=manager.subscribe(1,{a:null}),second=manager.subscribe(2,{b:null});calls.at(-1)!.resolve(reply({a:{x:1}}));await first;await assert.rejects(second,/client capacity/);await tick();await manager.close();});
test('invalid request never reaches peer and caller-owned fields are copied before queueing',async()=>{const {manager,calls}=harness();await assert.rejects(manager.subscribe(0,{}));await assert.rejects(manager.subscribe(1,{a:[false]}));assert.equal(calls.length,0);const objects={a:['x']},request=manager.subscribe(1,objects);objects.a[0]='y';assert.deepEqual(calls[0].objects,{webhooks:null,a:['x']});calls[0].resolve(reply({a:{x:1,y:2}}));assert.deepEqual((await request).status,{a:{x:1}});await tick();await manager.close();});
test('live deltas received during a new subscription are folded into its reply without leaking unrequested fields',async()=>{const {manager,calls,cache}=harness();const pending=manager.subscribe(1,{a:['x','y']});const live=prepareStatus({a:{x:2,private:9}});cache.apply(live);manager.publish(live,12);calls[0].resolve({status:{a:{x:1,y:3,private:0}},eventtime:10});assert.deepEqual(await pending,{status:{a:{x:2,y:3}},eventtime:12});assert.equal(cache.read().a.x,2);await tick();await manager.close();});
test('journal overflow aborts pending request, preserves old subscriber and continues live delivery',async()=>{const calls:any[]=[],sent:any[]=[],cache=new KlippyStatusCache(),manager=new SubscriptionManager({cache,journalLimits:{updates:1},request:(_objects,signal)=>new Promise(resolve=>calls.push({resolve,signal})),deliver:(id,status)=>sent.push({id,status})});const first=manager.subscribe(1,{a:null});calls[0].resolve(reply({a:{x:0}}));await first;await tick();const replacement=manager.subscribe(1,{a:['x']}),rejected=assert.rejects(replacement,/journal capacity/);manager.publish(prepareStatus({a:{x:1}}),11);manager.publish(prepareStatus({a:{x:2}}),12);await rejected;assert.equal(calls[1].signal.aborted,true);assert.equal(manager.metrics.pending,1);assert.equal(sent.length,2);calls[1].resolve(reply({a:{x:0}}));await tick();assert.equal(manager.metrics.clients,1);manager.publish(prepareStatus({a:{other:3}}),13);assert.deepEqual(sent.at(-1),{id:1,status:{a:{other:3}}});await manager.close();});
test('component subscriptions occupy a separate namespace and survive client removal without network delivery',async()=>{
 const {manager,calls,sent}=harness();await assert.rejects(manager.subscribe(-1,{}));await assert.rejects(manager.subscribeInternal(1,{}));
 const internal=manager.subscribeInternal(-1,{extruder:null});calls[0].resolve(reply({extruder:{temperature:20}}));await internal;await tick();
 const external=manager.subscribe(1,{toolhead:['x']});assert.deepEqual(calls[1].objects,{webhooks:null,toolhead:['x'],extruder:null});calls[1].resolve(reply({extruder:{temperature:21},toolhead:{x:1}}));await external;await tick();
 manager.publish(prepareStatus({extruder:{temperature:22},toolhead:{x:2}}),12);assert.deepEqual(sent.map(s=>s.id),[1]);manager.remove(1);
 const replacement=manager.subscribe(2,{fan:['speed']});assert.deepEqual(calls[2].objects,{webhooks:null,fan:['speed'],extruder:null});calls[2].resolve(reply({extruder:{temperature:23},fan:{speed:.5}}));await replacement;await tick();await manager.close();
});
