import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,open,writeFile,readFile,appendFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {crc32,deflateRawSync} from 'node:zlib';
import type {UfpArchiveLimits} from '../src/moonraker/ufp-archive.ts';
import {pathToFileURL} from 'node:url';
import {externalAcceptanceBundle,assertAcceptanceBundleUnchanged} from './helpers/acceptance-bundle.ts';
const retained=await externalAcceptanceBundle();if(retained)after(()=>assertAcceptanceBundleUnchanged(retained));
const {extractUfpArchive}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/ufp-archive.js')).href) as typeof import('../src/moonraker/ufp-archive.ts'):await import('../src/moonraker/ufp-archive.ts');
const {ApiError}=retained?await import(pathToFileURL(join(retained.path,'host/src/moonraker/rpc.js')).href) as typeof import('../src/moonraker/rpc.ts'):await import('../src/moonraker/rpc.ts');

// Independent little-endian ZIP formatter: no production ZIP writer/parser.
interface Member {name:string;data:Buffer;method?:number;descriptor?:boolean;crc?:number;size?:number;attributes?:number;flags?:number;}
function archive(members:Member[],zip64=false):Buffer {
 const locals:Buffer[]=[],centrals:Buffer[]=[];let offset=0;
 for(const m of members){
  const name=Buffer.from(m.name),method=m.method??0,data=method===8?deflateRawSync(m.data):m.data,checksum=m.crc??crc32(m.data),size=m.size??m.data.length,flags=(m.flags??0)|(m.descriptor?8:0);
  const header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(flags,6);header.writeUInt16LE(method,8);header.writeUInt16LE(name.length,26);
  if(!m.descriptor){header.writeUInt32LE(checksum,14);header.writeUInt32LE(data.length,18);header.writeUInt32LE(size,22);}
  const descriptor=Buffer.alloc(m.descriptor?16:0);if(m.descriptor){descriptor.writeUInt32LE(0x08074b50);descriptor.writeUInt32LE(checksum,4);descriptor.writeUInt32LE(data.length,8);descriptor.writeUInt32LE(size,12);}
  const central=Buffer.alloc(46),extra=Buffer.alloc(zip64?28:0);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(0x031e,4);central.writeUInt16LE(zip64?45:20,6);central.writeUInt16LE(flags,8);central.writeUInt16LE(method,10);central.writeUInt32LE(checksum,16);central.writeUInt32LE(zip64?0xffffffff:data.length,20);central.writeUInt32LE(zip64?0xffffffff:size,24);central.writeUInt16LE(name.length,28);central.writeUInt16LE(extra.length,30);central.writeUInt32LE(m.attributes??0x81a40000,38);central.writeUInt32LE(zip64?0xffffffff:offset,42);
  if(zip64){extra.writeUInt16LE(1);extra.writeUInt16LE(24,2);extra.writeBigUInt64LE(BigInt(size),4);extra.writeBigUInt64LE(BigInt(data.length),12);extra.writeBigUInt64LE(BigInt(offset),20);}
  locals.push(header,name,data,descriptor);centrals.push(central,name,extra);offset+=header.length+name.length+data.length+descriptor.length;
 }
 const directory=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(zip64?0xffff:members.length,8);end.writeUInt16LE(zip64?0xffff:members.length,10);end.writeUInt32LE(zip64?0xffffffff:directory.length,12);end.writeUInt32LE(zip64?0xffffffff:offset,16);
 const suffix:Buffer[]=[];if(zip64){const record=Buffer.alloc(56),locator=Buffer.alloc(20);record.writeUInt32LE(0x06064b50);record.writeBigUInt64LE(44n,4);record.writeUInt16LE(45,12);record.writeUInt16LE(45,14);record.writeBigUInt64LE(BigInt(members.length),24);record.writeBigUInt64LE(BigInt(members.length),32);record.writeBigUInt64LE(BigInt(directory.length),40);record.writeBigUInt64LE(BigInt(offset),48);locator.writeUInt32LE(0x07064b50);locator.writeBigUInt64LE(BigInt(offset+directory.length),8);locator.writeUInt32LE(1,16);suffix.push(record,locator);}
 return Buffer.concat([...locals,directory,...suffix,end]);
}
const model=Buffer.from('; generated by Cura\r\n; 中文模型\r\nG1 X0.12345678901234567 E0.01 F1200\r\n','utf8');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l5kAAAAASUVORK5CYII=','base64');
const member=(data=model,name='/3D/model.gcode'):Member=>({name,data});
const image=():Member=>({name:'/Metadata/thumbnail.png',data:png});
const status=(expected:number)=>(error:unknown)=>error instanceof ApiError&&error.status===expected;
async function fixture(bytes:Buffer){
 const dir=await mkdtemp(join(tmpdir(),'ufp-archive-')),sourcePath=join(dir,'input.ufp'),targetPath=join(dir,'model.gcode');await writeFile(sourcePath,bytes);const source=await open(sourcePath,'r'),target=await open(targetPath,'wx+');
 return {dir,sourcePath,targetPath,source,target,signal:new AbortController().signal,async close(){await source.close();await target.close();await rm(dir,{recursive:true,force:true});}};
}
for(const method of [0,8])for(const descriptor of [false,true])for(const zip64 of [false,true]){
 test(`UFP preserves exact model and independent PNG (method=${method}, descriptor=${descriptor}, ZIP64=${zip64})`,async()=>{
  const f=await fixture(archive([{...member(),method,descriptor},{...image(),method,descriptor}],zip64));
  try{const out=await extractUfpArchive(f.source,f.target,f.signal);assert.deepEqual(await readFile(f.targetPath),model);assert.equal(out.model.size,model.length);assert.equal(out.model.sha256,createHash('sha256').update(model).digest('hex'));assert.deepEqual(out.thumbnail?.bytes,png);assert.equal(out.thumbnail?.sha256,createHash('sha256').update(png).digest('hex'));assert.equal((await f.source.stat()).size,(await readFile(f.sourcePath)).length);assert.equal((await f.target.stat()).size,model.length);}finally{await f.close();}
 });
}
test('UFP accepts exact relative member aliases and ignores unsafe unrelated names without extracting them',async()=>{
 const f=await fixture(archive([member(Buffer.from('ignored'),'../../escape'),member(Buffer.from('ignored'),'C:\\escape'),member(model,'3D/model.gcode')]));
 try{const out=await extractUfpArchive(f.source,f.target,f.signal);assert.deepEqual(await readFile(f.targetPath),model);assert.equal(out.thumbnail,undefined);}finally{await f.close();}
});
for(const [name,members] of [
 ['missing model',[image()]],['duplicate model',[member(),member(model,'3D/model.gcode')]],['duplicate image',[member(),image(),{...image(),name:'Metadata/thumbnail.png'}]],
 ['encrypted model',[{...member(),flags:1}]],['unsupported compression',[{...member(),method:12}]],['symbolic link',[{...member(),attributes:0xa1ff0000}]],
 ['CRC mismatch',[{...member(),crc:(crc32(model)^1)>>>0}]],['deflate length mismatch',[{...member(),method:8,size:model.length-1}]],['invalid PNG',[member(),{...image(),data:Buffer.from('not PNG')}]],
 ] as [string,Member[]][]){test(`UFP rejects ${name}`,async()=>{const f=await fixture(archive(members));try{await assert.rejects(extractUfpArchive(f.source,f.target,f.signal),status(422));assert.equal((await f.source.stat()).size,(await readFile(f.sourcePath)).length);}finally{await f.close();}});}
for(const [name,options] of [
 ['archive',{maxArchiveBytes:8}],['model',{maxModelBytes:8}],['thumbnail',{maxThumbnailBytes:8}],['entry count',{maxEntries:1}],['directory bytes',{maxDirectoryBytes:8}],
 ] as [string,UfpArchiveLimits][]){test(`UFP rejects ${name} capacity before model output`,async()=>{const f=await fixture(archive([member(),image()]));try{await assert.rejects(extractUfpArchive(f.source,f.target,f.signal,options),status(413));assert.equal((await f.target.stat()).size,0);}finally{await f.close();}});}
test('UFP rejects malformed ZIP and invalid capacity; never closes either caller descriptor',async()=>{
 const f=await fixture(Buffer.from('not ZIP'));try{await assert.rejects(extractUfpArchive(f.source,f.target,f.signal),status(422));await assert.rejects(extractUfpArchive(f.source,f.target,f.signal,{maxEntries:0}),RangeError);assert.equal((await f.target.stat()).size,0);assert.equal((await f.source.stat()).size,7);}finally{await f.close();}
});
test('UFP refuses occupied model staging without truncating it',async()=>{
 const f=await fixture(archive([member()]));try{await f.target.write(Buffer.from('existing'));await assert.rejects(extractUfpArchive(f.source,f.target,f.signal),status(409));assert.equal((await readFile(f.targetPath)).toString(),'existing');}finally{await f.close();}
});
test('UFP preserves abort reason and drains a held source read before returning to its owner',async t=>{
 const f=await fixture(archive([member()])),abort=new AbortController(),entered=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),reason=new Error('cancel upload'),read=f.source.read.bind(f.source);let settled=false;
 t.mock.method(f.source,'read',async(buffer:Buffer,offset:number,length:number,position:number)=>{entered.resolve();await release.promise;return read(buffer,offset,length,position);});
 try{const extraction=extractUfpArchive(f.source,f.target,abort.signal);const observed=extraction.then(()=>{settled=true;throw new Error('unexpected success');},error=>{settled=true;return error;});await entered.promise;abort.abort(reason);await new Promise<void>(resolve=>setImmediate(resolve));assert.equal(settled,false);release.resolve();assert.equal(await observed,reason);assert.equal((await f.target.stat()).size,0);assert((await f.source.stat()).isFile());}finally{release.resolve();t.mock.restoreAll();await f.close();}
});
test('UFP rejects an externally changed source even when decoded bytes still match',async t=>{
 const f=await fixture(archive([member()])),write=f.target.write.bind(f.target);let changed=false;
 t.mock.method(f.target,'write',async(buffer:Buffer,offset:number,length:number,position:number)=>{if(!changed){changed=true;await appendFile(f.sourcePath,Buffer.from('external change'));}return write(buffer,offset,length,position);});
 try{await assert.rejects(extractUfpArchive(f.source,f.target,f.signal),status(409));assert.deepEqual(await readFile(f.targetPath),model);}finally{t.mock.restoreAll();await f.close();}
});
test('UFP distinguishes source I/O failure from malformed content',async t=>{
 const f=await fixture(archive([member()]));t.mock.method(f.source,'read',async()=>{throw new Error('synthetic read I/O failure');});
 try{await assert.rejects(extractUfpArchive(f.source,f.target,f.signal),status(500));assert.equal((await f.target.stat()).size,0);}finally{t.mock.restoreAll();await f.close();}
});
