import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:net';
import {Readable,Writable,PassThrough} from 'node:stream';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {consoleRequest,ConsoleFrames,webhookConsole} from '../src/diagnostics/webhook-console.ts';
test('complete-frame copies isolate callers while owned chunks preserve bytes across every split',()=>{
 const input=Buffer.from('abc\x03def\x03tail'),frames=new ConsoleFrames(3),out=frames.push(input);input.fill(0);assert.deepEqual(out.map(b=>b.toString()),['abc','def']);assert.equal(frames.finish()!.toString(),'tail');
 const source=Buffer.from('\x03你好\x03{"clock":9007199254740993}\x03tail');
 for(const owned of [false,true])for(let size=1;size<=source.length;size++){
  const decoder=new ConsoleFrames(3,64,owned),result:Buffer[]=[];
  for(let start=0;start<source.length;start+=size)result.push(...decoder.push(source.subarray(start,start+size)));
  assert.deepEqual(result.map(b=>b.toString()),['','你好','{"clock":9007199254740993}']);assert.equal(decoder.finish()!.toString(),'tail');
  assert.throws(()=>new ConsoleFrames(3,2,owned).push(Buffer.from('abc\x03')),/limit/);
 }
 const owned=new ConsoleFrames(3,64,true),one=owned.push(source)[1];assert.equal(one.buffer,source.buffer);assert.equal(one.byteOffset,source.byteOffset+1);
});
function sink(){let text='';const stream=new Writable({highWaterMark:1,write(chunk,_encoding,done){text+=chunk.toString();setImmediate(done);}});return {stream,text:()=>text};}
test('console framing handles fragmented UTF8, exact numeric lexemes and bounded tails',()=>{const frames=new ConsoleFrames(3,32),bytes=Buffer.from('你好\x03{}\x03tail'),got:Buffer[]=[];for(const b of bytes)got.push(...frames.push(Buffer.of(b)));assert.deepEqual(got.map(b=>b.toString()),['你好','{}']);assert.equal(frames.finish()!.toString(),'tail');assert.equal(frames.pending,0);assert.throws(()=>frames.push(Buffer.alloc(33)),RangeError);assert.equal(consoleRequest(Buffer.from(' { "id":9007199254740993, "x": 1.0000000000000001, "s":" a \\\" b " } ')),'{"id":9007199254740993,"x":1.0000000000000001,"s":" a \\\" b "}');assert.equal(consoleRequest(Buffer.from(' #comment')),undefined);assert.throws(()=>consoleRequest(Buffer.from('NaN')));assert.throws(()=>consoleRequest(Buffer.of(255)));});
test('console CLI exchanges ETX requests and final unterminated input, drains responses after EOF',async()=>{const dir=await mkdtemp(join(tmpdir(),'whconsole-')),path=join(dir,'socket'),received:string[]=[];const server=createServer({allowHalfOpen:true},socket=>{const f=new ConsoleFrames(3);socket.on('data',chunk=>{for(const frame of f.push(Buffer.from(chunk))){received.push(frame.toString());const reply=Buffer.from('{"result":"你好"}\x03');socket.write(reply.subarray(0,13));socket.write(reply.subarray(13));}});socket.on('end',()=>socket.end());});try{await new Promise<void>(r=>server.listen(path,r));const child=spawn(process.execPath,[fileURLToPath(new URL('../../scripts/whconsole.ts',import.meta.url)),path]);let out='',err='';child.stdout.on('data',c=>out+=c);child.stderr.on('data',c=>err+=c);child.stdin.end('# comment\ninvalid\n{"id":9007199254740993}\n{ "method": "info" }');const code=await new Promise(r=>child.once('exit',r));assert.equal(code,0,err);assert.deepEqual(received,['{"id":9007199254740993}','{"method":"info"}']);assert.equal((out.match(/GOT:/g)||[]).length,2);assert.match(out,/你好/);assert.match(err,/Unable to parse line/);}finally{await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}});
test('console rejects truncated frames, enforces response drain and cancels idle input',async()=>{for(const mode of ['truncated','timeout','abort'] as const){const dir=await mkdtemp(join(tmpdir(),'whconsole-close-')),path=join(dir,'socket'),input=mode==='abort'?new PassThrough():Readable.from([]),out=sink(),err=sink(),controller=new AbortController();const sockets=new Set<import('node:net').Socket>();const server=createServer({allowHalfOpen:true},socket=>{sockets.add(socket);if(mode==='truncated')socket.end('{');if(mode==='abort')setTimeout(()=>controller.abort(new Error('cancel test')),20);});try{await new Promise<void>(r=>server.listen(path,r));await assert.rejects(webhookConsole(path,input,out.stream,err.stream,controller.signal,{drainTimeoutMs:30}),mode==='truncated'?/incomplete/:mode==='timeout'?/drain timed out/:/cancel test|aborted/i);}finally{for(const s of sockets)s.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}}});
test('console rejects an initial diagnostic sink failure without an unhandled stream error',async()=>{const broken=new Writable({write(_chunk,_encoding,done){done(new Error('sink failed'));}});await assert.rejects(webhookConsole('/unused',Readable.from([]),sink().stream,broken,new AbortController().signal),/sink failed/);await new Promise(r=>setImmediate(r));});
test('slow output backpressures both send and receive without losing requests',async()=>{const dir=await mkdtemp(join(tmpdir(),'whconsole-pressure-')),path=join(dir,'socket');let count=0,maxQueued=0,out='';const output=new Writable({highWaterMark:1,write(chunk,_encoding,done){out+=chunk.toString();setTimeout(()=>{maxQueued=Math.max(maxQueued,output.writableLength);done();},1);}}),server=createServer({allowHalfOpen:true},socket=>{const frames=new ConsoleFrames(3);socket.on('data',chunk=>{for(const frame of frames.push(Buffer.from(chunk))){count++;socket.write(frame);socket.write('\x03');}});socket.on('end',()=>socket.end());});try{await new Promise<void>(r=>server.listen(path,r));await webhookConsole(path,Readable.from(Array.from({length:64},(_,i)=>`{"id":${i}}\n`)),output,sink().stream,new AbortController().signal);assert.equal(count,64);assert.equal((out.match(/GOT:/g)||[]).length,64);assert.equal((out.match(/SEND:/g)||[]).length,64);assert.ok(maxQueued<128,`queued ${maxQueued}`);}finally{await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}});
test('cancel interrupts blocked caller-owned output and initial status writes',async()=>{for(const initial of [true,false]){const dir=await mkdtemp(join(tmpdir(),'whconsole-blocked-')),path=join(dir,'socket'),controller=new AbortController(),peers=new Set<import('node:net').Socket>();let complete:((error?:Error|null)=>void)|undefined,entered!:()=>void;const writing=new Promise<void>(r=>entered=r),blocked=new Writable({write(_chunk,_encoding,done){complete=done;entered();}}),server=createServer(socket=>peers.add(socket));try{await new Promise<void>(r=>server.listen(path,r));const running=webhookConsole(path,Readable.from(['{"method":"info"}\n']),initial?sink().stream:blocked,initial?blocked:sink().stream,controller.signal);const rejected=assert.rejects(running,/blocked cancel/);await writing;controller.abort(new Error('blocked cancel'));await rejected;assert.equal(blocked.destroyed,false);complete!();await new Promise(r=>setImmediate(r));assert.equal(blocked.listenerCount('error'),0);}finally{for(const p of peers)p.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}}});
test('synchronous console output does not accumulate per-write error listeners',async()=>{const dir=await mkdtemp(join(tmpdir(),'whconsole-listeners-')),path=join(dir,'socket');let peak=0;const output=new Writable({write(_chunk,_encoding,done){peak=Math.max(peak,output.listenerCount('error'));done();}}),server=createServer(socket=>{socket.on('data',()=>{});});try{await new Promise<void>(r=>server.listen(path,r));await webhookConsole(path,Readable.from([Array.from({length:1000},(_,i)=>`{"id":${i}}\n`).join('')]),output,sink().stream,new AbortController().signal);assert.ok(peak<=2,`peak listeners ${peak}`);}finally{await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}});
test('peer close releases a blocked SEND and a late write completion cannot send a request',async()=>{const dir=await mkdtemp(join(tmpdir(),'whconsole-peer-close-')),path=join(dir,'socket');let complete:((error?:Error|null)=>void)|undefined,peer:import('node:net').Socket|undefined,received=0,entered!:()=>void;const writing=new Promise<void>(r=>entered=r),output=new Writable({write(_chunk,_encoding,done){complete=done;entered();}}),server=createServer(socket=>{peer=socket;socket.on('data',chunk=>received+=chunk.length);});try{await new Promise<void>(r=>server.listen(path,r));const running=webhookConsole(path,Readable.from(['{"method":"info"}\n']),output,sink().stream,new AbortController().signal);await writing;peer!.end();await running;complete!();await new Promise(r=>setImmediate(r));assert.equal(received,0);assert.equal(output.listenerCount('error'),0);}finally{peer?.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}});
test('span compaction preserves quoted whitespace, escapes and exact motion lexemes after decoder errors',()=>{
 // Build escaped strings independently of the compactor, retaining literal spaces.
 const label=JSON.stringify('你好 😀 \\ " a\tb\nc');
 const cases=[[' \t{ "id" : 9007199254740993 , "p" : [ -0 , 1.0000000000000001 , 1e-300 ], "text" : '+label+' }\r\n','{"id":9007199254740993,"p":[-0,1.0000000000000001,1e-300],"text":'+label+'}'],['[ 1,\n 2,\t3 ]','[1,2,3]'],['" spaces stay "','" spaces stay "'],[' true ','true']];
 for(const [input,expected] of cases){assert.equal(consoleRequest(Buffer.from(input)),expected);assert.equal(consoleRequest(Buffer.from(expected)),expected);}
 for(const invalid of [Buffer.of(0xc3),Buffer.of(0xff),Buffer.from('{"x":}')]){assert.throws(()=>consoleRequest(invalid));assert.equal(consoleRequest(Buffer.from('{"ok":1}')),'{"ok":1}');}
 assert.equal(consoleRequest(Buffer.from('\ufeff { "ok": 1 }')),'{"ok":1}');assert.equal(consoleRequest(Buffer.from('{"ok":2}')),'{"ok":2}');
});
