import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:net';
import {Readable,Writable,PassThrough} from 'node:stream';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {consoleRequest,ConsoleFrames,webhookConsole} from '../src/diagnostics/webhook-console.ts';
function sink(){let text='';const stream=new Writable({highWaterMark:1,write(chunk,_encoding,done){text+=chunk.toString();setImmediate(done);}});return {stream,text:()=>text};}
test('console framing handles fragmented UTF8, exact numeric lexemes and bounded tails',()=>{const frames=new ConsoleFrames(3,32),bytes=Buffer.from('你好\x03{}\x03tail'),got:Buffer[]=[];for(const b of bytes)got.push(...frames.push(Buffer.of(b)));assert.deepEqual(got.map(b=>b.toString()),['你好','{}']);assert.equal(frames.finish()!.toString(),'tail');assert.equal(frames.pending,0);assert.throws(()=>frames.push(Buffer.alloc(33)),RangeError);assert.equal(consoleRequest(Buffer.from(' { "id":9007199254740993, "x": 1.0000000000000001, "s":" a \\\" b " } ')),'{"id":9007199254740993,"x":1.0000000000000001,"s":" a \\\" b "}');assert.equal(consoleRequest(Buffer.from(' #comment')),undefined);assert.throws(()=>consoleRequest(Buffer.from('NaN')));assert.throws(()=>consoleRequest(Buffer.of(255)));});
test('console CLI exchanges ETX requests and final unterminated input, drains responses after EOF',async()=>{const dir=await mkdtemp(join(tmpdir(),'whconsole-')),path=join(dir,'socket'),received:string[]=[];const server=createServer({allowHalfOpen:true},socket=>{const f=new ConsoleFrames(3);socket.on('data',chunk=>{for(const frame of f.push(Buffer.from(chunk))){received.push(frame.toString());const reply=Buffer.from('{"result":"你好"}\x03');socket.write(reply.subarray(0,13));socket.write(reply.subarray(13));}});socket.on('end',()=>socket.end());});try{await new Promise<void>(r=>server.listen(path,r));const child=spawn(process.execPath,[fileURLToPath(new URL('../../scripts/whconsole.ts',import.meta.url)),path]);let out='',err='';child.stdout.on('data',c=>out+=c);child.stderr.on('data',c=>err+=c);child.stdin.end('# comment\ninvalid\n{"id":9007199254740993}\n{ "method": "info" }');const code=await new Promise(r=>child.once('exit',r));assert.equal(code,0,err);assert.deepEqual(received,['{"id":9007199254740993}','{"method":"info"}']);assert.equal((out.match(/GOT:/g)||[]).length,2);assert.match(out,/你好/);assert.match(err,/Unable to parse line/);}finally{await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}});
test('console rejects truncated frames, enforces response drain and cancels idle input',async()=>{for(const mode of ['truncated','timeout','abort'] as const){const dir=await mkdtemp(join(tmpdir(),'whconsole-close-')),path=join(dir,'socket'),input=mode==='abort'?new PassThrough():Readable.from([]),out=sink(),err=sink(),controller=new AbortController();const sockets=new Set<import('node:net').Socket>();const server=createServer({allowHalfOpen:true},socket=>{sockets.add(socket);if(mode==='truncated')socket.end('{');if(mode==='abort')setTimeout(()=>controller.abort(new Error('cancel test')),20);});try{await new Promise<void>(r=>server.listen(path,r));await assert.rejects(webhookConsole(path,input,out.stream,err.stream,controller.signal,{drainTimeoutMs:30}),mode==='truncated'?/incomplete/:mode==='timeout'?/drain timed out/:/cancel test|aborted/i);}finally{for(const s of sockets)s.destroy();await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}}});
test('console rejects an initial diagnostic sink failure without an unhandled stream error',async()=>{const broken=new Writable({write(_chunk,_encoding,done){done(new Error('sink failed'));}});await assert.rejects(webhookConsole('/unused',Readable.from([]),sink().stream,broken,new AbortController().signal),/sink failed/);await new Promise(r=>setImmediate(r));});
test('slow output backpressures both send and receive without losing requests',async()=>{const dir=await mkdtemp(join(tmpdir(),'whconsole-pressure-')),path=join(dir,'socket');let count=0,maxQueued=0,out='';const output=new Writable({highWaterMark:1,write(chunk,_encoding,done){out+=chunk.toString();setTimeout(()=>{maxQueued=Math.max(maxQueued,output.writableLength);done();},1);}}),server=createServer({allowHalfOpen:true},socket=>{const frames=new ConsoleFrames(3);socket.on('data',chunk=>{for(const frame of frames.push(Buffer.from(chunk))){count++;socket.write(frame);socket.write('\x03');}});socket.on('end',()=>socket.end());});try{await new Promise<void>(r=>server.listen(path,r));await webhookConsole(path,Readable.from(Array.from({length:64},(_,i)=>`{"id":${i}}\n`)),output,sink().stream,new AbortController().signal);assert.equal(count,64);assert.equal((out.match(/GOT:/g)||[]).length,64);assert.equal((out.match(/SEND:/g)||[]).length,64);assert.ok(maxQueued<128,`queued ${maxQueued}`);}finally{await new Promise<void>(r=>server.close(()=>r()));await rm(dir,{recursive:true,force:true});}});
